### PR TITLE
[master] ipatests: Bump PR-CI boxes

### PR DESCRIPTION
**Pull request by netoarmando**
Update Fedora 34 and 33 boxes to include new packages

Signed-off-by: Armando Neto <abiagion@redhat.com>

### CODE REVIEW

**Comment by stanislavlevin** [comment]
There are old versions of ldns in the image:
```
ldns-1.7.0-32.fc33.x86_64
ldns-utils-1.7.0-32.fc33.x86_64
```

**Comment by netoarmando** [comment]
@stanislavlevin My bad, I forgot to bump the version in some files (I was hoping we could move gating to F34, but there are still issues).

**Comment by abbra** [comment]
Please rebase as PR #5803 was pushed

**Comment by netoarmando** [comment]
@stanislavlevin @abbra during freeipa installation `ldns-1.7.0-32.fc33.x86_64` is the best package. There's a problem with the latest one in Fedora 33: https://bodhi.fedoraproject.org/updates/FEDORA-2021-eebc69f7ea#comment-2052076

**Comment by stanislavlevin** [comment]
Right now, it's working. Actual UB was changed with GCC11.
I want to say that the previous ldns (1.7.0) somehow works on F33.

**Comment by stanislavlevin** [comment]
@netoarmando, can you please rebase to master to get fix for sudo tests?

**Comment by netoarmando** [comment]
Rebased.

**Comment by abbra** [comment]
master:

* ba5b9c565d9ab39731c0716adb70b390519abb59 ipatests: Bump PR-CI boxes

**Pull request closed without merging**
