### PR TITLE
tests: Fix on test_sudo_rule_restricted_to_one_hostmask_negative

### PR DESCRIPTION
**Pull request by celestian**
The error message was changed. This patch fix the test
to current situation.

https://pagure.io/freeipa/issue/7543

### CODE REVIEW

**Comment by gkaihorodova** [comment]
Fix LGTM

**Comment by celestian** [comment]
Wau, it seems that it wasn't bug at all.

**Comment by celestian** [comment]
OK, we will try test it a little later. It seems that PR CI needs update. :-)

**Comment by celestian** [comment]
Interesting fact!
With older PR CI image, this PR looks like bug. But with newer, this is correct PR which really fix something, respectively sudo error message in our test.

**Comment by celestian** [comment]
This issue could be connected to:
https://pagure.io/SSSD/sssd/issue/3742

**Comment by celestian** [comment]
This approach how to solve the issue doesn't seem to be valid any more.  So I am closing this PR.

**Pull request closed without merging**
