### PR TITLE
ipa-crlgen-manage: manage the cert status task execution time

### PR DESCRIPTION
**Pull request by rcritten**
ca.certStatusUpdateInterval manages how frequently to update
the certificate status in LDAP (expired, etc).

By default this is not set on the initial master and pkispawn sets
it to 0 on replicas. This can lead to no server running this
task and therefore the status attribute not reflecting the current
state.

On enabling CRL generation remove any value which will cause PKI
to use its default. On disabling set it to 0.

Only one server should run the update status task to prevent
unnecessary replication.

Fixes: https://pagure.io/freeipa/issue/9569

### CODE REVIEW

**Comment by flo-renaud** [comment]
@rcritten works for me, tested on a deployment with master + replica, both having a CA instance.
After initial setup:
- master has no value for ca.certStatusUpdateInterval in /etc/pki/pki-tomcat/ca/CS.cfg
- replica has ca.certStatusUpdateInterval=0
After running ipa-crlgen-manage disable on the master:
- master has ca.certStatusUpdateInterval=0
After running ipa-crlgen-manage enable on the replica:
- replica has no value for ca.certStatusUpdateInterval

I would also add some code in cainstance.py in the is_crlgen_enabled method and raise InconsistentCRLGenConfigException if there is ca.certStatusUpdateInterval=0 on a non-CRLGen master server. This would be reported by ipa-crlgen-manage status as an inconsistency.

**Comment by rcritten** [comment]
> I would also add some code in cainstance.py in the is_crlgen_enabled method and raise InconsistentCRLGenConfigException if there is ca.certStatusUpdateInterval=0 on a non-CRLGen master server. This would be reported by ipa-crlgen-manage status as an inconsistency.

Good idea, added.

**Comment by rcritten** [comment]
It was pointed out in the ticket that ca.listenToCloneModifications should also follow the enable/disable cycle. Adding that now.

**Comment by flo-renaud** [comment]
@rcritten thanks for the update, LGTM. You can remove the temp commit and I will ack when PRCI completes

**Comment by flo-renaud** [comment]
master:

* f78d25fc972813f500c4ccfcf0faa2c6aa0d48b2 ipa-crlgen-manage: manage the cert status task execution time

**Pull request closed without merging**
