### PR TITLE
Move ipalib.install.kinit to ipalib

### PR DESCRIPTION
**Pull request by tiran**
- kinit helpers are now in `ipalib.kinit`.
- helpers can now use default ccache locations like many other similar helpers
- helpers return the result from `run` for debugging
- constants are now in `krb_utils`
- helpers pass `KRB5*` and `GSS*` env vars along, so `KRB5_TRACE` works
- document how to kinit for `ipalib.api`

### CODE REVIEW

**Comment by tiran** [comment]
@ spike77453  Please take a look. Does the PR work for you?

**Comment by spike77453** [comment]
> @ spike77453 Please take a look. Does the PR work for you?

Sure thing. Thanks a bunch!

**Comment by abbra** [comment]
@tiran so I have https://github.com/abbra/freeipa/commit/5aafe6c075d424ec6210e7e6f1a12274a3d0ba94 that allows you to plug re-acquivision callback into the process. This would make it possible to acquire cred if we don't have one.
It is in https://github.com/abbra/freeipa/tree/on-demand-kinit branch.

**Comment by spike77453** [comment]
If I get [abbra@5aafe6c](https://github.com/abbra/freeipa/commit/5aafe6c075d424ec6210e7e6f1a12274a3d0ba94) correctly, this would allow me to supply my own mechanism to do kinit. That'd be awesome since I don't always have the `kinit` command available.

**Comment by tiran** [comment]
> @tiran so I have [abbra@5aafe6c](https://github.com/abbra/freeipa/commit/5aafe6c075d424ec6210e7e6f1a12274a3d0ba94) that allows you to plug re-acquivision callback into the process. This would make it possible to acquire cred if we don't have one. It is in [abbra/freeipa@`on-demand-kinit`](https://github.com/abbra/freeipa/tree/on-demand-kinit?rgh-link-date=2024-03-22T10%3A24%3A39Z) branch.

Does the callback fire before the API objects retrieves API spec from the server? It's using the same callback, isn't it?

> If I get [abbra@5aafe6c](https://github.com/abbra/freeipa/commit/5aafe6c075d424ec6210e7e6f1a12274a3d0ba94) correctly, this would allow me to supply my own mechanism to do kinit. That'd be awesome since I don't always have the `kinit` command available.

You can do that already. Your `gssapi` password prompt should work as long as you set KRB5CCNAME, so both gssapi and rest of IPA use the same ccache.

**Comment by abbra** [comment]
Linter fails:
```
pycodestyle
-----------
local configuration: in /__w/1/s
checking ./ipaclient/install/client.py
checking ./ipaclient/install/ipa_client_automount.py
checking ./ipalib/__init__.py
./ipalib/__init__.py:966:1: W293 blank line contains whitespace
checking ./ipalib/install/kinit.py
checking ./ipalib/kinit.py
./ipalib/kinit.py:80:81: E501 line too long (82 > 80 characters)
checking ./ipalib/krb_utils.py
./ipalib/krb_utils.py:37:17: E221 multiple spaces before operator
./ipalib/krb_utils.py:37:45: E261 at least two spaces before inline comment
./ipalib/krb_utils.py:37:81: E501 line too long (89 > 80 characters)
./ipalib/krb_utils.py:38:28: E221 multiple spaces before operator
./ipalib/krb_utils.py:38:45: E261 at least two spaces before inline comment
./ipalib/krb_utils.py:38:81: E501 line too long (112 > 80 characters)
checking ./ipaserver/install/kra.py
checking ./ipaserver/install/server/replicainstall.py
checking ./ipatests/util.py
make: *** [Makefile:1248: fastcodestyle] Error 1
```

**Comment by tiran** [comment]
@abbra CI is passing now.

**Comment by abbra** [comment]
LGTM

**Comment by flo-renaud** [comment]
The change probably impacts ansible-freeipa. @t-woerner can you check the fix from this point of view? Thanks

**Comment by flo-renaud** [comment]
master:

* 38d0e74b6da63deedf3380a04dda2f6fe7c75d82 Move ipalib.install.kinit to ipalib

**Comment by flo-renaud** [comment]
@tiran a manual backport is required for ipa-4-11

**Comment by rcritten** [comment]
This PR concerns me because there is no background on the reason for the move (and no pagure issue), only the new use cases it supports. This has been moved from ipalib to ipalib.install and now back. So what was it about being in ipalib.install that required it to move?

**Pull request closed without merging**
