### PR TITLE
CA instances: make sure that an instance actually usable after a restart

### PR DESCRIPTION
**Pull request by abbra**
Restarting CA instance might take time.

Dogtag doesn't report status of its own services to init system.
However, in most cases where we expect CA to start, we actually want to
use its HTTP or HTTPS end-points.

Wait until CA status can be retrieved over HTTP end-point. This allows
us to operate in both provisioned and pre-provision environments when
certificates aren't available yet so we cannot rely on TLS.

Fixes: https://github.com/freeipa/ansible-freeipa/issues/72

### CODE REVIEW

**Comment by LucaPrete** [comment]
@abbra sure let me give it a try ;)

**Comment by tiran** [comment]
The PR is not necessary for Fedora and RHEL. ``DogtagInstance.restart()`` already waits for ``getStatus == 'running'`` through ``ipaplatform.redhat.services.RedHatCAService.restart()`` and ``wait_until_running()``. The bug is in the Debian specific service definition. It doesn't have a special case for CA instance and therefore does not wait.

## debian platform

https://github.com/freeipa/freeipa/blob/0ba25c7e68ae1a3a816070688eae460c6160acee/ipaplatform/debian/services.py#L163-L172

## redhat platform

https://github.com/freeipa/freeipa/blob/0ba25c7e68ae1a3a816070688eae460c6160acee/ipaplatform/redhat/services.py#L195-L199

https://github.com/freeipa/freeipa/blob/0ba25c7e68ae1a3a816070688eae460c6160acee/ipaplatform/redhat/services.py#L171-L187

## example log

```
>>> from ipalib import api
>>> from ipaplatform.services import service
>>> api.bootstrap(debug=True)
>>> srv = service('pki-tomcatd', api)
>>> srv.restart
<bound method RedHatCAService.restart of <ipaplatform.redhat.services.RedHatCAService object at 0x7ff0992e0080>>
>>> srv.restart()
ipa: DEBUG: Starting external process
ipa: DEBUG: args=['/bin/systemctl', 'restart', 'pki-tomcatd.target']
ipa: DEBUG: Process finished, return code=0
ipa: DEBUG: stdout=
ipa: DEBUG: stderr=
ipa: DEBUG: request POST http://master.ipa.example:8080/ca/admin/ca/getStatus
ipa: DEBUG: request body ''
ipa: DEBUG: httplib request failed:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ipapython/dogtag.py", line 232, in _httplib_request
    conn.request(method, uri, body=request_body, headers=headers)
  File "/usr/lib64/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/lib64/python3.7/http/client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib64/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/lib64/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
ipa: DEBUG: Failed to check CA status: cannot connect to 'http://master.ipa.example:8080/ca/admin/ca/getStatus': [Errno 111] Connection refused
ipa: DEBUG: Restart of pki-tomcatd.target complete
ipa: DEBUG: Waiting until the CA is running
ipa: DEBUG: request POST http://master.ipa.example:8080/ca/admin/ca/getStatus
ipa: DEBUG: request body ''
ipa: DEBUG: httplib request failed:
...
```

**Comment by tiran** [comment]
I filed https://pagure.io/freeipa/issue/7916 for Debian.

**Comment by LucaPrete** [comment]
Great!

Thanks Christian.
I'll give you in the meantime the log as soon as I can. I've just teared
down the VM last night..let me quickly bring it up again and go through the
installation.
Hopefully, something useful comes up.

In the meantime, if you have any other workaround in mind, please let us
know!

Il giorno mer 17 apr 2019 alle ore 08:58 Christian Heimes <
notifications@github.com> ha scritto:

**Comment by abbra** [comment]
Closing this one in favor of PR#3047

**Pull request closed without merging**
