### PR TITLE
DL0 removal: 1st step hide DL0 specific options and commands

### PR DESCRIPTION
**Pull request by t-woerner**
This is the first step of the DL0 removal: Hide domain level 0 specific options and programs:

- Remove `ipa-replica-prepare` (script and man page) from freeipa.spec.in and Makefile.am in install/tools and install/tools/man
- Remove replica_file support from ipa-ca-install and ipa-kra-install  (script and man page)
  - Add new error "Domain level 0 is not supported anymore" for remainaing args after parsing
  - Remove all "DOMAIN LEVEL 0" and "DOMAIN LEVEL 1" prefixes form the man pages.
- Add new error "Domain level 0 is not supported anymore" to ipaserver/install/server/_init.py if not promotion mode to ServerInstallInterface.init_ and to ServerReplicaInstall.main if replica_file is set.
- Deprecate replica_file Knob in ipalib/install/service.py
- Increase MIN_DOMAIN_LEVEL to DOMAIN_LEVEL_1 in ipalib/constants.py

### CODE REVIEW

**Comment by Tiboris** [comment]
Hello @t-woerner  please try to run  [make fastlint](https://www.freeipa.org/page/Contribute/Code#Test) there are some issues found by travis.

**Comment by t-woerner** [comment]
Here is the pagure issue: https://pagure.io/freeipa/issue/7669

**Comment by stlaz** [comment]
The `Do not install ipa-replica-prepare` removes the `ipa-replica-prepare` script from distributions. It should also be removed from the repository to avoid confusion situations like "Oh, wait, do we really have this script here even though we don't package it? Why?"
`ipa-replica-prepare` appears as a script in `install/tools` and a module in `ipaserver/install/ipa_replica_prepare.py`, both should be removed along with this change.

**Comment by abbra** [comment]
Removal is a separate story, first we disable external references. This is the purpose of the pull request we review, removal will be later.

**Comment by tiran** [comment]
master:

* f6fa2e94e40874cd8ffaaa1614e9f7e7633098b0 Do not install ipa-replica-prepare
* 38936817d28bfd0076a3a71f084bb8056c9eb0e1 Increase MIN_DOMAIN_LEVEL to DOMAIN_LEVEL_1
* 0ce79ec6f51083efe7dce724503ef502481b3f65 Mark replica_file option as deprecated
* 0377645747ee0fef4cbbd6630be1e66a8786c8e4 Raise error if DL is set to 0 or DL0 options are used
* a170b284c494703c1b3a60cd16fd93b3f0098164 Remove support for replica_file option from ipa-ca-install
* 5f5180b8254d93592eefbaf96ccf87715af43528 Remove support for replica_file option from ipa-kra-install
* 9c2b0ce77b8c7c0491bf8e2d0dbec098dc3292e8 Remove DL0 specific sections from ipa-replica-install man page
* 7e172e3b77ea08fb740ec6a2c8ffe332940e841d Remove "at DL1" from ipa-replica-manage man page
* 0eb140ea73bff9c20bc21f983dadcfe83a617d58 Remove "at DL1" from ipa-server-install man page
* b99dc46a9c9977e67641783a7b5cd69385627875 Move DL0 raises outside if existing conditionals to calm down pylint
* 2a788f1a608370bf22dcc786202c936365725a5b ipatests: Drop test_password_option_DL0
* 3b8c38ec8b5ce74fe253193c36d33cedb2107f45 ipatests/test_ipaserver/test_install/test_installer.py: Drop tempfile import
* c33cbe13fbeed3969fe1dee9074413e150ebdcc7 ipaserver/install/adtrust.py: Do not use DOMAIN_LEVEL_0 for minimum
* 94159bbe13fa25f70247ebc5373d8ab0d87ce5cc ipatests/test_xmlrpc/tracker/server_plugin.py: Increase hard coded mindomainlevel
* cb7f6b7be273618902b22ce8b1e24f5d30d777ff replicainstall: Make sure that domain fulfills minimal domain level requirement

**Pull request closed without merging**
