### PR TITLE
Add timings to install logs

### PR DESCRIPTION
**Pull request by tiran**
The logging manager now adds timings for installation steps to the
installer logs. The information can be extracted and dumped to a CSV
file with a simple grep command:

    grep -Po 'TIMING: \K.*' /var/log/ipaserver-install.log > ipaserver.csv

Signed-off-by: Christian Heimes <cheimes@redhat.com>

### CODE REVIEW

**Comment by abbra** [comment]
We already have something similar for each installer step. In Azure logs we even collect this information:
```
    echo "Installation complete. Performance of individual steps:"
    grep 'service duration:' /var/log/ipaserver-install.log | sed -e 's/DEBUG //g'


```

**Comment by rcritten** [comment]
A rebase is needed to pick up the updated dnf package for Azure to pass.

**Comment by abbra** [comment]
Not stale but a rebase is needed.

**Pull request closed without merging**
