### PR TITLE
Move ipa-otpd to $libexecdir/ipa, purge ffextension

### PR DESCRIPTION
**Pull request by tjaalton**
This is more consistent with the other daemons.

### CODE REVIEW

**Comment by mbasti-rh** [comment]
Hello @tjaalton, I cannot apply second commit, it needs rebase.

**Comment by mbasti-rh** [comment]
Fixed upstream
master:
https://fedorahosted.org/freeipa/changeset/6c53765ac1746ea3cb82554775a37fe43af062e8
https://fedorahosted.org/freeipa/changeset/6c09d6f8788b5436d6c9a5af4cc079a843f00e33

**Comment by frasertweedale** [comment]
I think this change has caused SELinux errors when starting the daemon.
(I had to `setenforce 0` to get the installer to complete).

**Comment by tjaalton** [comment]
that's possible, I'm unable to find where to fix that though

**Comment by martbab** [comment]
I have opened a bug against selinux-policy for this https://bugzilla.redhat.com/show_bug.cgi?id=1384872

**Pull request closed without merging**
