### PR TITLE
Fix errors newly exposed by pylint 2.4.0

### PR DESCRIPTION
**Pull request by stanislavlevin**
Newest Pylint introduced additional checks [1]:

- import-outside-toplevel [2]

> This check warns when modules are imported from places other
than a module toplevel, e.g. inside a function or a class.

- no-else-continue [3]

> These checks highlight unnecessary else and elif blocks after
break and continue statements.

- unnecessary-comprehension [4]

> This check is emitted when pylint finds list-, set- or
dict-comprehensions, that are unnecessary and can be rewritten
with the list-, set- or dict-constructors.

[1] https://github.com/PyCQA/pylint/blob/pylint-2.4.0/doc/whatsnew/2.4.rst
[2] https://github.com/PyCQA/pylint/issues/3067
[3] https://github.com/PyCQA/pylint/issues/2327
[4] https://github.com/PyCQA/pylint/issues/2905

Fixes: https://pagure.io/freeipa/issue/8077
Signed-off-by: Stanislav Levin <slev@altlinux.org>

### CODE REVIEW

**Comment by tiran** [comment]
I'm closing and reopening the PR to restart the Azure pipeline.

**Comment by stanislavlevin** [comment]
Let's rerun it until pass :-)

**Comment by stanislavlevin** [comment]
@tiran, I added a test commit.

**Comment by stanislavlevin** [comment]
At least, it passed on my AP:
https://dev.azure.com/slev0400/slev/_build/results?buildId=566&view=logs&j=52f5e815-4ccb-57c1-1ce3-126909c546bb

**Comment by frasertweedale** [comment]
master:

* d0b420f6dd9d5cb8019691866f6131117a12b713 Fixed errors newly exposed by pylint 2.4.0
* feae9de73ec9f084d8662690a61f5afefc9a1d6c (HEAD) Setup DNS for AP Docker container

**Pull request closed without merging**
