### PR TITLE
[Backport][ipa-4-6] Change KRA profiles in certmonger tracking so they can renew

### PR DESCRIPTION
**Pull request by rcritten**
This PR was opened manually because PR #5199 was pushed to master and backport to ipa-4-6 is required.

This also required backporting fixes from ticket https://pagure.io/freeipa/issue/7991

I'm not sure this is going to pass as I don't believe the required profile is available in downstream and a backport seems unlikely given the Fedora release is EOL.

### CODE REVIEW

**Comment by flo-renaud** [comment]
@rcritten I'm confused by your comment:

> This also required backporting fixes from ticket https://pagure.io/freeipa/issue/7991

because I thought the renewal failure was a regression introduced by the fix for 7991. Let me check if the issue is present on ipa-4-6 branch first (this backport may not be needed at all).

**Comment by flo-renaud** [comment]
I couldn't reproduce the issue on RHEL 7.9, I think we can simply close this backport and the BZ that was erroneously cloned to RHEL 7: https://bugzilla.redhat.com/show_bug.cgi?id=1872604.

**Comment by rcritten** [comment]
This is confusing to me. What profile is being used to renew the certificates then? Are the renewed certificates consistent with the originally-issued certificates?

**Comment by rcritten** [comment]
Discussed this out-of-band with @flo-renaud. We can close this because it doesn't apply.

In order to do this backport I had to also pull in https://pagure.io/freeipa/issue/7991. That PR specified to certmonger with profile to use for issuing certificates and was the root cause of the KRA renewal failures. It was using internal CA profiles.

Prior to this certmonger would renew by serial number using the existing CSR. dogtag will re-issue a new cert using that CSR so there is no need to use a profile.

Closing.

**Pull request closed without merging**
