### PR TITLE
[Backport][ipa-4-7] ipatests: add test for SSSD updating expired cache items

### PR DESCRIPTION
**Pull request by flo-renaud**
This PR was opened automatically because PR #3955 was pushed to master and backport to ipa-4-7 is required.

### CODE REVIEW

**Comment by flo-renaud** [comment]
PR was ACKed automatically because this is backport of PR #3955. Wait for CI to finish before pushing. In case of questions or problems contact @wladich who is author of the original PR.

**Comment by wladich** [comment]
Removing ACK as a temp commit was added

**Comment by wladich** [comment]
The test is failing because sssd version 2.2.2 is not available in Fedora 29, so the test needs to be marked as xfailing when running with old versions of sssd.
I will add the patch after #3924 is merged as that PR also brings convenient functions specifically for this task.

**Comment by tiran** [comment]
I'm closing the PR because the 4.7 branch has reached EOL and 4.7.5 was the last release of 4.7.

**Pull request closed without merging**
