### PR TITLE
docs: Mention that Keycloak requires openid scope

### PR DESCRIPTION
**Pull request by tiran**
See: https://www.keycloak.org/docs/latest/upgrading/index.html#userinfo-endpoint-changes

### CODE REVIEW

**Comment by abbra** [comment]
LGTM. I'd note that in the 'keycloak' template in `ipa idp-add` we default to `openid` and `email` scopes.

**Comment by abbra** [comment]
I checked the rest of the code, our tests use `ipa idp-add --provider=keycloak` and don't modify scopes, so they automatically get `openid` scope assigned.

**Comment by tiran** [comment]
I defined my own template for SSO and did not include the `openid` scope ... that's on me for trying to be clever.

**Comment by rcritten** [comment]
master:

* d97d62dead0a7b75929dec89ab072b87a0d889dd docs: Mention that Keycloak requires openid scope

**Pull request closed without merging**
