### PR TITLE
Build system refactoring phase 8: update translation system

### PR DESCRIPTION
**Pull request by pspacek**
This patch set moves IPA translation system towards standard Makefiles produced by gettextize framework.

Depends on #233 .

### CODE REVIEW

**Comment by mbasti-rh** [comment]
Lint failed

```
cd .; ./makeaci --validate
./makeaci: ipaserver/plugins/dogtag.py:244: ignoring ImportError: No module named backports_abc
cd .; ./makeapi --validate
./makeapi: ipaserver/plugins/dogtag.py:244: ignoring ImportError: No module named backports_abc
make -C ./po validate-src-strings
make[1]: Entering directory '/freeipa/po'
make[1]: Leaving directory '/freeipa/po'
make[1]: *** No rule to make target 'validate-src-strings'.  Stop.
make: *** [polint] Error 2
Makefile:1098: recipe for target 'polint' failed
```

**Comment by lslebodn** [comment]
Even after fixing lint issues there is a different issue
```
make[2]: Entering directory '/home/user/freeipa/po'
make[2]: *** No rule to make target 'distdir'.  Stop.
make[2]: Leaving directory '/home/user/freeipa/po'
make[1]: *** [Makefile:701: distdir] Error 1
make[1]: Leaving directory '/home/user/freeipa'
make: *** [Makefile:1068: rpms] Error 2
```

**Comment by lslebodn** [comment]
and also
```
Making install in po
make[1]: Entering directory '/home/user/freeipa/po'
make[1]: *** No rule to make target 'install'.  Stop.
make[1]: Leaving directory '/home/user/freeipa/po'
make: *** [Makefile:595: install-recursive] Error 1
```

**Comment by lslebodn** [comment]
The following files should be removed from git `m4/gettext.m4 m4/iconv.m4 m4/lib-ld.m4 m4/lib-link.m4 m4/lib-prefix.m4 m4/nls.m4 m4/po.m4`.

The latest versions should be used by autoreconf after installing build dependency `gettext-devel`.
Otherwise it's possible that tarball might contain outdated versions in future.

**Comment by pspacek** [comment]
This is rebased and fixed version. It should work including linters. Missing things:
- [ ] use fresh gettext files generated by autoreconf

**Comment by pspacek** [comment]
As far as I can tell all the nits mentioned below are addressed in the last version. Enjoy review :-)

**Comment by tiran** [comment]
Build is failing:

```
Can't exec "autopoint": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 345.
autoreconf: failed to run autopoint: No such file or directory
autoreconf: autopoint is needed because this package uses Gettext
```

The command is provided by gettext-devel:

```
BuildRequires: gettext-devel
```

**Comment by pspacek** [comment]
Good catch, fixed & rebased on top of current master.

**Comment by tiran** [comment]
Your patch adds ```config.rpath```. Is it necessary to include the file in source control? certmonger and sssd use the file but don't have it in git.

**Comment by lslebodn** [comment]
>Your patch adds `config.rpath`. Is it necessary to include the file in source control? certmonger and sssd use the file but don't have it in git.

Following patch fixes this issue
http://paste.fedoraproject.org/484212/47049414/

**Comment by pspacek** [comment]
@tiran You are right, I forgot to remove the `config.rpath` when `AM_GNU_GETTEXT_VERSION` macro was introduced. This version fixes this problem by removing `config.rpath` from Git.

@lslebodn We can do this change in some later PR. I do not want to mix it with translation system changes.

**Comment by mbasti-rh** [comment]
Fixed upstream
master:
https://fedorahosted.org/freeipa/changeset/4842231074683ff68be50b147560f5383aa305b6
https://fedorahosted.org/freeipa/changeset/d40c376ccc1ec9292df0306134c7bfdfd096566e
https://fedorahosted.org/freeipa/changeset/166257ec5b33dd2c95bbaf8463867c77fd6ef5db
https://fedorahosted.org/freeipa/changeset/9ef5a7de781f2508c2925225533973417458d0ea
https://fedorahosted.org/freeipa/changeset/8a7962585069d7b0ff7e8d87ce094f07c16b3cd4
https://fedorahosted.org/freeipa/changeset/4c133837d149352a68e1d6cbefbb28e4ae048755

**Pull request closed without merging**
