### PR TITLE
[Backport][ipa-4-8] SELinux: add dedicated policy for ipa-pki-retrieve-key + ipatests: enhance TestSubCAkeyReplication for better coverage

### PR DESCRIPTION
**Pull request by fcami**
MANUAL CHERRY PICK of commits in https://github.com/freeipa/freeipa/pull/5109
This PR was opened because PR https://github.com/freeipa/freeipa/pull/5109 was pushed to master and backport to ipa-4-8 is required.

### CODE REVIEW

**Comment by rcritten** [comment]
cherry-pick looks the same to me.

**Comment by fcami** [comment]
ipa-4-8:

* 52929cbadf0252fcac1019b74663a2808061ea1b ipatests: enhance TestSubCAkeyReplication
* 5a5962426d8174212f0b7efef1a9e53aaecb5901 SELinux: Add dedicated policy for ipa-pki-retrieve-key
* c126610ea6605a1ff36cecf2e2f5b2cb97130831 SELinux Policy: let custodia_t map custodia_tmp_t
* 310dbd6eec337f0747d73fa87363083a742fc5dc SELinux Policy: ipa_pki_retrieve_key_exec_t => ipa_pki_retrieve_key_t
* 0518c63768b50973f3d3129547f5b4b95335f4a8 SELinux Policy: ipa_custodia_pki_tomcat_exec_t => ipa_custodia_pki_tomcat_t
* 25cf7af0d41bbd34621f37c95802675b42baeae9 SELinux Policy: flag ipa_pki_retrieve_key_exec_t as domain_type
* 7ad04841245668e3126cb1718ef7ec1b744526e8 SELinux Policy: make interfaces for kernel modules non-optional
* 6a31605c1d249416ed7627755bca23a1cc45a581 SELinux Policy: Allow tomcat_t to read kerberos keytabs

**Pull request closed without merging**
