### PR TITLE
Allow issuing certificates with IP addresses in subjectAltName (ftweedal)

### PR DESCRIPTION
**Pull request by frasertweedale**
Continuation of https://github.com/freeipa/freeipa/pull/1700 by @ipilcher,
adding commits by @ftweedal.

Please keep both PRs open for the time being.

### CODE REVIEW

**Comment by frasertweedale** [comment]
@ipilcher thanks for your comments.

There is no CNAME loop detection, but there is a maximum depth which for practical purposes is sufficient, IMO.

The debug log cannot be seen by users, so it is of no use to users.  I'll restore the debug message anyway.  But we'll also need to rework the `ValidationError` exceptions that get thrown, so that they provide more information.

**Comment by frasertweedale** [comment]
@ipilcher I'll push an updated patch next week (hopefully early in the week).

**Comment by frasertweedale** [comment]
@ipilcher sorry, been a bit bogged down in other issues.  Will get back to this soon, I hope!

**Comment by ipilcher** [comment]
At this point, would it make sense to just use the "hacky" version in the original PR?

**Comment by BongoEADGC6** [comment]
@frasertweedale This would help for users that want to have signed Kubernetes certificates.

**Comment by cjeanneret** [comment]
Hello! any news on that one? Would be really useful in many cases.... Thanks!

**Comment by frasertweedale** [comment]
I'm hoping to push this over the line in the next couple of weeks.  Thank you all for your patience.

**Comment by frasertweedale** [comment]
Kicking this off again with a rebase.  I'll fix whatever needs fixing, add tests, and then we should be good to go.

**Comment by frasertweedale** [comment]
Couple of minor tweaks to come, as well as tests.  And a blog post to demo and plug the shiny new feature.  Should knock this off next week @ipilcher.

**Comment by frasertweedale** [comment]
Some tests are added.  There are more to write but I want to get some early feedback from a "big" CI run, while I continue expanding the tests for this feature.

**Comment by frasertweedale** [comment]
Expanded test suite.  Labels updated - this is ready for review now!

**Comment by flo-renaud** [comment]
Hi @frasertweedale 
thanks for the PR. So far I have tried (successfully) the following:

- [x] request a cert for a host with the CSR containing a SAN = host's IP @, IP @ and reverse record in IPA DNS zones
- [x] request a cert for a host with the CSR containing a SAN = another host's IP @, IP @ and reverse record in IPA DNS zones: properly get an error, but the message is `IP Address in SAN does not match any DNS name`, it would be more clear with `IP Address in SAN does not match the host DNS records`. 
- [x] request a cert for a host with the CSR containing a SAN = IP not defined in FreeIPA DNS, error
- [x] request a cert for a host with the CSR containing a SAN = IP defined in FreeIPA DNS but reverse record missing, error (but the message could be more clear with a hint to reverse DNS record missing).
- [x] create a kerberos principal alias for the host, add DNS record and reverse record, request a cert for a host with the CSR containing a SAN = IPalias, and DNSalias, success
- [x] if the DNS record or reverse record for the alias is missing, error as expected
- [x] if the CSR contains only the IPalias but not the DNS alias, error as expected

I will have a look at the xml tests later, but so far, so good.

**Comment by flo-renaud** [comment]
The xml tests are good.

My only concern is that a more specific error message would help troubleshoot in case of failure:

- IP address in SAN does not match any DNS name
- IP address in SAN does not match any of the hostnames in SAN
- reverse IP record missing

**Comment by frasertweedale** [comment]
@flo-renaud thanks for the review.  I pushed a new commit that causes different messages to be raised depending on the error:

- no forward resolution from DNS names to IP address
- no PTR record for IP address
- asymmetric PTR and forward records for IP address

**Comment by frasertweedale** [comment]
Removing backport tags - I'll wait for relevant BZs to get ACKed before backporting this feature.

**Comment by flo-renaud** [comment]
Hi @frasertweedale 
Thanks for the update, the error messages really help. Works for me, ACK.

**Comment by flo-renaud** [comment]
master:

* dccb2e0eb8953e449dadc344aaa7cd0d173b9717 Allow issuing certificates with IP addresses in subjectAltName
* 8ec4868a64a193917ee2c424ba5fdbf17f14b4ad cert-request: restrict IPAddress SAN to host/service principals
* eb70e64c0b0cd867dc0d771a3a145e5549012f92 cert-request: collect only qualified DNS names for IPAddress validation
* 9c750f0738ccc81004ced8cd1c816e48be539f8b cert-request: generalise _san_dnsname_ips for arbitrary cname depth
* e37c025dac7c89aa59de98d66a443d49f6009de5 cert-request: report all unmatched SAN IP addresses
* 474a2e6952e15fe3bf1bbf16853ecdc157355b0b Add tests for cert-request IP address SAN support
* a65c12d042e480ac5ff1c327feb94221c4b76782 cert-request: more specific errors in IP address validation

**Comment by flo-renaud** [comment]
@frasertweedale 
A manual backport is required for ipa-4-6 and ipa-4-7 branches, can you handle it? Thanks.

**Comment by frasertweedale** [comment]
@flo-renaud no worries, it's a simple backport but I intend to wait until relevant BZs have been ACKed.  Thanks for merging!

**Pull request closed without merging**
