### PR TITLE
[Backport][ipa-4-8] Simplify and make more reliable the server and client installation checks

### PR DESCRIPTION
**Pull request by rcritten**
This PR was opened manually because PR #4895 was pushed to master and backport to ipa-4-8 is required.

The merge conflict was due to 53d472b490ac7a14fc78516b448d4aa312b79b7f being only in master. Fixing this was straightforward.

### CODE REVIEW

**Comment by flo-renaud** [comment]
Hi @rcritten 
the azure failures are related to pycodestyle:
```
pycodestyle
-----------
./ipalib/install/sysrestore.py:11:1: E302 expected 2 blank lines, found 1
./ipalib/install/sysrestore.py:16:1: E302 expected 2 blank lines, found 1
./ipalib/sysrestore.py:61:28: E251 unexpected spaces around keyword / parameter equals
./ipalib/sysrestore.py:61:30: E251 unexpected spaces around keyword / parameter equals
./ipalib/sysrestore.py:61:58: E251 unexpected spaces around keyword / parameter equals
./ipalib/sysrestore.py:61:60: E251 unexpected spaces around keyword / parameter equals
./ipalib/sysrestore.py:61:81: E501 line too long (82 > 80 characters)
./ipalib/sysrestore.py:95:5: E303 too many blank lines (2)
./ipalib/sysrestore.py:137:17: E126 continuation line over-indented for hanging indent
./ipalib/sysrestore.py:166:42: E251 unexpected spaces around keyword / parameter equals
./ipalib/sysrestore.py:166:44: E251 unexpected spaces around keyword / parameter equals
./ipalib/sysrestore.py:323:28: E251 unexpected spaces around keyword / parameter equals
./ipalib/sysrestore.py:323:30: E251 unexpected spaces around keyword / parameter equals
./ipalib/sysrestore.py:323:58: E251 unexpected spaces around keyword / parameter equals
./ipalib/sysrestore.py:323:60: E251 unexpected spaces around keyword / parameter equals
./ipalib/sysrestore.py:323:81: E501 line too long (82 > 80 characters)
./ipalib/sysrestore.py:394:81: E501 line too long (87 > 80 characters)
make: *** [Makefile:1225: fastlint] Error 1
```

**Comment by rcritten** [comment]
Terrific. Fixing this is going to bring master and ipa-4-8 out-of-sync. How about I provide the lint fixes as a separate patch and then once merged, I submit the same patch to master with ipa-next flag to bring them back into sync?

**Comment by flo-renaud** [comment]
> Terrific. Fixing this is going to bring master and ipa-4-8 out-of-sync. How about I provide the lint fixes as a separate patch and then once merged, I submit the same patch to master with ipa-next flag to bring them back into sync?

That works for me.

**Comment by rcritten** [comment]
patch added

**Comment by flo-renaud** [comment]
@rcritten thanks for the backport, LGTM and tests are green.

**Comment by flo-renaud** [comment]
ipa-4-8:

* 1a47748499256544e6692ef0578073938015f7ea Simplify determining if an IPA server installation is complete
* 80a7e346a514530ea3af75d2cc338c18ec211537 Simplify determining if IPA client configuration is complete
* ee755a580c1f136b2501a395116ddf7e43c913b6 Create a common place to retrieve facts about an IPA installation
* cb6c48b21118abb198066126647709b7c9e26e10 Don't use the has_files() to know if client/server is configured
* b9e4c686634f5ba41f50f0aa0f75b5e214e25a4d Update check_client_configuration to use new client fact
* 4454af4bf31b73550eb5be2ed14be3e15c585ca3 Address legacy pylint issues in sysrestore.py

**Comment by flo-renaud** [comment]
@rcritten pushed, don't forget to backport 4454af4 Address legacy pylint issues in sysrestore.py to the master branch.

**Pull request closed without merging**
