### PR TITLE
 Fix "Configured size limit exceeded" warning on Web UI

### PR DESCRIPTION
**Pull request by serg-cymbaluk**
Suppress size limit warning in 'refresh' command.

Ticket: https://pagure.io/freeipa/issue/7603

### CODE REVIEW

**Comment by abbra** [comment]
Side from a magic number (13017) LGTM. May be, add a comment explaining where it comes from? The same constant is in use in install/ui/src/freeipa/widget.js

**Comment by serg-cymbaluk** [comment]
@abbra
Added UI constant for this warning, please check.

**Comment by abbra** [comment]
LGTM. Please remove the temp commit before pushing.

**Comment by serg-cymbaluk** [comment]
master:

* ef7a9037619ae27372df34f98204fe751f04ffcf Fix "Configured size limit exceeded" warning on Web UI

**Pull request closed without merging**
