### PR TITLE
ipatests: Add compatibility against python-cryptography 3.0

### PR DESCRIPTION
**Pull request by stanislavlevin**
The recently released python-cryptography 3.0 has backward incompatible
changes. One of them \[0\] breaks FreeIPA self-tests.

Note: this requires python-cryptography 2.7+.

[0] https://github.com/pyca/cryptography/commit/3b2102af549c1095d5478bb1243ee4cf76b9762b

Fixes: https://pagure.io/freeipa/issue/8428

### CODE REVIEW

**Comment by stanislavlevin** [comment]
The failure is not related to this PR:
```
2020-07-23 13:35:02,482    DEBUG  [ipatests.pytest_ipa.integration.host.Host.master.cmd29]   [11/31]: deploying ACME service
2020-07-23 13:35:02,482    DEBUG  [ipatests.pytest_ipa.integration.host.Host.master.cmd29]   [12/31]: starting certificate server instance
2020-07-23 13:40:21,390    DEBUG  [ipatests.pytest_ipa.integration.host.Host.master.cmd29]   [13/31]: configure certmonger for renewalsERROR [  3%]
2020-07-23 13:40:21,546    DEBUG  test_integration/test_commands.py::TestIPACommand::test_certmap_match_issue7520 ERROR [  6%]
2020-07-23 13:40:21,644    DEBUG  test_integration/test_commands.py::TestIPACommand::test_cert_find_issue7520 ERROR [  9%]
```

<details> <summary>ipaserver-install.log</summary>

```
2020-07-23T13:35:04Z DEBUG Starting external process
2020-07-23T13:35:04Z DEBUG args=['/usr/bin/openssl', 'pkcs12', '-nocerts', '-in', '/root/ca-agent.p12', '-out', '/var/lib/ipa/tmpv_q_p9ql', '-passin', 'file:/tmp/tmpnaupxymy', '-nodes']
2020-07-23T13:35:06Z DEBUG Process finished, return code=0
2020-07-23T13:35:06Z DEBUG stdout=
2020-07-23T13:35:06Z DEBUG stderr=
2020-07-23T13:35:07Z DEBUG certmonger request is in state dbus.String('GENERATING_KEY_PAIR', variant_level=1)
2020-07-23T13:35:12Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:35:17Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:35:22Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:35:27Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:35:32Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:35:37Z DEBUG wait_for_request raised request timed out
2020-07-23T13:35:37Z DEBUG Cert request 20200723133506 failed: TIMEOUT (None)
2020-07-23T13:35:37Z DEBUG 20200723133506 not in final state, continue waiting
2020-07-23T13:35:47Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:35:52Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:35:57Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:36:02Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:36:07Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:36:12Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:36:17Z DEBUG wait_for_request raised request timed out
2020-07-23T13:36:17Z DEBUG Cert request 20200723133506 failed: TIMEOUT (None)
2020-07-23T13:36:17Z DEBUG 20200723133506 not in final state, continue waiting
2020-07-23T13:36:27Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:36:32Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:36:37Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:36:42Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:36:47Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:36:52Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:36:57Z DEBUG wait_for_request raised request timed out
2020-07-23T13:36:57Z DEBUG Cert request 20200723133506 failed: TIMEOUT (None)
2020-07-23T13:36:57Z DEBUG 20200723133506 not in final state, continue waiting
2020-07-23T13:37:07Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:37:12Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:37:17Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:37:22Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:37:27Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:37:32Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:37:37Z DEBUG wait_for_request raised request timed out
2020-07-23T13:37:37Z DEBUG Cert request 20200723133506 failed: TIMEOUT (None)
2020-07-23T13:37:37Z DEBUG 20200723133506 not in final state, continue waiting
2020-07-23T13:37:47Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:37:52Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:37:57Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:38:02Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:38:07Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:38:12Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:38:17Z DEBUG wait_for_request raised request timed out
2020-07-23T13:38:17Z DEBUG Cert request 20200723133506 failed: TIMEOUT (None)
2020-07-23T13:38:17Z DEBUG 20200723133506 not in final state, continue waiting
2020-07-23T13:38:27Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:38:32Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:38:37Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:38:42Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:38:47Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:38:52Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:38:57Z DEBUG wait_for_request raised request timed out
2020-07-23T13:38:57Z DEBUG Cert request 20200723133506 failed: TIMEOUT (None)
2020-07-23T13:38:57Z DEBUG 20200723133506 not in final state, continue waiting
2020-07-23T13:39:07Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:39:12Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:39:17Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:39:22Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:39:27Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:39:32Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:39:37Z DEBUG wait_for_request raised request timed out
2020-07-23T13:39:37Z DEBUG Cert request 20200723133506 failed: TIMEOUT (None)
2020-07-23T13:39:37Z DEBUG 20200723133506 not in final state, continue waiting
2020-07-23T13:39:47Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:39:52Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:39:57Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:40:02Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:40:07Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:40:13Z DEBUG certmonger request is in state dbus.String('NEED_KEYINFO_READ_PIN', variant_level=1)
2020-07-23T13:40:18Z DEBUG wait_for_request raised request timed out
2020-07-23T13:40:18Z DEBUG Cert request 20200723133506 failed: TIMEOUT (None)
2020-07-23T13:40:18Z DEBUG Request 20200723133506 reached resubmit deadline
2020-07-23T13:40:18Z DEBUG Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ipaserver/install/service.py", line 603, in start_creation
    run_step(full_msg, method)
  File "/usr/lib/python3.8/site-packages/ipaserver/install/service.py", line 589, in run_step
    method()
  File "/usr/lib/python3.8/site-packages/ipaserver/install/cainstance.py", line 879, in __request_ra_certificate
    reqId = certmonger.request_and_wait_for_cert(
  File "/usr/lib/python3.8/site-packages/ipalib/install/certmonger.py", line 409, in request_and_wait_for_cert
    raise RuntimeError(
RuntimeError: Certificate issuance failed (TIMEOUT: None)

2020-07-23T13:40:18Z DEBUG   [error] RuntimeError: Certificate issuance failed (TIMEOUT: None)

```

</details>


<details><summary>journal</summary>

```
Jul 23 13:35:03 master.ipa.test dogtag-ipa-renew-agent-submit[21601]: usr/lib/api/apiutil.c Could not open /run/lock/opencryptoki/LCK..APIlock
Jul 23 13:35:03 master.ipa.test certmonger[21627]: 2020-07-23 13:35:03 [21627] Running enrollment/cadata helper "/usr/libexec/certmonger/dogtag-ipa-ca-renew-agent-submit".
Jul 23 13:35:03 master.ipa.test certmonger[21628]: 2020-07-23 13:35:03 [21628] Running enrollment/cadata helper "/usr/libexec/certmonger/dogtag-ipa-ca-renew-agent-submit".
Jul 23 13:35:03 master.ipa.test certmonger[21601]: Error opening "/etc/httpd/alias/pwdfile.txt": No such file or directory.
Jul 23 13:35:03 master.ipa.test certmonger[21629]: 2020-07-23 13:35:03 [21629] Running enrollment/cadata helper "/usr/libexec/certmonger/dogtag-ipa-ca-renew-agent-submit".
Jul 23 13:35:03 master.ipa.test certmonger[21630]: 2020-07-23 13:35:03 [21630] Running enrollment/cadata helper "/usr/libexec/certmonger/dogtag-ipa-ca-renew-agent-submit".
Jul 23 13:35:03 master.ipa.test certmonger[21632]: 2020-07-23 13:35:03 [21632] Running enrollment/cadata helper "/usr/libexec/certmonger/dogtag-ipa-ca-renew-agent-submit".
Jul 23 13:35:03 master.ipa.test certmonger[21633]: 2020-07-23 13:35:03 [21633] Running enrollment/cadata helper "/usr/libexec/certmonger/dogtag-ipa-ca-renew-agent-submit".
Jul 23 13:35:03 master.ipa.test certmonger[21634]: 2020-07-23 13:35:03 [21634] Running enrollment/cadata helper "/usr/libexec/certmonger/dogtag-ipa-ca-renew-agent-submit".
Jul 23 13:35:03 master.ipa.test certmonger[21635]: 2020-07-23 13:35:03 [21635] Running enrollment/cadata helper "/usr/libexec/certmonger/dogtag-ipa-ca-renew-agent-submit".
Jul 23 13:35:03 master.ipa.test certmonger[21636]: 2020-07-23 13:35:03 [21636] Running enrollment/cadata helper "/usr/libexec/certmonger/dogtag-ipa-ca-renew-agent-submit".
Jul 23 13:35:03 master.ipa.test certmonger[21637]: 2020-07-23 13:35:03 [21637] Running enrollment/cadata helper "/usr/libexec/certmonger/dogtag-ipa-ca-renew-agent-submit".
Jul 23 13:35:04 master.ipa.test certmonger[21638]: 2020-07-23 13:35:04 [21638] Running enrollment/cadata helper "/usr/libexec/certmonger/dogtag-ipa-ca-renew-agent-submit".
Jul 23 13:35:04 master.ipa.test certmonger[21639]: 2020-07-23 13:35:04 [21639] Running enrollment/cadata helper "/usr/libexec/certmonger/dogtag-ipa-ca-renew-agent-submit".
Jul 23 13:35:04 master.ipa.test certmonger[21640]: 2020-07-23 13:35:04 [21640] Running enrollment/cadata helper "/usr/libexec/certmonger/dogtag-ipa-ca-renew-agent-submit".
Jul 23 13:35:04 master.ipa.test certmonger[21641]: 2020-07-23 13:35:04 [21641] Running enrollment/cadata helper "/usr/libexec/certmonger/dogtag-ipa-ca-renew-agent-submit".
Jul 23 13:35:06 master.ipa.test certmonger[21645]: 2020-07-23 13:35:06 [21645] Running enrollment/cadata helper "/usr/libexec/certmonger/dogtag-submit".
Jul 23 13:35:06 master.ipa.test certmonger[21646]: 2020-07-23 13:35:06 [21646] Running enrollment/cadata helper "/usr/libexec/certmonger/dogtag-submit".
Jul 23 13:35:06 master.ipa.test certmonger[21647]: 2020-07-23 13:35:06 [21647] Running enrollment/cadata helper "/usr/libexec/certmonger/dogtag-submit".
Jul 23 13:35:06 master.ipa.test certmonger[21648]: 2020-07-23 13:35:06 [21648] Running enrollment/cadata helper "/usr/libexec/certmonger/dogtag-submit".
Jul 23 13:35:06 master.ipa.test certmonger[21649]: 2020-07-23 13:35:06 [21649] Running enrollment/cadata helper "/usr/libexec/certmonger/dogtag-submit".
Jul 23 13:35:06 master.ipa.test certmonger[21650]: 2020-07-23 13:35:06 [21650] Running enrollment/cadata helper "/usr/libexec/certmonger/dogtag-submit".
Jul 23 13:35:06 master.ipa.test certmonger[21651]: 2020-07-23 13:35:06 [21651] Running enrollment/cadata helper "/usr/libexec/certmonger/dogtag-submit".
Jul 23 13:35:06 master.ipa.test certmonger[21652]: 2020-07-23 13:35:06 [21652] Running enrollment/cadata helper "/usr/libexec/certmonger/dogtag-submit".
Jul 23 13:35:07 master.ipa.test dogtag-submit[21647]: usr/lib/api/apiutil.c Could not open /run/lock/opencryptoki/LCK..APIlock
Jul 23 13:35:07 master.ipa.test certmonger[21660]: 2020-07-23 13:35:07 [21660] Internal error reading key from "/var/lib/ipa/ra-agent.key".
Jul 23 13:35:07 master.ipa.test certmonger[21660]: 2020-07-23 13:35:07 [21660] error:0909006C:PEM routines:get_name:no start line
Jul 23 13:35:08 master.ipa.test certmonger[21662]: 2020-07-23 13:35:08 [21662] Error opening key file "/var/lib/ipa/ra-agent.key" for writing: File exists.
Jul 23 13:35:08 master.ipa.test certmonger[21662]: 2020-07-23 13:35:08 [21662] Attempting to open key file "/var/lib/ipa/ra-agent.key.zg2oA13s.key" for writing.
Jul 23 13:35:08 master.ipa.test certmonger[21663]: 2020-07-23 13:35:08 [21663] Internal error reading key from "/var/lib/ipa/ra-agent.key".
Jul 23 13:35:08 master.ipa.test certmonger[21663]: 2020-07-23 13:35:08 [21663] error:0909006C:PEM routines:get_name:no start line
Jul 23 13:35:11 master.ipa.test certmonger[21581]: 2020-07-23 13:35:11 [21581] No hooks set for ca-pre-save command.
Jul 23 13:35:11 master.ipa.test certmonger[21581]: 2020-07-23 13:35:11 [21581] No hooks set for ca-post-save command.
Jul 23 13:35:11 master.ipa.test certmonger[21665]: 2020-07-23 13:35:11 [21665] Certificate "Local Signing Authority" valid for 31535994s.
```

</details>

**Comment by rcritten** [comment]
My only hesitation is that Fedora 31 still has python3-cryptography-2.6.1-3.fc31.x86_64 which will not work with this. Given it is just in tests it may be ok. @netoarmando what do you think?

**Comment by netoarmando** [comment]
@rcritten if merged, some nightly runs will fail for Fedora 31 until the release of Fedora 33 (~November).

@tiran any reason not to update the package to 2.8 for Fedora 31?

**Comment by rcritten** [comment]
@tiran thoughts on python-cryptography?

**Comment by rcritten** [comment]
Removing ack. This does not work on F31. We still test on F31. So the question is, do we work around this in freeIPA or release an updated python3-cryptography in F31.

**Comment by abbra** [comment]
@stanislavlevin could you please add a fallback to the old method in case the original one does not exist? This would cover f31 environment.

**Comment by stanislavlevin** [comment]
If I understand correctly the FreeIPA workaround has been chosen. I'll check.

**Comment by stanislavlevin** [comment]
The method signature was not changed, thus, I made the version-based 'if-else' workaround instead of an implementation-based one.

**Comment by rcritten** [comment]
This looks good. Can you add a reference to Fedora 31 or F31 in there as well? It will tell us when we can remove this workaround.

**Comment by stanislavlevin** [comment]
I mentioned F31 in the code comment.
Below cryptography versions across Fedoras:

Fedora | cryptography
-----------|--------------------
33 | 3.0-1 |  
32 | 2.8-2 |  
31 | 2.6.1-3 |

**Comment by tiran** [comment]
RHEL 8 has python-cryptography 2.3.

**Comment by abbra** [comment]
So we would need to keep the fallback for quite some time.

**Comment by stanislavlevin** [comment]
Should I delete 'remove this workaround on EOL of Fedora31'?

**Comment by abbra** [comment]
The update you made is fine to me. I guess there are other platforms that would be affected by this, not just RHEL 8, so a generic statement like you added is perfectly fine. Thank you!

**Comment by abbra** [comment]
A test `test_integration/test_external_ca.py::TestSelfExternalSelf::test_issuerDN_after_renew_to_external` failed:
```
[ipatests.pytest_ipa.integration.host.Host.master.cmd65] RUN ['ipa', 'ca-show', 'ipa']
[ipatests.pytest_ipa.integration.host.Host.master.cmd65] ipa: ERROR: cannot connect to 'https://master.ipa.test/ipa/session/json': [Errno 111] Connection refused
[ipatests.pytest_ipa.integration.host.Host.master.cmd65] Exit code: 1
ipa: ERROR: stderr: ipa: ERROR: cannot connect to 'https://master.ipa.test/ipa/session/json': [Errno 111] Connection refused
```
It is refused because somehow we have damaged `/etc/ipa/ca.crt`, may be due to a race condition when replacing the `ca.crt` on renewal to an external CA?

```
[Thu Aug 06 08:34:32.435362 2020] [suexec:notice] [pid 25639:tid 139877776810304] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
AH00526: Syntax error on line 126 of /etc/httpd/conf.d/ssl.conf:
SSLCACertificateFile: file '/etc/ipa/ca.crt' does not exist or is empty
```

**Comment by abbra** [comment]
Failed test run logs: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/7e55b73e-d7bd-11ea-985b-fa163e2d2908/

**Comment by abbra** [comment]
I think the failed test (which now passed, so it is a race condition) would be fixed with PR#4989.

**Comment by abbra** [comment]
ACK

**Comment by rcritten** [comment]
master:

* 06a344a5d932db148b1921c03906d2843b3622cb ipatests: Add compatibility against python-cryptography 3.0

**Pull request closed without merging**
