### PR TITLE
Run test_fips in DS and PKI nightly

### PR DESCRIPTION
**Pull request by tiran**

### CODE REVIEW

**Comment by flo-renaud** [comment]
LGTM, but azure pipeline is failing while trying to publish the packages. Problably an infra issue, you can try to force-push.

**Comment by tiran** [comment]
> LGTM, but azure pipeline is failing while trying to publish the packages. Problably an infra issue, you can try to force-push.

Azure tests have been failing all day with different infrastructure related issues. I have restarted the pipeline.

**Comment by tiran** [comment]
master:

* a90eefafc98e1bf5a379440695d58f00a9a70e45 Run test_fips in DS and PKI nightly

**Pull request closed without merging**
