### PR TITLE
Extend Sub CA replication test

### PR DESCRIPTION
**Pull request by tiran**
Test more scenarios like replication replica -> master, validate keys.

See: https://pagure.io/freeipa/issue/7590
Signed-off-by: Christian Heimes <cheimes@redhat.com>

### CODE REVIEW

**Comment by rcritten** [comment]
Hopefully this test will start working once https://github.com/dogtagpki/jss/pull/13 merges.

**Comment by rcritten** [comment]
Official JSS build: https://bodhi.fedoraproject.org/updates/FEDORA-2018-c5ec2badbe

**Comment by rcritten** [comment]
This looks good to me. @tiran do we want to wait until the official JSS lands before pushing?

**Comment by tiran** [comment]
@rcritten Let's get more karma and ask Endi to push the fix ASAP.

**Comment by tiran** [comment]
master:

* 6896c90eb25ffa6ab1ae64efa06b1f8c854aaed6 Extend Sub CA replication test
* a7627a7d8a226dc274ba8e9fdd0804edefdba2c6 Require JSS 4.4.5 with replication fixes

**Pull request closed without merging**
