### PR TITLE
ipatests: kinit_as_user+create_active_user: collect kdcinfo.REALM

### PR DESCRIPTION
**Pull request by fcami**
Collecting:
/var/lib/sss/pubconf/kdcinfo.$REALM
will help determine how SSSD was selecting which KRB5KDC to use in both create_active_user and kinit_as_user.

Fixes: https://pagure.io/freeipa/issue/8510
Signed-off-by: François Cami <fcami@redhat.com>

### CODE REVIEW

**Comment by fcami** [comment]
Please hold and do not re-run PR-CI

**Comment by fcami** [comment]
With the change, this is [added](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/cb540e46-fd88-11ea-b879-fa163e74bb0d):
```
INFO     ipatests.pytest_ipa.integration.tasks:tasks.py:2020 Collecting kdcinfo log from: master.ipa.test
INFO     ipatests.pytest_ipa.integration.host.Host.master.IPAOpenSSHTransport:transport.py:436 GET /var/lib/sss/pubconf/kdcinfo.IPA.TEST
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd68:transport.py:513 RUN ['cat', '/var/lib/sss/pubconf/kdcinfo.IPA.TEST']
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd68:transport.py:217 Exit code: 0
INFO     ipatests.pytest_ipa.integration.tasks:tasks.py:2027 kdcinfo master.ipa.test contains:
b'192.168.122.69\n'
```

**Comment by fcami** [comment]
When this [fails](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/521a5fdc-fe3f-11ea-b659-fa163e7f018b/report.html):
```
INFO     ipatests.pytest_ipa.integration.tasks:tasks.py:2020 Collecting kdcinfo log from: master.ipa.test
INFO     ipatests.pytest_ipa.integration.host.Host.master.IPAOpenSSHTransport:transport.py:436 GET /var/lib/sss/pubconf/kdcinfo.IPA.TEST
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd68:transport.py:513 RUN ['cat', '/var/lib/sss/pubconf/kdcinfo.IPA.TEST']
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd68:transport.py:557 cat: /var/lib/sss/pubconf/kdcinfo.IPA.TEST: No such file or directory
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd68:transport.py:217 Exit code: 1
```

**Comment by fcami** [comment]
The new version only breaks when the kinit's return code is >0.
Failing to retrieve the kdcinfo file is not an issue for IPA per se.

Another run showing empty kdcinfo:
http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/b4b29442-fea4-11ea-b6de-fa163ebb6b2b/report.html

```
[ipatests.pytest_ipa.integration.host.Host.master.cmd67] Password for nonadmin@IPA.TEST: 
[ipatests.pytest_ipa.integration.host.Host.master.cmd67] [24096] 1600980648.561281: SPAKE key generated with pubkey D44D37FE29E02B8771396C7EEAFF3B68E7FBFB948C01942FDBF966F7114A095C
[ipatests.pytest_ipa.integration.host.Host.master.cmd67] [24096] 1600980648.561282: SPAKE algorithm result: 1C72AE453C7FB02F8420FEFB3BCC0DD41F8FEDD102EB014212C955CF4F484990
[ipatests.pytest_ipa.integration.host.Host.master.cmd67] [24096] 1600980648.561283: SPAKE final transcript hash: A38471527EC416C471738CEFBEE0931CC4017FE64253B3FDB766428EE4FBC3CB
[ipatests.pytest_ipa.integration.host.Host.master.cmd67] [24096] 1600980648.561284: Sending SPAKE response
[ipatests.pytest_ipa.integration.host.Host.master.cmd67] [24096] 1600980648.561285: Preauth module spake (151) (real) returned: 0/Success
[ipatests.pytest_ipa.integration.host.Host.master.cmd67] [24096] 1600980648.561286: Produced preauth for next request: PA-FX-COOKIE (133), PA-SPAKE (151)
[ipatests.pytest_ipa.integration.host.Host.master.cmd67] [24096] 1600980648.561287: Sending request (431 bytes) to IPA.TEST
[ipatests.pytest_ipa.integration.host.Host.master.cmd67] [24096] 1600980648.561288: Resolving hostname master.ipa.test
[ipatests.pytest_ipa.integration.host.Host.master.cmd67] [24096] 1600980648.561289: Initiating TCP connection to stream 192.168.122.190:88
[ipatests.pytest_ipa.integration.host.Host.master.cmd67] [24096] 1600980648.561290: Sending TCP request to stream 192.168.122.190:88
[ipatests.pytest_ipa.integration.host.Host.master.cmd67] [24096] 1600980648.561291: Received answer (1521 bytes) from stream 192.168.122.190:88
[ipatests.pytest_ipa.integration.host.Host.master.cmd67] [24096] 1600980648.561292: Terminating TCP connection to stream 192.168.122.190:88
[ipatests.pytest_ipa.integration.host.Host.master.cmd67] [24096] 1600980648.561293: Response was from master KDC
[ipatests.pytest_ipa.integration.host.Host.master.cmd67] [24096] 1600980648.561294: AS key determined by preauth: aes256-cts/3D70
[ipatests.pytest_ipa.integration.host.Host.master.cmd67] [24096] 1600980648.561295: Decrypted AS reply; session key is: aes256-cts/EBCD
[ipatests.pytest_ipa.integration.host.Host.master.cmd67] [24096] 1600980648.561296: FAST negotiation: available
[ipatests.pytest_ipa.integration.host.Host.master.cmd67] [24096] 1600980648.561297: Initializing KCM:0 with default princ nonadmin@IPA.TEST
[ipatests.pytest_ipa.integration.host.Host.master.cmd67] [24096] 1600980648.561298: Storing nonadmin@IPA.TEST -> krbtgt/IPA.TEST@IPA.TEST in KCM:0
[ipatests.pytest_ipa.integration.host.Host.master.cmd67] [24096] 1600980648.561299: Storing config in KCM:0 for krbtgt/IPA.TEST@IPA.TEST: fast_avail: yes
[ipatests.pytest_ipa.integration.host.Host.master.cmd67] [24096] 1600980648.561300: Storing nonadmin@IPA.TEST -> krb5_ccache_conf_data/fast_avail/krbtgt\/IPA.TEST\@IPA.TEST@X-CACHECONF: in KCM:0
[ipatests.pytest_ipa.integration.host.Host.master.cmd67] [24096] 1600980648.561301: Storing config in KCM:0 for krbtgt/IPA.TEST@IPA.TEST: pa_type: 151
[ipatests.pytest_ipa.integration.host.Host.master.cmd67] [24096] 1600980648.561302: Storing nonadmin@IPA.TEST -> krb5_ccache_conf_data/pa_type/krbtgt\/IPA.TEST\@IPA.TEST@X-CACHECONF: in KCM:0
[ipatests.pytest_ipa.integration.host.Host.master.cmd67] Exit code: 0
[ipatests.pytest_ipa.integration.tasks] Collecting kdcinfo log from: master.ipa.test
[ipatests.pytest_ipa.integration.host.Host.master.IPAOpenSSHTransport] GET /var/lib/sss/pubconf/kdcinfo.IPA.TEST
[ipatests.pytest_ipa.integration.host.Host.master.cmd68] RUN ['cat', '/var/lib/sss/pubconf/kdcinfo.IPA.TEST']
[ipatests.pytest_ipa.integration.host.Host.master.cmd68] cat: /var/lib/sss/pubconf/kdcinfo.IPA.TEST: No such file or directory
[ipatests.pytest_ipa.integration.host.Host.master.cmd68] Exit code: 1
ipa: WARNING: Exception collecting kdcinfo.IPA.TEST: File '/var/lib/sss/pubconf/kdcinfo.IPA.TEST' could not be read
SSSD is able to function without this file but logon attempts immediately after a password change might break.
```

**Comment by fcami** [comment]
This is ready for review.
@sumit-bose could you please have a look?
Please mention whether you consider the absence of the kdcinfo file a hard failure, in this case the first commit is right ; otherwise I'll squash the two test code changes so that the test silently continues when (kinit succeeds AND kdcinfo is absent).

**Comment by sumit-bose** [comment]
Hi,

I think the reason why the kdcinfo file is missing in some cases is that SSSD is offline or not online yet. If SSSD was started only shortly before the test depending on DNS lookups and other network operations SSSD might not be completely online and hence the kdcinfo file was not created yet.

You can check the online status with 'sssctl domain-status --online IPA.TEST'. But you should do this before checking if the kdcinfo file is present because if you check it afterwards SSSD might be already online when calling sssctl. Otherwise there is a race as well but here if sssctl says `offline` you know at least that it might happen that SSSD is offline when you try to check the prescence of the kdcinfo file.

HTH

bye,
Sumit

**Comment by rcritten** [comment]
Just a nit about the commit message, should it say it Fixes it? Maybe Related?

**Comment by fcami** [comment]
Re commit message, the ticket is about enhancing the test so that we get more debug information, so Fixes: is probably best, but we don't have set-in-stone rules about that yet.

**Comment by flo-renaud** [comment]
LGTM, the commit will help diagnose issues. You can remove the temp commits.

**Comment by flo-renaud** [comment]
master:

* a63eeaaec6dfa939faa2958354aa41da46a07cee ipatests: add check_if_sssd_is_online
* 884e0d36e9f655d0456229d0e259592e65714660 ipatests: add get_kdcinfo
* e0586f33a60a44e340889ec5adea0800bde21592 ipatests: create_active_user improvements
* 5d95794edfc41ffc61bd2eb38621837dbdb01e85 ipatests: kinit_as_user improvements

**Pull request closed without merging**
