### PR TITLE
baseuser: fix ipanthomedirectorydrive option name

### PR DESCRIPTION
**Pull request by pvoborni**
It should be ipanthomedirectorydrive and not ipanthomedirectoryrive.

This fixes showing the field in Web UI and also should fix CLI as it
probably never worked.

Signed-off-by: Petr Vobornik <pvoborni@redhat.com>

### CODE REVIEW

**Comment by abbra** [comment]
LGTM. We don't need to rise API version here as this is really a typo fix.

**Comment by pvoborni** [comment]
I wonder what are the next steps in this PR. It is approved by @abbra, but it doesn't have ACK label. Do we need another reviewer?

**Comment by abbra** [comment]
I added an ACK.

**Comment by rcritten** [comment]
master:

* 3912e8e6739058ef8fcb2964fda0edc3ee23fc1e baseuser: fix ipanthomedirectorydrive option name

**Pull request closed without merging**
