### PR TITLE
test_dnssec: re-add named-pkcs11 workarounds

### PR DESCRIPTION
**Pull request by tomaskrizek**
DNSSEC tests starrted to fail again, probably due to a bug in
some underlaying component.

This reverts commit 8bc677512296a7e94c29edd0c1a96aa7273f352a
and makes the xfail test check less strict - it will no longer
mark the test suite red if it passes.

Related https://pagure.io/freeipa/issue/5348

### CODE REVIEW

**Comment by tomaskrizek** [comment]
This does seem to fix the test suite.

Link to test run: https://fedorapeople.org/groups/freeipa/prci/jobs/2fffc1c0-81ac-11e7-97c3-001a4a2316f3/

It's interesting that the xfail has passed -- perhaps the issue isn't always happen, or the added test doesn't correctly cover the issue.

**Comment by tomaskrizek** [comment]
2 failed tests in the second run, the test suite is either unstable or the problem may be elsewhere.

https://fedorapeople.org/groups/freeipa/prci/jobs/e1c98672-81c8-11e7-bee1-001a4a2316f3/

**Comment by tiran** [comment]
@tomaskrizek suggested to fix and merge this fix first for #1011

**Comment by tiran** [comment]
I have created a new PR #1559 to finish @tomaskrizek PR.

**Pull request closed without merging**
