### PR TITLE
spec file: clean up BuildRequires

### PR DESCRIPTION
**Pull request by jcholast**
Add missing cyrus-sasl-devel, python-cffi, python-custodia, python-nose,
python-paste, python-sssdconfig and systemd-python BuildRequires.

Remove unused custodia, java-headless, m4, policycoreutils,
python-kdcproxy, python-rhsm, pyOpenSSL and systemd-units BuildRequires.

Correct versioned BuildRequires and provide explanatory comments.

**spec file: do not include BuildRequires for lint by default**

Lint is never executed from rpmbuild, so the BuildRequires for lint are
purely informational.

Include them only if %with_lint RPM macro is specified.

**pylint: enable the import-error check**

Check for import errors with pylint to make sure new python package
dependencies are not overlooked.

**ipaserver: remove ipalib import from setup.py**

Instead of importing ipalib to get IPA version string, create setup.py from
a template and have the version string automatically filled in.

This makes it possible to build the ipaserver package without having to
have ipalib dependencies installed.

**makeapi, makeaci: do not fail on missing imports**

Add import hook to makeapi and makeaci which makes them ignore import
errors in modules in our source tree and instead print a warning.

This makes it possible to build IPA without having to have most of our
runtime dependencies installed.

**client: remove unused libcurl build dependency**

**pwpolicy: do not run klist on import**

On pwpolicy module import, "klist -V" is run to determine if the installed
krb5 version supports account lockout (>= 1.8).

Remove the check, as we require a krb5 version which does support account
lockout (1.12).

### CODE REVIEW

**Comment by pspacek** [comment]
Interestingly, the CI failed with following errors:

************* Module ipatests.test_xmlrpc.test_automount_plugin

ipatests/test_xmlrpc/test_automount_plugin.py:34: [E0401(import-error), ] Unable to import 'nose.tools')

************* Module ipatests.test_xmlrpc.test_hbactest_plugin

ipatests/test_xmlrpc/test_hbactest_plugin.py:27: [E0401(import-error), ] Unable to import 'nose.tools')

************* Module ipatests.test_xmlrpc.test_pwpolicy_plugin

ipatests/test_xmlrpc/test_pwpolicy_plugin.py:24: [E0401(import-error), ] Unable to import 'nose.tools')

************* Module ipatests.test_xmlrpc.test_external_members

ipatests/test_xmlrpc/test_external_members.py:24: [E0401(import-error), ] Unable to import 'nose')

************* Module lite-server

lite-server.py:36: [E0401(import-error), ] Unable to import 'paste')

lite-server.py:37: [E0401(import-error), ] Unable to import 'paste.gzipper')

lite-server.py:38: [E0401(import-error), ] Unable to import 'paste.urlmap')

************* Module ipa-ods-exporter

daemons/dnssec/ipa-ods-exporter:29: [E0401(import-error), ] Unable to import 'systemd.daemon')

daemons/dnssec/ipa-ods-exporter:30: [E0401(import-error), ] Unable to import 'systemd.journal')


Weren't you to eager in pruning BuildRequires? :-)

**Comment by mbasti-rh** [comment]
Please update BUILD.txt with how to run pylint with build, probably freeipa.org should be updated as well

**Comment by jcholast** [comment]
@pspacek, @mbasti-rh, fixed.

**Comment by pspacek** [comment]
- python2-dateutil and python2-sss-murmur packages are missing in with_lint condition.
 - the message from import error was confusing to me:

> ipaserver/plugins/dogtag.py:244: No module named backports_abc
> ipaserver/plugins/dogtag.py:244: No module named backports_abc

In person, we were talking about some changes in the message. I would try something like this:
> argv[0]: ipaserver/plugins/dogtag.py:244: No module named backports_abc. Ignoring missing module. It might be required only for lint or only conditionally.

**Comment by stlaz** [comment]
For some reason, after running `sudo dnf builddep freeipa.spec`, which is successful, if I run the same command again, if fails:
```
[login@vm freeipa-git]$ sudo dnf builddep --spec freeipa.spec
Last metadata expiration check: 0:23:03 ago on Wed Oct 19 13:53:25 2016.
Failed to open: 'freeipa.spec', not a valid spec file.
Error: Some packages could not be found.
```
Adding `-v` or `-d 10` options did not provide any more useful output about this error.

**Comment by martbab** [comment]
On F24 you need to explicitly install python-srpm-macros due to broken package dependencies

    dnf install -y python-srpm-macros

otherwise dnf/rpm is unable to expand python-specific macros in the spec and fails.

**Comment by stlaz** [comment]
@martbab Thanks, that worked. ACK.

**Comment by pspacek** [comment]
Version rebased on top of current master (without PR 171) is available from https://github.com/pspacek/freeipa/tree/pr159-rebase .

**Comment by pspacek** [comment]
Commit 6256e8014aa3d68dc46e6c878be813473bffd1ac breaks pylint because it is not compatible with ipaplatform implementation introduced in 8f98fa1bd5f1da207fab6f89b75e0cdc19d00797. I do not care which part will be changed but we need to fix this first. (Either change ipaplatform to not confuse pylint or improve pylint plugin.)

**Comment by pspacek** [comment]
This pull request was (again) rebased on top of PR#171. PR#171 changes ipaplatform handling to symlinks so the issue caused by `__path__` trick should go away. I.e. the rebased version is functional only with PR#171.

**Comment by pspacek** [comment]
The rebased PR have passed build + all XMLRPC tests in Jenkins:
job/build_refactoring-build-f24build_refactoring/18/

The test included everything up to e33e00bdc17dc164a1c143d8cba85f5df6de9d7e

**Comment by dkupka** [comment]
Fixed upstream
master:
https://fedorahosted.org/freeipa/changeset/21395d1724e6bf044438a8bc25ba028ed38cde8c
https://fedorahosted.org/freeipa/changeset/1077743d90902fc776f837f8486fa7f08b560673
https://fedorahosted.org/freeipa/changeset/0d370a959b6b55f995661b2febe55c379065c4d9
https://fedorahosted.org/freeipa/changeset/0b91735c79a0ba577f9540e946180760a97913a4
https://fedorahosted.org/freeipa/changeset/9b534238157e003d2d7c3e1a7fd27531ab1dfd25
https://fedorahosted.org/freeipa/changeset/9477e39b4b267922dbdd86a65869f773d980df8e
https://fedorahosted.org/freeipa/changeset/cc5ad6b3f951a6cb8298181690248d680c39922b

**Pull request closed without merging**
