### PR TITLE
.gitignore: add ipa-cert-fix program

### PR DESCRIPTION
**Pull request by frasertweedale**

### CODE REVIEW

**Comment by flo-renaud** [comment]
LGTM, I just added the re-run label because PRCI had issues with
`Process "vagrant provision" exited with error code 1`

**Comment by frasertweedale** [comment]
@flo-renaud don't worry about CI; prci won't come to the party due to https://github.com/freeipa/freeipa/pull/3210 not being merged yet, due to failing tests, which I tried (and failed so far) to address with https://github.com/freeipa/freeipa/pull/3216.  So we can either merge it despite failing tests, because it is trivial, or wait out a fix, because it is trivial :D

**Comment by abbra** [comment]
@frasertweedale do we need this in ipa-4-7?

**Comment by frasertweedale** [comment]
@abbra, less it looks like it's needed on ipa-4-7 too.

**Comment by frasertweedale** [comment]
master:

* df99680eadcce43582d925711acab04f521e4aad (HEAD) .gitignore: add ipa-cert-fix program

**Pull request closed without merging**
