### PR TITLE
ldap2: fix crash in development mode

### PR DESCRIPTION
**Pull request by HonzaCholasta**
Do not set or delete attributes directly on the ldap2 instance, as that
raises an AttributeError in development mode because of ReadOnly locking.

Use the usual workaround of `object.__setattr__` and `object.__delattr__`
to fix the issue.

https://pagure.io/freeipa/issue/6625

### CODE REVIEW

**Comment by tomaskrizek** [comment]
Seems to work all right, but the locking issue still affects other parts of the code. For example, `ipa cert-show` in development mode fails with:

```
AttributeError: locked: cannot set ra_lightweight_ca.cookie 
```

I'm not sure if that's in the ticket's scope or not.

**Comment by HonzaCholasta** [comment]
Let's see what Travis detects.

**Comment by HonzaCholasta** [comment]
Travis didn't detect anything else, so I think we are good to go. Shall we keep the `.test_runner_config.yaml` change? (@martbab?)

**Comment by martbab** [comment]
Yes but please split it into a separate patch so that CI-related changes are tracked separately and do not pollute the changes in the code.

**Comment by HonzaCholasta** [comment]
Turns out unsetting mode in default.conf is not good enough, one has to explicitly set it to "development" to enable development mode, because "production" is the default.

Let's see if Travis detects something this time.

**Comment by HonzaCholasta** [comment]
OK everything is green now.

**Comment by MartinBasti** [comment]
master:

* 8fdd7a9ffc263c1198afa5479cda41d319f11d91 backend plugins: fix crashes in development mode
* fe4489ede2b40902fb7d734d04a1f997c6df86fb Travis CI: run tests in development mode

**Pull request closed without merging**
