### PR TITLE
WebUI: services without canonical name are shown correctly

### PR DESCRIPTION
**Pull request by pvomacka**
There is a change introduced in 4.4 that new services have canonical name. The old ones
didn't have it, therefore these services were not correctly displayed in WebUI.

This patch adds support for this type of services. Service name is taken from
'krbprincipalname' attribute in case that 'krbcanonicalname' attribute is not present
in server response.

https://fedorahosted.org/freeipa/ticket/6397

### CODE REVIEW

**Comment by pvoborni** [comment]
Works for me. Code look OK. I have only one minor nitpick: name of the adaper. Current is `SearchTableColumnFieldAdapter` imho better would be e.g. `AlternateAttrFieldAdapter`. I.e., to describe function and not place of use. IMO it can be even placed in field.js

If you don't want to address that then ACK.

**Comment by pvomacka** [comment]
Thank you for review. I moved the adapter into field.js and also renamed it. Proposed name looks better.

**Comment by pvomacka** [comment]
I forgot to improve AlternateAttrFieldAdapter comment. Fixed now.

**Comment by pvoborni** [comment]
new version works for me ACK

**Comment by pvoborni** [comment]
Fixed upstream
master:
https://fedorahosted.org/freeipa/changeset/4f760dffa011a3656b6072c74088b497ff416a8d
ipa-4-4:
https://fedorahosted.org/freeipa/changeset/599a7ff90d7dddc6b5804ed6844e5d3faff017ed

**Pull request closed without merging**
