### PR TITLE
Spec file: bump bind version on f37+

### PR DESCRIPTION
**Pull request by flo-renaud**
### Spec file: bump bind version on f37+

On fedora37+, require at least bind 9.18.7-1 to avoid
dnssec regression (see BZ#2117342) related to bind and
OpenSSL 3.0 engine support.

Fixes: https://pagure.io/freeipa/issue/9216

### ipatests: re-enable dnssec tests

On fedora 37+ the dnssec tests were broken. The tests
launched for each pull request were disabled or marked
as xfail.
With the bump of bind version, they should now succeed
and can be re-enabled.

Related: https://pagure.io/freeipa/issue/9216

### CODE REVIEW

**Comment by flo-renaud** [comment]
Fedora 37 is not officially released yet, need to wait a bit before the update is available. Setting WIP in the mean time

**Comment by abbra** [comment]
LGTM. Please remove the temp commit.

**Comment by flo-renaud** [comment]
@abbra thanks for the review. Temp commit removed and tests are green.

**Comment by flo-renaud** [comment]
master:

* dface55b1f6b86b3c53ea08b6257b3da8bb4fbf8 Spec file: bump bind version on f37+
* d9ecb12d57ab57129c33f6249d0ac6bf462834ca ipatests: re-enable dnssec tests

**Pull request closed without merging**
