### PR TITLE
[ipa-4-8] prci: Test on Fedora 32

### PR DESCRIPTION
**Pull request by netoarmando**
"previous" jobs updated to Fedora 31
"latest" jobs updated to Fedora 32

Signed-off-by: Armando Neto <abiagion@redhat.com>

### CODE REVIEW

**Comment by netoarmando** [comment]
`test_smb` is also failing in master: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/aa40bd3e-8b24-11ea-9314-fa163eabec81/

**Comment by f-trivino** [comment]
test_smb is blocking f32 changes. After quick investigation, test_smb fixes will take time so I remove it from gating for now (different PR). I'll add it back once it is working and stable.

**Comment by abbra** [comment]
@netoarmando you need to rebase and re-push to make sure `test_smb` is not used.

**Comment by f-trivino** [comment]
> @netoarmando you need to rebase and re-push to make sure `test_smb` is not used.

Thanks @abbra, I'll do that.

**Comment by f-trivino** [comment]
I close this PR in favour of https://github.com/freeipa/freeipa/pull/4655

I have no permissions to push changes to @netoarmando fork.

**Pull request closed without merging**
