### PR TITLE
WebUI: Fix certificate serial number representation

### PR DESCRIPTION
**Pull request by serg-cymbaluk**
Big numbers are automatically translated to scientific notation in JavaScript.
It causes an issue with some certificate serial numbers.
The fix normalizes the notation base on original value from serial_number_hex.

The implementation works only for browsers that support BigInt.
It would not work for old browsers like Internet Explorer.

Ticket: https://pagure.io/freeipa/issue/8754

Signed-off-by: Serhii Tsymbaliuk <stsymbal@redhat.com>

### CODE REVIEW

**Comment by serg-cymbaluk** [comment]
Hi @flo-renaud 

Could you please take a look at the patch?

**Comment by flo-renaud** [comment]
Hi @serg-cymbaluk 
thanks for the patch. It works well for displaying the certificates in the user/host/service pages (the box containing the certificate with serial number/issued by/valid from/valid to contains the right serial number, and clicking on "View" also displays the right value).
I couldn't test the revoke button with a high serial number but it's working as expected for certs issued by IPA.

There is something that isn't consistent, though. When navigating to Authentication > Certificates > Certificates, the table containing all the certificates still displays the wrong serial number in the column "serial_number".
certificates_table

**Comment by serg-cymbaluk** [comment]
@flo-renaud 
Thanks for the feedback.
I will provide a fix for the 'Certificates' page ASAP.

**Comment by serg-cymbaluk** [comment]
@flo-renaud 

PR updated. Could you please check the changes?

**Comment by flo-renaud** [comment]
Hi @serg-cymbaluk 
thanks for the updated patch, works for me. The certificates are now displayed with the proper serial number in the certificates table.
You can remove the temp commit and I will ack when PRCI completes.
certs_table

**Comment by serg-cymbaluk** [comment]
@flo-renaud 

Temp commit is removed. Pipeline is green.

**Comment by serg-cymbaluk** [comment]
master:

* 1439764c0e8ab9fd046c465e00f065684682f6b0 WebUI: Fix certificate serial number representation

**Pull request closed without merging**
