### PR TITLE
[ipa-4-6] Build on ipa-4-6 branch

### PR DESCRIPTION
**Pull request by flo-renaud**
Call autoreconf

### CODE REVIEW

**Comment by flo-renaud** [comment]
The nightly tests are compiling ipa-4-6 branch using the playbook defined in freeipa-pr-ci repository: [build.yml](https://github.com/freeipa/freeipa-pr-ci/blob/master/ansible/build.yml).
This playbook has a special task for ipa-4-6 branch that adds `autoreconf -if` in the freeipa.spec.in file if the version is 4.6.9.dev: in [create_spec.yml](https://github.com/freeipa/freeipa-pr-ci/blob/master/ansible/roles/builder/build/tasks/create_spec.yml):
```
- name: add autoreconf to spec file (ipa-4-6 branch only)
  lineinfile:
    path: /root/freeipa/freeipa.spec.in
    insertafter: "^%setup"
    line: autoreconf -if
  when: build_version is version('4.6.9.dev', '=')
```

Since commit https://pagure.io/freeipa/c/a1f6ea7fd7470b13307ae78148ebe756d30a7bcc?branch=ipa-4-6, the version on ipa-4-6 branch is 4.6.11 and the task is not called anymore.

This fix is permanently updating the freeipa.spec.in file in ipa-4-6 branch so that the tests are not fragile and dependent on a harcoded version.

**Comment by abbra** [comment]
LGTM.

**Comment by flo-renaud** [comment]
ipa-4-6:

* d5240eb474f98472309be078bb4eb6f633ec07e3 Build on ipa-4-6 branch Call autoreconf

**Comment by flo-renaud** [comment]
Readthedocs failure is a known issue, it is not configured on this branch. Forcing the push

**Pull request closed without merging**
