### PR TITLE
[Backport][ipa-4-5] Run tox tests for PyPI packages on Travis

### PR DESCRIPTION
**Pull request by tomaskrizek**
Original PR: #1293

### CODE REVIEW

**Comment by tiran** [comment]
``with_wheel`` section in the spec file is missing dependency on ``python2-tox``

**Comment by tomaskrizek** [comment]
I see... In that case, perhaps we shouldn't add tox testing to `ipa-4-5` branch. I don't want to introduce another build dependency to stable version. Most patches go through `master` or `ipa-4-6` anyway, so this shouldn't be much of an issue.

@tiran What do you think?

**Comment by tomaskrizek** [comment]
The `python-tox` dependency is used only in the `with_wheels` section, so it doesn't affect the build dependencies for rpm builds.

**Comment by tomaskrizek** [comment]
We'd also have to backport at least 3a5b3be8b92a509d207d814c9fe294ee7b4e81c4 to get tox testing in `ipa-4-5`. Considering not much development is going on in this branch, I don't think it's worth it.

**Pull request closed without merging**
