### PR TITLE
[ipa-4-5] backport #6999 to ipa-4-5

### PR DESCRIPTION
**Pull request by pvoborni**
Such simple fix should be in stabilization release.

https://pagure.io/freeipa/issue/7092 or https://pagure.io/freeipa/issue/6999 one needs to be opened on push.

### CODE REVIEW

**Comment by pvoborni** [comment]
Previous PR: #701

**Comment by pvoborni** [comment]
@rcritten I see that you "approved these changes" which I would understand as an ACK. Was it an ACK?

**Comment by rcritten** [comment]
Yes, ACK

**Comment by pvomacka** [comment]
ipa-4-5:

* 9308e63fde736ea4274a280f18c83a4bc2935c81 Store help in Schema before writing to disk
* 7352b731169e4f995b3ffe254b9e0cae6b82a763 Disable pylint in get_help function because of type confusion.

**Pull request closed without merging**
