### PR TITLE
Check ca_wrapped in ipa-custodia-check

### PR DESCRIPTION
**Pull request by tiran**
ca_wrapped uses Dogtag's pki tool (written in Java) to wrap key
material. Add checks to custodia to verify that key wrapping works.

Signed-off-by: Christian Heimes <cheimes@redhat.com>

### CODE REVIEW

**Comment by rcritten** [comment]
Manual execution of ipa-custodia-check fails with these two keys. The others all pass.

[2020-09-18T18:41:33 ipa-custodia-tester] <ERROR>: Failed to retrieve key 'ca_wrapped/auditSigningCert cert-pki-ca': 404 Client Error: Not Found for url: https://replica.example.test/ipa/keys/ca_wrapped/auditSigningCert%20cert-pki-ca?type=kem&value=eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkEyNTZDQkMtSFM1MTIiLCJraWQiOm51bGx9.K_9BTNVqxhPSiUjnRSTzwNxIGJTPO0_BtkAngTojJSFzEf6ctl50J8DcRbJPOhpcqtv8G0OevHRuTw8bEqTjuZQYb9gE1RsnGLgw6_FgMCGE5W2BbtW0BDPyVGWC1xqGVE0TIyfXQak_60ZZ3LYatdkvni-ZWKWzYWFSMcMhi9jIpsafmDglt94iKSdydwlKVfHQJH5RVNTk0Ddsmnw6HXPxqcp1olidkTvbcG-Ib6XRKaAwFVkaSVCcnfnr7zGVdUa5ty51c74hQ4P1EPh3OXg1kZbNEj-8FfQpPuuGfv2cB4nW2PWTKk7KU5QLx3o19pqWNMepqO2AppO4ZmMrzA.32gWTP5ku61mT_UeGyk_Xg.r79IoT3cNekGe3xCe8xLqvmclaNWUjk-X0p4duw6-q4ZcH1RcIf9cDqHey5_sKNBPXsPatXONxZWE2gHLIXPp8bw1bkvFWhqUhL659_HrMv0YYjmyXyNdFoVn3d3I4FkpgkZCn_7vH-PtIOJWBfBEaawCl6hCpi9vmI7vxg0Mb75W3fXc1Ndl1ByDV3YSVJNw8EFbjdJd_zpdewYGgjCSl6gDs_Ad1N_0lXHu2c-8ms-BpG6CdUYH5cUh3cHMzmu-CXoEyqzkCAdUgbJDMQr9ZfYNVbgzSu3Cw4kvqEJzLuFy3O5n7KaT7pAEXbeFc7ReLVeqBtGhqJDbJBJuV92Nyc2AKm26gInR-APFgi65uane42JpcWoqMtqqqpO5P40Kf-JSc8vRaXrmqhEJagbWMRl5nvtxj1XTTG2NSuD-4g8ODlt8elC830ZYRGr7xQ-EltCMb5OEKeGwFPQJNz0f6m_-mWLUM9VJcrhq2Wx5q1f1aJJTrtYJTdCMuoZ06wo0IRFTJNTEo04XBvr7kJtUzuBm7NNVpGVnsOwX-WYC1Ic8F0rViKYMix6hSNen64xNJpoLfX1EfA54reQJfMkvJb0tU8upp-tIDkwLb0-UDQyCxDg18zx226TU1zPMnQuuCvMb2TVqxK7CWo7Xu7iwwqY69om5mGwxFHmPMZnUD25Dm3HCSLwFhRX1SS6AKfd.nK3269aR2pcOURcT6F1CuseqGL6UC9bDVr2GSgvOWDs.
[2020-09-18T18:41:33 ipa-custodia-tester] <ERROR>: Failed to retrieve key 'ca_wrapped/auditSigningCert cert-pki-ca/1.2.840.113549.3.7': 404 Client Error: Not Found for url: https://replica.example.test/ipa/keys/ca_wrapped/auditSigningCert%20cert-pki-ca/1.2.840.113549.3.7?type=kem&value=eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkEyNTZDQkMtSFM1MTIiLCJraWQiOm51bGx9.wFmIJz9LEvz37SsdqV6QVM5Ejr3Psk6zWcLOkNzsglREn4E1SJc2IBfFjbWxL7AjNdVw9EF1jtJSxoHGvEFY2L7aJUY-s0oN9pOi8UMqom2L3UFYVMlQXjAOTXGgM_zKYQhYEL5_N88R-vShJZpuM0CR-AGHssLT_Ug133qzpgugFYiFouXiDCJsBimz-N1vxttSq5bymxs2AwkrnxvF63l20aZvkp39tAw0O-WpJt5_1F3CNm1lDUGDF4mUmfajO5U8mOlER39zetgEsWdVWMACZmWnPXeV6VVL48aQdHROuykf0RoCt-5EpPKA95UPbhHiTEArmZi_pk2HyLuqgw.ss9UNKzw0DgJcxIcAdvjfg.CHuQik9Ac71LQeW9xZWk3Z5DslROY1qFmv44UtOV5Vt5gZdLzYe4uvMts9rV-WX6Syut6RYWGA4MZE97SGRz4htsKbgg3-7MZejXQs3I_VInS39sY_JPDyn8ZKfU5nBw1V1UqMLbEw2CwDePPU0aeQUZJIYJS4lZJNX3WKUG5vr489E2hrZ-xDgdfwho8du4tAS4PuBBpMq9XtTrNvMdl24ONLkgul_r2qB3MWLSseqEH59GA7Dgzm33WLXydL9LXnrfUdM7RGE37s0FpM0v25Y6ZGMrv6Pa0hx1ySJ5ny3zOaFRYcMB2oafkQMJpvQeZgpGIE43OMKNBrSw3AacutSxZAavMjkMt1SNZZxoWpPC52iPSG4_a8yOHLOVwIlBi4dnAQzzQZLArmgsU7outvf1qsmO5orY3PgfpGeWFQkrfdmEoa0WnmjrIpjiZ90AodINAS9ybi8A7pzMkDRRRSa1ImbqlVTV0YkBw4pMSshwTNSFmc8QxUhYmscgM8ovkObz0nGkOYnvlDd7Ftc86BzR7YUIzobAiXZ0f7hXxSv0byyuYOH598zJfcpb9DQ0NKofh2b2NdeG1vv48SNeoRvPWLKb5h-3ErSsF1yur1Ec2n0lb1qf7081ZWjUtvI2G6Cs1BGL0VFy01DpLu3kb7WjSxZKXqCiP6Dvk1LfxE5C4ZWOqk3fbW4a7B5E5DPj_B53MWED-Jjnym7u4BUDfg.T7oeXw11DWJPcfx3JL7I0FsSqrV5OkHIpeD8fdFPEBE.
[ERROR] One or more tests have failed.

**Comment by tiran** [comment]
SELinux is blocking the operation. PR https://github.com/freeipa/freeipa/pull/5109 will fix the issue.

@fcami how about you add this changeset to your PR and include a test to run the checker on master and with master as hostname? It's a simple reproducer for the SELinux AVC.

**Comment by fcami** [comment]
@tiran I'm afraid I'll have to postpone writing a test until after https://github.com/freeipa/freeipa/pull/5109 is merged.

**Comment by tiran** [comment]
> @tiran I'm afraid I'll have to postpone writing a test until after #5109 is merged.

Understood! I have added additional tests. The tests should trigger AVCs until the #5109 is merged.

**Comment by rcritten** [comment]
ipa-custodia-check is working for me locally again in enforcing mode. All certs were successfully checked.

**Comment by rcritten** [comment]
@fcami it looks ok to me, wanted to give you an opportunity to give it a second look.

**Comment by fcami** [comment]
LGTM. ACK, even

**Review by fcami — CHANGES_REQUESTED** [review]
test_ipa_custodia_check was moved around.

**Comment by fcami** [comment]
ACK, thanks for this @tiran

**Comment by tiran** [comment]
master:

* fbb6484dbe31cc8ae4efb9729e3417f001a6637c Check ca_wrapped in ipa-custodia-check
* 9a9cd30255bc42e2c9ea5d6c4e3cca550f567f99 Verify freeipa-selinux's ipa module is loaded

**Pull request closed without merging**
