### PR TITLE
Test installation with (fake) userspace FIPS

### PR DESCRIPTION
**Pull request by tiran**
Based on userspace FIPS mode by Ondrej Moris.

Userspace FIPS mode fakes a Kernel in FIPS enforcing mode. User space
programs behave like the Kernel was booted in FIPS enforcing mode. Kernel
space code still runs in standard mode.

### CODE REVIEW

**Comment by tiran** [comment]
temp commit with successful run of test_fips http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/7f72a73a-06bc-11ea-9bec-fa163ef64b9b

**Comment by abbra** [comment]
Looks good. We need to remove temp commit before giving an ack.

**Comment by tiran** [comment]
I had to push another fix to add the new config entries to ``test_testconfig``.

**Comment by abbra** [comment]
LGTM

**Comment by tiran** [comment]
master:

* 8124b1bd4cc3857c8ab4ee8cd5330b5315a23787 Test installation with (fake) userspace FIPS

**Pull request closed without merging**
