### PR TITLE
FIPS mode and NT hashes

### PR DESCRIPTION
**Pull request by sumit-bose**
In FIPS mode NT hashes (aka md4) are not allowed. If FIPS more is detected we
disable NT hashes in the password plugin even is they are allowed by IPA
configuration.

Since ipa-sam is running as part of smbd is it safe to use the E_md4hash()
from Samba. This way ipa-sam does not depend on other crypto libraries
which might depend on other rules like e.g. FIPS mode.

### CODE REVIEW

**Comment by abbra** [comment]
LGTM. @stlaz, please test it in FIPS mode enabled.

**Comment by pvoborni** [comment]
Ticket for the fix: https://pagure.io/freeipa/issue/7026

**Comment by sumit-bose** [comment]
I just pushed a new version which include the upstream ticket reference in the commit message, there are no changes to the code.

**Comment by stlaz** [comment]
@sumit-bose Thank you for your patch. I can positively say that the error no more breaks server installation in FIPS mode, I was also able to set up a trust against my own AD server.
I did see some errors but those turn out to be probably caused by some misconfiguration of my system since your patches most certainly don't affect them.
Therefore I am giving an ACK to this PR :)

**Comment by pvomacka** [comment]
master:

* f169481b558bd7ec9102e02e40eb38df7867a694 ipa-sam: replace encode_nt_key() with E_md4hash()
* 1f0ca6aafd966e086692007a0df76e3c3276915f ipa_pwd_extop: do not generate NT hashes in FIPS mode


ipa-4-5:

* b63b6790efc82c87398c39ba4f55330756b7b3cf ipa-sam: replace encode_nt_key() with E_md4hash()
* 79a5f3bf321f15e4c120d16b8988ed0cdb0ae64c ipa_pwd_extop: do not generate NT hashes in FIPS mode

**Pull request closed without merging**
