### PR TITLE
Removing extra spaces present in man ipa-server-install

### PR DESCRIPTION
**Pull request by amitkumar50**
There are extras space present in man page. PR removes
identified extra spaces.

### CODE REVIEW

**Comment by stlaz** [comment]
Thank you, LGTM. ACK :)

**Comment by adelton** [comment]
Isn't double space after the period at the end of sentences the standard in US English?

**Comment by slaykovsky** [comment]
@adelton as I can see [here](https://en.wikipedia.org/wiki/Sentence_spacing#Typography), double spacing is being deprecated.

**Comment by rcritten** [comment]
Double-spaces after a period was a convention in manual typing (it's how I learned). It can go.

ack +1

**Comment by flo-renaud** [comment]
master:

* e6ca3b0c737b6d2e7449a7a3a477d379e8274240 Removing extra spaces present in man ipa-server-install

**Pull request closed without merging**
