### PR TITLE
Include supported migration scenarios in the ipa-to-ipa docs

### PR DESCRIPTION
**Pull request by rcritten**
Lay out the supported migration paths. Users are likely to get creative with migration so we need to narrow the path for which we can provide support.

### CODE REVIEW

**Comment by abbra** [comment]
The migration paths description looks good to me. One thing it made me wonder is how we can differentiate these between in the software?

**Comment by rcritten** [comment]
That is a really interesting question and I've pondered it a while now and can't come up with anything beyond the backup scenario. We could probably look for other files expected in the backup directory to tell what they are doing but this would be trivially circumvented.

There are valid reasons to migration in different ways. For example, a user unfortunately used the same domain as the AD server so they've never been able to set up trust. Migration could be used to switch to a unique domain so trust can work. I imagine that NETBIOS name could be similarly changed.

The typical scenario we see is users have a broken installation, usually the CA is hopeless. Migration would be a way out for that. We also see users wanting to skip wide swaths of upgrades. Using migration is probably not the best choice for this but I think we need to test the actual process before we set down in stone how far back one will be allowed to go. We probably don't want users upgrading from IPA v3.3.0 -> 4.11. But 4.9 -> 4.11 may be fine.

Since migration is not destructive we probably want to strongly encourage users to keep their old system around for a while after migration as a just in case. I think this PR is more a statement of what we will support than a statement of what is possible. If people color outside the lines then they may be on their own. Maybe that's scenario #4?

**Comment by abbra** [comment]
I have had two concerns in mind when asked that question. First, are the outlined scenarios define a contract that the migration tool has to enforce? This is important because scenarios imply different behaviour, even opposite for some cases. Second, change of properties might require wiping out data in some of the databases we normally don't modify. For example, Samba databases have records about domain and NetBIOS name, as well as entries for account credentials (machine account, trusted domain object accounts) and group mapping. If migration choices cause changes to them, the migration tool must then apply those but it is not clear from the design whether it will do so and under what conditions.

**Comment by rcritten** [comment]
We can, for example, prevent domain/realm/netbios changes. I'd prefer to provide flexibility, even if a --force flag is necessary for it.

The new server wins in all cases.

There are some corner cases regarding ranges, whether we want to force to retain the old one or add a new idrange to handle the existing users, groups, etc. And in that case what to do with DNA, if anything.

The assumption is that the user knows what domain, realm, etc they want for the replacement installation.

There is no real enforcement mechanism unless we force everything to remain the same, which doesn't account for a staging environment, needing a rename to get into an ipa-specific domain, handle an organization rename (e.g. merger), etc.

**Comment by rcritten** [comment]
I don't think we can. The installer favors the local install over the remote one when it comes to domain, realm, etc, assuming the admin knows what they are doing and that any changes are intentional. I think the best we could do, and Mark has suggested elsewhere, is to make a user confirm that they know they are changing these options.

In my mind these scenarios are for outlining what we will support only. If someone wants to go off the reservation we can say "good luck, don't do that".

**Comment by abbra** [comment]
Ok, let's then merge this update, no more changes are needed.

**Comment by abbra** [comment]
There is definitely a need to be more explicit about it.

**Comment by rcritten** [comment]
I added a couple of sentences about lack of enforcement.

**Comment by flo-renaud** [comment]
@rcritten if you don't want to spend time investigating the tox issue, you can review my PR that is moving azure pipeline from fedora 38 to fedora 39: https://github.com/freeipa/freeipa/pull/7090

**Comment by rcritten** [comment]
master:

* 11877d59030ef3cd158aefb298c3a6a334047412 Include supported migration scenarios in the ipa-to-ipa docs

**Pull request closed without merging**
