### PR TITLE
WebUI: Fix topology graph navigation crash

### PR DESCRIPTION
**Pull request by serg-cymbaluk**
Add get_navigation_options method to all facet variations to unify forming facet links.

Ticket: https://pagure.io/freeipa/issue/8523

### CODE REVIEW

**Comment by abbra** [comment]
`test_webui_users` failed due to FAS plugin being installed, known issue and can be ignored. However, `test_webui_general` failed due to timeouts and screenshots are all white. This is not expected. The rest looks good.

**Comment by stanislavlevin** [comment]
Are there topology graph tests to prevent possible future regressions?

**Comment by flo-renaud** [comment]
`test_webui_general` failure is also linked to the fas plugin being installed, please see https://pagure.io/freeipa/issue/8570

**Comment by serg-cymbaluk** [comment]
@stanislavlevin 

Let me add some simple test to check if the page is opened and rendered in general.

@abbra @flo-renaud 

Thanks for the notice. I will update the temp commit soon.

**Comment by serg-cymbaluk** [comment]
@stanislavlevin added test

**Review by pvoborni — APPROVED** [review]
Code looks good to me. Tried to navigate to topology graph - it works. Test also looks OK. Approving.

**Comment by abbra** [comment]
LGTM. Please remove the temp commit

**Comment by serg-cymbaluk** [comment]
@abbra @pvoborni 

Thanks for the review. Temp commit is removed.

**Comment by stanislavlevin** [comment]
@serg-cymbaluk, many thanks!

**Comment by abbra** [comment]
Added ACK, we can push even thoough Azure CI runs didn't run for some reason.

**Comment by serg-cymbaluk** [comment]
master:

* 1512acc7de5b6c2ea3f9edbe661d6d1e2bdc5889 WebUI: Fix topology graph navigation crash
* 69368fccdb8786fca63341a780f9c48a91c84f5e WebUI tests: Add simple test to check topology graph page is available

**Comment by abbra** [comment]
@serg-cymbaluk this has to be backported to ipa-4-8.

**Pull request closed without merging**
