### PR TITLE
Test: basic kerberos over http functionality

### PR DESCRIPTION
**Pull request by ofayans**
https://fedorahosted.org/freeipa/ticket/6446

### CODE REVIEW

**Comment by apophys** [comment]
Please rebase the commits in the right order.

What will happen when the hosts in the topology have both IPv4 and IPv6 stacks when you disable ports for only one? Is the IPA server serving on both network stacks?

**Comment by ofayans** [comment]
Commits were swapped. The traffic blocking is now performed on a client for both ipv4 and ipv6

**Comment by apophys** [comment]
Thank you for rebasing the commits. The test looks good.

**Comment by mbasti-rh** [comment]
Fixed upstream
master:
https://fedorahosted.org/freeipa/changeset/c7fd46e42a9f5b4676415910b800e0340f77dc88
https://fedorahosted.org/freeipa/changeset/503d0929e9265dfc0c6c28ac49146b72a0a7edea

**Pull request closed without merging**
