### PR TITLE
ipapython/graph.py complexity optimization.

### PR DESCRIPTION
**Pull request by slaykovsky**
Hi!

I've just read the code and I saw that graph bfs uses not optimal
for Python solution. So I've edited it with more optimal one.

Also I've changed string formatting for Value Errors raise and
deletion of edges in remove_vertex method because there's no need
to store redundant variable in memory.

Could you please take a look and leave some comments and maybe
merge it.

Thanks!

### CODE REVIEW

**Comment by abbra** [comment]
Thanks for the patch. Please split unrelated changes into separate commits.

**Comment by slaykovsky** [comment]
@abbra Thanks, done.

**Comment by abbra** [comment]
Please note that we require tickets to be open for each related changeset to be able to address backports. Graph optimizations need such tickets, it would also help to add information there explaining why and how new code is better. A numeric comparison would help as well.

**Comment by slaykovsky** [comment]
Thanks, will do.

**Comment by slaykovsky** [comment]
@abbra https://pagure.io/freeipa/issue/7051

**Comment by abbra** [comment]
Thanks, please add a reference to the ticket to commit messages. See https://www.freeipa.org/page/Contribute/Patch_Format for details.

**Comment by slaykovsky** [comment]
@abbra done.

**Comment by abbra** [comment]
Ok, LGTM, but I'd like to see someone else's review too. @MartinBasti?

**Comment by MartinBasti** [comment]
LGTM

**Comment by tomaskrizek** [comment]
master:

* 6097b5ca5c9e686af25b375bd2c9a462fd8d8cbc ipapython/graph.py complexity optimization
* c06bc2a36e9163839c6c99be9e2be1b386a8eae4 ipapython/graph.py String formatting
* 370d9c57dff72abe7c3d39c8a74672b316b43de7 ipapython/graph.py redundant variable fix

**Comment by tomaskrizek** [comment]
I accidentally pushed this PR to a mirror repo instead of upstream. Sorry about that.

Since the original branch is already deleted, I'm opening a new PR #917 instead of re-opening this one. Please see new PR if you're looking for the merged committs.

**Comment by tomaskrizek** [comment]
master:

* 52a435978b367fb94834f7c02debd06327c5e930 ipapython/graph.py complexity optimization
* fe913b9c9f8ce6e481f8f1f78bc082b55390fbea ipapython/graph.py String formatting
* c39da523adbcc1b2e0d7ca702971c69dc40135ba ipapython/graph.py redundant variable fix

**Pull request closed without merging**
