### PR TITLE
Extend WebUI test_krbpolicy automation suite

### PR DESCRIPTION
**Pull request by varunmylaraiah**
Extend WebUI test_krbpolicy suite with the following test cases
     test_verifying_button (verify button's action in various scenarios)
     test_negative_value (verify invalid values)
     test_verifying_measurement_unit
    
    https://pagure.io/freeipa/issue/7540

### CODE REVIEW

**Comment by pvoborni** [comment]
> @varunmylaraiah please increase timeout in ".freeipa-pr-ci.yaml" so we can get test results...

Or split it into multiple jobs as @Rezney did in some of his PRs so that more runners can run it in parallel.

**Comment by Rezney** [comment]
@pvoborni  @varunmylaraiah You can use PR#1925 as example. There is one definition for all tests and 4x for parallel execution.

For the moment this is a little hack because when using regexes those were not properly expanded. I have PR on PRCI for this:

 https://github.com/freeipa/freeipa-pr-ci/pull/200

**Comment by felipevolpone** [comment]
We have added more webui tests, you have to change test_webui timeout to a bigger value (maybe 12000)?

**Comment by Rezney** [comment]
LGTM, @pvoborni could you please take a brief look? Thanks...

**Comment by varunmylaraiah** [comment]
@Rezney Thanks for the Feedback

**Comment by Rezney** [comment]
@varunmylaraiah  please remove the tempcomit. Thanks...

**Comment by Rezney** [comment]
master:

* 3508227fc873be005f612a8b5f27a7a9fe1fb1be Extend WebUI test_krbpolicy suite with the following test cases: test_verifying_button (verify button's action in various scenarios) test_negative_value (verify invalid values) test_verifying_measurement_unit

**Pull request closed without merging**
