### PR TITLE
Making nigthly test definition editable by FreeIPA's contributors

### PR DESCRIPTION
**Pull request by tiran**
Now the test definition of nightly tests will be on freeipa repo. The
definition that's used on every PR (previously as .freeipa-pr-ci.yaml)
is in ipatests/prci_definitions/gating and the .freeipa-pr-ci.yaml file
is just a symlink to the real file.

In the same dir there is also nightly_master and nightly_rawhide, both
to be used in nightly tests.

This PR is the result of discussion on freeipa-devel mailing list [1].

[1] https://lists.fedoraproject.org/archives/list/freeipa-devel@lists.fedorahosted.org/message/4VAWJ4SFKKBFFICDLQCTXJWRRQHIYJLL

Also in the PR:
* Fix topology configuration of nightly runs 
* Add convenient template for temp commits

PR replaces https://github.com/freeipa/freeipa/pull/1957

### CODE REVIEW

**Comment by tiran** [comment]
The change also depends on https://github.com/freeipa/freeipa-pr-ci/pull/201

**Comment by Rezney** [comment]
freeipa/freeipa-pr-ci#201 was pushed. The patch looks good to me. Lets push it together with introducing #201 into production. Cheers!

**Comment by Tiboris** [comment]
@Rezney I have updated topology tests.

**Comment by Rezney** [comment]
master:

* 8f202bbd760e39138ab2a16fd304e1d9c1cb2ab0 Making nigthly test definition editable by FreeIPA's contributors
* 6212423cdafeb8b132d75f96d7700c82deb98bb1 Fix topology configuration of nightly runs
* 8edde14e56ed649a6e443b6920a5e28b1f751adb Add convenient template for temp commits

**Pull request closed without merging**
