### PR TITLE
Add __name__ == __main__ guards to setup.pys

### PR DESCRIPTION
**Pull request by tiran**
Signed-off-by: Christian Heimes <cheimes@redhat.com>

### CODE REVIEW

**Comment by mirielka** [comment]
Thanks, this fixes setup.py related failure in intree tests.

**Comment by pspacek** [comment]
@tiran PEP8 errors need to be fixed first:
~~~
./ipaclient/setup.py:28:80: E501 line too long (80 > 79 characters)
./ipalib/setup.py:28:80: E501 line too long (80 > 79 characters)
./ipaplatform/setup.py:28:80: E501 line too long (80 > 79 characters)
./ipaserver/setup.py:30:80: E501 line too long (80 > 79 characters)
./ipatests/setup.py:29:80: E501 line too long (80 > 79 characters)
~~~

Other than that, functional ACK.

**Comment by tiran** [comment]
@pspacek Fixed

**Comment by mbasti-rh** [comment]
Fixed upstream
master:
https://fedorahosted.org/freeipa/changeset/91920e7cb48cbf143ae281c9c073df14b2c2dddf

**Pull request closed without merging**
