### PR TITLE
Translations update from Fedora Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Fedora Weblate](https://translate.fedoraproject.org) for [freeipa/master](https://translate.fedoraproject.org/projects/freeipa/master/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by abbra** [comment]
Georgian translation is broken and misses `$` before `{entity}`:
```
1 validation errors in ka.po
--------------------------------------------------------------------------------
locations: ipaserver/plugins/internal.py:276
The following substitutions are absent in msgstr: ${entity}
>>> msgid <<<
Edit ${entity}
>>> msgstr <<<
{entity}-ის ჩასწორება
ka.po: 4877 entries, 4929 msgid, 560 msgstr, 0 warnings 1 errors

```

**Comment by rffontenelle** [comment]
@NorwayFun can you fix the error pointed above? The string is: https://translate.fedoraproject.org/translate/freeipa/master/ka/?checksum=20335f2074fb809a

**Comment by NorwayFun** [comment]
Hello,
With pleasure, but file is locked on weblate. Please, unlock it and Ill fix the file right away.

**Comment by rffontenelle** [comment]
> Hello, With pleasure, but file is locked on weblate. Please, unlock it and Ill fix the file right away.

Unlocked.

**Comment by NorwayFun** [comment]
Fixed.

**Comment by rffontenelle** [comment]
@abbra It is fixed in Weblate, but the commit is not being pushed to this PR's branch because there is a merge conflict. Solving this merge conflict requires write permissions to this repository. Can you or anyone else with write permissions help with this?

This task requires setting up and running the [Weblate Client "wlc"](https://docs.weblate.org/en/weblate-5.3.1/wlc.html) in a local checkout of freeipa repository. Here is an untested suggestion of wlc configuration file ~/.config/weblate:

```ini
[weblate]
url = https://translate.fedoraproject.org/api/
key = your_Fedora_Weblate_API_key
translation = freeipa/master
```

See the error message and the commands suggested by Weblate in the [alert page](https://translate.fedoraproject.org/projects/freeipa/master/#alerts):

> **Could not merge the repository.**
> 
> Weblate could not merge upstream changes while updating the repository.
> 
>     Rebasing (1/50)
>     Auto-merging po/LINGUAS
>     CONFLICT (content): Merge conflict in po/LINGUAS
>     Auto-merging po/bn_IN.po
>     Auto-merging po/ca.po
>     Auto-merging po/cs.po
>     Auto-merging po/de.po
>     Auto-merging po/en_GB.po
>     Auto-merging po/es.po
>     Auto-merging po/eu.po
>     Auto-merging po/fi.po
>     Auto-merging po/fr.po
>     Auto-merging po/hi.po
>     Auto-merging po/hu.po
>     Auto-merging po/id.po
>     Auto-merging po/ja.po
>     Auto-merging po/kn.po
>     Auto-merging po/mr.po
>     Auto-merging po/nl.po
>     Auto-merging po/pa.po
>     Auto-merging po/pl.po
>     Auto-merging po/pt.po
>     Auto-merging po/pt_BR.po
>     Auto-merging po/ru.po
>     Auto-merging po/sk.po
>     Auto-merging po/tg.po
>     Auto-merging po/tr.po
>     Auto-merging po/uk.po
>     Auto-merging po/zh_CN.po
>     error: could not apply 01dc8424d... Update translation files
>     hint: Resolve all conflicts manually, mark them as resolved with
>     hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
>     hint: You can instead skip this commit: run "git rebase --skip".
>     hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
>     Could not apply 01dc8424d... Update translation files
>      (1)
> 
> **Typical workflow for fixing merge conflicts**
> 
> 1. Commit all pending changes in Weblate and lock the translation component.
>   `wlc commit; wlc lock`
> 2. Add Weblate exported repository as a remote.
>   `git remote add weblate https://translate.fedoraproject.org/git/freeipa/master/ ; git remote update weblate`
> 3. Merge Weblate changes and resolve any conflicts.
>   `git merge weblate/master`
> 4. Rebase Weblate changes on top of upstream and resolve any conflicts.
>   `git rebase origin/master`
> 5. Push changes into upstream repository.
>   `git push origin master`
> 6. Weblate should now be able to see updated repository and you can unlock it.
>     `wlc pull ; wlc unlock`
>
> [Check the FAQ for info on how to resolve this.](https://docs.weblate.org/en/weblate-5.3.1/faq.html#merge)
> Appeared 3 months ago, last seen a second ago

**Comment by abbra** [comment]
@rffontenelle we do not push to github directly. It is a mirror of the pagure's source repository. Thus, we don't do it this way.

I have tried to do merges from wlc tree myself for several times and, frankly, I have given it up. All those conflicts are rolling, by moving one or two lines in each translation file over and over again, so after fixing one, you get another ~4-20 conflicting files again on the next round of merge attempts. To me this looks like a task not worth going over.

**Comment by rffontenelle** [comment]
How about you manually replace the msgstr from msgid `Edit ${entity}` from "ka.po" with the @NorwayFun contribution?

This way, the error is fixed, PR merged, and I can perform destructive operations on Weblate as only one commit will be lost.

```
msgid "Edit ${entity}"
msgtr "${entity}-ის ჩასწორება"
```

**Comment by abbra** [comment]
Can you (or @NorwayFun ) submit this as a separate PR?

**Comment by rffontenelle** [comment]
@abbra Please see if #7133 is what you are expecting. It is this PR + the Georgian fix.

**Comment by abbra** [comment]
Thank you, @rffontenelle. Let us know next steps once you are done with refactoring on the weblate side.

**Comment by rffontenelle** [comment]
@abbra I reset the freeipa/master weblate repository based on the current state of commits in the source code repository, hence solving the merge conflicts. #7215 is a result of this fix.

**Pull request closed without merging**
