### PR TITLE
[Backport][ipa-4-9] tasks.py: fix flake8-reported issues

### PR DESCRIPTION
**Pull request by fcami**
This PR was opened automatically because PR #5911 was pushed to master and backport to ipa-4-9 is required.

### CODE REVIEW

**Comment by fcami** [comment]
PR was ACKed automatically because this is backport of PR #5911. Wait for CI to finish before pushing. In case of questions or problems contact @fcami who is author of the original PR.

**Comment by rcritten** [comment]
re-run, a couple of tests failed with DNS issues

**Comment by rcritten** [comment]
ipa-4-9:

* 5b826ab3582566b15a618f57cb2e002a9c16ef64 tasks.py: fix flake8-reported issues

**Pull request closed without merging**
