### PR TITLE
WebUI: Add authentication indicator specific fields to "Kerberos Ticket Policy" page

### PR DESCRIPTION
**Pull request by serg-cymbaluk**
Ticket: https://pagure.io/freeipa/issue/8207

### CODE REVIEW

**Comment by pvoborni** [comment]
The CI failure is IMO cause by backend bug - the krbtpolicy-mod doesn't handle to set 2 values of the same type. It works individually. Example:

```
[root@master ~]# ipa krbtpolicy-mod --pkinit-maxlife 7200 --radius-maxlife 7200
ipa: ERROR: attribute "krbauthindmaxticketlife" not allowed
[root@master ~]# ipa krbtpolicy-mod --pkinit-maxrenew 7200 --radius-maxrenew 7200
ipa: ERROR: attribute "krbauthindmaxrenewableage" not allowed
[root@master ~]# ipa krbtpolicy-mod --pkinit-maxrenew 7200 
  Max life: 86400
  Max renew: 604800
  OTP max life: 364
  OTP max renew: 36031
  RADIUS max life: 36021
  RADIUS max renew: 36011
  PKINIT max life: 23432
  PKINIT max renew: 7200
  Hardened max life: 22332
  Hardened max renew: 23331
[root@master ~]# ipa krbtpolicy-mod --pkinit-maxlife 7200 
  Max life: 86400
  Max renew: 604800
  OTP max life: 364
  OTP max renew: 36031
  RADIUS max life: 36021
  RADIUS max renew: 36011
  PKINIT max life: 7200
  PKINIT max renew: 7200
  Hardened max life: 22332
  Hardened max renew: 23331
```

By simple search, I did not see a bug so filed a new one: https://pagure.io/freeipa/issue/8328

The Web UI code otherwise looks good to me.

We could have better fields description though. Ideally add some tool-tips which explains meanings of individual fields. This can be done in another PR.

**Comment by pvoborni** [comment]
@serg-cymbaluk - could you rebase and push - to include patch from https://github.com/freeipa/freeipa/pull/4703 and see it it helped?

**Comment by pvoborni** [comment]
Looks good to me.  Let's remove the temp commit and merge.

**Comment by serg-cymbaluk** [comment]
@pvoborni thanks
Temp commit is removed.

**Comment by serg-cymbaluk** [comment]
master:

* 7bef36de644a055ac6b0844ae17aa6526a87bc61 WebUI: Add authentication indicator specific fields to "Kerberos Ticket Policy" page
* e668b61fd2843edc4863d39f9707fd7993571b2e WebUI tests: Test all available fields on "Kerberos Ticket Policy" page

**Pull request closed without merging**
