### PR TITLE
Allow rename of a host group

### PR DESCRIPTION
**Pull request by abbra**
Fixes: https://pagure.io/freeipa/issue/6783
Signed-off-by: Alexander Bokovoy <abokovoy@redhat.com>

### CODE REVIEW

**Comment by fcami** [comment]
./ipatests/test_xmlrpc/test_hostgroup_plugin.py:114:17: E126 continuation line over-indented for hanging indent
./ipatests/test_xmlrpc/test_hostgroup_plugin.py:122:17: E126 continuation line over-indented for hanging indent

**Comment by rcritten** [comment]
We'll need to figure out what to do with VERSION for backports.

In my testing there is a cached version of the netgroup hanging around somewhere:

```
$ ipa hostgroup-add test
$ ipa hostgroup-add-member --hosts `hostname` test
$ getent netgroup test
test (tuple)
$ ipa hostgroup-mod --rename test2 test
$ getent netgroup test2
test2 (tuple)
$ getent netgroup test
test (tuple)
```

**Comment by abbra** [comment]
> We'll need to figure out what to do with VERSION for backports.
> 
> In my testing there is a cached version of the netgroup hanging around somewhere:
> 
> ```
> $ ipa hostgroup-add test
> $ ipa hostgroup-add-member --hosts `hostname` test
> $ getent netgroup test
> test (tuple)
> $ ipa hostgroup-mod --rename test2 test
> $ getent netgroup test2
> test2 (tuple)
> $ getent netgroup test
> test (tuple)
> ```
This looks like a caching on the client (SSSD?). Because the MEP entry in LDAP did get renamed when I ran `ldapmodrdn` on my system (this is equivalent of what we do here):

```
# foobar, hostgroups, accounts, xs.ipa.cool
dn: cn=foobar,cn=hostgroups,cn=accounts,dc=xs,dc=ipa,dc=cool
cn: foobar
description: foogroup
objectClass: ipaobject
objectClass: ipahostgroup
objectClass: nestedGroup
objectClass: groupOfNames
objectClass: top
objectClass: mepOriginEntry
ipaUniqueID: 44f9a0cc-b4ff-11e9-be1e-001a4a62eb77
memberOf: cn=foobar,cn=ng,cn=alt,dc=xs,dc=ipa,dc=cool
mepManagedEntry: cn=foobar,cn=ng,cn=alt,dc=xs,dc=ipa,dc=cool

# foobar, ng, alt, xs.ipa.cool
dn: cn=foobar,cn=ng,cn=alt,dc=xs,dc=ipa,dc=cool
objectClass: ipanisnetgroup
objectClass: ipaobject
objectClass: mepManagedEntry
objectClass: ipaAssociation
objectClass: top
nisDomainName: myexample.com
cn: foobar
memberHost: cn=foobar,cn=hostgroups,cn=accounts,dc=xs,dc=ipa,dc=cool
description: ipaNetgroup foobar
mepManagedBy: cn=foobar,cn=hostgroups,cn=accounts,dc=xs,dc=ipa,dc=cool
ipaUniqueID: 44fbeee0-b4ff-11e9-be1e-001a4a62eb77

After running:
ldapmodrdn -Y GSSAPI cn=foobar,cn=hostgroups,cn=accounts,dc=xs,dc=ipa,dc=cool cn=foobaz

# foobaz, hostgroups, accounts, xs.ipa.cool
dn: cn=foobaz,cn=hostgroups,cn=accounts,dc=xs,dc=ipa,dc=cool
cn: foobar
cn: foobaz
description: foogroup
objectClass: ipaobject
objectClass: ipahostgroup
objectClass: nestedGroup
objectClass: groupOfNames
objectClass: top
objectClass: mepOriginEntry
ipaUniqueID: 44f9a0cc-b4ff-11e9-be1e-001a4a62eb77
mepManagedEntry: cn=foobaz,cn=ng,cn=alt,dc=xs,dc=ipa,dc=cool
memberOf: cn=foobaz,cn=ng,cn=alt,dc=xs,dc=ipa,dc=cool

# foobaz, ng, alt, xs.ipa.cool
dn: cn=foobaz,cn=ng,cn=alt,dc=xs,dc=ipa,dc=cool
objectClass: ipanisnetgroup
objectClass: ipaobject
objectClass: mepManagedEntry
objectClass: ipaAssociation
objectClass: top
nisDomainName: myexample.com
description: ipaNetgroup foobar
mepManagedBy: cn=foobaz,cn=hostgroups,cn=accounts,dc=xs,dc=ipa,dc=cool
ipaUniqueID: 44fbeee0-b4ff-11e9-be1e-001a4a62eb77
memberHost: cn=foobaz,cn=hostgroups,cn=accounts,dc=xs,dc=ipa,dc=cool
cn: foobaz
```

**Comment by abbra** [comment]
Azure Pipelines cannot create build environment anymore, I filed bug against libdnf: https://bugzilla.redhat.com/show_bug.cgi?id=1818119

**Comment by rcritten** [comment]
I still wonder what to do about API_VERSION.

On the one hand we don't want the same capability to have different values between different  versions (the clients would hate that), but it also advertises the server as having capabilities it doesn't actually have.

I don't think we need to solve that in this PR though so I'm adding the ack.

**Comment by flo-renaud** [comment]
Hi @abbra 
thanks for the PR, works for me. Tested the following:
- [x] rename of ipaservers hostgroup is refused with the message `ipa: ERROR: hostgroup ipaservers cannot be deleted/modified: privileged hostgroup`
- [x] rename of a given hostgroup properly renames the LDAP entry below `cn=hostgroups,cn=accounts,$BASEDN` + the entry below `cn=ng,cn=alt,$BASEDN`
- [x] As Rob mentioned, `getent netgroup $oldname` may still return the previous group but after `sss_cache -N` (invalidate all the netgroups), only the new group is returned.

**Comment by abbra** [comment]
master:

* 01b207bcd5ea53f7f588771c530318cab1f9d0ef Add 'api' and 'aci' targets to make
* 6472a107d6b4f231dd9d9d8587ba550dfa8b0b0a Allow rename of a host group

**Pull request closed without merging**
