### PR TITLE
Fix regression in test_webui/test_translation.py

### PR DESCRIPTION
**Pull request by flo-renaud**
Nightly failure detected in test_webui/test_translation.py (see PR #[4263](https://github.com/freeipa/freeipa/pull/4263)) was introduced by commit e4966f9 which fixed a string in ssbrowser.html.
The content of the page https://master.example.com/ipa/config/ssbrowser.html is taken from ssbrowser.html when javascript is disabled, but from ipaserver/plugins/internal.py when javascript is enabled.
Need to update internal.py to be consistent.

### CODE REVIEW

**Comment by flo-renaud** [comment]
Adding ipa-4-8 label as commit e4966f9 was also backported to ipa-4-8.

**Comment by kaleemsiddiqu** [comment]
@flo-renaud 
LGTM. Tests are green.
Please remove temp_commit.

**Comment by flo-renaud** [comment]
Hi @kaleemsiddiqu 
thanks for the review, temp commit removed.

**Comment by flo-renaud** [comment]
master:

* 9eb1be875276c61127663c3860228f03a66ebfbd Part2: Don't fully quality the FQDN in ssbrowser.html for Chrome

**Pull request closed without merging**
