### PR TITLE
ipalib.x509 autumn cleanup

### PR DESCRIPTION
**Pull request by stlaz**
This is a cleanup of the x509 module which removes an ugly hack that prevents a circular dependency and the `strip_header()` function which is properly replaced by the `load_unknown_x509_certificate()` function where needed.

### CODE REVIEW

**Comment by Tiboris** [comment]
Thanks @stlaz !

**Comment by rcritten** [comment]
No ticket(s)?

x509 shouldn't be moved from ipalib to ipapython until there is a discussion about how/if the API is supported.

**Comment by stlaz** [comment]
This is a code cleanup, the changes are explained in the commit messages, I don't think it needs a ticket.

`x509` is not moved from `ipalib` to `ipapython` here at all. I have another branch for that where I do that rather poorly (it does not work) but I can make it better and make it work if we wanted to do that switch. It would seem only natural because our `x509` module does not really need to depend on `ipalib` at all. That should not be discussed here, though, if you want, we can talk about that on IRC, get a ticket, discuss it on devel meeting and get it done.

Also, if you don't want this pushed, please, remove the ACK label.

**Comment by rcritten** [comment]
You should remove the references to moving the code from the commit message. It isn't relevant to this change.

It was my understanding that policy was that all changes required a ticket in order for proper planning, scoping and to enhance the history of what changed and why.

The changes themselves seem ok otherwise.

**Comment by stlaz** [comment]
I will remove the reference, thanks for pointing that out, it shouldn't really be there.

I believe that some changes, like cleanup actions, should not require a ticket if the changes are explained in the commit messages clearly. That's the best way of keeping the history of the changes, anyway.
Please bear in mind that we already have 1400+ tickets for about 10 developers. That is a clear message that we fail in a very horrible and gruesome manner as far as planning goes, however sad this information is (to me).

**Comment by rcritten** [comment]
The use of tickets is probably better for a broader audience but they are important for planning, scoping and just knowing what others are working on. This doesn't mean unplanned work cannot be done but it needs to be agreed upon work otherwise something else could slip. This will become more important once sprints are used.

The number of opened issues is not relevant to the question of whether a commit should be associated to one.

**Comment by stlaz** [comment]
I asked the team to either close or ACK this last week. They did neither, so I am re-adding the original ACK and pushing the change.

**Comment by stlaz** [comment]
master:

* c9265a7b0528b7f2495bf15e79cd9dd96af578aa x509: remove the strip_header() function
* 4cc94512719be2addf3c90f7a4913709a4ed0f0d x509: remove subject_base() function

**Pull request closed without merging**
