### PR TITLE
ipatests: Don't assume sshd flush its logs immediately

### PR DESCRIPTION
**Pull request by stanislavlevin**
`sshd` logs are not displayed immediately in `journalctl`, this results in the tests checked the corresponding system logs are racy. I can't find a way to flush ones. So, the best is the time delay before reading the system log.

I've experimented with the delay, 5 sec is not enough.
Of course, this is just a workaround.

Related: https://pagure.io/freeipa/issue/8682

### CODE REVIEW

**Comment by fcami** [comment]
Hi @stanislavlevin thanks for the contribution. Out of curiosity, did you try restarting sshd to see if that would flush logs? E.g. is the buffer sshd-side?

**Comment by wladich** [comment]
Hi @stanislavlevin.

I think we can try to avoid using time.sleep here by repeatedly executing `journalctl` until we get needed result.
`tasks.run_repeatedly()` is just for that and it has "test" parameter to check the output. This approach should work without issues with "test_login_wrong_password". 
As for "test_ssh_key_connection" which checks that output does NOT contain specific message, we need to wait for some expected message to be present in output first, which would mean that logs are flushed. Do you know if there is such "marker" message based on your experiments?

**Comment by stanislavlevin** [comment]
@fcami, I've tried to restart `sshd`, if the service restart occurs _before_ logs writing, then the remaining logs are lost.

**Comment by stanislavlevin** [comment]
I don't have any problems with `test_ssh_key_connection` because as you mentioned it checks that the output doesn't match the expected pattern, but there may be no output at all, so this test may check nothing. Regarding this test, I didn't do any experiments.

**Comment by stanislavlevin** [comment]
@wladich, thank you for the suggestions, will check.

**Comment by wladich** [comment]
Ok, I will not insist on "fixing" `test_ssh_key_connection` as part this PR, time.sleep will improve it anyway. 

I will leave some observations and ideas about this testcase in case someone decides to improve it.

Here is what journalctl output looks like in `test_ssh_key_connection`:
```
INFO     ipatests.pytest_ipa.integration.host.Host.master.IPAOpenSSHTransport:transport.py:391 RUN ['journalctl', '--since=today', '-u', 'sshd']
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd203:transport.py:513 RUN ['journalctl', '--since=today', '-u', 'sshd']
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd203:transport.py:557 -- Logs begin at Fri 2021-01-22 17:29:11 UTC, end at Fri 2021-01-22 17:51:33 UTC. --
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd203:transport.py:557 Jan 22 17:29:21 localhost systemd[1]: Starting OpenSSH server daemon...
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd203:transport.py:557 Jan 22 17:29:21 localhost sshd[555]: Server listening on 0.0.0.0 port 22.
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd203:transport.py:557 Jan 22 17:29:21 localhost sshd[555]: Server listening on :: port 22.
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd203:transport.py:557 Jan 22 17:29:21 localhost systemd[1]: Started OpenSSH server daemon.
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd203:transport.py:557 Jan 22 17:29:31 localhost sshd[592]: Accepted publickey for root from 192.168.122.1 port 54254 ssh2: RSA SHA256:1M4RzhMyWuFS/86uPY/ce2prh/dVTHW7iD2RhpquOZA
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd203:transport.py:557 Jan 22 17:29:32 localhost sshd[592]: pam_unix(sshd:session): session opened for user root by (uid=0)
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd203:transport.py:557 Jan 22 17:29:34 localhost sshd[1268]: Accepted publickey for root from 192.168.122.1 port 54260 ssh2: RSA SHA256:S2i6XGTQ5apc9jssmamLLxaPWqSaPQKgwd9k6Wp/7mc
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd203:transport.py:557 Jan 22 17:29:34 localhost sshd[1268]: pam_unix(sshd:session): session opened for user root by (uid=0)
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd203:transport.py:557 Jan 22 17:29:38 localhost sshd[2389]: Accepted publickey for root from 192.168.122.1 port 54266 ssh2: RSA SHA256:S2i6XGTQ5apc9jssmamLLxaPWqSaPQKgwd9k6Wp/7mc
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd203:transport.py:557 Jan 22 17:29:38 localhost sshd[2389]: pam_unix(sshd:session): session opened for user root by (uid=0)
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd203:transport.py:557 Jan 22 17:29:44 localhost sshd[2587]: Accepted publickey for root from 192.168.122.1 port 54274 ssh2: RSA SHA256:S2i6XGTQ5apc9jssmamLLxaPWqSaPQKgwd9k6Wp/7mc
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd203:transport.py:557 Jan 22 17:29:44 localhost sshd[2587]: pam_unix(sshd:session): session opened for user root by (uid=0)
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd203:transport.py:557 Jan 22 17:32:26 master.ipa.test sshd[18491]: Accepted publickey for root from 192.168.122.72 port 49442 ssh2: RSA SHA256:4uXUt6L6HMea8DFDrkpsTes8noOfx+uyoPBb27QTGYU
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd203:transport.py:557 Jan 22 17:32:26 master.ipa.test sshd[18490]: Accepted publickey for root from 192.168.122.72 port 49440 ssh2: RSA SHA256:4uXUt6L6HMea8DFDrkpsTes8noOfx+uyoPBb27QTGYU
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd203:transport.py:557 Jan 22 17:32:26 master.ipa.test sshd[18491]: pam_unix(sshd:session): session opened for user root by (uid=0)
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd203:transport.py:557 Jan 22 17:32:26 master.ipa.test sshd[18490]: pam_unix(sshd:session): session opened for user root by (uid=0)
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd203:transport.py:557 Jan 22 17:32:26 master.ipa.test sshd[18491]: pam_unix(sshd:session): session closed for user root
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd203:transport.py:557 Jan 22 17:38:39 master.ipa.test sshd[555]: Received signal 15; terminating.
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd203:transport.py:557 Jan 22 17:38:39 master.ipa.test systemd[1]: Stopping OpenSSH server daemon...
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd203:transport.py:557 Jan 22 17:38:39 master.ipa.test systemd[1]: sshd.service: Succeeded.
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd203:transport.py:557 Jan 22 17:38:39 master.ipa.test systemd[1]: Stopped OpenSSH server daemon.
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd203:transport.py:557 Jan 22 17:38:39 master.ipa.test systemd[1]: Starting OpenSSH server daemon...
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd203:transport.py:557 Jan 22 17:38:39 master.ipa.test sshd[22939]: Server listening on 0.0.0.0 port 22.
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd203:transport.py:557 Jan 22 17:38:39 master.ipa.test sshd[22939]: Server listening on :: port 22.
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd203:transport.py:557 Jan 22 17:38:39 master.ipa.test systemd[1]: Started OpenSSH server daemon.
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd203:transport.py:557 Jan 22 17:51:32 master.ipa.test sshd[26903]: Accepted publickey for test-ssh from 192.168.122.72 port 49452 ssh2: RSA SHA256:sj6YkxrrJHHyeQbH46pY1MOtIwTM6W19qoWr9F50cSY
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd203:transport.py:557 Jan 22 17:51:32 master.ipa.test sshd[26903]: pam_unix(sshd:session): session opened for user test-ssh by (uid=0)
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd203:transport.py:557 Jan 22 17:51:33 master.ipa.test sshd[26903]: pam_unix(sshd:session): session closed for user test-ssh
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd203:transport.py:217 Exit code: 0
```
It seems that "session closed for user ssh-tester" message is a sufficient sign that all logs are written.

To check the logs in a poper way  this test should be changed a little:
* replace "--since=today" with expression similar to one in `test_login_wrong_password`
* run "journalctl" using `run_repeatedly` and check for presence of "session closed for user ssh-tester" and absence of "exited on signal 13" (btw, regexp is not needed here).

**Comment by stanislavlevin** [comment]
I'm fixing this now.

**Comment by stanislavlevin** [comment]
From the related tickets, I don't see the actual sshd log in error case:
https://pagure.io/freeipa/issue/7664
https://pagure.io/SSSD/sssd/issue/3747

Maybe it is in Bugzilla, I don't have access to that ticket.

**Comment by wladich** [comment]
The relevant parts from the BZ:

```
Description of problem:

When a user tries to login to a RedHat 7.5 system with pubkey authentication where the keys are stored in an IdM server the login is asking for a password (or a passphrase with a passphrase-less key).

error: AuthorizedKeysCommand /usr/bin/sss_ssh_authorizedkeys testuser exited on signal 13.

Version-Release number of selected component (if applicable):

sssd-1.16.0-19.el7.x86_6
RHEL 7.5
```

```
Failing on "sssd-1.16.0-19.el7.x86_64":

[root@master-01 ~]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.5 (Maipo)
[root@master-01 ~]# 
[root@master-01 ~]# rpm -qa | grep sssd-1
sssd-1.16.0-19.el7.x86_64
[root@master-01 ~]# 
[root@master-01 ~]# /usr/bin/sss_ssh_authorizedkeys ssh-tester | wc -l
50
[root@master-01 ~]# 
[root@master-01 ~]# ssh ssh-tester@localhost -i keys/ipakey_1
Password: 
[root@master-01 ~]# 
[root@master-01 ~]# date
[root@master-01 ~]# 
[root@master-01 ~]# tail -n2 /var/log/secure
Jul 25 03:19:51 master-01 sshd[31070]: error: AuthorizedKeysCommand /usr/bin/sss_ssh_authorizedkeys ssh-tester exited on signal 13
Jul 25 03:19:53 master-01 sshd[31070]: Connection closed by ::1 port 35690 [preauth]
[root@master-01 ~]# 
[root@master-01 ~]# 

Verified on: 

[root@master-01 ~]# yum update sssd
...
...
[root@master-01 ~]# rpm -qa | grep sssd-1
sssd-1.16.0-19.el7_5.6.x86_64
[root@master-01 ~]# 
[root@master-01 ~]# systemctl restart sssd
[root@master-01 ~]#
[root@master-01 ~]# date
Wed Jul 25 09:15:46 EDT 2018
[root@master-01 ~]# ssh ssh-tester@localhost -i keys/ipakey_1
Last failed login: Tue Jul 24 07:40:11 EDT 2018 from localhost on ssh:notty
There was 1 failed login attempt since the last successful login.
...
...
[root@master-01 ~]# tail -n5 /var/log/secure
Jul 25 09:15:55 master-01 sshd[32414]: Accepted publickey for ssh-tester from ::1 port 36024 ssh2: RSA SHA256:gevAjOdAf9El17xO8WJ8bMaEiwrZ3Q5gLI2nn52MHog
Jul 25 09:15:55 master-01 sshd[32414]: pam_unix(sshd:session): session opened for user ssh-tester by (uid=0)
Jul 25 09:16:03 master-01 sshd[32420]: Received disconnect from ::1 port 36024:11: disconnected by user
Jul 25 09:16:03 master-01 sshd[32420]: Disconnected from ::1 port 36024
Jul 25 09:16:03 master-01 sshd[32414]: pam_unix(sshd:session): session closed for user ssh-tester

```

Actually with the original issue the test should fail at `tasks.run_ssh_cmd`... But I would prefer to keep checking logs as well.

**Comment by stanislavlevin** [comment]
Thank you for the logs!
So, `session closed for user test-ssh` is never reachable in the failure case.

**Comment by wladich** [comment]
Well, it WAS not reachable in that very case. So I would prefer to keep the check for "exited on signal 13" as well.

**Comment by wladich** [comment]
Thank you, the changes LGTM.
I will ACK the PR when the tests complete.

**Comment by wladich** [comment]
master:

* fdd5ba3f48096cf50f90e9f3045766e89cd75508 ipatests: Don't assume sshd flush its logs immediately

**Pull request closed without merging**
