### PR TITLE
Integration test for sssd_ssh leaks

### PR DESCRIPTION
**Pull request by Rezney**
Integration test for sssd_ssh leaks

https://pagure.io/SSSD/sssd/issue/3794

### CODE REVIEW

**Comment by rcritten** [comment]
Travis failed with:

ipatests/test_integration/test_commands.py:385: [W0612(unused-variable), TestIPACommand.test_ssh_leak] Unused variable 'i')

The test failed with:

DEBUG  >           assert current_num_of_pipes == num_of_pipes
DEBUG  E           assert 6 == 2

**Comment by Rezney** [comment]
Cool, looks like we are hitting the issue we are trying to test. The latest "sssd" package which fixes the issue got into "updates" just recently. Will most probably have to create a new template.

**Comment by Rezney** [comment]
@rcritten seems to be ok now...

**Comment by Tiboris** [comment]
Thanks for creating upstream ticket @Rezney. ACK

**Comment by Tiboris** [comment]
master:

* 31a92c1677998756aa1a2393b74fadfce817004f tests: sssd_ssh fd leaks when user cert converted into SSH key
* c29581c9a0e3d3c38344b8b3f4765b971ea7713d add strip_cert_header() to tasks.py

**Pull request closed without merging**
