### PR TITLE
Exit on fail in azure multiline script

### PR DESCRIPTION
**Pull request by stanislavlevin**
By default, the `last` exit code returned from Azure script will be
checked and, if non-zero, treated as a step failure.  Luckily,
for Linux script is a shortcut for Bash. Hence errexit/e option
could be applied. But Azure pipelines doesn't set it by default:
https://github.com/microsoft/azure-pipelines-agent/issues/1803

For multiline script this is a problem unless otherwise designed.
Some of the benefits of checking the result of each subcommand:
- preventing subsequent issues (broken packages, container images, etc.)
- time saving (next steps will not run)
- good diagnostics (tells which part of the script fails)

### CODE REVIEW

**Comment by abbra** [comment]
LGTM.

**Comment by abbra** [comment]
Let us run full test too.

**Comment by abbra** [comment]
master:

* b5bb436e9fece23f76b35055eddf638f7b8251fe Exit on fail in azure multiline script

**Comment by stanislavlevin** [comment]
Thank you!

**Pull request closed without merging**
