### PR TITLE
Fix regexp in user/group name

### PR DESCRIPTION
**Pull request by mbasti-rh**
Regexp should not enforce lenght of string, we have different checks for
that. Secondly regexp with length specified produces an incorrect error
message.

https://fedorahosted.org/freeipa/ticket/5822

### CODE REVIEW

**Comment by stlaz** [comment]
Would the gist of this patch also apply to any of idviews, servicedelegation or topology plugins where a similar or slightly different regexp is used? Could we rather have the regexp as a constant somewhere so it does not have to be changed at all places it appears every time we want to modify it?

**Comment by abbra** [comment]
'uid' in user object and 'cn' in group object have meaning in POSIX environments. 'cn' in other objects is not subject for strict limits.

**Comment by stlaz** [comment]
Sure. But from what I see, this patch may possibly break idviews plugin for users of username of about 255 characters (see idoverrideuser - 'uid'), same for groups (with 'cn' ofc).
NACK until that is fixed.

**Comment by abbra** [comment]
LGTM. Thanks for first fixing the regexp and then replacing it by a constant, this will help with backports.

**Comment by stlaz** [comment]
The tests seem to pass as well.

**Comment by martbab** [comment]
Fixed upstream
master:
https://fedorahosted.org/freeipa/changeset/37200806118d39ef8afe84ad5887a294d54e2659
https://fedorahosted.org/freeipa/changeset/8f8e3d008f1de91337a83ea6d271662432209767
ipa-4-4:
https://fedorahosted.org/freeipa/changeset/85ee93deb62ce8026122e5c40cdc8813f6a70e81
https://fedorahosted.org/freeipa/changeset/63914414bcc151ca954258215757ddd2bf4c3843

**Pull request closed without merging**
