### PR TITLE
[EPN] SMTP client enhancements

### PR DESCRIPTION
**Pull request by stanislavlevin**
- don't downgrade security
- enable SMTP server certificate validation and hostname checking
- allow authentication by SMTP client's certificate

https://pagure.io/freeipa/issue/8578
https://pagure.io/freeipa/issue/8579
https://pagure.io/freeipa/issue/8580

### CODE REVIEW

**Comment by abbra** [comment]
The code looks good to me, complete with tests, thanks!

**Comment by stanislavlevin** [comment]
The fails were not expected by me.
I run tests on ALT and that works, so, there are distro-specifics here (Fedora vs ALT).
Hope, tests have been fixed :)

**Comment by rcritten** [comment]
This looks good to me. Please remove temp commit.

**Comment by stanislavlevin** [comment]
@abbra, @rcritten, thank you for the review.
Removed temp commit.

**Comment by stanislavlevin** [comment]
Rebased on `master` to skip flaky `test_dnssec`.

**Comment by abbra** [comment]
`test_cert` is still pending...

**Comment by abbra** [comment]
Ok, can be merged.

**Comment by abbra** [comment]
master:

* be006ad6c4e36fd53212a5e573524d1c96dfab39 ipatests: Respect platform's openssl dir
* 94adee3c73f039fc2d985afd1681cd64ece55116 EPN: Don't downgrade security
* 977063a56ef8f11c75a4cdd836f8692155337c7b test_epn: Standardize EPN configs for deduplication
* 32aa1540f0f25864816eced0b2f569a6cdfd3973 EPN: Enable certificate validation and hostname checking
* 17f430efc4cf438b6c052465b8252688bc5822f9 EPN: Allow authentication by SMTP client's certificate
* 82e69008ad43b993a2d3664b3ea35d9f84f2679a ipatests: Collect EPN log for debugging

**Pull request closed without merging**
