### PR TITLE
ipatests: add tests to check that only secure TLS protocols are enabled in Apache

### PR DESCRIPTION
**Pull request by wladich**
Related to: https://pagure.io/freeipa/issue/7995

### CODE REVIEW

**Comment by rcritten** [comment]
Failures are due to new version of pylint.

**Comment by wladich** [comment]
@

> Failures are due to new version of pylint.

I do not understand what I can do about it. It found issues in files I did not touch.

**Comment by rcritten** [comment]
Sorry, I should have mentioned that. This is being looked at upstream, there isn't anything you can do about it.

**Comment by rcritten** [comment]
The commit message line wraps.
More details than "secure" are needed. I'd just say:

ipatests: add test to check that only TLS 1.2 is enabled in Apache

Maybe it's a style thing but since is_tls_version_enabled() is only used within one test you should be able to embed that function inside it.

**Comment by rcritten** [comment]
master:

* 14be2715334e16a2d3f07a6b64bcd6d068ce89c1 ipatests: add test to check that only TLS 1.2 is enabled in Apache

**Comment by rcritten** [comment]
@wladich can you do manual backports to the ipa-4-7 and ipa-4-6 branches?

**Pull request closed without merging**
