### PR TITLE
[Backport][ipa-4-7] Unify and simplify LDAP service discovery

### PR DESCRIPTION
**Pull request by tiran**
This PR was opened automatically because PR #2144 was pushed to master and backport to ipa-4-7 is required.

### CODE REVIEW

**Comment by tiran** [comment]
PR was ACKed automatically because this is backport of PR #2144. Wait for CI to finish before pushing. In case of questions or problems contact @tiran who is author of the original PR.

**Comment by tiran** [comment]
vagrant provision failed, re-run

**Comment by rcritten** [comment]
Removing ack. The original PR was for ipa-next. I considered this when reviewing.

**Comment by abbra** [comment]
@rcritten so you do not want this to be backported to ipa-4-7 at all? Should we just close the pull request then?

**Comment by rcritten** [comment]
I'm just confused. The original PR was for ipa-next. My concern is that this could have some side-effects not seen in the limited testing I was able to do that could get shaken out over development of 4.8.

Mostly I'm just trying to reconcile the original PR vs the backport.

**Comment by abbra** [comment]
Ok, let us skip the backport right now and focus on making sure all bugs are weeded out during 4.8 development. If by the release of 4.8.0 we wouldn't see any bugs related to this PR, we can reconsider a backport.

Would this work, @rcritten, @tiran?

**Comment by rcritten** [comment]
+1

**Comment by rcritten** [comment]
Closing the PR.

**Pull request closed without merging**
