### PR TITLE
Temp commit: test against updated ACME pki build

### PR DESCRIPTION
**Pull request by rcritten**
No need to review this.

### CODE REVIEW

**Comment by mrizwan93** [comment]
```
2021-01-22 02:41:19,474    DEBUG  ipa: ERROR: stderr: Saving debug log to /var/log/letsencrypt/letsencrypt.log
2021-01-22 02:41:19,474    DEBUG  Plugins selected: Authenticator standalone, Installer None
2021-01-22 02:41:19,474    DEBUG  Performing the following challenges:
2021-01-22 02:41:19,474    DEBUG  http-01 challenge for client0.ipa.test
2021-01-22 02:41:19,474    DEBUG  Waiting for verification...
2021-01-22 02:41:19,475    DEBUG  Cleaning up challenges
2021-01-22 02:41:19,475    DEBUG  An unexpected error occurred:
2021-01-22 02:41:19,475    DEBUG  acme.errors.ClientError: <Response [500]>
2021-01-22 02:41:19,475    DEBUG  Please see the logfiles in /var/log/letsencrypt for more details.
```
This is the same error I was getting on RHEL. Additionally there were a trace back in acme debug log on server too.

**Comment by rcritten** [comment]
@edewata test with IPA against your ACME copr build.

**Comment by rcritten** [comment]
Re-running against newer build that fixes https://bugzilla.redhat.com/show_bug.cgi?id=1919282

**Comment by rcritten** [comment]
Original log http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/a3ac2f70-5c4e-11eb-a34c-fa163eb81564

**Comment by edewata** [comment]
If you're testing bug 1919282, please use the COPR repo listed in the bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1919282#c9

**Comment by rcritten** [comment]
DNS resolution problem looking up copr.fedorainfracloud.org. Re-running to see if it is a one-off.

**Comment by rcritten** [comment]
It's failing in part because there are only F33 builds and PR-CI uses F32 vagrant images.

This isn't related to the second failure where the replica is unable to look up the repo at all in DNS. I'm not sure what's going on there.

**Comment by edewata** [comment]
Looks like it's picking up pki 10.10.3-3 from Fedora instead of COPR so I had to bump the version to 10.10.3-4. The COPR repo has builds for f32, f33, and rawhide. Please try again.

**Comment by rcritten** [comment]
The tests pass. Pushing another round that will execute it five times to check for stability.

**Comment by rcritten** [comment]
Configure baseURL to point to the local IPA server and re-enable Endi's copr repo that contains both the 500 fix and the nonce fix to utilize baseURL.

**Comment by rcritten** [comment]
4 out of 5 passed with one timeout failure. Pushing a new patch to address the Azure complaints so the whole PR has a chance of going green.

**Comment by rcritten** [comment]
3 out of 5 but both had some pretty major DNS issues underlying the installation. Re-running.

**Comment by rcritten** [comment]
Kicking off tests again to check for robustness.

**Comment by rcritten** [comment]
All five tests passed. Adding another replica to the mix to further stress it.

**Comment by rcritten** [comment]
Fixed the timeout for all 5 runs. Three of the five had timed out. The only one to pass was the one with the increased timeout. I think the fourth would have timed out soon as well.

**Comment by rcritten** [comment]
@edewata seems like your changes are working ok.

**Comment by edewata** [comment]
Thanks!

**Comment by rcritten** [comment]
Closing this since upstream pki change was merged.

**Pull request closed without merging**
