### PR TITLE
Issue 3656 - Extend schema get function to return MAY or MUST attrs

### PR DESCRIPTION
**Pull request by mreynolds389**
Add new paramters to get_allowed_attributes() to return just MAY or MUST attributes

relates: https://pagure.io/freeipa/issue/3656

### CODE REVIEW

**Comment by abbra** [comment]
LGTM except one thing. We use 'Related: ...', not 'relates: ...' in the commit message. Could you please fix that?

**Comment by mreynolds389** [comment]
> LGTM except one thing. We use 'Related: ...', not 'relates: ...' in the commit message. Could you please fix that?

Fixed, but as I understand it "related" and "relates" have the exact same behavior, same for fixes/fixed.

**Comment by abbra** [comment]
Kind of, yes. The logic is described here: https://github.com/freeipa/freeipa-tools/blob/master/release/README.MD#git-commits, so the word does not matter, URL does. We historically use 'Fixes:' and 'Related:'.

**Comment by mreynolds389** [comment]
> Kind of, yes. The logic is described here: https://github.com/freeipa/freeipa-tools/blob/master/release/README.MD#git-commits, so the word does not matter, URL does. We historically use 'Fixes:' and 'Related:'.

Yeah it's no problem and thanks for the clarification.  

So once this passes the tests someone will have to merge it as I am not set as a collaborator yet.

**Comment by abbra** [comment]
Correct.

**Comment by tiran** [comment]
I find the function signature misleading. With the current implementation, the call `get_allowed_attributes(..., return_may=True, return_must=True)` returns only must attributes and `get_allowed_attributes(..., return_may=False, return_must=False)` returns both must and may attributes.

I suggest that you use a single argument with a string enum with possible values `all`, `must`, `may` instead, e.g. `get_allowed_attributes(..., attributes="must")`.

**Comment by mreynolds389** [comment]
> I find the function signature misleading. With the current implementation, the call `get_allowed_attributes(..., return_may=True, return_must=True)` returns only must attributes and `get_allowed_attributes(..., return_may=False, return_must=False)` returns both must and may attributes.
> 
> I suggest that you use a single argument with a string enum with possible values `all`, `must`, `may` instead, e.g. `get_allowed_attributes(..., attributes="must")`.

Good point, I'll work on that...

**Comment by abbra** [comment]
LGTM for me, @tiran your take?
I'll restart upgrade test in Azure CI.

**Comment by mreynolds389** [comment]
Any concerns here?  It's been over two weeks since I made the requested changes

**Comment by abbra** [comment]
No concerns, all tests green now.

**Comment by mreynolds389** [comment]
> No concerns, all tests green now.

Thanks, but someone else will have to merge this as I do not have those permissions yet

**Comment by flo-renaud** [comment]
master:

* 5c8614157d5546033528f92700f5abfebd4e5838 Issue 3656 - Extend schema function to return MAY or MUST attrs

**Pull request closed without merging**
