### PR TITLE
[Backport][ipa-4-6] Added tests for 2FA prompting configurations

### PR DESCRIPTION
**Pull request by amore17**
Manual back-port of : #4272

### CODE REVIEW

**Comment by flo-renaud** [comment]
Hi @amore17 
please rebase as commit 423a052  will fix the travis issue

**Comment by abbra** [comment]
You cannot use f-string syntax in Python 2, the patch that added it should be changed to `"{password}{otp}".format(password=password, otp=otp)`
```
Compiling /builddir/build/BUILDROOT/freeipa-4.6.7.dev-0.fc27.x86_64/usr/lib/python2.7/site-packages/ipatests/test_integration/test_otp.py ...
  File "/usr/lib/python2.7/site-packages/ipatests/test_integration/test_otp.py", line 77
    stdin_text=f"{password}{otp}\n",
                                  ^
SyntaxError: invalid syntax
```

**Comment by flo-renaud** [comment]
Hi @amore17 
you can remove the temp commit and I will ack when prci completes.

**Comment by flo-renaud** [comment]
Tests are green, ACK.

**Comment by flo-renaud** [comment]
ipa-4-6:

* cabb7abfc07b093a9912b20ee712baaa40d16d19 Add test case for OTP login
* b36c4a70fc0e577265bb587de1e1b7bd739a8709 ipatests: Added test when 2FA prompting configurations is set.
* 734121fa1497ef2e074d2879ab9fc54c0ace95b8 Mark xfail for tests using sssd-1.16.3

**Pull request closed without merging**
