### PR TITLE
support more DateTime attributes

### PR DESCRIPTION
**Pull request by abbra**

### CODE REVIEW

**Comment by abbra** [comment]
It is not working yet, the conversion back to LDAP attribute does not yet work.

**Comment by rcritten** [comment]
I'd prefer it if the mapping table include the syntax/attribute names for the datetime values.

If the import is changed from: `import datetime` to `from datetime import datetime` and references switched from `datetime.datetime` to `datetime` then we have enough characters to fit the attribute names for pylint.

**Comment by rcritten** [comment]
I have a candidate patch but didn't force push it to the PR to avoid CI churn if the idea isn't accepted.

**Comment by abbra** [comment]
Yeah, I didn't think about importing `datetime.datetime` in a shorter form. That could work to reduce the length of the lines. My original commit had them all named explicitly but the length was beyond the allowed 80 characters so I had to remove those.

Feel free to push an update.

I also thought about a test. May be a simple test that creates a class which defines a `DateTime` option and uses  `LDAPSearch.get_attr_filter()` to retrieve a LDAP filter as a string , then checks that the value of the `DateTime` parameter is present in the LDAP format?

**Comment by rcritten** [comment]
I added a test that uses user-mod and user-find since I suppose this is how the conversion will be done in practice.

**Comment by abbra** [comment]
review is needed

**Comment by antoniotorresm** [comment]
LGTM

**Comment by antoniotorresm** [comment]
master:

* ef955c90150d7d1df145b16b1f17940769d42f56 support more DateTime attributes in LDAP searches in IPA API

**Pull request closed without merging**
