### PR TITLE
ipadiscovery: Return realm as a string

### PR DESCRIPTION
**Pull request by stlaz**
We don't have a use for realm as a bytes instance, return it as a
string, otherwise there's a use of str() on bytes in py3.

https://pagure.io/freeipa/issue/4985

### CODE REVIEW

**Comment by MartinBasti** [comment]
A TXT record can contain anything in any encoding, it contains just bytes without predefined semantic, we should play safe here and catch UnicodeDecodeError.

Also currently we support only ASCII for realms, I'm not sure which character are allowed to be in realm outside IPA world, I haven't found a clear answer.

**Comment by stlaz** [comment]
https://tools.ietf.org/html/rfc1464 suggests that only ASCII may be contained in a TXT record, although I like to go with the Internet rule: "Trust noone." and so I decided to decode it as UTF-8.
You want to go even further on the aforementioned rule which is OK with me, then, I will update the PR.

**Comment by MartinBasti** [comment]
That is an experimental only RFC. By general it can contain any byte textually represented in octal form.

str() in python2 converts from bytes using ASCII codec, so by keeping compatibility and avoiding to parse weird realms it should be IMO ASCII. But I can live with utf-8 as well, but I haven't checked how is this handled later in code

**Comment by MartinBasti** [comment]
LGTM, we anyway assume inside framework that everything is in utf-8

**Comment by MartinBasti** [comment]
master:

* 1cab1e980c7cad65943e2984158a458a6472c9d2 ipadiscovery: Return realm as a string
* c8cc62564b09959c451522b1d7eb122566594867 Docstring+refactor of IPADiscovery.ipadnssearchkrbrealm()

**Pull request closed without merging**
