### PR TITLE
Update man page for ipa-adtrust-install by removing --no-msdcs option

### PR DESCRIPTION
**Pull request by pspacek**
https://bugzilla.redhat.com/show_bug.cgi?id=1392778

### CODE REVIEW

**Comment by martbab** [comment]
Please add the upstream ticket to the commit message.

**Comment by pspacek** [comment]
Here you go.

**Comment by mbasti-rh** [comment]
Fixed upstream
master:
https://fedorahosted.org/freeipa/changeset/623cc428cfd79ea228bda6e88dc48bad9aaf61aa

**Comment by pspacek** [comment]
Given the code change went to ipa-4-4 branch, I would merge it to ipa-4-4 as well. It does not make sense to keep it only in 4.5 and have incorrect documentation in 4.4.

**Comment by mbasti-rh** [comment]
So please re-triage it today, yesterday was only 4.5 milestone agreed

**Comment by mbasti-rh** [comment]
Fixed upstream
ipa-4-4:
https://fedorahosted.org/freeipa/changeset/ef988aab6c756d5fec4513c182d702fb0a1db249

**Pull request closed without merging**
