### PR TITLE
[Backport][ipa-4-7] Wrap CustodiaClient in context manager

### PR DESCRIPTION
**Pull request by frasertweedale**
Manual backport of #3262

### CODE REVIEW

**Comment by frasertweedale** [comment]
Conflicts were trivial; auto-ack.

**Comment by flo-renaud** [comment]
Hi @frasertweedale 
there is a pylint error:
```
Pylint on /usr/bin/python2 is running, please wait ...
************* Module ipaserver.secrets.client
ipaserver/secrets/client.py:7: [E0401(import-error), ] Unable to import 'secrets')
------------------------------------
```

**Comment by frasertweedale** [comment]
@tiran just a heads-up, this is failing with error
```
2019-06-19 03:20:40,539    DEBUG  transport.py               558 DEBUG    Error storing key "keys/dm/DMHash": 'NoneType' object is not subscriptable
```
See http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/3519bc8e-923e-11e9-82c9-fa163ef01e1e/runner.log.gz.  I'm trying to work out what's going on.  Adding WIP label.  Calling it a day soon (except for Falcon planning).

**Comment by frasertweedale** [comment]
n.b. there is currently a debug commit, please do not merge until CI is green *and* I removed WIP label.

**Comment by frasertweedale** [comment]
@abbra all systems go.

**Comment by abbra** [comment]
LGTM

**Comment by abbra** [comment]
ipa-4-7:

* 16016e847a817c5a10300bd085678db3449a99a8 Handle missing LWCA certificate or chain
* 6e57abb239f9e7b91ec4ef93abcf9af12fcb4222 Fix CustodiaClient ccache handling
* 5f0b0b521b9700612107e7347dfe28ebfbee7133 CustodiaClient: use ldapi when ldap_uri not specified
* 54a5bbb5a979d1a8f0cb7bff04ebf86cee52eb2b CustodiaClient: fix IPASecStore config on ipa-4-7

**Pull request closed without merging**
