### PR TITLE
Doc: add a design template

### PR DESCRIPTION
**Pull request by flo-renaud**
Add a template for new features in doc/designs/template.md
The template is excluded from automatic doc generation.

Signed-off-by: Florence Blanc-Renaud <flo@redhat.com>

### CODE REVIEW

**Comment by abbra** [comment]
LGTM. Ack after the re-run of failed unrelated test suites.

**Comment by flo-renaud** [comment]
Adding ipa-next label as the template does not need to be copied to the other branches

**Comment by rcritten** [comment]
Tests are green, ack from me too.

**Comment by rcritten** [comment]
master:

* 5edf144a7e6d8ec8d61360d05d87208f6339f049 Doc: add a design template

**Pull request closed without merging**
