### PR TITLE
ipatests: Add debug option to healthcheck_run

### PR DESCRIPTION
**Pull request by menonsudhir**
Currently the run_healthcheck doesnot display the debug ouput while running, hence added the --debug option 
everytime healthcheck_run is called

### CODE REVIEW

**Review by flo-renaud — COMMENTED** [review]
Hi @menonsudhir 
I would add debug as an optional argument with default value=True:
```
def run_healthcheck(host, source=None, check=None, output_type="json",
                    failures_only=False, debug=True):
```
and provide --debug only when requested:
```
cmd = ["ipa-healthcheck"]
if debug:
    cmd.append("--debug")
```

**Comment by menonsudhir** [comment]
> Hi @menonsudhir
> I would add debug as an optional argument with default value=True:
> 
> ```
> def run_healthcheck(host, source=None, check=None, output_type="json",
>                     failures_only=False, debug=True):
> ```
> 
> and provide --debug only when requested:
> 
> ```
> cmd = ["ipa-healthcheck"]
> if debug:
>     cmd.append("--debug")
> ```

**Comment by menonsudhir** [comment]
Reopening the PR since it was closed by mistake.

**Comment by menonsudhir** [comment]
The test failed is due to known issue: https://pagure.io/freeipa/issue/8506

**Comment by menonsudhir** [comment]
@flo-renaud the test has now passed in rerun, seems to be intermittent issue.

**Comment by flo-renaud** [comment]
`ipa-healthcheck` command is sometimes called directly with `self.master.run_command` and these calls don't benefit from the `--debug` option. You may want to replace them with `run_healthcheck(self.master, source=...)`. I noted for instance the following tests: test_dogtag_ca_check_exists, test_replication_check_exists, test_ipa_cert_check_exists, test_ipa_trust_check_exists, test_ipa_healthcheck_output_indent, test_ipahealthcheck_topology_with_ipactl_stop.

**Comment by rcritten** [comment]
It does seem to make sense to extend run_healthcheck() to handle the other possible options: indent, severity, input-file, etc.

**Comment by abbra** [comment]
There are suggestions from review that weren't implemented in past two weeks. I am turning WIP label back here.

**Pull request closed without merging**
