### PR TITLE
Test PR 3262 on f30

### PR DESCRIPTION
**Pull request by frasertweedale**
https://github.com/freeipa/freeipa/pull/3262 plus https://github.com/freeipa/freeipa/pull/3210 plus temp commit :)

### CODE REVIEW

**Comment by frasertweedale** [comment]
@tiran we can observe the same failures as I continued to experience in my PR.
In [Dogtag debug log](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/06868836-8db9-11e9-b5c4-fa163e6f8958/test_replica_promotion.py-TestSubCAkeyReplication--test_subca_master/replica0.ipa.test/var/log/pki/pki-tomcat/ca/debug.2019-06-13.log.gz), key retrieval failure:
```
2019-06-13 09:13:32 [KeyRetrieverRunner-ff8ae1f9-90b2-4ed4-b9a6-c9ba07518ea0] SEVERE: Failed to retrieve key from any host.
2019-06-13 09:13:32 [KeyRetrieverRunner-ff8ae1f9-90b2-4ed4-b9a6-c9ba07518ea0] WARNING: KeyRetriever did not return a result.
```

And in [journal](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/06868836-8db9-11e9-b5c4-fa163e6f8958/test_replica_promotion.py-TestSubCAkeyReplication--test_subca_master/replica0.ipa.test/journal.gz), a GSS failure to find credential in ccache:
```
Jun 13 09:13:32 replica0.ipa.test python3[21283]: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (No Kerberos credentials available (default cache: KCM:))
```

Your PR #3262 (as did mine #3216) fixed the issue when running on local machine, but fails in CI.  I remain baffled.

**Comment by tiran** [comment]
I'm puzzled about the error message ``GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (No Kerberos credentials available (default cache: KCM:))``. Why does it mention ``KCM:`` when the code sets ccache to ``MEMORY:``?

**Comment by frasertweedale** [comment]
It is possible `os.environ['KRB5CCNAME'] = x` / `setenv(3)` is silently failing somehow?

**Comment by tiran** [comment]
D'oh! The error message ``GSSAPI Error: Unspecified GSS failure. Minor code may provide more information (No Kerberos credentials available (default cache: KCM:))`` is not logged by the client side process. It is coming from the server side. gssapi is using ``int main(int argc, char **argv)`` argv[0] as logger name. That value is 'python3' for the forked request handler in ipa-custodia.

I have added more debugging code to my PR. The request process is now setting a syslog name based on sys.argv[0], which is different than ``int main(int argc, char **argv)``'s argv[0]. I also ensured that the ipa-custodia code only uses ``EXTERNAL`` auth. The process should use ldapi as root everywhere. Not sure why it stopped to do that.

**Comment by frasertweedale** [comment]
Closing; we now have f30 pr-ci temp commit in https://github.com/freeipa/freeipa/pull/3262.

**Comment by frasertweedale** [comment]
Successfully tested LWCA key replication on f30 with a temp commit: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/f6c75014-90cf-11e9-95bf-fa163e7e8887/.

Now I will remove the temp commit, and cherry-pick #3210 on top of this PR to try the usual test suite on F30.

**Pull request closed without merging**
