### PR TITLE
advise: Use `name` instead of `__name__` to get plugin names

### PR DESCRIPTION
**Pull request by martbab**
This change will allow ipa-advise to correctly handle advise plugins with
custom names.

### CODE REVIEW

**Comment by stlaz** [comment]
Seems to be doing more or less the same but in cleaner manner => LGTM. Do we need a ticket for this?

**Comment by martbab** [comment]
This change is intended only for master branch and I think a ticket would be a bit overkill.

**Comment by stlaz** [comment]
Sure.

**Comment by martbab** [comment]
Fixed upstream
master:
https://fedorahosted.org/freeipa/changeset/5b9516753cae324126fac7e17b6918c08e210d59

**Pull request closed without merging**
