### PR TITLE
python-netifaces: update to reflect upstream changes

### PR DESCRIPTION
**Pull request by MartinBasti**
python-netifaces now provides IPv6 netmask in format mask/prefix. It
breaks freeipa as it is unexpected format for python-netaddr. We must
split netmask and provide only prefix for netaddr.

https://pagure.io/freeipa/issue/7021

### CODE REVIEW

**Comment by martbab** [comment]
Shouldn't we bump requires on python-netifaces so that we don't accidentally pull in the older version that can break this new code?

**Comment by pvoborni** [comment]
Could the checked addresses(input from netifaces) be logged? It is easier to debug if something goes wrong.

**Comment by MartinBasti** [comment]
@martbab should work with both versions, I don't want to bump requires for this
@pvoborni It could, I'll update PR

**Comment by martbab** [comment]
master:

* 52b43c7168d02e84865e31faa478d8a93be7a913 python-netifaces: update to reflect upstream changes


ipa-4-5:

* 56d04b3dccc967630d869006dfbd0003fcfedabe python-netifaces: update to reflect upstream changes

**Pull request closed without merging**
