### PR TITLE
[Backport][ipa-4-9] ipatests: WebUI: do not allow subid range deletion #6379

### PR DESCRIPTION
**Pull request by menonsudhir**
This PR was opened manually because PR https://github.com/freeipa/freeipa/pull/6379 was pushed to master and backport to ipa-4-9 is required.

### CODE REVIEW

**Comment by rcritten** [comment]
Looks good. You can remove the temp commit. I think that this is already covered in prci_definitions so I think it's ok to merge once CI is done again

Link to passing test http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/5ef6e014-1953-11ed-999e-fa163e46d29b

**Comment by flo-renaud** [comment]
Please wait a bit before pushing this PR to ipa-4-9 branch. The test is buggy (see https://pagure.io/freeipa/issue/9214) and succeeds only if only `test_subid.py::test_subid::test_subid_range_deletion_not_allowed` is executed. When the whole test `test_subid.py::test_subid` is run, it fails.
There is a PR in progress that tries to fix the issue (https://github.com/freeipa/freeipa/pull/6396) but it is still WIP. I'd rather wait for PR 6396 and push both at the same time.

**Comment by rcritten** [comment]
Should this PR be rebased on top of the change in https://github.com/freeipa/freeipa/pull/6510 for re-testing?

**Comment by flo-renaud** [comment]
@rcritten @menonsudhir I combined the changes from this PR and from #6510 into a new PR: #6520.
We can close this one (#6407) in favor of #6520.

**Pull request closed without merging**
