### PR TITLE
Don't stop certmonger during IPA uninstallation

### PR DESCRIPTION
**Pull request by rcritten**
An effort prevent CI failures.

https://pagure.io/freeipa/issue/8533

Signed-off-by: Rob Crittenden <rcritten@redhat.com>

### CODE REVIEW

**Comment by rcritten** [comment]
It passed, re-running.

**Comment by rcritten** [comment]
Passed five times, re-running.

**Comment by rcritten** [comment]
@flo-renaud do you think there is a better test to exercise this re-ordering of the uninstall?

**Comment by flo-renaud** [comment]
@rcritten test_cert_fix and test_replica_promotion_TestHiddenReplicaPromotion are probably the jobs that fail the most frequently. But I think the right ticket is https://pagure.io/freeipa/issue/8506 for this issue (8533 happens during replica installation while configuring the cert tracking).

**Comment by rcritten** [comment]
Thanks for the suggestion, updating the test. I'll have to remember to go back to fix the ticket number.

**Comment by rcritten** [comment]
Both invocations of test_integration/test_replica_promotion.py::TestHiddenReplicaPromotion failed due to DNS issues. Re-running.

**Comment by rcritten** [comment]
Two more failures, unrelated to dbus.

**Comment by rcritten** [comment]
Try test_integration/test_caless.py::TestReplicaCALessToCAFull to try to provoke failure. If I can't maybe I'll drop the change to see if I can more easily reproduce this and then add the change back in to see if it actually did anything.

**Comment by rcritten** [comment]
Re-based and dropped change to see if one or more of the tests fail.

**Comment by rcritten** [comment]
temp_commit_2 reproduced the uninstall dbus error:

[ipatests.pytest_ipa.integration.host.Host.master.cmd54] org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

**Comment by rcritten** [comment]
All five executions of test_ipa_cert_fix.py failed with the dbus error and the re-organized code change.

**Comment by rcritten** [comment]
I think I may have it worked out but I've heavily redone the patch so we'll see. Originally I was trying to move the certmonger CA removal ahead of shutting down IPA. I've dropped that and went with the original code in cainstance.py but wrapped it with a loop.

dbus is socket activated and I think that sometimes it takes longer than certmonger is willing to wait to start up. So stick it into a loop and try up to 5 times.

In testing it never took more than 2 tries with no sleep.

**Comment by rcritten** [comment]
One of the dbus failures related to stop tracking of the CA certs in certmonger. We got a DBus timeout. Upon retrying sometimes we would also get a no_such_entry from certmonger which is very odd. It basically means that we asked for a request from certmonger and it returned one, but the path to that request is not found upon requesting stop tracking. I added code to skip in that case. We should see in the uninstall log if there are remaining untracked certs.

**Comment by rcritten** [comment]
What I observed in the last set of logs is the request to stop tracking failed with a DBus timeout but the request was actually successful. Tune up the logging around this so it is more clear what went on.

We would see a message like "Some certificates may still be tracked by certmonger." in the server uninstall log if there were remaining certificates. I haven't seen this in these dbus timeout failure cases.

**Comment by rcritten** [comment]
For the reviewer:

There are two categories of errors here:

1. Stop tracking the CA certificates in certmonger faisl with a DBus.Error.NoReply.

A handled failure looks like:

024-02-11T15:50:57Z DEBUG Attempt 1 to stop tracking for 'auditSigningCert cert-pki-ca in /etc/pki/pki-tomcat/alias'
2024-02-11T15:51:22Z DEBUG org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
2024-02-11T15:51:22Z DEBUG Attempt 2 to stop tracking for 'auditSigningCert cert-pki-ca in /etc/pki/pki-tomcat/alias'
2024-02-11T15:51:43Z DEBUG org.fedorahosted.certmonger.no_such_entry: No matching entry found.
2024-02-11T15:51:43Z DEBUG Tracking no longer exists, stop trying
2024-02-11T15:51:43Z DEBUG Attempt 1 to stop tracking for 'ocspSigningCert cert-pki-ca in /etc/pki/pki-tomcat/alias'
2024-02-11T15:51:43Z DEBUG stop tracking successful

What you see here is the first attempt failing, it being caught, and a second attempt only to find out that the path doesn't exist. This means that the original request was successful but not communicated back.

A success on the first try looks like:

2021-02-10T16:02:37Z DEBUG Attempt 1 to stop tracking for /var/kerberos/krb5kdc/kdc.crt
2021-02-10T16:02:37Z DEBUG stop tracking successful

I tend to see this failure in test_integration-test_ipa_cert_fix.py-TestIpaCertFix-uninstall. You'll find the entries in the uninstall log.

The other error happens when trying to remove the IPA-created CA's in certmonger. Similarly we don't get a response back but the retry succeeds without a not found error.

A success looks like:
2024-02-11T15:51:45Z DEBUG Attempt 1 to remove certmonger CAs
2024-02-11T15:51:45Z DEBUG certmonger CA removal successful

A handled failure looks like:
2021-02-10T16:02:06Z DEBUG Attempt 1 to remove certmonger CAs
2021-02-10T16:02:31Z DEBUG org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
2021-02-10T16:02:31Z DEBUG Attempt 2 to remove certmonger CAs
2021-02-10T16:02:32Z DEBUG certmonger CA removal successful

I tend to see this most in test_integration-test_caless.py-TestReplicaCALessToCAFull-uninstall on the replica in the uninstall log.

**Comment by rcritten** [comment]
I'm going to try to generalize this test loop. https://pagure.io/freeipa/issue/8470 shows this dbus error also on a fresh installation.

**Comment by rcritten** [comment]
So. Maybe it's been luck, but I made another change so that certmonger is not restarted during uninstall and that seems to have helped. I just ran a successful set with just that change and passed. I'll kick it again once Azure is done.

**Comment by rcritten** [comment]
Dropping WIP label, this seems to have fixed the uninstallation dbus-related issue.

**Comment by abbra** [comment]
LGTM. Please remove temp commit.

**Comment by rcritten** [comment]
Dropped the temp commits.

**Comment by abbra** [comment]
ACK.

**Comment by abbra** [comment]
master:

* 71047f68b55ab59d4615c2601b702ec4a84bce4f Remove the option stop_certmonger from stop_tracking_*

**Pull request closed without merging**
