### PR TITLE
doc: Design document for LDAP graceperiod

### PR DESCRIPTION
**Pull request by rcritten**
Implement part of RFC https://tools.ietf.org/id/draft-behera-ldap-password-policy-10.html

https://pagure.io/freeipa/issue/1539

Signed-off-by: Rob Crittenden <rcritten@redhat.com>

### CODE REVIEW

**Comment by abbra** [comment]
LGTM

**Comment by stanislavlevin** [comment]
@rcritten, is there a proposed default for policy `passwordGraceLimit`?

**Comment by rcritten** [comment]
> > @rcritten, is there a proposed default for policy `passwordGraceLimit`?
> 
> from the commit [f347c3f](https://github.com/freeipa/freeipa/commit/f347c3f2302e468b7f92ec0146100b19570e382e) :
> 
> ```
> +option: Int('passwordgracelimit?', cli_name='gracelimit', default=0)
> ```

I wonder if it should be -1 instead. 0 disables all LDAP authentications at expiration. This could be a bit of a jolt to many users that I hadn't considered a time of coding.

**Comment by abbra** [comment]
I would keep current behavior as a default, this would be least invasive, I'd think. So, -1?

**Comment by abbra** [comment]
The changes to add defaults need more handling as upgrade now fails, visible in `test_upgrade` test suite run -- previous `global_policy` has no new objectclass `ipaPwdPolicy` so it does not allow to add `passwordGraceLimit`.

**Comment by rcritten** [comment]
Upgrades are being addressed in https://github.com/freeipa/freeipa/pull/6283

**Comment by rcritten** [comment]
What I'll do here is rebase this on top of the upgrade patch once I merge it. I believe that will address the failures.

**Comment by abbra** [comment]
LGTM again. ;)

**Comment by rcritten** [comment]
master:

* 08ab274744794f269081f4ba0259e662038ab9a3 doc: Design document for LDAP graceperiod
* deb0c765561bc5dbc42c509005e4aab57d0b4a0b Set default LDAP password grace period to -1
* 420344ed49e5b50454853969c5edfcc7190d1de7 graceperiod: ignore case when checking for missing objectclass

**Pull request closed without merging**
