### PR TITLE
Teach pylint how our api works

### PR DESCRIPTION
**Pull request by tiran**
pylint 2.0 is more strict and complains about several aspects of
ipalib.api. It turns out that AstroidBuilder.string_build() can be used
to easily teach pylint about object attributes and attribute values.
Although the assignment wouldn't work with the actual implementation,
the string builder assignments shows pylint the names and values of
members. It works without additional transformation.

See: pagure.io/freeipa/issue/7614
Signed-off-by: Christian Heimes <cheimes@redhat.com>

### CODE REVIEW

**Comment by netoarmando** [comment]
Should this address violation `W1306(missing-format-attribute)` in cases [like the following](https://github.com/freeipa/freeipa/blob/master/ipaserver/install/server/replicainstall.py#L875)?
```python
kinit_keytab(
    'host/{env.host}@{env.realm}'.format(env=api.env),
    paths.KRB5_KEYTAB,
    ccache,
)
```

**Comment by tiran** [comment]
@netoarmando yes, it addresses the issue.

**Comment by netoarmando** [comment]
@tiran LGTM

**Comment by tiran** [comment]
master:

* 4fc7f72648df0ae03ac90f701425e297db72e9d6 Teach pylint how our api works
* aacf185ff8eb1bf6b54e0ba893ca4e750cb69564 Add pylint ignore to magic config.Env attributes

**Pull request closed without merging**
