### PR TITLE
Misc Python 3 fixes for ipaserver.secrets

### PR DESCRIPTION
**Pull request by tiran**
bytes/str fixes for LDAP data, JSON encoding and temp files.

Related to https://bugzilla.redhat.com/show_bug.cgi?id=1476150

### CODE REVIEW

**Comment by stlaz** [comment]
If I run `ipa-replica-install` like `sudo python3 -bb /usr/sbin/ipa-replica-install --domain myawesome.domain --admin-password password_even_more_awesome787` I still get the exceptions mentioned in the Bugzilla.

**Comment by tiran** [comment]
https://github.com/latchset/jwcrypto/pull/84 addresses a bytes/str comparison bug in jwcrypto. I'll create another release as soon as @simo5 has reviewed and ACKed the PR and another one.

**Comment by stlaz** [comment]
I had to do:
```diff
@@ -183 +183 @@ class CustodiaInstance(SimpleServiceInstance):
-                with open(pk12file, 'w+') as f:
+                with open(pk12file, 'wb') as f:
```
for the install to successfully finish but it does eventually.

@tiran, would you kindly add the above change + add the `python{2,3}-jwcrypto` dependency to the FreeIPA spec file? @dkupka / @tomaskrizek will kindly add the latest build (to our copr) so that it does not destroy our PRCI? Jolly thanks in advance.

**Comment by stlaz** [comment]
@tiran it should now be safe to do --^

**Comment by stlaz** [comment]
Works for me and the tests pass => ACK. Thanks for this fix!

**Comment by tomaskrizek** [comment]
I'm glad to see the PR CI picked up the new jwcrypto build from COPR without any issues :)

**Comment by tomaskrizek** [comment]
@tiran Please link the commit to an upstream ticket.

**Comment by tiran** [comment]
@tomaskrizek Just post the upstream ticket number here and I'll update my PR.

**Comment by tomaskrizek** [comment]
@tiran I think we can put this under the py3 fixes ticket: https://pagure.io/freeipa/issue/4985

**Comment by tiran** [comment]
Done

**Comment by tomaskrizek** [comment]
master:

* 5f0332905132b7c8fa65d6ed16cd2c028e5a0ed5 Misc Python 3 fixes for ipaserver.secrets

**Pull request closed without merging**
