### PR TITLE
adtrust: filter out subdomains when defining our topology to AD

### PR DESCRIPTION
**Pull request by abbra**
When definining a topology of a forest to be visible over a cross-forest
trust, we set *.<forest name> as all-catch top level name already.

This means that all DNS subdomains of the forest will already be matched
by this TLN. If we add more TLNs for subdomains, Active Directory will
respond with NT_STATUS_INVALID_PARAMETER.

Filter out all subdomains of the forest root domain. All other realm
domains will be added with explicit TLN records.

Fixes https://pagure.io/freeipa/issue/6666

### CODE REVIEW

**Comment by stlaz** [comment]
`ipaserver/dcerpc.py:1606: [W0612(unused-variable), TrustDomainJoins.get_realmdomains] Unused variable 'tforest')`

**Comment by abbra** [comment]
I turned the assignment into a comment. ;)

**Comment by stlaz** [comment]
pep8 wants you to have a space after the start of the comment :) I did not get to do a more proper review yet.
```
PEP-8 errors:
./ipaserver/dcerpc.py:1607:9: E265 block comment should start with '# '
```

**Comment by abbra** [comment]
;) I fixed this. Looked at other pep8 reports and there are none new.

**Comment by abbra** [comment]
master:

* 443ecbc29e3342e9021f6f4ae72ce11d5b238ba6 adtrust: filter out subdomains when defining our topology to AD

**Pull request closed without merging**
