### PR TITLE
Handle whitespace, add separator to regex in set_directive_lines

### PR DESCRIPTION
**Pull request by rcritten**
We added the separator to the regex in set_directive_lines to avoid
grabbing just a prefix. This doesn't allow for whitespace around
the separator.

For the Apache case we expected that the separator would be just
spaces but it can also use tabs (like Ubuntu 18). Add a special
case so that passing in a space separator is treated as whitespace
(tab or space).

https://pagure.io/freeipa/issue/7490

Signed-off-by: Rob Crittenden <rcritten@redhat.com>

### CODE REVIEW

**Comment by flo-renaud** [comment]
Hi @rcritten 
The code change looks good to me. The only issue I see is that the new test does not exhibit the issue (if you run it on the code without the fix, the test passes). You may want to add a test removing or modifying a directive that contains a tab.

**Comment by rcritten** [comment]
Excellent catch, new test added

**Comment by tjaalton** [comment]
seems to work here, thanks

**Comment by tiran** [comment]
@rcritten ``set_directive`` looks ok, but what about ``get_directive``? It can't handle ``\t`` yet.

**Comment by rcritten** [comment]
Good catch, I hadn't considered that. Currently looks like it throws an exception:

ValueError: Malformed directive: SSLCertificateFile     /etc/ssl/certs/ssl-cert-snakeoil.pem

**Comment by flo-renaud** [comment]
@rcritten 
thanks for the updated PR, works for me. Let's wait for @tiran approval.

**Pull request closed without merging**
