### PR TITLE
[Backport][ipa-4-9] schema plugin: Generate stable fingerprint

### PR DESCRIPTION
**Pull request by flo-renaud**
This PR was opened automatically because PR #5979 was pushed to master and backport to ipa-4-9 is required.

### CODE REVIEW

**Comment by flo-renaud** [comment]
PR was ACKed automatically because this is backport of PR #5979. Wait for CI to finish before pushing. In case of questions or problems contact @stanislavlevin who is author of the original PR.

**Comment by stanislavlevin** [comment]
New Pylint 2.9.6 arrived at Fedora.

**Comment by stanislavlevin** [comment]
Quick style task should borrow the Lint task schema(PyPI's Pylint but constrained versions).

**Comment by stanislavlevin** [comment]
https://pagure.io/freeipa/issue/8961

**Comment by stanislavlevin** [comment]
Can this PR be rebased to updated ipa-4-9?

**Comment by stanislavlevin** [comment]
If it is not possible with automatic tools, I can do it manually.

**Comment by flo-renaud** [comment]
Rebased to include the fix from PR #5988

**Comment by flo-renaud** [comment]
ipa-4-9:

* 939d0f5df67aa39cd31f68a6da4153460066ca66 schema plugin: Generate stable fingerprint
* 14ad52238543ab845a8d6dadd65ff2fb6e67d8df ipatests: Add tests for `schema` Command

**Pull request closed without merging**
