### PR TITLE
Test self-signed > external CA > self-signed test case.

### PR DESCRIPTION
**Pull request by Rezney**
Various changes are being done in this PR:

1. In order to avoid boilerplate code we add a function for signing a CA.
2. We add self-signed > external CA > self-signed test case itself + introduce two new constants.
3. We move create_caless_pki.py and create_external_ca.py modules to pytest_plugins. Details:

Till now both create_caless_pki.py and create_external_ca.py were
stored in test_integration folder. However when trying to import
e.g. "from create_external_ca import ExternalCA" from tasks.py
where all other integration test`s support functions lives we get
"AttributeError: module 'pytest' has no attribute 'config' as pytest
was not completely initialized at the moment of the import.

Backtrace from the issue:

```
  File "/usr/lib/python3.6/site-packages/_pytest/config.py", line 421, in consider_module
    self._import_plugin_specs(getattr(mod, 'pytest_plugins', []))
  File "/usr/lib/python3.6/site-packages/_pytest/config.py", line 426, in _import_plugin_specs
    self.import_plugin(import_spec)
  File "/usr/lib/python3.6/site-packages/_pytest/config.py", line 443, in import_plugin
    __import__(importspec)
  File "/usr/lib/python3.6/site-packages/ipatests/pytest_plugins/integration/__init__.py", line 37, in <module>
    from . import tasks
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/usr/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 212, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/usr/lib/python3.6/site-packages/ipatests/pytest_plugins/integration/tasks.py", line 47, in <module>
    from ipatests.test_integration.create_external_ca import ExternalCA
  File "/usr/lib/python3.6/site-packages/ipatests/test_integration/__init__.py", line 22, in <module>
    ipatests.util.check_ipaclient_unittests()
  File "/usr/lib/python3.6/site-packages/ipatests/util.py", line 71, in check_ipaclient_unittests
    if pytest.config.getoption('ipaclient_unittests', False):
AttributeError: module 'pytest' has no attribute 'config'
```

### CODE REVIEW

**Comment by flo-renaud** [comment]
Hi @Rezney 
thank you for this important test case!

You may want to extend the TestExternalCA test with a few checks after switching back to self-signed (related to [BZ 1512952](https://bugzilla.redhat.com/show_bug.cgi?id=1512952)):
- check that there are no errors in the journal related to renew_ca_cert (they can be found with `journalctl --since today -u certmonger SYSLOG_IDENTIFIER=/renew_ca_cert`
- check that the external CA is present in the `/etc/pki/pki-tomcat/alias` NSS database with `C,,` flags at least
- check that the unit `pki-tomcatd@pki-tomcat` has been restarted

Also you may want to add the test in .freeipa-pr-ci.yaml (currently it is specifically calling `test_integration/test_external_ca.py::TestExternalCA` and will not include the new test `test_integration/test_external_ca.py::TestSelfExternalSelf`).

**Comment by tiran** [comment]
@Rezney your PR needs another rebase and pylint fixes:

```
ipatests/test_integration/test_external_ca.py:55: [W1637(zip-builtin-not-iterating), match_in_journal] zip built-in referenced when not iterating)
ipatests/test_integration/test_external_ca.py:146: [E1120(no-value-for-parameter), TestSelfExternalSelf.test_switch_back_to_self_signed] No value for argument 'host' in function call)
ipatests/test_integration/test_external_ca.py:151: [E1120(no-value-for-parameter), TestSelfExternalSelf.test_switch_back_to_self_signed] No value for argument 'host' in function call)
```

**Comment by Rezney** [comment]
@flo-renaud thanks for taking a look. I may have misinterpreted some of your requirements in your original comment. Will fix it. The PRCI commit was attached as discussed internally.

**Comment by Rezney** [comment]
@flo-renaud Please check if your concerns were addressed. I had to switch to regexp when checking the CA flags as with previous implementation it would have not worked when there  was just one empty space delimiter.

**Comment by flo-renaud** [comment]
Hi @Rezney,
thank you for the patch, works as expected.

**Comment by Rezney** [comment]
@flo-renaud Thanks for the review. As there was the issue with pytest ordering probably after adding @tasks.collect_logs to every test_function lets wait with this PR after NY. You can remove ACK label for now.

**Comment by flo-renaud** [comment]
ok, removed ACK. Let's check this after the new year.

**Comment by Rezney** [comment]
@flo-renaud The logs collection should be addressed by https://github.com/freeipa/freeipa/pull/1423 so there will be no need to add @tasks.collect_logs anymore.

**Comment by flo-renaud** [comment]
@Rezney 
thank you for the heads-up, tested with PR 1423 and the logs are properly collected.
ACK

**Comment by tiran** [comment]
master:

* 0cef5107639beb00a65e02a7ae8e52612cfdb6f4 paths: add IPA_CACERT_MANAGE and IPA_CERTUPDATE constants
* efe21a1bda22fcfc1ad786fadf781bdcf6eb3b21 test_tasks: add sign_ca_and_transport() function
* ad996d79c639f92f57a20503b583ae68c77521e8 test_external_ca: selfsigned->ext_ca->selfsigned
* 3bdac1a84d363c876fc4b735fa75590fcb3ffead tests: move CA related modules to pytest_plugins
* 099856e1845f8c8a4b15bd8174a6e0d948b1ec16 prci: run full external_ca test suite

**Pull request closed without merging**
