### PR TITLE
[4.5, master] Fix PKCS11 helper

### PR DESCRIPTION
**Pull request by MartinBasti**
Slots in HSM are not assigned statically, we have to chose proper
slot from token label.

Softhsm i2.2.0 changed this behavior and now slots can change over
time (it is allowed by pkcs11 standard).

Changelog:
* created method get_slot() that returns slot number from
  used label
* replaces usage of slot in __init__ method of P11_Helper
  with label
* slot is dynamically detected from token label before
  session is opened
* pkcs11-util --init-token now uses '--free' instead '--slot'
  which uses first free slot (we don't care about slot numbers
  anymore)

https://pagure.io/freeipa/issue/6692

### CODE REVIEW

**Comment by stlaz** [comment]
`cffi.api.CDefError: cannot parse "typedef CK_RV (*CK_C_GetSlotList) (CK_BBOOL tokenPresent,`
-> you're using CK_BBOOL type before defining it.

**Comment by MartinBasti** [comment]
In 50% cases DNSSEC works for me :-). Ready for review.

(The issue was unrelated to PKCS11, I had somehow broken machine probably)

**Comment by stlaz** [comment]
I ran the integration test and the result was fine, ACK.

**Comment by MartinBasti** [comment]
ipa-4-5:

* e6b2ed6b68589ff7ee39b95559836af54f39e2de Fix PKCS11 helper


master:

* e8f2a415b3dcba30b0c39cd542acd6b459f46957 Fix PKCS11 helper

**Pull request closed without merging**
