### PR TITLE
ccache_sweeper: Add gssproxy service

### PR DESCRIPTION
**Pull request by stanislavlevin**
The usage of the existing gssproxy service(`service/ipa-api`) leads to undesirable for this case side effects such as auto renew of expired credentials.

Fixes: https://pagure.io/freeipa/issue/8735

### CODE REVIEW

**Comment by abbra** [comment]
Looks good to me. I don't see anything running, though. CI runners must be busy...

**Comment by abbra** [comment]
ACK now.

**Comment by stanislavlevin** [comment]
@abbra, thank you for the review!
I'm sorry just pushed:
- commit to drop `HTTP_CCACHE`
- provided more description

**Comment by stanislavlevin** [comment]
Sorry for inconvenience, no more changes are planned here.

**Comment by abbra** [comment]
Ok, I removed the ACK until the CIs complete. No additional review is needed, I think.

**Comment by stanislavlevin** [comment]
http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/e52f4e74-7c46-11eb-9ef8-fa163e4416a0/runner.log.gz:
- test_integration/test_krbtpolicy.py::TestPWPolicy::test_ccache_sweep_expired - PASSED
- test_integration/test_krbtpolicy.py::TestPWPolicy::test_ccache_sweep_valid - PASSED

**Comment by stanislavlevin** [comment]
@abbra, the related tests passed. Can I remove the temp commit?

**Comment by abbra** [comment]
Yes, please do.

**Comment by abbra** [comment]
master:

* 271fd162a76d999c9b03c5b2103ededdf3eb2fd9 ccache_sweeper: Add gssproxy service
* 7972d28240d57f5dfbc4bb58aeb08f456524c24f cleanup: Drop never used path for httpd's ccache

**Pull request closed without merging**
