### PR TITLE
ipatests: add missing nightly tests for replica_promotion installation and external_ca

### PR DESCRIPTION
**Pull request by flo-renaud**
## ipatests: add missing tests for test_installation.py

Some tests were missing in the nightly:
- test_installation.py::TestInstallWithCA_DNS3
- test_installation.py::TestInstallWithCA_DNS4

## ipatests: add missing tests for test_replica_promotion.py
    
The following test was missing from nightly:
test_replica_promotion.py::TestReplicaInstallCustodia

## ipatests: add missing tests for test_external_ca.py

Some tests were missing from nightly definition:
- test_external_ca.py::TestExternalCAdirsrvStop
- test_external_ca.py::TestExternalCAInvalidCert
- test_external_ca.py::TestMultipleExternalCA

Related to https://pagure.io/freeipa/issue/7743

### CODE REVIEW

**Comment by abbra** [comment]
Looks good. Please remove temp commit.

**Comment by flo-renaud** [comment]
Thanks, temp commit removed

**Comment by abbra** [comment]
Both travis and PR-CI encountered networking issues with fedora repositories. Re-starting the run.

**Comment by flo-renaud** [comment]
master:

* 1e7be6fb3d1b50e6d5f398ea385f4fec6fad6598 ipatests: add missing tests for test_external_ca.py
* 19211257c64ac95d1b0cc0d83729383dea7a98d1 ipatests: add missing tests for test_installation.py
* d18b0d558ba56f3da16c6240d46ed9809c37b256 ipatests: add missing tests for test_replica_promotion.py

**Pull request closed without merging**
