### PR TITLE
ipa-replica-install: fix pkinit setup 

### PR DESCRIPTION
**Pull request by flo-renaud**
### ipa-replica-install: fix pkinit setup
commit 7284097 (Delay enabling services until end of installer)
introduced a regression in replica installation.
When the replica requests a cert for PKINIT, a check is done
to ensure that the hostname corresponds to a machine with a
KDC service enabled (ipaconfigstring attribute of
cn=KDC,cn=<hostname>,cn=masters,cn=ipa,cn=etc,$BASEDN must contain
'enabledService').
With the commit mentioned above, the service is set to enabled only
at the end of the installation.

The fix makes a less strict check, ensuring that 'enabledService'
or 'configuredService' is in ipaconfigstring.

Fixes: https://pagure.io/freeipa/issue/7566

### Tests: test successful PKINIT install on replica

Add a test checking that ipa-replica-install successfully configures
PKINIT on the replica

### CODE REVIEW

**Comment by tiran** [comment]
Isn't there a better way to test, if pkinit is fully and correctly installed? The check depends on a hard-coded error message.

**Comment by flo-renaud** [comment]
@tiran you are right, I can use `ipa-pkinit-manage status` instead to check if pkinit was successfully enabled. Will update the test.

**Comment by tiran** [comment]
@flo-renaud ACK, please remove the temp commit.

**Comment by flo-renaud** [comment]
Adding the re-run label as test_vault failed.

**Comment by flo-renaud** [comment]
master:

* 2a227c240fae802d3625805e0905a8ce71706b2f ipa-replica-install: fix pkinit setup
* bcfd18f336d752483dffc048e1d9c0edac1628fd Tests: test successful PKINIT install on replica

**Pull request closed without merging**
