### PR TITLE
[Backport][ipa-4-9] ipatests: Test to check ipa ca-show <authority ID> error handling

### PR DESCRIPTION
**Pull request by ssidhaye**
Test to verify if the case of a request for /ca/rest/authority/{id}/cert (or .../chain)

where {id} is an unknown authority ID.

Test Steps:
1. Setup a freeipa server and a replica
2. Stop ipa-custodia service on replica
3. Create a LWCA on the replica
4. Verify LWCA is recognized on the server
5. Run `ipa ca-show <LWCA>`

Signed-off-by: Sumedh Sidhaye <ssidhaye@redhat.com>

### CODE REVIEW

**Comment by ssidhaye** [comment]
This is a manual backport of #6046 

@flo-renaud or @rcritten Can you review this?

**Review by mrizwan93 — APPROVED** [review]
LGTM

**Comment by flo-renaud** [comment]
@ssidhaye thanks for the backport, test is green, ACK

**Comment by flo-renaud** [comment]
ipa-4-9:

* 4c14b8cfddf78d4e792eb944ef1a765a115e3f10 Test to verify if the case of a request for /ca/rest/authority/{id}/cert (or .../chain)

**Pull request closed without merging**
