### PR TITLE
Uninstaller: uninstall PKI before shutting down services

### PR DESCRIPTION
**Pull request by flo-renaud**
The uninstaller is stopping all the services before
calling pkidestroy to uninstall the CA.
With PKI 11.4+ this sequence fails as pkidestroy tries
to connect to PKI server in order to unregister from the
security domain. The error interrupts the full completion
of pkidestroy, is logged but doesn't make ipa uninstallation
fail.
The issue is that trying to re-install later on would fail because
pkidestroy did not completely uninstall the CA.

To avoid this, call pkidestroy before shutting down the services.

Fixes: https://pagure.io/freeipa/issue/9330

Signed-off-by: Florence Blanc-Renaud <flo@redhat.com>

### CODE REVIEW

**Comment by rcritten** [comment]
What happens if the CA can't start? Say it failed for some reason durng install (not uncommon) or the certificates are expired?

**Comment by flo-renaud** [comment]
> What happens if the CA can't start? Say it failed for some reason durng install (not uncommon) or the certificates are expired?

We can also use `pkidestroy --force`, that succeeds even if PKI is down.

**Comment by rcritten** [comment]
The KRA was moved prior to shutdown in 1870c933542d41766dd9e2076deb7db758726864

An uninstall check is used to ensure that IPA is running. The CA likely needs something similar.

**Comment by flo-renaud** [comment]
For future ref: link to successful run of `test_backup_and_restore_TestBackupReinstallRestoreWithKRA` with PKI nightly build: [Details](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/062140ca-0ad3-11ee-9b98-fa163e04db38)

Removing the temp commit.

**Comment by rcritten** [comment]
If the CA cannot be started then it cannot be uninstalled.

Reproducer:
1. Install IPA
2. certutil -d /etc/pki/pki-tomcat/alias -D -n 'auditSigningCert cert-pki-ca'
3. systemctl stop pki-tomcatd@pki-tomcat

The installer will attempt to start the CA and fail, then proceed and will fail in the CA uninstall. The rest of IPA will be removed.

An odd side-effect I noticed is that "Unconfiguring CA" doesn't appear when the CA isn't started. I don't know if it's going down another path or not.

I did not test the KRA uninstall but I imagine it is similar. Perhaps if the CA can't be started we can add --force to pkidestroy.

**Comment by rcritten** [comment]
It affects the KRA as well.

**Comment by flo-renaud** [comment]
> An odd side-effect I noticed is that "Unconfiguring CA" doesn't appear when the CA isn't started. I don't know if it's going down another path or not.

This is because of the way we detect if a subsystem is installed. The code is using `pki-server subsystem-show ca` (see in https://github.com/freeipa/freeipa/blob/ae6549ffae1ffe2bb6a1ba7dce0620ec0c20cabf/ipaserver/install/dogtaginstance.py#L176-L189) and parses the output. When the pki server is started and everything works well, we see:
```
# pki-server subsystem-show ca
  Subsystem ID: ca
  Instance ID: pki-tomcat
  Enabled: True
```
but if the CA failed to start (because of the missing 'auditSigningCert cert-pki-ca' cert for instance), the output is the following:
```
# pki-server subsystem-show ca
  Subsystem ID: ca
  Instance ID: pki-tomcat
  Enabled: False
```
On a system where a subsystem hasn't been installed, the output is:
```
# pki-server subsystem-show kra
ERROR: ERROR: No kra subsystem in instance pki-tomcat.
```

I will fix this detection method in my next patch (only need to ensure that "Enabled: " is present, we don't care if it is enabled or disabled but only care if it has been installed. And also always add --force option to pkidestroy.

**Comment by flo-renaud** [comment]
Discussed with @ckelleyRH the --force flag and here is what is wrote:

- I have checked the code to see what are the side effects of calling pkispawn with –force. There is a check in pkispawn for whether the PKI instance that was previously installed still exists and –force bypasses this. Then there is a second check for whether the subsystem you are trying to destroy still exists within that instance - which –force bypasses.
- From there pkispawn calls various scriptlets to do the rest of the work, passing in no args. So as far as I can see passing in –force does exactly what you want to do - be able to uninstall broken/partially removed systems. And crucially it does this with no other consequences elsewhere in the scripts

**Comment by rcritten** [comment]
Thanks, these changes look good. Just one more small thing. When forcing the CA to not start (deleting cert) there is a very long pause where the is no output at all. It looks hung. I wonder if a message 'Restarting services" in both the ca and kra uninstall_check would help there.

Also of note, as expected, in the failure case the security domain is not cleaned up unless ipa server-del <replica> is executed first, which is the recommendation anyway. But people don't always do it.

FWIW I wrote a blog post recently on how to manually clean it, https://rcritten.wordpress.com/2023/04/28/dogtag-pki-security-domain-management/

**Comment by rcritten** [comment]
Thanks, change tested and LGTM.

**Comment by flo-renaud** [comment]
master:

* 67a33e5a305c7510fb182f84e46f304043f6ab37 Uninstaller: uninstall PKI before shutting down services
* 6c84ae5c3035ecd917404cc41c32a4b25c607b46 Detection of PKI subsystem

**Pull request closed without merging**
