### PR TITLE
docs: add security section to idp

### PR DESCRIPTION
**Pull request by pbrezina**

### CODE REVIEW

**Comment by abbra** [comment]
Thank you for the PR. I think there is only minor issue: the 'Security' section needs to be one level up so that it is at the same level as 'Individual tasks', not under it.

**Comment by pbrezina** [comment]
Thank you for a quick review, it should be fixed now.

**Comment by abbra** [comment]
Since this is a documentation-only change, I am not going to run the full CI. A rendered documentation update can be seen here: https://freeipa--6539.org.readthedocs.build/en/6539/designs/external-idp/external-idp.html#security

Let's wait until Azure CI finishes and then ACK.

**Comment by rcritten** [comment]
Should the idp tickets be added to the commit message?

    Related: https://pagure.io/freeipa/issue/8805
    Related: https://pagure.io/freeipa/issue/8804
    Related: https://pagure.io/freeipa/issue/8803

**Comment by abbra** [comment]
Yes, good catch.

**Comment by pbrezina** [comment]
Done.

**Pull request closed without merging**
