### PR TITLE
[Backport][ipa-4-6] ACI: grant access to admins group instead of admin user

### PR DESCRIPTION
**Pull request by Tiboris**
This PR was opened automatically because PR #1426 was pushed to master and backport to ipa-4-6 is required.

### CODE REVIEW

**Comment by Tiboris** [comment]
PR was ACKed automatically because this is backport of PR #1426. Wait for CI to finish before pushing. In case of questions or problems contact @flo-renaud who is author of the original PR.

**Comment by Tiboris** [comment]
Removed ACK and added WIP because of potential security issues.

**Comment by pvoborni** [comment]
@Tiboris, @flo-renaud   Usually, backport PRs are pushed when CI passes. This one has WIP label and ACK removed. Is there a reason to not push it?

**Comment by flo-renaud** [comment]
@pvoborni 
yes it's because of ticket #7402. We need to discuss if the current behavior is acceptable or if we need to plan some work around it.

**Comment by flo-renaud** [comment]
WIP flag removed, issue was discussed and agreed to backport to 4-6. Ticket 7402 has been triaged to 4.8 so this fix is needed in the meantime.

**Comment by flo-renaud** [comment]
ipa-4-6:

* 35f6a1a11baadf0f69c3d3ec7cc9933c87dd4abf ACI: grant access to admins group instead of admin user

**Pull request closed without merging**
