### PR TITLE
tests: webui: Address several issues

### PR DESCRIPTION
**Pull request by stanislavlevin**
- allow file access from files in tests
- load qunit only once
- updated vendored qunit

Related: https://pagure.io/freeipa/issue/9329

### CODE REVIEW

**Comment by stanislavlevin** [comment]
`qunit` tests manually checked against FF and Chromium.

**Comment by stanislavlevin** [comment]
The tests are broken with recent `grunt-contrib-qunit 7`, but it's worth to notice that the previous version
`6.2.1` literally checks nothing. For example,
https://dev.azure.com/freeipa/freeipa/_build/results?buildId=12471&view=logs&j=95a7e090-ce4f-5217-53f4-3d03c3589378&t=0fca0f6f-4451-532e-f43d-ff5cce934480:
```
Running "qunit:all" (qunit) task
Verifying property qunit.all exists in config...OK
Files: test/all_tests.html -> all
Options: timeout=5000, inject="/__w/1/s/install/ui/node_modules/grunt-contrib-qunit/chrome/bridge.js", urls=[], force=false, console, httpBase=false, summaryOnly=false
Finishing: WebUI Unit Tests
```
and there was no produced tests report.

**Comment by stanislavlevin** [comment]
There are several *unrelated* to this PR warnings/errors in FF/Chromium, but I think it's ok as it is.

**Comment by flo-renaud** [comment]
@stanislavlevin 
thanks for the patch, it will unblock many PRs in review :star:
Also tested manually: follow the instructions from https://www.freeipa.org/page/FreeIPAv2:UI_Unit_Tests#Necessary_steps_for_running_tests
- with firefox, one needs to change the setting `security.fileuri.strict_origin_policy` to false (in about:config), then launch cd install/ui/test && firefox index.html
- with google-chrome: cd install/ui/test && google-chrome --allow-file-access-from-files  index.html

**Comment by flo-renaud** [comment]
master:

* 5c35405e78cc5cf00f824acde1c5cf85d685a306 tests: webui: Allow file access from files in tests
* a7e13f9719223f04ed1bceb7c7c91d5a04a7d761 tests: webui: Load qunit only once
* 8d634d8abf296f52b5c348e582c19bb4bdce2983 AP: webui: List installed nodejs packages
* 64fa6b7241eec2547b2c427fbdb9225cf9153721 tests: webui: Update vendored qunit

**Comment by stanislavlevin** [comment]
@flo-renaud, thank you!

**Pull request closed without merging**
