### PR TITLE
Always check peer has keys before connecting

### PR DESCRIPTION
**Pull request by simo5**
When pulling the DM password we may have the same issues reported in
ticket #6838 for CA keys.
This commit makes sure we always check the peer has keys before any
client operation.

### CODE REVIEW

**Comment by Rezney** [comment]
Run the test (TestLineTopologyWithoutCA) where I was having the issue 15x with this patch and did not hit it anymore.

**Comment by stlaz** [comment]
Wouldn't this make CA uninstallable on a replica in a CA-less domain?

**Comment by simo5** [comment]
I do not see how, the keys we are looking for are custodia keys and they are always created by us and then replicated, we are just making sure they are replicated to the other master before continuing.
custodia runs regardless of the fact the other server is or not a CA or whether a CA exists at all.

**Comment by stlaz** [comment]
Ah, sorry, I got carried away while thinking about some other issues.

**Comment by simo5** [comment]
@stlaz do we have anything blocking this one ?

**Comment by stlaz** [comment]
Yes, the problem was that nobody was actually reviewing this, I am going to have a review morning tomorrow so I'll have a look.

**Comment by stlaz** [comment]
Tested three different topologies and with CA-less. Seems to work fine, thanks! ACK.

**Comment by pvomacka** [comment]
master:

* c565fa1781121cf284886e1f2d0691cfe10760d2 Always check peer has keys before connecting


ipa-4-5:

* 2dccb91792f9369a5fe0248f8d2a3e95081737c3 Always check peer has keys before connecting

**Pull request closed without merging**
