### PR TITLE
ipatests: add missing tests to nightly run for ipa-4-6

### PR DESCRIPTION
**Pull request by wladich**
The following tests were missing in nightly_ipa-4-6.yaml:
- test_idviews (partially)
- test_replica_promotion (partially)
- test_installation (partially)
- test_crlgen_manage
- test_nfs.py
- test_otp

### CODE REVIEW

**Comment by flo-renaud** [comment]
- `test_server_del` needs a fix provided by PRs [3943](https://github.com/freeipa/freeipa/pull/3943) and [3978](https://github.com/freeipa/freeipa/pull/3978) that were not backported to ipa-4-6
- `test_otp` yaml definition should not use `ipaserver` topology as this implies installation of the server before running the test, but rather `master_1repl`.

**Comment by flo-renaud** [comment]
Hi @wladich 
the uninstall failed in test_installation_TestInstallWithCA_KRA1 because the uninstall code is checking the domain level, but at this point the API is not usable anymore and default level=0 is returned. As a consequence, --ignore-last-of-role is not added.

**Comment by wladich** [comment]
Removed test_server_del from this PR, it is still [failing](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/4e052888-7824-11ea-bdcb-fa163e168469/report.html).
It will be fixed later.

**Comment by wladich** [comment]
@flo-renaud 
I have removed the test_server_del test from PR, other tests are green.
Please check if everything looks fine.

**Comment by flo-renaud** [comment]
Hi @sorlov,
the list of tests LGTM, please remove the temp commit.

**Comment by flo-renaud** [comment]
Tests are green and temp commit removed, ack.

**Comment by wladich** [comment]
ipa-4-6:

* 2ffd1bd2c98f7a2e8e8d60836b5b3a1b851d4d51 ipatests: generic uninstall should call ipa server-del
* 6942c48253e326263ddc83286f1d0c7e799b0221 ipatests: add missing tests to nightly run
* 47ba3bd64cd4ef34eaf683b3630a677e4785b21f ipatests: remove unneeded xfails
* f36789135d3e9deb20c4959dc0a9b9542f9311f7 ipatests: specify domain level
* d08a8c5ab17788baa527f514d17d760cf6fb68bd ipatests: add missing classes from test_installation to nightly runs
* 67ad001580a02641e17078d1bb0cf662e576ca6a ipatests: add TestReplicaPromotionLevel0 to nightly runs
* c3c665cef82b2a6a573583741abc525d43f0c4f2 ipatests: add AD DC as a DNS forwarder before establishing trust
* 1aa43de46c795c6f7ccc282a9d13388fc84b25fa ipatests: explicitly save output of certutil
* 533996fcafeed1d89e5ceeabb7aaecfbf88d669c ipatests: do not modify sssd.conf if not needed
* 5bcc7039891503913fb8f3820aa02d5aa283e11a ipatests: run all cases from test_integration/test_idviews.py in nightlies

**Pull request closed without merging**
