### PR TITLE
[Backport][ipa-4-6] dnsrecord-mod: allow to modify ttl without passing the record

### PR DESCRIPTION
**Pull request by flo-renaud**
This PR was opened automatically because PR #3288 was pushed to master and backport to ipa-4-6 is required.

### CODE REVIEW

**Comment by flo-renaud** [comment]
PR was ACKed automatically because this is backport of PR #3288. Wait for CI to finish before pushing. In case of questions or problems contact @flo-renaud who is author of the original PR.

**Comment by flo-renaud** [comment]
Added a fix related to python2/python3 (see PR #3356 on the master branch).

**Comment by rcritten** [comment]
Please rebase to pick up tox fix which should let CI complete.

**Comment by flo-renaud** [comment]
Re-adding the automatic ACL as this is a simple backport of PR #3288 and #3356.

**Comment by flo-renaud** [comment]
ipa-4-6:

* e7fa5f31379dce4fc245359499301233b455136b dnsrecord-mod: allow to modify ttl without passing the record
* de17f2af7343d2980ab676808d8f08065d512537 XMLRPC tests: add new test for ipa dsnrecord-mod $ZONE $RECORD --ttl
* 104247dab79f039e1ecace985240bbd5bd220cb9 ipatests: fix ipatests/test_xmlrpc/test_dns_plugin.py

**Pull request closed without merging**
