### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by abbra**
Update translations from Zanata and add Portuguese translation

### CODE REVIEW

**Comment by netoarmando** [comment]
Portuguese translation looks fine!

**Comment by stanislavlevin** [comment]
@abbra, is it possible to wait today/tomorrow to update Ru translation in Zanata by our translation team?

**Comment by abbra** [comment]
@stanislavlevin you can update the translation in Zanata. It is harder to postpone the release, though. We can include the updates in the next release (I'm planning to do one more in December to pick up more fixes before going for Christmas vacations).

**Comment by stanislavlevin** [comment]
> @stanislavlevin you can update the translation in Zanata. It is harder to postpone the release, though. We can include the updates in the next release (I'm planning to do one more in December to pick up more fixes before going for Christmas vacations).

No problem, translation work is going.

Just a proposal: if there would be a release plan (any kind of) everybody could synchronize her/his work with such schedule. Of course, you know this better than me.

**Comment by abbra** [comment]
@stanislavlevin Fedora Bodhi is experiencing outage, so I will postpone release till tonight (after 15:00 UTC at least).

**Comment by abbra** [comment]
master:

* d317fd4de7b16dd2f50a360d7f8d2954b975fe1e Update translations

**Pull request closed without merging**
