### PR TITLE
[Backport][ipa-4-12] ipatests: Fixes for ipa-idrange-fix testsuite

### PR DESCRIPTION
**Pull request by rcritten**
This PR was opened automatically because PR #7548 was pushed to master and backport to ipa-4-12 is required.

### CODE REVIEW

**Comment by rcritten** [comment]
PR was ACKed automatically because this is backport of PR #7548. Wait for CI to finish before pushing. In case of questions or problems contact @menonsudhir who is author of the original PR.

**Comment by flo-renaud** [comment]
Hi @menonsudhir 
this backport and the original fix are incomplete. The test is executed with the `topology: *ipaserver` (see https://github.com/freeipa/freeipa/blob/26af2164a464f4df544d6850eb1ba21b14df45a6/ipatests/prci_definitions/nightly_latest.yaml#L1797-L1807) which is using a Vagrantfile that already installs the server (https://github.com/freeipa/freeipa-pr-ci/blob/master/templates/vagrantfiles/Vagrantfile.ipaserver). See example of a failure in the nightly test http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/c63808ee-8511-11ef-820b-fa163e2355e3/report.html?sort=result).

If the test defines topology='line', the installation is called a second time. This means that you need to use a different topology, one that doesn't pre-install the server (for instance `topology: *master_1repl` instead of ipaserver). You need to update all the nightly test definitions with that topology.

**Comment by flo-renaud** [comment]
@menonsudhir I made a fix in https://github.com/freeipa/freeipa/pull/7558, please review

**Comment by flo-renaud** [comment]
PR #7558 has been merged and I added the backport into this PR. ACK again

**Comment by flo-renaud** [comment]
ipa-4-12:

* ae4c2ad6cd966d48c063814f494dcc16cf0ccd4c ipatests: Fixes for ipa-idrange-fix testsuite
* 4b34bfb9819fa9a9b7b8131dddc772c59c14501f Nightly test definition: use master_1repl topology for idrange_fix

**Pull request closed without merging**
