### PR TITLE
fix selenium imports in automount web UI test

### PR DESCRIPTION
**Pull request by abbra**
Fixes: https://pagure.io/freeipa/issue/7942

### CODE REVIEW

**Comment by abbra** [comment]
I added an experimental fix for trust legacy clients test, let's see if this gets the full battery of tests running.

**Comment by abbra** [comment]
@stanislavlevin there is a bug in i18n translations code, it seems: https://github.com/freeipa/freeipa/pull/3146/checks?check_run_id=127791824

**Comment by abbra** [comment]
@stanislavlevin I opened https://pagure.io/freeipa/issue/7951 to track the translations failure issue.

**Comment by stanislavlevin** [comment]
@abbra, sorry for a delay. Most likely, the problem is in the missing `fr-fr` locale on Azure test machine. For Travis i added that here f49fac7bda8150aee2086be9afdbe4eb81c3f18a

**Comment by abbra** [comment]
@stanislavlevin thanks! I added the same to the Dockerfile used to generate the container.

**Comment by abbra** [comment]
master:

* 9cb6817b3064da5a85d415b6b29dbfd9429d6d8d azure-run-tests: handle single unexpanded parameter too
* c41b3ae98f0782d05318dd2c36c88f66aa25909b fix selenium imports in automount web UI test
* 245a8bcdfe32f665a0a1902e54d49e4ba2cd4ce4 test_legacy_clients: fix class inheritance
* 74f3ca5db054d333a0a8d65abee90edba32a202a i18n_messages: get back a locale needed for testing

**Pull request closed without merging**
