### PR TITLE
Fix azure pipelines to use Fedora 31

### PR DESCRIPTION
**Pull request by abbra**

### CODE REVIEW

**Comment by abbra** [comment]
Should work now. Ready for review.

**Comment by stanislavlevin** [comment]
pytest-4.6.6 ...

**Comment by abbra** [comment]
Any suggestion, @stanislavlevin ?

**Comment by stanislavlevin** [comment]
@abbra, there are several options in my opinion:
1) https://github.com/freeipa/freeipa/pull/3783 (need to rebase and recheck)
2) if #3783 is not suitable for some reason, I think it's possible to write some workaround
to address only spotted issues
3) It looks like integration tests passed, this means we could use PyPI packages installed via `pip` on azure as a temporary workaround for F31.

**Comment by abbra** [comment]
@stanislavlevin I'd like option (1). Could you  please rebase it and add commits from this one? I think it is better to have your PR with my two commits than the other way around.

**Comment by stanislavlevin** [comment]
> @stanislavlevin I'd like option (1). Could you please rebase it and add commits from this one? I think it is better to have your PR with my two commits than the other way around.

Sure.
PR relay race  :)

**Comment by stanislavlevin** [comment]
Azure tests passed in https://github.com/freeipa/freeipa/pull/3783

**Comment by abbra** [comment]
This PR can now be closed because an alternative one which included parts of this PR was merged already.

**Pull request closed without merging**
