### PR TITLE
Backup HTTPD's mod_ssl config and cert-key pair

### PR DESCRIPTION
**Pull request by stlaz**
https://pagure.io/freeipa/issue/3757

### CODE REVIEW

**Comment by pvoborni** [comment]
I was wondering whether you could create either a temp PR or temporary modify this PR with backup and restore tests to see if the change fixes some of the backup and restore tests which now currently fails in nightly testing on a check which doesn `ipa user-show admin` - returning an error about certificate verification.

**Comment by rcritten** [comment]
The change looks good to me.

**Comment by stlaz** [comment]
@pvoborni not a fan of temporary commits. If you want additional checks in PR CI on request, either implement a way to do that easily and without additional overhead (would require a UI) or I'm going to leave that up to the reviewer. If they want, they can add any commits in my PRs.

**Comment by flo-renaud** [comment]
master:

* 7960352f1c3a0982ac87d061b9bef8418c2dae48 Backup HTTPD's mod_ssl config and cert-key pair

**Pull request closed without merging**
