### PR TITLE
ipatests: call the CALess install method to generate the CA

### PR DESCRIPTION
**Pull request by rcritten**
ipatests: call the CALess install method to generate the CA

https://pagure.io/freeipa/issue/8581

Signed-off-by: Rob Crittenden <rcritten@redhat.com>

### CODE REVIEW

**Comment by rcritten** [comment]
Ok, so ACME isn't executing at all because the minimum version is not available. It still has pki-ca-10.9.4-x.

@netoarmando is pki baked into the images? If so we need pki-ca-10.10.0+.

**Comment by netoarmando** [comment]
> Ok, so ACME isn't executing at all because the minimum version is not available. It still has pki-ca-10.9.4-x.
> 
> @netoarmando is pki baked into the images? If so we need pki-ca-10.10.0+.

I've built the current images on Thursday and pki-ca-10.10.0+ landed the stable repos on Saturday :/ I'm going to trigger new builds today.

**Comment by mrizwan93** [comment]
We still have `pki-ca-10.9.4-1.fc32.noarch` and not `pki-ca-10.10.0+` in pr-ci
http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/2d384cc8-28f2-11eb-a1ae-fa163eba70f5/installed_packages/installed_packages_master.log.gz

**Comment by rcritten** [comment]
Rebased patch.

**Comment by rcritten** [comment]
Still pki-ca-10.9.4-1.fc32.noarch. AFAICT it is using the new image, 0.0.13.

**Comment by rcritten** [comment]
@netoarmando I'm confused that this isn't picking up the new pki build. Is my temp commit wrong in some way?

**Comment by flo-renaud** [comment]
@rcritten you can update the vagrant image version in temp_commit.yaml by replacing the line "version: 0.0.13" with the most recent version of the vagrant image (0.0.15 as can be seen in https://app.vagrantup.com/freeipa/boxes/ci-master-f32).

**Comment by rcritten** [comment]
I'd swear I looked at th at and saw the version still as 13.

In any case I dropped the temp commit. If acme passes then it's good-to-go.

**Comment by flo-renaud** [comment]
@rcritten all the tests in test_acme were skipped (see [report](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/0d6fbf50-2a75-11eb-b90b-fa163e48abf8/report.html)) and the install wasn't even called :(

**Comment by rcritten** [comment]
tasks.common.PopenException: Process "vagrant box add freeipa/ci-master-f32 --box-version 0.0.15 --provider libvirt" exited with error code 1
2020-11-20 13:26:57,942    ERROR  Box download failed

**Comment by rcritten** [comment]
New issue discovered: TestACMEwithExternalCA needs a replica server configured

**Comment by rcritten** [comment]
I can only assume that the previous CI runs executed against pki-ca < 10.10.0 so the ACME tests didn't actually execute so were all green and it wasn't noticed. I managed to fix a couple of the issues. @mrizwan93 can you take a look at the rest?

**test_integration/test_acme.py::TestACMEwithExternalCA::test_mod_md**

curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**test_integration/test_acme.py::TestACMEwithExternalCA::test_third_party_certs**

create_pkcs12 is failing with
       FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ipatest-66k7tlug/ca1/server.pem'

**Comment by rcritten** [comment]
I believe test_integration/test_acme.py::TestACMEwithExternalCA::test_third_party_certs is failing because it isn't calling the CALessBase constructor which would generate the necessary files. Working on a patch.

**Comment by mrizwan93** [comment]
LGTM.
pr-ci are green. results are here: 
[temp commit](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/3aa734da-2de5-11eb-ab96-fa163e7187f1/)

@flo-renaud Can you have a look too?

**Comment by flo-renaud** [comment]
> @flo-renaud Can you have a look too?
The changes LGTM, too, you can remove the temp commit.
I noticed that `ipatests/prci_definitions/gating.yaml` defines a timeout (3600) different from the other nightlies for fedora-latest/test_acme. Could you leverage this PR to update the timeout to 7200? Thx

**Comment by rcritten** [comment]
Updated timeout to 7200, tests green.

**Comment by mrizwan93** [comment]
Template version in gating.yaml is `version: 0.0.13` and required pki-ca version for ACME is available in `version: 0.0.15`. Hence all test in test_acme.py got skipped.

**Comment by rcritten** [comment]
Now it's all green and the ACME tests have executed.

**Comment by rcritten** [comment]
master:

* 790b765598bf6ee5813163785e2e4fae12f03081 ipatests: call the CALess install method to generate the CA
* 89fddb07503c2df1bd547b4f0c2f2b119cbd23b8 ipatests: Configure a replica in TestACMEwithExternalCA
* 70306515f78de52baa8c965fb9141bb3bc1bb304 ipatests: Clean up existing ACME registration and certs
* 3a9fc0115698fa013ff6d36301ceca0ff0655a9e ipatests: configure MDStoreDir for mod_md ACME test
* e6489dcb8cb34e0eb8955e601b329a4521a82f3e ipatests: honor class inheritance in TestACMEwithExternalCA
* 75e3803b688362fdce82d7633edd305bc2b354d8 ipatests: Increase timeout for ACME in gating.yaml
* b6004cf88f97e00740e60c2d1facb4c3f467f21d ipatests: Bump PR-CI templates

**Pull request closed without merging**
