### PR TITLE
Remove special characters from random password generation in host_add OTPs.

### PR DESCRIPTION
**Pull request by johnclarson**
https://pagure.io/freeipa/issue/7380

From d398d4282280fc3b730aa0d626e0a617db8dc90b Mon Sep 17 00:00:00 2001
From: John L <segfault@XXXXXXXX>
Date: Mon, 29 Jan 2018 12:25:31 -0500
Subject: [PATCH] This fixes a regression in how random host-add OTP password
 are generated. Some shells try and interpret certain special characters when
 they confront them in unattended ipa-client-install where the OTP is used.
 Before 4.5.0, this was fixed by excluding an arbitrary list of special
 characters during OTP random password generation. This fix goes a step
 further and removes ALL special characters when the OTP is generated. In my
 opinion, the period of time between random OTP generation and use is small
 and the password is useless after the host is installed so removing special
 characters presents minimal security risk

---
 ipaserver/plugins/host.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/ipaserver/plugins/host.py b/ipaserver/plugins/host.py
index 6487cd612de96d11ed49b97425a31f22e481c98d..291a90a2abdaf6e95e96fb41889ce838d5f9b5f6 100644
--- a/ipaserver/plugins/host.py
+++ b/ipaserver/plugins/host.py
@@ -686,7 +686,7 @@ class host_add(LDAPCreate):
                 entry_attrs['objectclass'].remove('krbprincipal')
         if options.get('random'):
             entry_attrs['userpassword'] = ipa_generate_password(
-                entropy_bits=TMP_PWD_ENTROPY_BITS)
+                entropy_bits=TMP_PWD_ENTROPY_BITS, special=None)
             # save the password so it can be displayed in post_callback
             setattr(context, 'randompassword', entry_attrs['userpassword'])
 
-- 
1.8.3.1

### CODE REVIEW

**Comment by felipevolpone** [comment]
Hi @johnclarson , it seems that you're creating a PR from ipa-4-6 against master. Which is not a good idea. 
Also, could you change the title of the PR and your commit message to reflects what it the change and what it wants to address?

Here, https://www.freeipa.org/page/Contribute/Code, you can find how to create PRs and contribute to the project.

**Comment by johnclarson** [comment]
Apologies on the PR from ipa-4-6 against master. First attempt at this. I have updated the title and the commit message. What should my PR be from and against?

**Comment by johnclarson** [comment]
Opened new PR from master against ipa-4-6. Not sure how to delete this one.

**Comment by Tiboris** [comment]
@johnclarson could you please try to change pull request to be against master and not ipa-4-6 branch? 

This is how PRs should be created:

- [ ] change your base branch to master with : `git checkout master` 
- (all patches to the upstream should be developed on master branch then if required they will be backported to other branches)
- [ ] create branch from master: `git checkout -b name_of_your_fix_branch`
- [ ] apply patches which you would like to contribute on created branch and commit them
- [ ] create Pull Request from your branch against master

Thanks!

**Comment by Tiboris** [comment]
> Here, https://www.freeipa.org/page/Contribute/Code, you can find how to create PRs and contribute to the project.

@felipevolpone I believe this is kind of outdated :)

**Comment by rcritten** [comment]
@Tiboris so update it with your findings?

**Comment by Tiboris** [comment]
Sure @rcritten I will update it.

**Comment by johnclarson** [comment]
Sorry to be a noob and thanks for your patience. Is this right?:

https://github.com/freeipa/freeipa/pull/1505

**Comment by Tiboris** [comment]
@johnclarson  please close pull request if it is covered by: https://github.com/freeipa/freeipa/pull/1505

**Pull request closed without merging**
