### PR TITLE
[Backport][ipa-4-8] test_nfs.py: switch to tasks.config_replica_resolvconf_with_master_data()

### PR DESCRIPTION
**Pull request by fcami**
This PR was opened automatically because PR #3463 was pushed to master and backport to ipa-4-8 is required.

### CODE REVIEW

**Comment by fcami** [comment]
PR was ACKed automatically because this is backport of PR #3463. Wait for CI to finish before pushing. In case of questions or problems contact @fcami who is author of the original PR.

**Comment by abbra** [comment]
Error in linting:
```
yaml.composer.ComposerError: found undefined alias 'master_3client'
  in "ipatests/prci_definitions/nightly_rawhide.yaml", line 1254, column 19
```

**Comment by fcami** [comment]
Yes, that's because https://github.com/freeipa/freeipa/pull/3476 was not merged.

**Comment by fcami** [comment]
ipa-4-8:

* 68f98e29d3b289d253141a2144c8664070700fcd test_nfs.py: switch to tasks.config_replica_resolvconf_with_master_data()
* 0fdfce5249f7ce71dded78103989b91e76d62512 ipatests: rename config_replica_resolvconf_with_master_data()
* 1ad3bf4832279642141192013234d3b3ebed4110 test_nfs.py: switch to master_3repl

**Pull request closed without merging**
