### PR TITLE
Fix missing translation string

### PR DESCRIPTION
**Pull request by shanyin**
Fix missing translation string.

### CODE REVIEW

**Comment by mbasti-rh** [comment]
Hello, could you please remove `fix miss translation in Chinese` and `Delete zh_CN.po` from this PR?

**Comment by shanyin** [comment]
Hello,
I am sorry that I sent redundant files. I have tried to remove it, but seem to be failed. It may not be the right way, I try again.

**Comment by shanyin** [comment]
Hello,
I am sorry that I don't know if I removed it successfully. If not, Should I send a PR again?

**Comment by martbab** [comment]
Shanyin,

you can try to rebase your local branch interactively against master and just throw out the redundant commits. See https://git-scm.com/docs/git-rebase for more details.

Then force push into your remote branch to update PR.

**Comment by mbasti-rh** [comment]
```
git rebase -i master fix-missing-translation-string
```

it will open interactive mode and you can remove all lines (commits) that you want to remove.
Then save that document

**Comment by shanyin** [comment]
Ok, I have done changes, commit and push operations on local branch.

Thanks!  @martbab @mbasti-rh

**Comment by mbasti-rh** [comment]
@shanyin could you force push to github remote branch to have updated PR?

**Comment by shanyin** [comment]
Oh my god, git rebase or push command has a problem. I force push my local branch to remote branch. Is this time whether meet the requirement?

**Comment by mbasti-rh** [comment]
I pushed just commit `fix missing translation string`

* 0499ba5795cf483756ac980604fd2c26fda7ba39 fix missing translation string

Thank you!

**Pull request closed without merging**
