### PR TITLE
bump PRCI template version to 0.1.8

### PR DESCRIPTION
**Pull request by Rezney**
bump PRCI template version to 0.1.8

### CODE REVIEW

**Comment by flo-renaud** [comment]
Hi @Rezney 
thanks for the update, looks good to me. You may also want to update ipatests/prci_definitions/temp_commit.yaml.

**Comment by Rezney** [comment]
Thanks for checking this @flo-renaud - fixed...

**Comment by flo-renaud** [comment]
Tests are now green, ACK

**Comment by flo-renaud** [comment]
master:

* 59df37ad9b55d3bd7774ab540c087f186a7986aa bump PRCI template version to 0.1.8

**Pull request closed without merging**
