### PR TITLE
[Backport][ipa-4-8] DNS install check: Fix overlapping DNS zone from the master itself

### PR DESCRIPTION
**Pull request by t-woerner**
This PR was opened automatically because PR #4044 was pushed to master and backport to ipa-4-8 is required.

### CODE REVIEW

**Comment by t-woerner** [comment]
PR was ACKed automatically because this is backport of PR #4044. Wait for CI to finish before pushing. In case of questions or problems contact @t-woerner who is author of the original PR.

**Comment by f-trivino** [comment]
@t-woerner test_commands is unstable and gets stuck very often. We plan to remove from gating until it is stable again. We can merge this PR.

**Comment by t-woerner** [comment]
The test_commands test has stability issues. It has been restarted several times, but runs into the same problem again.

**Comment by t-woerner** [comment]
ipa-4-8:

* 2c2cef7063315766d893b275185b422be3f3c019 DNS install check: Fix overlapping DNS zone from the master itself

**Comment by AdamWill** [comment]
For the record, I backported this fix to the F31 update, and the tests pass now.

**Pull request closed without merging**
