### PR TITLE
ipa-4-5: python2-pyasn1 workaround

### PR DESCRIPTION
**Pull request by Rezney**
initialize ASN.1 object by hand to make it compatible with ancient pyasn1

### CODE REVIEW

**Comment by Rezney** [comment]
This PR was opened mainly because of testing on RHEL7.5 where we are missing "native" decoder in "python2-pyasn1-0.1.9-7.el7.noarch" package.

**Comment by rcritten** [comment]
Please add that comment to the commit message and replace the "ancient" comment in the code with this.

**Comment by Rezney** [comment]
Done. Thanks for checking this.

**Comment by Rezney** [comment]
ipa-4-5:

* 416bae8b67eb9726b8a441af7ea949a7463b87bb ipa-4-5: python2-pyasn1 workaround

**Pull request closed without merging**
