### PR TITLE
[ipa-4-8] ipatests: Replace PR-CI box with ci-ipa-4-8-f34

### PR DESCRIPTION
**Pull request by netoarmando**
Removing ci-master-f34 to use fresh box built for ipa-4-8 branch.

This branch is no longer being tested nightly, thus nightly definitions for 'selinux' and 'previous' runs were removed, but 'latest' was kept as reference for all available jobs.

### CODE REVIEW

**Comment by stanislavlevin** [comment]
so fast, thank you!
could we completely drop F32?
`ipatests/prci_definitions/nightly_ipa-4-8_previous.yaml:          name: freeipa/ci-ipa-4-8-f32`

**Comment by netoarmando** [comment]
Sure, given that we don't execute nightly tests for this branch anymore I'm removing unnecessary files and leaving only `nightly_ipa-4-8_latest.yaml` as reference for all available jobs.

**Comment by stanislavlevin** [comment]
LGTM! Thank you.

**Comment by flo-renaud** [comment]
ipa-4-8:

* 4b0ef48a9813e64c86ee4c2ceb7646ffb2a08d28 ipatests: Replace PR-CI box with ci-ipa-4-8-f34

**Pull request closed without merging**
