### PR TITLE
389-DS BDB: switch deadlock behavior to DB_LOCK_MINWRITE

### PR DESCRIPTION
**Pull request by fcami**
Some IPA updates are expensive in term of processing and #page hit.
The likelihood to generate a DS Berkeley DB database deadlock can be high
for some common operations.

When a deadlock is detected one deadlocking thread needs to be
rejected to let the other(s) complete.
DB_LOCK_YOUNGEST (9) is the DS default: it  means the most recent operation
fails in favor to the oldest one.
DB_LOCK_MINWRITE (6) means the reader(s) are rejected in favor
of the writers even if the reader(s) are older.

Switch the default for FreeIPA to DB_LOCK_MINWRITE for new installs and
also existing installs at update time.
This depends on the backend redesign (https://pagure.io/389-ds-base/issue/49476)
and therefore is valid on 389-DS 1.4.2.3 and higher.

Explanation provided by Thierry Bordaz.

Fixes: https://pagure.io/freeipa/issue/8479
Signed-off-by: François Cami <fcami@redhat.com>

### CODE REVIEW

**Comment by netoarmando** [comment]
@fcami oddly `selinux-policy >= 3.14.5-43.fc32` can't be installed, I've opened https://github.com/freeipa/freeipa/pull/5072 to see if a newer box fixes that issue.

**Comment by fcami** [comment]
Expected test failure: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/9f958d8a-ec61-11ea-a869-fa163e045818/
```
AssertionError: assert 'nsslapd-db-deadlock-policy: 6' in 'dn: cn=bdb,cn=config,cn=ldbm database,cn=plugins,cn=config\nnsslapd-db-deadlock-policy: 9\n\n'
```

**Comment by fcami** [comment]
Test is green: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/f0f8e790-ec65-11ea-ae5c-fa163e670c62/
```
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd52:transport.py:557 dn: cn=bdb,cn=config,cn=ldbm database,cn=plugins,cn=config
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd52:transport.py:557 nsslapd-db-deadlock-policy: 6
```
```
DEBUG    ipatests.pytest_ipa.integration.host.Host.replica0.cmd64:transport.py:557 dn: cn=bdb,cn=config,cn=ldbm database,cn=plugins,cn=config
DEBUG    ipatests.pytest_ipa.integration.host.Host.replica0.cmd64:transport.py:557 nsslapd-db-deadlock-policy: 6
```

**Comment by fcami** [comment]
The only change is the year in the test file header.

**Comment by abbra** [comment]
LGTM. Please remove the temp commit and add the tests to nightlies.

**Comment by fcami** [comment]
Thanks @abbra I think the nightly templates are already modified by the test commit.

**Comment by stanislavlevin** [comment]
As I see from the original 389-ds ticket and corresponding 389-ds PR this is mostly refactoring. Therefore, the functionality will be the same, if so then why the version is pinned to `> 1.4.2.3`? The older database supports the same but the configuration path differs `cn=config,cn=ldbm database,cn=plugins,cn=config`.

**Comment by fcami** [comment]
@stanislavlevin There is no plan to backport this to older RHEL or Fedora releases that don't have 389-ds > 1.4.2.3.
Would you be interested in having this fix for older versions?

**Comment by stanislavlevin** [comment]
I have FreeIPA 4.8.x + 389-ds 1.4.1.x for the stable repo.
It would be nice to have such fix.

**Comment by fcami** [comment]
@stanislavlevin I am not sure how to handle that. At this point we're not sure to backport it to ipa-4-8 either. Can you carry a downstream patch?

**Comment by stanislavlevin** [comment]
@fcami, no problem :smile:
I will either rebase 389-ds to 1.4.2 or write a patch.

**Comment by fcami** [comment]
Thank you @stanislavlevin

**Comment by rcritten** [comment]
So if this is rebased it can be merged?

**Comment by fcami** [comment]
It has not been tested at scale yet.

**Comment by abbra** [comment]
Moving to WIP state.

**Pull request closed without merging**
