### PR TITLE
ipa-migrate should migrate dns forward zones

### PR DESCRIPTION
**Pull request by mreynolds389**
Fixes: https://pagure.io/freeipa/issue/9686

### CODE REVIEW

**Comment by rcritten** [comment]
In my quickie test this didn't migrate the forward zone. There is no mention of forward in the ipa-migrate.log either.

**Comment by mreynolds389** [comment]
> In my quickie test this didn't migrate the forward zone. There is no mention of forward in the ipa-migrate.log either.

Did you use the "--migrate-dns" option?

**Comment by rcritten** [comment]
No I did not. With the option the forward is migrated.

**Comment by flo-renaud** [comment]
Thanks for the PR, works for me.

**Comment by mreynolds389** [comment]
> No I did not. With the option the forward is migrated.

We used to migrate it by default, we even had a "--skip-dns" option, but at some point we made it where you had to explicitly ask to migrate it

**Comment by rcritten** [comment]
master:

* 0abfb20c34ade85d5c10a358a73ba33626b2f1ef ipa-migrate should migrate dns forward zones

**Pull request closed without merging**
