### PR TITLE
Simplify and make more reliable the server and client installation checks

### PR DESCRIPTION
**Pull request by rcritten**
Rather than relying on file existence and whether the installer backed up files actually set a value when the installation is complete for the client and server and use that.

For the server this can be reliable moving forward because we can detect the missing state and fix it on upgrades. On the client we're stuck so use it but leave the old method as a fallback. Also remove the requirement to pass in the filestore to the client check as that makes it more complex as a fact.

Both can be checked fairly easily with:
```
python -c 'from ipalib.install.facts import is_ipa_client_configured; print ("%s" % is_ipa_client_configured())'
python -c 'from ipalib.install.facts import is_ipa_configured; print("%s" % is_ipa_configured())'
```
Edit: updated to show new facts import

### CODE REVIEW

**Comment by abbra** [comment]
Please remove `ipa.pot` update from the PR.

We also have `check_client_configuration()` that does similar and used in many places. May be its use can be streamlined and unified too?

**Comment by rcritten** [comment]
> Please remove `ipa.pot` update from the PR.

Done. I hate it when I include that.
 
> We also have `check_client_configuration()` that does similar and used in many places. May be its use can be streamlined and unified too?

I changed it to call out to is_ipa_client_configured() instead of rolling its own. It is a useful function for AdminTool scripts so raising an exception means less duplicated code doing if not is_ipa_client_configure(): raise <same exception>

It also explicitly supports the IPA_CONFDIR environment variable that Christian added.

**Comment by abbra** [comment]
Well, now four other tools that call `check_client_configuration` will issue warnings. May be better to make sure warning is not there or change the callers to use the new one?

**Comment by rcritten** [comment]
This isn't changing behavior of `check_client_configuration.` The only difference between that function and `is_ipa_client_configured` is it honors the `IPACONF` environment variable and raises an exception if the client is not configured rather than returning a boolean. This makes the code to check whether a client is installed a one-liner and centralizes the error message.

I'm ok with two similar functions because their usage is different enough. There are places where just getting the boolean on installed or not is simpler code and others where having the side-effect of raising an exception is preferable.

**Comment by abbra** [comment]
I messed up my review because I saw `warnings.message` in one place and mentally applied it to another. Sorry for that. The rest is OK.

**Comment by abbra** [comment]
Linter failed:
```
2020-07-10T07:19:46.1400462Z Please wait ...
2020-07-10T07:19:46.1400666Z 
2020-07-10T07:24:07.8385559Z internal error with sending report for module ['ipaserver/plugins/serverroles.py']
2020-07-10T07:24:07.8387184Z maximum recursion depth exceeded while calling a Python object
2020-07-10T07:24:07.8832969Z ************* Module ipalib.util
2020-07-10T07:24:07.8834457Z ipalib/util.py:63: [W9901(ipa-forbidden-import), ] Forbidden import ipalib.install.facts.is_ipa_client_configured (can't import from ipalib.install in ipalib))

```

**Comment by abbra** [comment]
And also during tox checks:
```
2020-07-10T07:22:13.3575505Z >   from ipalib.install.facts import is_ipa_client_configured
2020-07-10T07:22:13.3576342Z E   ModuleNotFoundError: No module named 'ipalib.install'
2020-07-10T07:22:13.3576661Z 
2020-07-10T07:22:13.3577173Z lib/python3.8/site-packages/ipalib/util.py:63: ModuleNotFoundError
2020-07-10T07:22:13.3623984Z =========================== short test summary info ============================
2020-07-10T07:22:13.3625171Z FAILED ../../pypi/test_placeholder.py::test_import[ipalib] - ModuleNotFoundEr...
2020-07-10T07:22:13.3625672Z ========================= 1 failed, 15 passed in 0.31s =========================
2020-07-10T07:22:13.3849863Z ERROR: InvocationError for command /__w/1/s/.tox/pypi/bin/python -m pytest /__w/1/s/pypi/test_placeholder.py (exited with code 1)
2020-07-10T07:22:13.3854461Z pylint3 create: /__w/1/s/.tox/pylint3
2020-07-10T07:22:16.0860032Z pylint3 installdeps: ipaclient[csrgen,otptoken_yubikey,ldap], pylint
2020-07-10T07:22:28.9504053Z pylint3 installed: astroid==2.4.2,cffi==1.14.0,cryptography==2.9.2,decorator==4.4.2,dnspython==1.16.0,gssapi==1.6.9,ipaclient==4.9.0.dev202007100720+git1354d9774,ipalib==4.9.0.dev202007100720+git1354d9774,ipaplatform==4.9.0.dev202007100720+git1354d9774,ipapython==4.9.0.dev202007100720+git1354d9774,isort==4.3.21,Jinja2==2.11.2,lazy-object-proxy==1.4.3,MarkupSafe==1.1.1,mccabe==0.6.1,netaddr==0.8.0,pyasn1==0.4.8,pyasn1-modules==0.2.8,pycparser==2.20,pylint==2.5.3,python-ldap==3.3.1,python-yubico==1.3.3,pyusb==1.0.2,qrcode==6.1,six==1.15.0,toml==0.10.1,wrapt==1.12.1
2020-07-10T07:22:28.9510324Z pylint3 run-test-pre: PYTHONHASHSEED='1766362633'
2020-07-10T07:22:28.9512545Z pylint3 run-test: commands[0] | /__w/1/s/.tox/pylint3/bin/python -m pylint --rcfile=/__w/1/s/pylintrc --load-plugins pylint_plugins /__w/1/s/.tox/pylint3/lib/python3.8/site-packages/ipaclient /__w/1/s/.tox/pylint3/lib/python3.8/site-packages/ipalib /__w/1/s/.tox/pylint3/lib/python3.8/site-packages/ipapython
2020-07-10T07:23:28.6929533Z [7;33m************* Module ipalib.util[0m
2020-07-10T07:23:28.6931414Z lib/python3.8/site-packages/ipalib/util.py:63: [E0611([1;31mno-name-in-module[0m), ] [1;31mNo name 'install' in module 'ipalib'[0m)
2020-07-10T07:23:28.6932760Z lib/python3.8/site-packages/ipalib/util.py:63: [W9901([35mipa-forbidden-import[0m), ] [35mForbidden import ipalib.install.facts.is_ipa_client_configured (can't import from ipalib.install in ipalib)[0m)
2020-07-10T07:23:28.6933928Z lib/python3.8/site-packages/ipalib/util.py:63: [E0401([1;31mimport-error[0m), ] [1;31mUnable to import 'ipalib.install.facts'[0m)
2020-07-10T07:23:28.6934952Z lib/python3.8/site-packages/ipalib/util.py:63: [E0611([1;31mno-name-in-module[0m), ] [1;31mNo name 'install' in module 'ipalib'[0m)
2020-07-10T07:23:28.6936300Z lib/python3.8/site-packages/ipalib/util.py:63: [W9901([35mipa-forbidden-import[0m), ] [35mForbidden import ipalib.install.facts.is_ipa_client_configured (can't import from ipalib.install in ipalib)[0m)
2020-07-10T07:23:28.6937519Z lib/python3.8/site-packages/ipalib/util.py:63: [E0401([1;31mimport-error[0m), ] [1;31mUnable to import 'ipalib.install.facts'[0m)
2020-07-10T07:23:28.6938547Z lib/python3.8/site-packages/ipalib/util.py:63: [E0611([1;31mno-name-in-module[0m), ] [1;31mNo name 'install' in module 'ipalib'[0m)
2020-07-10T07:23:28.6939737Z lib/python3.8/site-packages/ipalib/util.py:63: [W9901([35mipa-forbidden-import[0m), ] [35mForbidden import ipalib.install.facts.is_ipa_client_configured (can't import from ipalib.install in ipalib)[0m)
2020-07-10T07:23:28.6940859Z lib/python3.8/site-packages/ipalib/util.py:63: [E0401([1;31mimport-error[0m), ] [1;31mUnable to import 'ipalib.install.facts'[0m)
2020-07-10T07:23:28.6941910Z lib/python3.8/site-packages/ipalib/util.py:63: [E0611([1;31mno-name-in-module[0m), ] [1;31mNo name 'install' in module 'ipalib'[0m)
2020-07-10T07:23:28.6943094Z lib/python3.8/site-packages/ipalib/util.py:63: [W9901([35mipa-forbidden-import[0m), ] [35mForbidden import ipalib.install.facts.is_ipa_client_configured (can't import from ipalib.install in ipalib)[0m)
2020-07-10T07:23:28.6944243Z lib/python3.8/site-packages/ipalib/util.py:63: [E0401([1;31mimport-error[0m), ] [1;31mUnable to import 'ipalib.install.facts'[0m)
2020-07-10T07:23:28.6945757Z lib/python3.8/site-packages/ipalib/util.py:63: [E0611([1;31mno-name-in-module[0m), ] [1;31mNo name 'install' in module 'ipalib'[0m)
2020-07-10T07:23:28.6947198Z lib/python3.8/site-packages/ipalib/util.py:63: [W9901([35mipa-forbidden-import[0m), ] [35mForbidden import ipalib.install.facts.is_ipa_client_configured (can't import from ipalib.install in ipalib)[0m)
2020-07-10T07:23:28.6948151Z lib/python3.8/site-packages/ipalib/util.py:63: [E0401([1;31mimport-error[0m), ] [1;31mUnable to import 'ipalib.install.facts'[0m)
2020-07-10T07:23:28.6948985Z lib/python3.8/site-packages/ipalib/util.py:63: [E0611([1;31mno-name-in-module[0m), ] [1;31mNo name 'install' in module 'ipalib'[0m)
2020-07-10T07:23:28.6950244Z lib/python3.8/site-packages/ipalib/util.py:63: [W9901([35mipa-forbidden-import[0m), ] [35mForbidden import ipalib.install.facts.is_ipa_client_configured (can't import from ipalib.install in ipalib)[0m)
2020-07-10T07:23:28.6951183Z lib/python3.8/site-packages/ipalib/util.py:63: [E0401([1;31mimport-error[0m), ] [1;31mUnable to import 'ipalib.install.facts'[0m)
2020-07-10T07:23:28.6952012Z lib/python3.8/site-packages/ipalib/util.py:63: [E0611([1;31mno-name-in-module[0m), ] [1;31mNo name 'install' in module 'ipalib'[0m)
2020-07-10T07:23:28.6953038Z lib/python3.8/site-packages/ipalib/util.py:63: [W9901([35mipa-forbidden-import[0m), ] [35mForbidden import ipalib.install.facts.is_ipa_client_configured (can't import from ipalib.install in ipalib)[0m)
2020-07-10T07:23:28.6954075Z lib/python3.8/site-packages/ipalib/util.py:63: [E0401([1;31mimport-error[0m), ] [1;31mUnable to import 'ipalib.install.facts'[0m)
2020-07-10T07:23:28.6954915Z lib/python3.8/site-packages/ipalib/util.py:63: [E0611([1;31mno-name-in-module[0m), ] [1;31mNo name 'install' in module 'ipalib'[0m)
2020-07-10T07:23:28.6955899Z lib/python3.8/site-packages/ipalib/util.py:63: [W9901([35mipa-forbidden-import[0m), ] [35mForbidden import ipalib.install.facts.is_ipa_client_configured (can't import from ipalib.install in ipalib)[0m)
2020-07-10T07:23:28.6956835Z lib/python3.8/site-packages/ipalib/util.py:63: [E0401([1;31mimport-error[0m), ] [1;31mUnable to import 'ipalib.install.facts'[0m)
2020-07-10T07:23:28.6957661Z lib/python3.8/site-packages/ipalib/util.py:63: [E0611([1;31mno-name-in-module[0m), ] [1;31mNo name 'install' in module 'ipalib'[0m)
2020-07-10T07:23:28.6958652Z lib/python3.8/site-packages/ipalib/util.py:63: [W9901([35mipa-forbidden-import[0m), ] [35mForbidden import ipalib.install.facts.is_ipa_client_configured (can't import from ipalib.install in ipalib)[0m)
2020-07-10T07:23:28.6959580Z lib/python3.8/site-packages/ipalib/util.py:63: [E0401([1;31mimport-error[0m), ] [1;31mUnable to import 'ipalib.install.facts'[0m)
2020-07-10T07:23:28.6960427Z lib/python3.8/site-packages/ipalib/util.py:63: [E0611([1;31mno-name-in-module[0m), ] [1;31mNo name 'install' in module 'ipalib'[0m)
2020-07-10T07:23:28.6961403Z lib/python3.8/site-packages/ipalib/util.py:63: [W9901([35mipa-forbidden-import[0m), ] [35mForbidden import ipalib.install.facts.is_ipa_client_configured (can't import from ipalib.install in ipalib)[0m)
2020-07-10T07:23:28.6962336Z lib/python3.8/site-packages/ipalib/util.py:63: [E0401([1;31mimport-error[0m), ] [1;31mUnable to import 'ipalib.install.facts'[0m)
2020-07-10T07:23:28.6963180Z lib/python3.8/site-packages/ipalib/util.py:63: [E0611([1;31mno-name-in-module[0m), ] [1;31mNo name 'install' in module 'ipalib'[0m)
2020-07-10T07:23:28.6964164Z lib/python3.8/site-packages/ipalib/util.py:63: [W9901([35mipa-forbidden-import[0m), ] [35mForbidden import ipalib.install.facts.is_ipa_client_configured (can't import from ipalib.install in ipalib)[0m)
2020-07-10T07:23:28.6965108Z lib/python3.8/site-packages/ipalib/util.py:63: [E0401([1;31mimport-error[0m), ] [1;31mUnable to import 'ipalib.install.facts'[0m)

```

**Comment by rcritten** [comment]
pylint in Azure is complaining about:

lib/python3.8/site-packages/ipalib/util.py:64: [E0611(no-name-in-module), ] No name 'install' in module 'ipalib')
lib/python3.8/site-packages/ipalib/util.py:64: [E0401(import-error), ] Unable to import 'ipalib.install.facts')

and I have no idea how to address it.

**Comment by rcritten** [comment]
Move ipalib.install.sysrestore and ipalib.install.facts into ipalib so it will be in the PyPI builds.

**Comment by flo-renaud** [comment]
master:

* 0fa8686918f6b79d09ac8fa959fe988f6db633b2 Simplify determining if an IPA server installation is complete
* 4758db121ea0c555dab89bc1781c8752f188e414 Simplify determining if IPA client configuration is complete
* d7a4756dac5140d4416312ed92270eb3249c83e3 Create a common place to retrieve facts about an IPA installation
* 5e027134815512862ad6ae77867e74a83aee2b59 Don't use the has_files() to know if client/server is configured
* 2c3a042c06b919ff754bfce2ce6e40b9f1827e97 Update check_client_configuration to use new client fact

**Comment by flo-renaud** [comment]
@rcritten this PR will need a manual backport to ipa-4-8, can you handle it? thx

**Comment by rcritten** [comment]
The merge issue is that 53d472b490ac7a14fc78516b448d4aa312b79b7f exists only in master. Working around it now.

**Pull request closed without merging**
