### PR TITLE
[Backport][ipa-4-9] Better support for unreadable NSS database

### PR DESCRIPTION
**Pull request by flo-renaud**
This PR was opened automatically because PR #5489 was pushed to master and backport to ipa-4-9 is required.

### CODE REVIEW

**Comment by flo-renaud** [comment]
PR was ACKed automatically because this is backport of PR #5489. Wait for CI to finish before pushing. In case of questions or problems contact @rcritten who is author of the original PR.

**Comment by rcritten** [comment]
Hang off on merging this. @stanislavlevin discovered that this will fail in Fedora 33. Working on a patch.

**Comment by rcritten** [comment]
related PR https://github.com/freeipa/freeipa/pull/5491

**Comment by flo-renaud** [comment]
The commit from #5491 was cherry-picked, we can push this one now.

**Comment by flo-renaud** [comment]
ipa-4-9:

* b71c0c678430c38cbd22663cbf48229a23f19c8e Report the NSS database directory if it cannot be opened
* 348d4eef6f974c75cb546fc690bb3a20a789de28 Ignore database errors when trying to extract ipaCert on upgrade
* 7f1849e74a7c81213ec658058aec97033c84e038 ipatests: Update NSSDatabase DBM test on non-DBM-capable installs

**Pull request closed without merging**
