### PR TITLE
[Backport][ipa-4-6] Test for ipa-replica-install fails with PIN error for CA-less env.

### PR DESCRIPTION
**Pull request by mrizwan93**
Signed-off-by: Anuja More <amore@redhat.com>
Reviewed-By: Florence Blanc-Renaud <frenaud@redhat.com>
Reviewed-By: Aleksei Slaikovskii <aslaikov@redhat.com>
Reviewed-By: Stanislav Laznicka <slaznick@redhat.com>

### CODE REVIEW

**Comment by mrizwan93** [comment]
Manual backport for https://github.com/freeipa/freeipa/pull/1991

**Comment by Tiboris** [comment]
Hello @mrizwan93.
Why is this being backported please?

**Comment by mrizwan93** [comment]
Hi @Tiboris 
I was verifying it for RHEL7.6 and came to know that this testcase is not present in ipa-4-6. That's why this backport is needed.

**Comment by Tiboris** [comment]
Aha but i see fix from @flo-renaud in 4.7.0 only is it is not relevant for 4.6?

**Comment by Tiboris** [comment]
Ok is it here: https://github.com/freeipa/freeipa/pull/2298

**Comment by Tiboris** [comment]
ipa-4-6:

* 1a80ecc36f716bab88b4788ea8fb1a0aa3f5a9ce Test for ipa-replica-install fails with PIN error for CA-less env.

**Pull request closed without merging**
