### PR TITLE
Add .eggs to Gitignore

### PR DESCRIPTION
**Pull request by pspacek**
These are result of new Python builds.

### CODE REVIEW

**Comment by pspacek** [comment]
@tiran Please provide me a ticket number which is linked to the commits which caused creation of .eggs. Thanks.

**Comment by tiran** [comment]
I can't reproduce the issue locally. What's inside your .eggs directory? It's used by setuptools.dist to cache install, build and test dependencies. It should not be generated in the first place.

**Comment by pspacek** [comment]
I'm using this script to build IPA:
~~~
rm -rvf ~/rpmbuild/{BUILD,BUILDROOT,SPECS,SOURCES,RPMS,SRPMS}
mkdir -pv ~/rpmbuild/{BUILD,BUILDROOT,SPECS,SOURCES,RPMS,SRPMS}
autoreconf -i
./configure
make dist
cp freeipa-*.tar.gz ~/rpmbuild/SOURCES/
cp freeipa.spec ~/rpmbuild/SPECS/
rpmbuild --noclean -ba ~/rpmbuild/SPECS/freeipa.spec
~~~

The ipapython/.eggs directory contains this:
~~~
ipapython/.eggs
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/pep425tags.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/install.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/test_keys.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/simple.dist
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/simple.dist/setup.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/simple.dist/simpledist
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/simple.dist/simpledist/__init__.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/simple.dist/simpledist/__init__.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/simple.dist/setup.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/test_paths.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/test_signatures.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/test_wheelfile.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/test_keys.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/test-1.0-py2.py3-none-win32.whl
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/test_wheelfile.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/headers.dist
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/headers.dist/header.h
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/headers.dist/setup.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/headers.dist/headersdist.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/headers.dist/headersdist.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/headers.dist/setup.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/test_basic.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/test_install.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/__init__.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/test_tool.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/test_paths.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/test_ranking.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/conftest.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/test_ranking.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/test_signatures.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/test_tagopt.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/test_basic.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/conftest.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/test_install.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/pydist-schema.json
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/complex-dist
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/complex-dist/setup.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/complex-dist/setup.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/complex-dist/complexdist
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/complex-dist/complexdist/__init__.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/complex-dist/complexdist/__init__.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/extension.dist
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/extension.dist/setup.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/extension.dist/setup.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/test_tool.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/__init__.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/test/test_tagopt.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/install.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/decorator.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/pkginfo.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/pep425tags.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/eggnames.txt
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/paths.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/bdist_wheel.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/decorator.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/egg2wheel.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/__main__.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/signatures
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/signatures/keys.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/signatures/ed25519py.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/signatures/djbec.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/signatures/__init__.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/signatures/keys.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/signatures/djbec.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/signatures/ed25519py.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/signatures/__init__.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/archive.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/__init__.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/tool
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/tool/__init__.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/tool/__init__.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/paths.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/pkginfo.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/__main__.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/wininst2wheel.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/egg2wheel.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/metadata.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/wininst2wheel.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/bdist_wheel.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/metadata.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/archive.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/util.py
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/util.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/wheel/__init__.pyc
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/EGG-INFO
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/EGG-INFO/not-zip-safe
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/EGG-INFO/top_level.txt
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/EGG-INFO/requires.txt
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/EGG-INFO/PKG-INFO
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/EGG-INFO/dependency_links.txt
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/EGG-INFO/entry_points.txt
ipapython/.eggs/wheel-0.30.0a0-py2.7.egg/EGG-INFO/SOURCES.txt
ipapython/.eggs/README.txt
~~~

**Comment by tiran** [comment]
Ah, you don't have python-wheel installed. The package download is triggered by ```setup_requires=["wheel"]```. I assumed that Fedora installs the wheel package with pip. Apparently it does not. Since RHEL and CentOS do not have a python-wheel package, we can't work fix the problem with a build requirement. I have to remove ```setup_requires```.

**Comment by tiran** [comment]
#255 takes care of .eggs and some other minor issues in setup.py.

**Pull request closed without merging**
