### PR TITLE
ipatests: add test for ipa-restore in multi-master configuration

### PR DESCRIPTION
**Pull request by wladich**
Test ensures that after ipa-restore on the master, the replica can be
re-synchronized and a new replica can be created.

https://pagure.io/freeipa/issue/7455

### CODE REVIEW

**Comment by Tiboris** [comment]
Re submit of https://github.com/freeipa/freeipa/pull/2521 because of GH button used; PLEASE DO NOT TOUCH GH BUTTONS :laughing:

**Comment by Tiboris** [comment]
Acking due to https://github.com/freeipa/freeipa/pull/2521#event-1977230331

**Comment by wladich** [comment]
master:

* 8182ebc6c3ca636276fc277186cfbff4ea9cf5c6 ipatests: add test for ipa-restore in multi-master configuration

**Comment by Tiboris** [comment]
We need manual backport @wladich.

**Pull request closed without merging**
