### PR TITLE
[Backport][ipa-4-6] Disable Pylint 2.0 violations

### PR DESCRIPTION
**Pull request by tiran**
This PR was opened automatically because PR #2150 was pushed to master and backport to ipa-4-6 is required.

### CODE REVIEW

**Comment by tiran** [comment]
PR was ACKed automatically because this is backport of PR #2150. Wait for CI to finish before pushing. In case of questions or problems contact @netoarmando who is author of the original PR.

**Comment by netoarmando** [comment]
@tiran perhaps PR #2085 should have been backported?

**Comment by tiran** [comment]
@netoarmando Thanks for noticing. I have included the pylint plugin change in this PR.

**Comment by tiran** [comment]
ipa-4-6:

* 46344dd23a1059526c0dd331530c5f84237e115c Disable Pylint 2.0 violations

**Pull request closed without merging**
