### PR TITLE
[Backport][ipa-4-9] frontend: add systemd journal audit of executed API commands 

### PR DESCRIPTION
**Pull request by abbra**
This PR was opened automatically because PR https://github.com/freeipa/freeipa/pull/7348 was pushed to master and backport to ipa-4-9 is required.

### CODE REVIEW

**Comment by abbra** [comment]
I added couple commits that turned tox into reporting green but the real result is that tox tests didn't run at all because we cannot install additional packages required by 389-ds Python code:
```
Installing collected packages: setuptools, pycodestyle, pip
  WARNING: The script pycodestyle is installed in '/home/vsts_azpcontainer/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts pip, pip3 and pip3.10 are installed in '/home/vsts_azpcontainer/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lib389 1.4.0.1 requires argparse-manpage, which is not installed.

```

Is this worth fixing? This is a general problem with outdated environments (we run on Fedora 36 here) and up-to-date linting tools (Tox is using Python 3.12).

**Comment by abbra** [comment]
Ok, fixed with pinning to Python 3.10.

**Comment by rcritten** [comment]
The proposed changes for CI LGTM.

**Comment by rcritten** [comment]
webUI is a known failure

**Comment by rcritten** [comment]
ipa-4-9:

* b6a5767b2f37076304859b26ccb2e90e36c24052 ipalib: move json formatter to a separate file
* 1c72ab660277f478774a0800392b37c2106c54dc ipalib/rpc: Reformat after moving json code around
* 025f446875fef64989aea229db5700202ddf9661 frontend: add systemd journal audit of executed API commands
* 401987ec0d09247a47f68b7fc2dcfb57274d4383 Tox: use sitepackages
* 0e96d9f6e4b1a40bc7386c76bbec72a289bc21d3 tox: allow systemd-python in tox environment
* ea93ef9a087ce0a504382e3689e5ee9f1809c082 Force python 3.10 in tox environments

**Pull request closed without merging**
