### PR TITLE
Move ipa-epn systemd files and run RPM hooks

### PR DESCRIPTION
**Pull request by tiran**
The init/systemd directory is for server only and not part of
CLIENT_ONLY builds.

It's necesary to run pre/post installation hooks to make systemd aware
of new files.

Signed-off-by: Christian Heimes <cheimes@redhat.com>

### CODE REVIEW

**Comment by rcritten** [comment]
@fcami FYI

**Comment by abbra** [comment]
LGTM. @fcami please review.

**Comment by rcritten** [comment]
Tested and this works fine.

I had attempted to avoid creating a client-specific directory for systemd but alas there is no other way without creating an ugly mess.

**Comment by fcami** [comment]
Tested, works. ACK.

**Comment by fcami** [comment]
master:

* a18d406b5631f80134e202ae3310580683937f92 Move ipa-epn systemd files and run RPM hooks

**Pull request closed without merging**
