### PR TITLE
Fix script loading errors in ssbrowser.html and unauthorized.html

### PR DESCRIPTION
**Pull request by serg-cymbaluk**
Related issue: https://pagure.io/freeipa/issue/7703

### CODE REVIEW

**Comment by rcritten** [comment]
So the fix was just to move the javascript out of the html file? Can you describe the reasoning for the fix in the commit message?

**Comment by stanislavlevin** [comment]
Hello, @serg-cymbaluk 
My apologies, this was my mistake (checked at dev mode only).

Please take a look at last commit: 
https://github.com/stanislavlevin/freeipa/commits/fix_js_at_production

It completely fixes the issue.

**Comment by serg-cymbaluk** [comment]
@rcritten 

> So the fix was just to move the javascript out of the html file? Can you describe the reasoning for the fix in the commit message?

We can't import modules in HTML-file because it requires  js file in the runtime. But when we import module from other module this dependency is resolved in compile-time.
So idea is that all pages have own compiled js file with all dependencies inside.
But at this moment I am inclined to accept @stanislavlevin's [patch](https://github.com/stanislavlevin/freeipa/commit/21acc955be46b4090c4ed0b96467fd28c4a0a464) because it's simpler one.

**Comment by serg-cymbaluk** [comment]
> Please take a look at last commit:
> https://github.com/stanislavlevin/freeipa/commits/fix_js_at_production
@stanislavlevin, please create new PR if it is final edits.

**Comment by stanislavlevin** [comment]
#2387 opened.
Excuse me one more time.

**Comment by tiran** [comment]
@stanislavlevin This PR needs rebase, too.

**Comment by stanislavlevin** [comment]
> @stanislavlevin This PR needs rebase, too.

It does not belong to me ;-)
The issue was fixed at #2387 (already pushed).

About this PR, in my opinion, it is no longer needed.

**Comment by tiran** [comment]
Sorry @stanislavlevin 

@serg-cymbalu, what about this PR? Is it still necessary?

**Comment by serg-cymbaluk** [comment]
@tiran 

> what about this PR? Is it still necessary?

It is already not actual.

**Pull request closed without merging**
