### PR TITLE
[Backport][ipa-4-7] Moving prompt for NTP options to install_check

### PR DESCRIPTION
**Pull request by Tiboris**
This PR is manual backport of https://github.com/freeipa/freeipa/pull/3106 please wait for CI before pushing and do not forget about backport to branches specified with labels.
In case of questions or problems contact @Tiboris who is author of the original PR.

### CODE REVIEW

**Comment by Tiboris** [comment]
Giving ACK as this is a backport.

**Comment by flo-renaud** [comment]
Hi @Tiboris 
There is a pylint error which may mean the backport is not as straightforward as it seems:
```
Pylint on /usr/bin/python2 is running, please wait ...
************* Module ipaclient.install.client
ipaclient/install/client.py:2503: [E0602(undefined-variable), sync_time] Undefined variable 'discovery')
```

**Comment by rcritten** [comment]
Did it fail to merge because of ipadiscovery vs discovery?

**Comment by Tiboris** [comment]
@rcritten yes it did.

**Comment by flo-renaud** [comment]
Hi @Tiboris 
Thanks for the backport, LGTM.

**Comment by Tiboris** [comment]
ipa-4-7:

* 9a0142ef6f032e0bfe42d4e6bd096636d08da16c Moving prompt for NTP options to install_check
* 6b6ad5df426c1cbdf7be4dbf4a094b5ffb16e81f ipatests: Add Unattended option to external ca task

**Pull request closed without merging**
