### PR TITLE
webui:test realm domain add with DNS check

### PR DESCRIPTION
**Pull request by pvoborni**
Try adding and deleting with "Check DNS" (in html 'ok' button)

DNS check expects that the added domain will have DNS record:
    TXT _kerberos.$domain "$REALM"

When a new domain is added using dnszone-add it automatically adds
this TXT record and adds a realm domain. So in order to test without
external DNS we must get into state where realm domain is not added
(in order to add it) but DNS domain with the TXT record exists.

### CODE REVIEW

**Comment by pvoborni** [comment]
When somebody will do initial review and ack the approach, I'll remove the temp commit to trigger the usual PR-CI gating tests but till then I'll keep the results fo the Web UI test run here.

**Comment by celestian** [comment]
ACK

**Comment by tiran** [comment]
master:

* d7d13bc95043a85bd7621e364554df5989a7ce9d webui:tests: move DNS test data to separate file
* d73d49f3f69ed34cf8386422822a85a4707bf669 webui:tests: realm domain add with DNS check
* 6b214512b335998b424ef0c160b593b162b07c29 webui:tests: close big notifications in realm domains tests
* db2222fee4558004968900e8d1421abfb409f53a temp commit to run the affected tests

**Comment by pvoborni** [comment]
This PR was acked bit soon, the temp commit should have been removed. It was reverted. Given that it changes only tests, there is low chance that it broke IPA (usualy PR-CI test were not run).

**Pull request closed without merging**
