### PR TITLE
[ipa-4-6] Create nightly test definition

### PR DESCRIPTION
**Pull request by flo-renaud**
### PRCI: add nightly definition for ipa-4-6 branch

Replace .freeipa-pr-ci.yaml with a link to ipatests/prci_definitions/gating.yaml
Create a nightly test definition

### tests: fix test_user_permissions.py::TestInstallClientNoAdmin

Adapt the test to ipa-4-6 branch. On this branch, the calls to external commands are logged with
    ---8<---
    Starting external process
    args=/usr/bin/getent passwd testuser1@domain.com
    ---8<---

while on master branch the logs are
    ---8<---
    Starting external process
    args=['/usr/bin/getent', 'passwd', 'testuser1@domain.com']
    ---8<---

This is because 9c2c3df was not backported to ipa-4-6 branch and modified the debug logs when calling ipautil.run()

### CODE REVIEW

**Comment by flo-renaud** [comment]
Note: I didn't add all the tests defined in the master branch as
- some were not backported to ipa-4-6
- some are failing and need to be fixed first (test_server_del.py, test_replication_layouts.py, test_uninstallation.py)

You can see a successful run of the nightly tests at https://github.com/freeipa-pr-ci2/freeipa/pull/9 if you click on the green tick.

**Comment by tiran** [comment]
@flo-renaud The list of successful nightly tests is no longer available. GH hides the results as soon as a PR is closed.

**Comment by flo-renaud** [comment]
nightly_results

@tiran If you click on the green tick you should be able to see the result

**Comment by flo-renaud** [comment]
@f-trivino Could you check if this PR is consistent with the nightly jobs we define on other branches? For instance I named the nightly test def nightly_ipa-4-6.yaml. Thanks

**Comment by f-trivino** [comment]
LGTM!, I have review that the topologies are correct and the ci-ipa-4-6 template is the latest that we have: v1.0.1. Looks good to me. Let's get it merged.

**Comment by flo-renaud** [comment]
ipa-4-6:

* a0014db2a9c30fcd6f2da68b872603c5268517e1 PRCI: add nightly definition for ipa-4-6 branch
* 5ca8b4f6ba7ca2aca855dee35b0e3e96724bf643 tests: fix test_user_permissions.py::TestInstallClientNoAdmin

**Pull request closed without merging**
