### PR TITLE
Bump required version of gssproxy to 0.7.0

### PR DESCRIPTION
**Pull request by dkupka**
https://fedorahosted.org/freeipa/ticket/6698

### CODE REVIEW

**Comment by stlaz** [comment]
Works for me

**Comment by stlaz** [comment]
Unfortunately, we can't push this until we find a way to provide the rpm for Travis.

**Comment by HonzaCholasta** [comment]
@stlaz, https://copr.fedorainfracloud.org/coprs/g/freeipa/freeipa-master/build/519196/

**Comment by stlaz** [comment]
@HonzaCholasta Thank you, please kick Travis once the build is done

**Comment by stlaz** [comment]
There's going to be 0.6.3 version fixing some more issues.

**Comment by puiterwijk** [comment]
Perhaps it'd be an idea to update the ticket link in the code to https://pagure.io/freeipa/issue/6698 ?

**Comment by MartinBasti** [comment]
@puiterwijk It shouldn't be an issue with https://pagure.io/fedora-infrastructure/issue/5845 fixed :)
but yes since this is not acked yet commit should be updated

**Comment by puiterwijk** [comment]
@MartinBasti Yeah, I know. I just figured that since it's not merged yet, we might as well just change it :).

**Comment by dkupka** [comment]
@stlaz And do we need the fixes going to 0.6.3. for FreeIPA to work properly? Is there any fix that actually affects us planned for 0.6.3?

**Comment by dkupka** [comment]
@puiterwijk @MartinBasti with the redirection working it's not needed. But I should get used to paste links to pagure. Updated.

**Comment by stlaz** [comment]
@dkupka Those fixes should allow us to setup trusts again (more or less).

**Comment by dkupka** [comment]
@stlaz Thanks. Then we really rather wait for 0.6.3.

**Comment by simo5** [comment]
We are actually planning 0.7 at this point, due to the changes in the last few patchsets :-)

**Comment by dkupka** [comment]
Ok, please comment here once 0.7 is out and I will update the commit.

**Comment by MartinBasti** [comment]
I see gssproxy 0.7 in koji, can we update this an test rather early by putting it into freeipa-master repo?

**Comment by stlaz** [comment]
+1

**Comment by simo5** [comment]
Can you prepare patch for spec file that requires gssproxy >= 0.7.0 and mod_auth_gssapi >= 1.5.0 ?

**Comment by HonzaCholasta** [comment]
FYI built both in the freeipa-master COPR.

**Comment by dkupka** [comment]
@simo5 We already require mod_auth_gssapi >= 1.5.0 
https://github.com/freeipa/freeipa/blob/master/freeipa.spec.in#L255

**Comment by stlaz** [comment]
Is this in RHEL already? If not, it will break upstream-downstreamish tests 😞

**Comment by MartinBasti** [comment]
We need to have our upstream-upstream tests green first, then we can care about upstream-downstream

**Comment by MartinBasti** [comment]
and gssproxy 0.7 is not in RHEL yet

**Comment by stlaz** [comment]
Meh, I'll be damned to eternity then 👿

**Comment by MartinBasti** [comment]
master:

* c37254e1b124c95d6ea874f6513979ca165fb31d Bump required version of gssproxy to 0.7.0

**Pull request closed without merging**
