### PR TITLE
Correct PyPI package dependencies

### PR DESCRIPTION
**Pull request by tiran**
* Remove unused install requires
* Correct dependencies for yubico otptoken
* Add explicit dependency on cffi for csrgen
* Python 2 uses python-ldap, Python 3 pyldap

Signed-off-by: Christian Heimes <cheimes@redhat.com>

Needs backport to 4.5 for 4.5.1 PyPI packaging.

### CODE REVIEW

**Comment by MartinBasti** [comment]
For backport to 4.5 ticket and agreement on ticket triage must be done

**Comment by tiran** [comment]
With recent changes, 4.5 needs a different patch. Let's merge this one and I'll prepare a new one with a ticket another time.

**Comment by MartinBasti** [comment]
Pylint targets are failing with following errror
```
Collecting pyusb; extra == "otptoken_yubikey" (from ipaclient==4.5.90.dev201704251040+git0ebdd30->-c /tmp/freeipa/.wheelconstraints (line 5))
  Could not find a version that satisfies the requirement pyusb; extra == "otptoken_yubikey" (from ipaclient==4.5.90.dev201704251040+git0ebdd30->-c /tmp/freeipa/.wheelconstraints (line 5)) (from versions: )
No matching distribution found for pyusb; extra == "otptoken_yubikey" (from ipaclient==4.5.90.dev201704251040+git0ebdd30->-c /tmp/freeipa/.wheelconstraints (line 5))
```

**Comment by tiran** [comment]
You are running into a pip bug. I've added band-aid for the issue. To speed up testing, tox caches packages. I guess I never ran into the problem because I had the packages pre-build and cached.

**Comment by MartinBasti** [comment]
master:

* 26ab51ddf47f421f3404709052db89f08c05adaa Correct PyPI package dependencies
* 994d24d288080e924e039ca0a7b0b0dfc2355ac1 Band-aid for pip dependency bug

**Pull request closed without merging**
