### PR TITLE
Add IPA RA Agent to ACME group on the CA

### PR DESCRIPTION
**Pull request by rcritten**
Add IPA RA Agent to ACME group on the CA

Move the addition of the RA agent to the ACME Enterprise Users
group into setup_acme() so it is also added on upgrades.

This allows ipa-acme-manage to authenticate to the CA REST
API using the RA Agent credentials.

https://pagure.io/freeipa/issue/8603

Signed-off-by: Rob Crittenden <rcritten@redhat.com>

### CODE REVIEW

**Comment by mrizwan93** [comment]
I build the ipa packages from this branch(i.e rcritten:issue_8603) and upgraded to it from `freeipa-server-4.8.10-6.fc32.x86_64`

My test results
~~~~~~~~~~~
After upgrade:
```
[root@master freeipa]# ipa-acme-manage enable
The ipa-acme-manage command was successful
[root@master freeipa]# echo $?
0
[root@master freeipa]# curl https://ipa-ca.testrelm.test/acme/directory
{"newNonce":"https://ipa-ca.testrelm.test/acme/new-nonce","newAccount":"https://ipa-ca.testrelm.test/acme/new-account","newOrder":"https://ipa-ca.testrelm.test/acme/new-order","revokeCert":"https://ipa-ca.testrelm.test/acme/revoke-cert","meta":{"termsOfService":"https://www.dogtagpki.org/wiki/PKI_ACME_Responder","website":"https://www.dogtagpki.org","caaIdentities":["dogtagpki.org"],"externalAccountRequired":false}}
```
Fresh system:
```
[root@master dist]# ipa-acme-manage enable
The ipa-acme-manage command was successful
[root@master dist]# echo $?
0
[root@master dist]# curl https://ipa-ca.testrelm.test/acme/directory
{"newNonce":"https://ipa-ca.testrelm.test/acme/new-nonce","newAccount":"https://ipa-ca.testrelm.test/acme/new-account","newOrder":"https://ipa-ca.testrelm.test/acme/new-order","revokeCert":"https://ipa-ca.testrelm.test/acme/revoke-cert","meta":{"termsOfService":"https://www.dogtagpki.org/wiki/PKI_ACME_Responder","website":"https://www.dogtagpki.org","caaIdentities":["dogtagpki.org"],"externalAccountRequired":false}}
```

**Review by mrizwan93 — APPROVED** [review]
Approving based on my testing results.

@flo-renaud @frasertweedale could you have a look too, please?

**Comment by frasertweedale** [comment]
I haven't tested it but I don't see any red flags.

**Comment by tiran** [comment]
LGTM

Since 4.8 is not affected and 4.9.0 final has not been released yet, the change does not need any migration code.

**Comment by abbra** [comment]
master:

* 81c97bb9928a88a595b3afe6fa70fcfb267b1440 Remove test for minimum ACME support and rely on package deps
* 2068c7c472d3548962dfef76b26ac2ff19dec4dd Reorder when ACME is enabled to fix failure on upgrade

**Pull request closed without merging**
