### PR TITLE
ipa-kdb: do not fail if certmap rule cannot be added

### PR DESCRIPTION
**Pull request by sumit-bose**
Currently if a certificate mapping and matching rule has a typo or is of
an unsupported type the whole rule processing is aborted and the IPA
certmap plugin works without any rules effectively disabling PKINIT for
users. Since each rule would only allow more certificates for PKINIT it
would be more user/admin friendly to just ignore the failed rules with a
log message and continue with what is left or use the default rule if
nothing is left.

### CODE REVIEW

**Comment by abbra** [comment]
@sumit-bose ping, could you please update the commit message as suggested in https://github.com/freeipa/freeipa/pull/6442#issuecomment-1239094201 ?

**Comment by sumit-bose** [comment]
Hi,

sorry, I missed that. I just updated the message with a reference.

bye,
Sumit

**Comment by sumit-bose** [comment]
> @sumit-bose can you rebase your PR on top of the master branch? The test failure in test_commands has been fixed there with [7aeb9e5](https://pagure.io/freeipa/c/7aeb9e58600854045c2790550e3829df2c8e917d) ipa-cacert-manage prune: remove all expired certs

done

**Comment by abbra** [comment]
LGTM

**Comment by flo-renaud** [comment]
master:

* 0ce3ab36b486297cd89064095a11803d611660ac ipa-kdb: do not fail if certmap rule cannot be added

**Pull request closed without merging**
