### PR TITLE
Fix translation of title of entity's add dialog

### PR DESCRIPTION
**Pull request by stanislavlevin**
As for now the default title of 'add' dialog is set to something like:
```
'Add ${entity}'
```
where 'entity' is also translatable text. Such construction is used via method 'adder_dialog' of Entity for the all 'Add' actions.

From now a mentioned title (containing entire sentence) is taken from the spec and should be specified explicitly.
    
Fixes: https://pagure.io/freeipa/issue/7707

### CODE REVIEW

**Comment by serg-cymbaluk** [comment]
Is it necessary to make 23 commits for this changes?

**Comment by stanislavlevin** [comment]
I have many changes to the same file within different topic branches.
Workflow is like: modify/check one entity -> commit.
It is conveniently for me. 
I don't like huge commits.

But of course, I can squash them to something more compact.

**Comment by serg-cymbaluk** [comment]
@stanislavlevin 
> But of course, I can squash them to something more compact.
If it helps you to fix your work just leave it as it is.

**Comment by serg-cymbaluk** [comment]
@stanislavlevin  please rebase this branch and fix conflicts on it.

**Comment by stanislavlevin** [comment]
rebased, waiting for tests' result.

**Comment by tiran** [comment]
Although GH doesn't show a merge conflict, I'm unable to push the PR

```
$ ipatool pr-push 2378 -rstsymbal@redhat.com -B ipa-4-7
Reviewer: Serhii Tsymbaliuk <stsymbal@redhat.com>
Will apply 23 patches to: master
Fetching...
Aplying to master: Drop concatenated title of 'add' dialog
Aplying to master: Add title to 'add' dialog for 'Users' entity
Aplying to master: Add title to 'add' dialog for 'OTP' entity
Aplying to master: Add title to 'add' dialog for 'Host' entity
Aplying to master: Add title to 'add' dialog for 'Service' entity
Aplying to master: Add title to 'add' dialog for 'Groups' entity
Aplying to master: Add title to 'add' dialog for 'ID Views' entity
Aplying to master: Drop concatenated title of 'add' dialog for 'attribute_table' widget
Aplying to master: Add title to 'add' dialog for 'Automember' entity
Aplying to master: Add title to 'add' dialog for 'HBAC' entity
Aplying to master: Add title to 'add' dialog for 'Sudo' entity
Aplying to master: Add title to 'add' dialog for 'SELinux' entity
Aplying to master: Add title to 'add' dialog for 'Password Policies' entity
Aplying to master: Add title to 'add' dialog for 'Certificates' entity
Aplying to master: Add title to 'add' dialog for 'RADIUS' entity
Aplying to master: Add title to 'add' dialog for 'Certificate Identity' entity
Aplying to master: Add title to 'add' dialog for 'Automount' entity
Aplying to master: Add title to 'add' dialog for 'DNS' entity
Aplying to master: Add title to 'add' dialog for 'Vault' entity
Aplying to master: Add title to 'add' dialog for 'RBAC' entity
Aplying to master: Add title to 'add' dialog for 'ID Ranges' entity
Aplying to master: Add title to 'add' dialog for 'Trusts' entity
Aplying to master: Add title to 'add' dialog for 'Topology' entity
git am
Applying: Add title to 'add' dialog for 'Topology' entity
Patch failed at 0001 Add title to 'add' dialog for 'Topology' entity
Use 'git am --show-current-patch' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
error: patch failed: ipaserver/plugins/internal.py:1075
error: ipaserver/plugins/internal.py: patch does not apply
→ 128
Command failed
Cleaning up
```

**Comment by serg-cymbaluk** [comment]
> @stanislavlevin `-B ipa-4-7` means "also create a backport to 4.7".

@tiran, unfortunately backport of this PR depends on #2393, so there is no chance to merge it now.

**Comment by serg-cymbaluk** [comment]
master:

* 234c71ca8187dede91785d595f66f70fea8efbe9 Drop concatenated title of 'add' dialog
* c6221a5104d946f6cbc10fa0df8cdb297be37792 Add title to 'add' dialog for 'Users' entity
* 70cb5ba0958b0a6380adcef0abfd39153359521c Add title to 'add' dialog for 'OTP' entity
* 6881bf8d7438b5f52fd0daf4b63f479f6fac67f9 Add title to 'add' dialog for 'Host' entity
* 8a834cdaa09b9befc3834539206a607d73e22227 Add title to 'add' dialog for 'Service' entity
* 794a51ea93106800ccbb91ef92618be105ad701e Add title to 'add' dialog for 'Groups' entity
* 348e813b653d947353e6ce38eb84a179f3782de4 Add title to 'add' dialog for 'ID Views' entity
* bf49664ddd93c5191582e2faf847cae807e1b0d8 Drop concatenated title of 'add' dialog for 'attribute_table' widget
* e363fb3ebc73fd4d6b172f06e76816797c61b456 Add title to 'add' dialog for 'Automember' entity
* fd732aaafebb5958994d05c600674b9d1545f0fc Add title to 'add' dialog for 'HBAC' entity
* 8655c9beb076c79f8b7cee9a214386c7627218a8 Add title to 'add' dialog for 'Sudo' entity
* e506f266ef03fe5e15311a0d96d92d52b4e81de3 Add title to 'add' dialog for 'SELinux' entity
* 4bd03e47230c607ba56148b0c968561b1131ff48 Add title to 'add' dialog for 'Password Policies' entity
* c38aab10453bdb75a6afad546797944e9d7586df Add title to 'add' dialog for 'Certificates' entity
* 38ea2dae2d2592303b6ac34c55c14b4b75cdd43d Add title to 'add' dialog for 'RADIUS' entity
* 98c290e4035f179c63a94eb59fc9f2ec9e30c01b Add title to 'add' dialog for 'Certificate Identity' entity
* bafa0d5f4aaa4934ae7bbad5378a18e986977cc4 Add title to 'add' dialog for 'Automount' entity
* 8dddc003bdd42ed2d379e7c7f276dae7b0145330 Add title to 'add' dialog for 'DNS' entity
* f3584661b4076238eb967df3438f28572e55a012 Add title to 'add' dialog for 'Vault' entity
* 16fed6e97a50bbb8740216fdd6e9a9c52b795a9d Add title to 'add' dialog for 'RBAC' entity
* f349479f5c0e3e9ff8f2cf2e5fe80423032dca6d Add title to 'add' dialog for 'ID Ranges' entity
* e3c0c4d752a18ad1a463ec4c981b19009fb9b81d Add title to 'add' dialog for 'Trusts' entity
* e89493e26033a800f62a5dceb98ac3dcdcd8c17b Add title to 'add' dialog for 'Topology' entity

**Pull request closed without merging**
