### PR TITLE
[Backport][ipa-4-8] pylint: Fix warning and error

### PR DESCRIPTION
**Pull request by rcritten**
This PR was opened automatically because PR #4982 was pushed to master and backport to ipa-4-8 is required.

### CODE REVIEW

**Comment by rcritten** [comment]
PR was ACKed automatically because this is backport of PR #4982. Wait for CI to finish before pushing. In case of questions or problems contact @stanislavlevin who is author of the original PR.

**Comment by abbra** [comment]
ipa-4-8:

* e4c753dc03c48b8c3509e6077dd7fa5074f73670 pylint: Fix warning and error

**Pull request closed without merging**
