### PR TITLE
ipa-pwd-extop: clarify OTP use over LDAP binds

### PR DESCRIPTION
**Pull request by abbra**
OTP use during LDAP bind can be enforced either explicitly via client specifying a control with OID 2.16.840.1.113730.3.8.10.7 and no payload or implicitly through the global IPA configuration with EnforceLDAPOTP.

OTP token enforcement overrides IPA user authentication types requirements:

If OTP enforcement is required:

 - if user authentication types still allow password authentication, authentication with just a password is denied, regardless whether OTP tokens are associated with the user or not.

If OTP enforcement is not required:

 - if user has no OTP tokens but user authentication types require OTP use, authentication with just a password is allowed until a token is added.

 - if user has OTP tokens and user authentication types require OTP use but not password, authentication with just a password is denied.

Additionally, enforcement of OTP only applies to LDAP objects which don't use 'simpleSecurityObject' objectclass. This allows system service accounts to continue authenticate with a password regardless of the OTP enforcement.

Fixes: https://pagure.io/freeipa/issue/9699
Fixes: https://pagure.io/freeipa/issue/9711

### CODE REVIEW

**Comment by rcritten** [comment]
It looks ok but the condition `otpreq != OTP_IS_NOT_REQUIRED` kinda hurts my brain because it reads like a double negative. Same with `!notokens`.
I have no suggestions for the first but the second could be `notokens == true` which might be clearer? I don't know.
I guess I'm more concerned about future changes and it being misinterpreted. This is also an important section that pairs with ipapwd_pre_bind_otp()

**Comment by abbra** [comment]
> It looks ok but the condition `otpreq != OTP_IS_NOT_REQUIRED` kinda hurts my brain because it reads like a double negative. Same with `!notokens`. I have no suggestions for the first but the second could be `notokens == true` which might be clearer? I don't know. I guess I'm more concerned about future changes and it being misinterpreted. This is also an important section that pairs with ipapwd_pre_bind_otp()

So we have these two conditions:
- OTP enforcement is set (implicitly or explicitly)
- OTP authentication type is set on the account to be bound or globally

Both of these conditions will get us through the OTP tokens check in `ipapwd_pre_bind_otp()` and if there are no tokens found, we either return false (OTP enforcement isn't set but the account is required to use OTP) or true (OTP enforcement was set, regardless whether account has OTP authentication type forced). So we can simply see if tokens were present and deny that access -- it means token verification failed. That simplifies logic in `ipapwd_pre_bind()` now: if we ever get `false` from the `ipwpwd_pre_bind_otp()`, `notokens == false` means failure.

This gets us to a simplified logic:
- in `ipapwd_pre_bind()` we only define `otpreq` state based on the facts we know
- in `ipapwd_pre_bind_otp()` we apply `otpreq` state to the tokens and their evaluation

I created a small test script that tests this logic. It runs password-only authentication over a number of accounts with different properties:

```
$ sh ./test.sh 
Binds: sudo admin test-user another-user
Configuration:
  ipaconfigstring: AllowNThash
  ipaconfigstring: KDC:Disable Last Success

With EnforceLDAPOTP:
  ipaconfigstring: AllowNThash
  ipaconfigstring: KDC:Disable Last Success
  ipaconfigstring: EnforceLDAPOTP

=== System account account 'uid=sudo,cn=sysaccounts,cn=etc,dc=ipa1,dc=test'
=== LDAP bind as uid=sudo,cn=sysaccounts,cn=etc,dc=ipa1,dc=test:
dn: uid=sudo,cn=sysaccounts,cn=etc,dc=ipa1,dc=test
=== Result: 0

=== User account 'admin' config:
  nsaccountlock: FALSE
0 OTP tokens matched
=== LDAP bind as uid=admin,cn=users,cn=accounts,dc=ipa1,dc=test:
dn: uid=admin,cn=users,cn=accounts,dc=ipa1,dc=test
=== Result: 0

=== User account 'test-user' config:
  ipauserauthtype: otp
  nsaccountlock: FALSE
  objectClass: ipauserauthtypeclass
1 OTP token matched
=== LDAP bind as uid=test-user,cn=users,cn=accounts,dc=ipa1,dc=test:
ldap_bind: Invalid credentials (49)
=== Result: 49

=== User account 'another-user' config:
  ipauserauthtype: otp
  nsaccountlock: FALSE
  objectClass: ipauserauthtypeclass
0 OTP tokens matched
=== LDAP bind as uid=another-user,cn=users,cn=accounts,dc=ipa1,dc=test:
dn: uid=another-user,cn=users,cn=accounts,dc=ipa1,dc=test
=== Result: 0


Without EnforceLDAPOTP:
  ipaconfigstring: AllowNThash
  ipaconfigstring: KDC:Disable Last Success

=== System account account 'uid=sudo,cn=sysaccounts,cn=etc,dc=ipa1,dc=test'
=== LDAP bind as uid=sudo,cn=sysaccounts,cn=etc,dc=ipa1,dc=test:
dn: uid=sudo,cn=sysaccounts,cn=etc,dc=ipa1,dc=test
=== Result: 0

=== User account 'admin' config:
  nsaccountlock: FALSE
0 OTP tokens matched
=== LDAP bind as uid=admin,cn=users,cn=accounts,dc=ipa1,dc=test:
dn: uid=admin,cn=users,cn=accounts,dc=ipa1,dc=test
=== Result: 0

=== User account 'test-user' config:
  ipauserauthtype: otp
  nsaccountlock: FALSE
  objectClass: ipauserauthtypeclass
1 OTP token matched
=== LDAP bind as uid=test-user,cn=users,cn=accounts,dc=ipa1,dc=test:
ldap_bind: Invalid credentials (49)
=== Result: 49

=== User account 'another-user' config:
  ipauserauthtype: otp
  nsaccountlock: FALSE
  objectClass: ipauserauthtypeclass
0 OTP tokens matched
=== LDAP bind as uid=another-user,cn=users,cn=accounts,dc=ipa1,dc=test:
dn: uid=another-user,cn=users,cn=accounts,dc=ipa1,dc=test
=== Result: 0

```

**Comment by abbra** [comment]
I added a fixup with the change.

In both cases, users without OTP tokens associated can bind to LDAP to be able to change their password or add tokens.

**Comment by abbra** [comment]
I also ran comparison with the current master version. The differences are:

- sysaccount binding does not work in EnforceLDAPOTP mode
- account without OTP user authentication type set and no tokens (admin) cannot bind at all in EnforceLDAPOTP mode
- user with OTP user authentication type set and defined token (test-user) can bind without OTP in non-EnforceLDAPOTP mode (a bug)

Full output:
```
$ sh ./test.sh 
Binds: sudo admin test-user another-user
Configuration:
  ipaconfigstring: AllowNThash
  ipaconfigstring: KDC:Disable Last Success

With EnforceLDAPOTP:
  ipaconfigstring: AllowNThash
  ipaconfigstring: KDC:Disable Last Success
  ipaconfigstring: EnforceLDAPOTP

=== System account account 'uid=sudo,cn=sysaccounts,cn=etc,dc=ipa1,dc=test'
=== LDAP bind as uid=sudo,cn=sysaccounts,cn=etc,dc=ipa1,dc=test:
ldap_bind: Invalid credentials (49)
=== Result: 49

=== User account 'admin' config:
  nsaccountlock: FALSE
0 OTP tokens matched
=== LDAP bind as uid=admin,cn=users,cn=accounts,dc=ipa1,dc=test:
ldap_bind: Invalid credentials (49)
=== Result: 49

=== User account 'test-user' config:
  ipauserauthtype: otp
  nsaccountlock: FALSE
  objectClass: ipauserauthtypeclass
1 OTP token matched
=== LDAP bind as uid=test-user,cn=users,cn=accounts,dc=ipa1,dc=test:
ldap_bind: Invalid credentials (49)
=== Result: 49

=== User account 'another-user' config:
  ipauserauthtype: otp
  nsaccountlock: FALSE
  objectClass: ipauserauthtypeclass
0 OTP tokens matched
=== LDAP bind as uid=another-user,cn=users,cn=accounts,dc=ipa1,dc=test:
dn: uid=another-user,cn=users,cn=accounts,dc=ipa1,dc=test
=== Result: 0


Without EnforceLDAPOTP:
  ipaconfigstring: AllowNThash
  ipaconfigstring: KDC:Disable Last Success

=== System account account 'uid=sudo,cn=sysaccounts,cn=etc,dc=ipa1,dc=test'
=== LDAP bind as uid=sudo,cn=sysaccounts,cn=etc,dc=ipa1,dc=test:
dn: uid=sudo,cn=sysaccounts,cn=etc,dc=ipa1,dc=test
=== Result: 0

=== User account 'admin' config:
  nsaccountlock: FALSE
0 OTP tokens matched
=== LDAP bind as uid=admin,cn=users,cn=accounts,dc=ipa1,dc=test:
dn: uid=admin,cn=users,cn=accounts,dc=ipa1,dc=test
=== Result: 0

=== User account 'test-user' config:
  ipauserauthtype: otp
  nsaccountlock: FALSE
  objectClass: ipauserauthtypeclass
1 OTP token matched
=== LDAP bind as uid=test-user,cn=users,cn=accounts,dc=ipa1,dc=test:
dn: uid=test-user,cn=users,cn=accounts,dc=ipa1,dc=test
=== Result: 0

=== User account 'another-user' config:
  ipauserauthtype: otp
  nsaccountlock: FALSE
  objectClass: ipauserauthtypeclass
0 OTP tokens matched
=== LDAP bind as uid=another-user,cn=users,cn=accounts,dc=ipa1,dc=test:
dn: uid=another-user,cn=users,cn=accounts,dc=ipa1,dc=test
=== Result: 0
```

**Comment by abbra** [comment]
I think this now covers wanted configuration:

With EnforceLDAPOTP:
- sysaccounts can bind with password
- users without OTP user authentication type cannot bind at all (admin)
- users with OTP user authentication type can only bind with password if they have no OTP token, to aim password change and OTP creation

Without EnforceLDAPOTP:
- sysaccounts can bind with password
- users without OTP user authentication type can bind with password
- users with only OTP user authentication type can bind with password only if they have no OTP token

```
$ sh ./test.sh 
Binds: sudo admin test-user another-user
Configuration:
  ipaconfigstring: AllowNThash
  ipaconfigstring: KDC:Disable Last Success

With EnforceLDAPOTP:
  ipaconfigstring: AllowNThash
  ipaconfigstring: KDC:Disable Last Success
  ipaconfigstring: EnforceLDAPOTP

=== System account account 'uid=sudo,cn=sysaccounts,cn=etc,dc=ipa1,dc=test'
=== LDAP bind as uid=sudo,cn=sysaccounts,cn=etc,dc=ipa1,dc=test:
dn: uid=sudo,cn=sysaccounts,cn=etc,dc=ipa1,dc=test
=== Result: 0

=== User account 'admin' config:
  nsaccountlock: FALSE
0 OTP tokens matched
=== LDAP bind as uid=admin,cn=users,cn=accounts,dc=ipa1,dc=test:
ldap_bind: Invalid credentials (49)
=== Result: 49

=== User account 'test-user' config:
  ipauserauthtype: otp
  nsaccountlock: FALSE
  objectClass: ipauserauthtypeclass
1 OTP token matched
=== LDAP bind as uid=test-user,cn=users,cn=accounts,dc=ipa1,dc=test:
ldap_bind: Invalid credentials (49)
=== Result: 49

=== User account 'another-user' config:
  ipauserauthtype: otp
  nsaccountlock: FALSE
  objectClass: ipauserauthtypeclass
0 OTP tokens matched
=== LDAP bind as uid=another-user,cn=users,cn=accounts,dc=ipa1,dc=test:
dn: uid=another-user,cn=users,cn=accounts,dc=ipa1,dc=test
=== Result: 0


Without EnforceLDAPOTP:
  ipaconfigstring: AllowNThash
  ipaconfigstring: KDC:Disable Last Success

=== System account account 'uid=sudo,cn=sysaccounts,cn=etc,dc=ipa1,dc=test'
=== LDAP bind as uid=sudo,cn=sysaccounts,cn=etc,dc=ipa1,dc=test:
dn: uid=sudo,cn=sysaccounts,cn=etc,dc=ipa1,dc=test
=== Result: 0

=== User account 'admin' config:
  nsaccountlock: FALSE
0 OTP tokens matched
=== LDAP bind as uid=admin,cn=users,cn=accounts,dc=ipa1,dc=test:
dn: uid=admin,cn=users,cn=accounts,dc=ipa1,dc=test
=== Result: 0

=== User account 'test-user' config:
  ipauserauthtype: otp
  nsaccountlock: FALSE
  objectClass: ipauserauthtypeclass
1 OTP token matched
=== LDAP bind as uid=test-user,cn=users,cn=accounts,dc=ipa1,dc=test:
ldap_bind: Invalid credentials (49)
=== Result: 49

=== User account 'another-user' config:
  ipauserauthtype: otp
  nsaccountlock: FALSE
  objectClass: ipauserauthtypeclass
0 OTP tokens matched
=== LDAP bind as uid=another-user,cn=users,cn=accounts,dc=ipa1,dc=test:
dn: uid=another-user,cn=users,cn=accounts,dc=ipa1,dc=test
=== Result: 0
```

**Comment by rcritten** [comment]
I duplicated the test results. Code looks good.

**Comment by rcritten** [comment]
master:

* 60f9bd043075ad9efce4cd908b23781b81065ca4 ipa-pwd-extop: clarify OTP use over LDAP binds

**Pull request closed without merging**
