### PR TITLE
ipatests: fix TestIpaHealthCheckWithoutDNS failure

### PR DESCRIPTION
**Pull request by flo-renaud**
TestIpaHealthCheckWithoutDNS is launched after
TestIpaHealthCheck::test_ipa_healthcheck_expiring that is playing with
the date. At the end of test_ipa_healthcheck_expiring, the date is
reset using systemctl start chronyd but the date may need time to adjust
and the subsequent tests may be launched with a system date set in the
future.

When this happens, dnf install fails because the certificate for
the package repo is seen as expired, and TestIpaHealthCheckWithoutDNS
fails.

In order to avoid this issue, call chronyc waitsync to make sure the
date was adjusted back.

Fixes: https://pagure.io/freeipa/issue/8447

### CODE REVIEW

**Comment by rcritten** [comment]
The failure does seem to suggest your hypothesis. Perhaps increase the number of tries to 6 to try over a minute and add the -d option for more output.

It would probably also be a good idea to grab datetime.datetime.utcnow() at the beginning of the test and set to that value when the test is done before the waitsync and restarting chronyd to get more in the ballpark of the current time.

It's very strange, I must have run this code a dozen times locally without a failure :-(

**Comment by rcritten** [comment]
Patch looks good, please remote the temp commit.

**Comment by flo-renaud** [comment]
Rebased to include the azure pipeline fix.

**Comment by flo-renaud** [comment]
master:

* f2711321679f99be9a8521f07c81e715bad74b06 ipatests: fix TestIpaHealthCheckWithoutDNS failure

**Pull request closed without merging**
