### PR TITLE
Lower test_nfs.py memory usage

### PR DESCRIPTION
**Pull request by fcami**
test_nfs.py: change pr-ci configuration to run on master_2repl_1client

### CODE REVIEW

**Comment by fcami** [comment]
I'll prefer using the fix in https://github.com/freeipa/freeipa/pull/3325 - Holding.

**Comment by fcami** [comment]
hi @netoarmando could you ack/nack this please?

**Comment by flo-renaud** [comment]
master:

* 54836bce6e38221e6799f253d1c0b4920158e6da test_nfs.py: change pr-ci configuration to run on master_2repl_1client

**Comment by flo-renaud** [comment]
@fcami 
A manual backport is needed for ipa-4-7, can you handle it? thanks

**Comment by fcami** [comment]
hi @flo-renaud yes - https://github.com/freeipa/freeipa/pull/3332

**Pull request closed without merging**
