### PR TITLE
krb5: make sure KDC certificate is readable

### PR DESCRIPTION
**Pull request by abbra**
When requesting certificate for KDC profile, make sure its public part
is actually readable to others.

Fixes https://pagure.io/freeipa/issue/6973

### CODE REVIEW

**Comment by HonzaCholasta** [comment]
I have already "solved" this by changing the permissions of the cert file in the `renew_kdc_cert`. Your solution is definitely better, please remove the chmod call from `renew_kdc_cert`.

**Comment by abbra** [comment]
I removed chmod call now. Sorry for not noticing it yesterday. ;)

**Comment by HonzaCholasta** [comment]
No problem, thank you.

**Comment by MartinBasti** [comment]
Please fix pylint errors:
```
************* Module renew_kdc_cert
install/restart_scripts/renew_kdc_cert:6: [W0611(unused-import), ] Unused import os)
install/restart_scripts/renew_kdc_cert:11: [W0611(unused-import), ] Unused paths imported from ipaplatform.paths)
```

**Comment by abbra** [comment]
Can we get this pulled in?

**Comment by martbab** [comment]
master:

* 9c3fad9cef7785a65c795f1b4fc3f94e50af9db2 krb5: make sure KDC certificate is readable
ipa-4-5:

* db7967061b9b7d001c923ce3da9d6c6036627253 krb5: make sure KDC certificate is readable

**Pull request closed without merging**
