### PR TITLE
[Backport][ipa-4-10] frontend: add systemd journal audit of executed API commands

### PR DESCRIPTION
**Pull request by rcritten**
This PR was opened automatically because PR #7348 was pushed to master and backport to ipa-4-10 is required.

### CODE REVIEW

**Comment by rcritten** [comment]
PR was ACKed automatically because this is backport of PR #7348. Wait for CI to finish before pushing. In case of questions or problems contact @abbra who is author of the original PR.

**Comment by abbra** [comment]
tox test failed because there is no python-systemd installed so pylint cannot resolve an import statement. Some update of the pylintrc/tox.ini is needed to use `systemd-python`?

**Comment by rcritten** [comment]
I'm ok pulling in the same proposed CI changes from the 4-9 PR https://github.com/freeipa/freeipa/pull/7366

**Comment by rcritten** [comment]
ipa-4-10:

* 1c86ef42e40c5b7380f03065a63810d6647b7c9a ipalib: move json formatter to a separate file
* c0bcca0a26e696407499ae08edde8d01e8c5d34c ipalib/rpc: Reformat after moving json code around
* 378320d97c3413802ba05156568ade906355efc0 frontend: add systemd journal audit of executed API commands
* 568d422d0a2038c3082d9e887ca73eb6d29264cb tox: allow systemd-python in tox environment
* 5f5c6542882752daf253b2aa2630c5a2a56fd6e9 Force python 3.11 in tox environments

**Pull request closed without merging**
