### PR TITLE
Py3: Remove subclassing from object

### PR DESCRIPTION
**Pull request by tiran**
Python 2 had old style and new style classes. Python 3 has only new
style classes. There is no point to subclass from object any more.

See: https://pagure.io/freeipa/issue/7715
Signed-off-by: Christian Heimes <cheimes@redhat.com>

### CODE REVIEW

**Comment by flo-renaud** [comment]
Hi @tiran 
thanks for the PR. You may also want to modify the following files:
- install/tools/ipa-custodia-check.in
- install/tools/ipa-httpd-kdcproxy.in
- install/tools/ipa-replica-conncheck.in

**Comment by tiran** [comment]
@flo-renaud good catch! I fixed the three files, too.

**Comment by flo-renaud** [comment]
@tiran thanks for the update, ack

**Comment by tiran** [comment]
master:

* b431e9b684df11c811892bd9d2a5711355f0076e Py3: Remove subclassing from object

**Pull request closed without merging**
