### PR TITLE
ipatests: use proper template for TestMaskInstall

### PR DESCRIPTION
**Pull request by wladich**
TestMaskInstall is a usual integration tests and should
    install freeipa server during test run.
    "ipaserver" template provides pre-install freeipa server and
    is intended for use with webui and xmlrpc tests.

### CODE REVIEW

**Comment by wladich** [comment]
test_mask results are [green](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/9a9dc7b0-80d7-11eb-89e0-fa163e05ce82), removing temp commit

**Review by fcami — APPROVED** [review]
ACK for when CI passes

**Comment by wladich** [comment]
Added labels for backports (manual backport will be needed)

**Comment by flo-renaud** [comment]
Rerunning `fedora-latest/test_service_permissions` because it timed out

**Comment by wladich** [comment]
master:

* 886506f89f6b86f16fbbc118a3716ff9a44e0bfa ipatests: use proper template for TestMaskInstall

**Pull request closed without merging**
