### PR TITLE
[Backport][ipa-4-8] plugins: Don't treat keys of API as bytes

### PR DESCRIPTION
**Pull request by abbra**
This PR was opened automatically because PR #5857 was pushed to master and backport to ipa-4-8 is required.

### CODE REVIEW

**Comment by abbra** [comment]
PR was ACKed automatically because this is backport of PR #5857. Wait for CI to finish before pushing. In case of questions or problems contact @stanislavlevin who is author of the original PR.

**Comment by flo-renaud** [comment]
@abbra can you rebase this backport? PR #5865 has been merged and should fix the azure CI issues

**Comment by abbra** [comment]
Hm...
```
IPA server upgrade failed: Inspect /var/log/ipaupgrade.log and run command ipa-server-upgrade manually.
1	[2021-06-29 15:38:49] Unexpected error - see /var/log/ipaupgrade.log for details:
1	[2021-06-29 15:38:49] TypeError: 'NoneType' object is not subscriptable
1	[2021-06-29 15:38:49] The ipa-server-upgrade command failed. See /var/log/ipaupgrade.log for more information

```

**Comment by abbra** [comment]
In the upgrade log:
```
2021-06-29T15:37:42Z DEBUG   File "/usr/lib/python3.9/site-packages/ipapython/admintool.py", line 180, in execute
    return_value = self.run()
  File "/usr/lib/python3.9/site-packages/ipaserver/install/ipa_server_upgrade.py", line 54, in run
    server.upgrade()
  File "/usr/lib/python3.9/site-packages/ipaserver/install/server/upgrade.py", line 1855, in upgrade
    upgrade_configuration()
  File "/usr/lib/python3.9/site-packages/ipaserver/install/server/upgrade.py", line 1695, in upgrade_configuration
    certificate_renewal_update(ca, kra, ds, http),
  File "/usr/lib/python3.9/site-packages/ipaserver/install/server/upgrade.py", line 560, in certificate_renewal_update
    if certs.is_ipa_issued_cert(api, cert):
  File "/usr/lib/python3.9/site-packages/ipaserver/install/certs.py", line 131, in is_ipa_issued_cert
    cacert_subject = certstore.get_ca_subject(
  File "/usr/lib/python3.9/site-packages/ipalib/install/certstore.py", line 403, in get_ca_subject
    subject_base = attrs.get('ipacertificatesubjectbase')[0]

2021-06-29T15:37:42Z DEBUG The ipa-server-upgrade command failed, exception: TypeError: 'NoneType' object is not subscriptable
2021-06-29T15:37:42Z ERROR Unexpected error - see /var/log/ipaupgrade.log for details:
TypeError: 'NoneType' object is not subscriptable

```

**Comment by abbra** [comment]
Looks like an unrelated issue that this run uncovered.

**Comment by flo-renaud** [comment]
ipa-4-8:

* d59a2e5c46e90969d2f59a3f9a8374e551d6dd05 plugins: Don't treat keys of api as bytes
* c55bc46ac5b063c5b6660838976b66c7b6280a5d ipatests: Add tests for `plugins` plugin
* 9a2fe470cc4b9d6814e9f02c83f45ba3072ba786 ipatests: Add tests for `env` plugin

**Pull request closed without merging**
