### PR TITLE
Use TLS for the cert-find operation

### PR DESCRIPTION
**Pull request by rcritten**
Switch from using urllib.request to dogtag.https_request

https://pagure.io/freeipa/issue/7027

Signed-off-by: Rob Crittenden <rcritten@redhat.com>

### CODE REVIEW

**Comment by stlaz** [comment]
If you rebase your PR onto https://github.com/freeipa/freeipa/pull/1043, we should be able to find out what's wrong.

**Comment by pvoborni** [comment]
I miss  explanation why the change is being done in the commit message.

**Comment by stlaz** [comment]
You should probably remove the unused variable. Also, PR CI does not seem to like you for some reason 😞

**Comment by stlaz** [comment]
master:

* fa6181293a1bf3207c4da1494d9d6cf9d715377b Use TLS for the cert-find operation

**Pull request closed without merging**
