### PR TITLE
[ipa-4-9] ipatests: Bump PR-CI boxes

### PR DESCRIPTION
**Pull request by netoarmando**
Update Fedora 34 and 33 boxes to include new packages.

Signed-off-by: Armando Neto <abiagion@redhat.com>

### CODE REVIEW

**Comment by abbra** [comment]
Please rebase as PR #5804 was pushed

**Comment by netoarmando** [comment]
Rebased.

**Comment by flo-renaud** [comment]
The failure in `test_adtrust_install` happens randomly ([Details](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/ac68ec80-c4a3-11eb-a991-fa163e383601)), looks similar to known issue [8353](https://pagure.io/freeipa/issue/8353).
Re-running the test.

**Comment by flo-renaud** [comment]
ipa-4-9:

* 79e0919132adf0df764400f9c27268cbadd2578b ipatests: Bump PR-CI boxes

**Pull request closed without merging**
