### PR TITLE
azure tests: move to fedora 39

### PR DESCRIPTION
**Pull request by flo-renaud**

### CODE REVIEW

**Comment by abbra** [comment]
we need to install `python3-setuptools` now in Tox: https://github.com/abbra/freeipa/pull/100/commits/18fcecf3f931272ec63bd0b8b968527f6cf51aeb

**Comment by flo-renaud** [comment]
> we need to install `python3-setuptools` now in Tox: [abbra@18fcecf](https://github.com/abbra/freeipa/commit/18fcecf3f931272ec63bd0b8b968527f6cf51aeb)

For tox we run first the `prepare-build-fedora.yaml` script (https://pagure.io/freeipa/blob/master/f/ipatests/azure/azure-pipelines.yml#_102), which calls `dnf builddep` and already installs python3-setuptools (https://pagure.io/freeipa/blob/master/f/freeipa.spec.in#_291).
The issue with tox is rather that python 3.12 does not install setuptools any more in virtual environments.

**Comment by flo-renaud** [comment]
The azure test now show a single failure in AzurePipeline.freeipa (BASE_XMLRPC base_1_to_2) - from this [report](https://dev.azure.com/freeipa/freeipa/_build/results?buildId=13826&view=logs&j=20458f29-bded-5917-d18b-00cdd1c4ba29&t=7f9c5ac8-1fb9-5e35-248d-414a6a9bc4dd):
```
[2023-12-11 21:50:17] =========================== short test summary info ============================
1	[2023-12-11 21:50:17] SKIPPED [22] test_cmdline/test_cli.py:359: Must have root privileges to run this test and IPA must not be installed
1	[2023-12-11 21:50:17] SKIPPED [1] test_cmdline/test_ipagetkeytab.py:441: Must have trust support enabled for this test
1	[2023-12-11 21:50:17] SKIPPED [1] test_cmdline/test_ipagetkeytab.py:453: Must have trust support enabled for this test
1	[2023-12-11 21:50:17] SKIPPED [1] test_ipapython/test_certdb.py:47: NSS is built without support of the legacy database(DBM)
1	[2023-12-11 21:50:17] SKIPPED [1] test_ipapython/test_certdb.py:104: NSS is built without support of the legacy database(DBM)
1	[2023-12-11 21:50:17] SKIPPED [1] test_ipapython/test_certdb.py:143: NSS is built without support of the legacy database(DBM)
1	[2023-12-11 21:50:17] SKIPPED [1] test_ipapython/test_ipautil.py:165: Python 2 only
1	[2023-12-11 21:50:17] SKIPPED [10] conftest.py:174: Skip test on 'any' container type: kernel keyrings are not namespaced yet
1	[2023-12-11 21:50:17] SKIPPED [1] test_ipaserver/test_ldap.py:272: Python 2 only
1	[2023-12-11 21:50:17] XFAIL test_ipaclient/test_ldapconf.py::test_openldap_conf_mixed - freeipa ticket 7838
1	[2023-12-11 21:50:17] FAILED test_ipaserver/test_migratepw.py::test_migratepw::test_bad_params - AssertionError: 500 != 400
1	[2023-12-11 21:50:17] FAILED test_ipaserver/test_migratepw.py::test_migratepw::test_not_post_method - AssertionError: 500 != 302
1	[2023-12-11 21:50:17] FAILED test_ipaserver/test_migratepw.py::test_migratepw::test_invalid_password - AssertionError: 500 != 200
1	[2023-12-11 21:50:17] FAILED test_ipaserver/test_migratepw.py::test_migratepw::test_migration_success - AssertionError: 500 != 200
1	[2023-12-11 21:50:17] = 4 failed, 1117 passed, 39 skipped, 31 deselected, 1 xfailed, 41 warnings in 599.19s (0:09:59) =

```

I had a hard time understanding the problem, but httpd's error log shows the following:
```
[Mon Dec 11 21:41:16.233784 2023] [wsgi:error] [pid 7916:tid 7967] [client 2001:db8:1:1::2:33906] mod_wsgi (pid=7916): Failed to exec Python script file '/usr/share/ipa/migration/migration.py'., referer: https://master1.ipa.test/ipa/migration/migration.py
[Mon Dec 11 21:41:16.233826 2023] [wsgi:error] [pid 7916:tid 7967] [client 2001:db8:1:1::2:33906] mod_wsgi (pid=7916): Exception occurred processing WSGI script '/usr/share/ipa/migration/migration.py'., referer: https://master1.ipa.test/ipa/migration/migration.py
[Mon Dec 11 21:41:16.234046 2023] [wsgi:error] [pid 7916:tid 7967] [client 2001:db8:1:1::2:33906] Traceback (most recent call last):, referer: https://master1.ipa.test/ipa/migration/migration.py
[Mon Dec 11 21:41:16.234190 2023] [wsgi:error] [pid 7916:tid 7967] [client 2001:db8:1:1::2:33906]   File "/usr/share/ipa/migration/migration.py", line 30, in <module>, referer: https://master1.ipa.test/ipa/migration/migration.py
[Mon Dec 11 21:41:16.234198 2023] [wsgi:error] [pid 7916:tid 7967] [client 2001:db8:1:1::2:33906]     from ipapython.dn import DN, referer: https://master1.ipa.test/ipa/migration/migration.py
[Mon Dec 11 21:41:16.234208 2023] [wsgi:error] [pid 7916:tid 7967] [client 2001:db8:1:1::2:33906]   File "/usr/lib/python3.12/site-packages/ipapython/dn.py", line 425, in <module>, referer: https://master1.ipa.test/ipa/migration/migration.py
[Mon Dec 11 21:41:16.234213 2023] [wsgi:error] [pid 7916:tid 7967] [client 2001:db8:1:1::2:33906]     import cryptography.x509, referer: https://master1.ipa.test/ipa/migration/migration.py
[Mon Dec 11 21:41:16.234231 2023] [wsgi:error] [pid 7916:tid 7967] [client 2001:db8:1:1::2:33906]   File "/usr/lib64/python3.12/site-packages/cryptography/x509/__init__.py", line 8, in <module>, referer: https://master1.ipa.test/ipa/migration/migration.py
[Mon Dec 11 21:41:16.234236 2023] [wsgi:error] [pid 7916:tid 7967] [client 2001:db8:1:1::2:33906]     from cryptography.x509.base import (, referer: https://master1.ipa.test/ipa/migration/migration.py
[Mon Dec 11 21:41:16.234244 2023] [wsgi:error] [pid 7916:tid 7967] [client 2001:db8:1:1::2:33906]   File "/usr/lib64/python3.12/site-packages/cryptography/x509/base.py", line 14, in <module>, referer: https://master1.ipa.test/ipa/migration/migration.py
[Mon Dec 11 21:41:16.234249 2023] [wsgi:error] [pid 7916:tid 7967] [client 2001:db8:1:1::2:33906]     from cryptography.hazmat.primitives import hashes, serialization, referer: https://master1.ipa.test/ipa/migration/migration.py
[Mon Dec 11 21:41:16.234258 2023] [wsgi:error] [pid 7916:tid 7967] [client 2001:db8:1:1::2:33906]   File "/usr/lib64/python3.12/site-packages/cryptography/hazmat/primitives/serialization/__init__.py", line 25, in <module>, referer: https://master1.ipa.test/ipa/migration/migration.py
[Mon Dec 11 21:41:16.234263 2023] [wsgi:error] [pid 7916:tid 7967] [client 2001:db8:1:1::2:33906]     from cryptography.hazmat.primitives.serialization.ssh import (, referer: https://master1.ipa.test/ipa/migration/migration.py
[Mon Dec 11 21:41:16.234272 2023] [wsgi:error] [pid 7916:tid 7967] [client 2001:db8:1:1::2:33906]   File "/usr/lib64/python3.12/site-packages/cryptography/hazmat/primitives/serialization/ssh.py", line 105, in <module>, referer: https://master1.ipa.test/ipa/migration/migration.py
[Mon Dec 11 21:41:16.234276 2023] [wsgi:error] [pid 7916:tid 7967] [client 2001:db8:1:1::2:33906]     b"aes256-ctr": _SSHCipher(, referer: https://master1.ipa.test/ipa/migration/migration.py
[Mon Dec 11 21:41:16.234280 2023] [wsgi:error] [pid 7916:tid 7967] [client 2001:db8:1:1::2:33906]                    ^^^^^^^^^^^, referer: https://master1.ipa.test/ipa/migration/migration.py
[Mon Dec 11 21:41:16.234295 2023] [wsgi:error] [pid 7916:tid 7967] [client 2001:db8:1:1::2:33906] TypeError: _SSHCipher() takes no arguments, referer: https://master1.ipa.test/ipa/migration/migration.py
```
and it pointed me into the right direction:
[Bug 2252567](https://bugzilla.redhat.com/show_bug.cgi?id=2252567) - Python 3.12.0-1 breaks Flask apps running from subinterpreters

We need to wait for the update of [python3.12](https://bodhi.fedoraproject.org/updates/FEDORA-2023-c209acd8a1) to reach the stable repo

**Comment by rcritten** [comment]
A couple of nits:

In "azure tests: move to fedora 39" there is a reference to upgrading because of python and a BZ but it leaves the user to assume that F39 contains a newer version of python than F38. Is that the case?

Can we manually install setup-tools in the venv rather than relying on site-packages? Is there concern that site-packages may obscure failures? I use this setting in freeipa-healthcheck tests as well without problem, but freeipa is quite a lot more complex.

Otherwise the changes LGTM.

**Comment by flo-renaud** [comment]
> A couple of nits:
> 
> In "azure tests: move to fedora 39" there is a reference to upgrading because of python and a BZ but it leaves the user to assume that F39 contains a newer version of python than F38. Is that the case?

On f38 we are using python 3.11.7 but on f39 the default is 3.12.0 / 3.12. in updates.
> 
> Can we manually install setup-tools in the venv rather than relying on site-packages? Is there concern that site-packages may obscure failures? I use this setting in freeipa-healthcheck tests as well without problem, but freeipa is quite a lot more complex.
> 
If I install setuptools and wheel in the venv, I see additional failures in test_ipapython/test_ipautil.py::test_ip_address (similar to the ones you saw in PR https://github.com/freeipa/freeipa/pull/7078, with `ValueError: Unrecognized IPAddress flags value: 1`).

> Otherwise the changes LGTM.

**Comment by rcritten** [comment]
Ok. What branches do we want to backport this to? I assume 4.10 and 4.11?

**Comment by flo-renaud** [comment]
ipa-4-10 branch is supported up to fedora 38, no need to backport this change on ipa-4-10. Adding ipa-4-11 label only.

**Comment by flo-renaud** [comment]
master:

* 8981ede1a2d62e61d24b0c500016212e20c31a13 azure tests: move to fedora 39
* 020af153db23b37da6370a5cc70ba967245f42c0 pylint: updates related to deprecations
* 7f485ba7dcd627ba8ae62ead1f13fb26bd90088c pylint: disable new checks
* 8d7bd6c6ab68a4ef3fed2620ef8e07a03aa92d34 pylint: fix errors
* bf1110bda1e8b47869c210b596c12369f2242e49 Tox: use sitepackages

**Pull request closed without merging**
