### PR TITLE
[Backport][ipa-4-8] Bunch of Azure improvements

### PR DESCRIPTION
**Pull request by stanislavlevin**
This PR was opened automatically because PR #5660 was pushed to master and backport to ipa-4-8 is required.

### CODE REVIEW

**Comment by stanislavlevin** [comment]
compared to original PR:
- partly applied 061ef8ac05b2a1901ef6906e4328b1e023e4b217 (ipa-4-8 doesn't have docs build task)
- dropped 4d7f4193abfe6b5fd0924048b90306d5788223bc (ipa-4-8 runs on Ubuntu 18.04).

**Comment by abbra** [comment]
May be we should upgrade ipa-4-8 to newer Ubuntu runs too? I don't see a reason for not doing that.

**Comment by stanislavlevin** [comment]
@abbra, good idea :) Pulled in several Azure commits from master.

**Comment by abbra** [comment]
ipa-4-8:

* 695a42d75c8fda72416f5f57e68a29cdf8530bf4 Azure: Make it possible to pass additional Pytest args
* ea5e38cf8a0853da63271ed6101869ad24f2d96b Azure: Show disk usage
* 9374e996902def0f7fd4bd515522434c20f1d314 Azure: Make unique built artifacts names
* 7f35e8e4babd17926390ee31254546aa7545bd31 Azure: Collect Host's systemd journal
* b2e6bbf7624236eb71a6d8d8287532f9e83cbe9d Azure: Warn about Host's AVC and SECCOMP
* e3ab472869363bd0f25f91814114903db7ed0eba Azure: Disable AppArmor profile for chrony
* 781ca84a75d925855323d491efdd3b9550b3fdf2 Azure CI: use Ubuntu-20.04 image by default
* 9dd4983c07a4b8adfc39efe0d3b4d9d1a98e615b Azure CI: use PPA to provide newer libseccomp version
* 902146d81a736bd2bb7e961b18d0b64979f26596 Azure: Don't install pypi's docker
* 030d8b3364c4af670a471af09da3998d7d412963 pylint: Fix several warnings
* 8e97deb84cd2ac2bc73709fc9a3097d26e25977d Azure: Run Lint task as separate job

**Pull request closed without merging**
