### PR TITLE
[Manual][Backport] Tests for Autoprivate group.

### PR DESCRIPTION
**Pull request by miskopo**
Added tests using posix AD trust and non posix AD trust.
For option --auto-private-groups=[hybrid/true/false]
Related : https://pagure.io/freeipa/issue/8807

### CODE REVIEW

**Comment by miskopo** [comment]
This is a manual backport of https://github.com/freeipa/freeipa/pull/6150. Please, review, especially the PR-CI definitions, as they had conflict which were manually resolved.

**Comment by amore17** [comment]
Thanks @miskopo for manual backport.
from commit  337f1d8d21d515afed2a9146263c9b4f2d3de7ca 
You can remove : as they are not part of ipa-4-9 branch by default.
ipatests/prci_definitions/nightly_latest_testing.yaml 
ipatests/prci_definitions/nightly_latest_testing_selinux.yaml 
ipatests/prci_definitions/nightly_rawhide.yaml

**Comment by amore17** [comment]
LGTM i'll add ACK once PR-CI completes successfully.

**Comment by miskopo** [comment]
@amore17 sorry, I removed them accidentally based on your first comment. Everything should be fine now :)

**Comment by flo-renaud** [comment]
ipa-4-9:

* 6b70e3c49acc55b5553101cf850fc40978861979 ipatests: Tests for Autoprivate group.
* 84381001d2e114b1f29fe89e16155c040b56b80f mark xfail for test_idoverride_with_auto_private_group[hybrid]
* 7ad500e5d3f7d9af81e8a3137158672c6fafb0b4 Mark xfail test_gidnumber_not_corresponding_existing_group[true,hybrid]

**Pull request closed without merging**
