### PR TITLE
azure: bump F32->F34

### PR DESCRIPTION
**Pull request by stanislavlevin**
Bundle of changes required for F34 on Azure.
Shuffling of tests between envs may still be required (under testing for stability).

Fixes: https://pagure.io/freeipa/issue/8848

Opened here for preview.

### CODE REVIEW

**Comment by stanislavlevin** [comment]
OOM crash, rebalanced.

**Comment by stanislavlevin** [comment]
I checked CI for stability last weekend. Random fails occured, but almost all on Azure side is fine. The most important in my opinion is 389 crash during `test_integration/test_upgrade.py`, which happens regularly(~10-20%):
https://dev.azure.com/slev0538/slev_/_build/results?buildId=183&view=logs&j=86c6696a-bb23-5b39-e9a5-efa4858bfa98
So, ready for comments.

**Comment by abbra** [comment]
Thanks for the patch set.
Could you please add ticket https://pagure.io/freeipa/issue/8856 to a changeset 'BIND: Setup logging'? We had a bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1951511 reported about a month ago about the same and I cloned it to Pagure when I saw you already solved it.

**Comment by abbra** [comment]
I had checked the rest of the code and it looks good to me.

**Comment by stanislavlevin** [comment]
Great, thank you!
The latest ldns is pulled in on Azure, but not on PR-CI (it seems I need to bump required release for F34 in spec).

**Comment by abbra** [comment]
@netoarmando how can we get a newer ldns in PR-CI image for F34?

**Comment by netoarmando** [comment]
@abbra F34 images have `ldns-1.7.1-3.fc34.x86_64`, if `ldns-1.7.1-4.fc34` is needed then I have to trigger new builds, should I?

**Comment by abbra** [comment]
@netoarmando yes, we need 1.7.1-4 in all Fedora images: https://bugzilla.redhat.com/show_bug.cgi?id=1962010

**Comment by netoarmando** [comment]
@abbra Ok! I'll build F34 today and will wait for https://bodhi.fedoraproject.org/updates/FEDORA-2021-eebc69f7ea to get into stable F33 repo.

**Comment by stanislavlevin** [comment]
@netoarmando ,  awesome! thank you!

@abbra, one important thing I didn't do is the replacement of JS linter :( https://pagure.io/freeipa/issue/8847

**Comment by stanislavlevin** [comment]
Is it possible to revive jsl in F34?

**Comment by abbra** [comment]
Sadly, no, unless someone would have it maintained in Fedora.
What we could do in Azure CI, though, use npm to install one of JS linters into a test environment.

**Comment by stanislavlevin** [comment]
Yes, I did the same for FleetCommander. But it may be not trivial for FreeIPA.

**Comment by abbra** [comment]
master:

* 6fe8620668c1bf94bab0f908560af1a1a9a8aa31 azure: bump F32->F34
* a8fd65be655469f79ba508f10d81a48c495386c4 freeipa.spec: do not use jsl for linting on Fedora 34+
* be2f659aa7f746446aa521d4a2bf996e00596181 azure: Collect systemd boot log
* 09a4918f03b1ed3782d7f2430d661e17564f44cc azure: Enforce multi-user.target as default systemd's target
* 1c82895c20aeaf963b456f60789c2638d6bc6c11 azure: Wait for systemd booted
* 7ed21f158cf700e8aeacf54835163552ef3f27eb azure: Remove no longer needed repo
* 06d7c7f1d3f5f9dd64e9739c60ed92a9bd52bbc8 azure: Mask systemd-resolved
* 1aff24e8913b4ce876abefa5de557117057ffdcb ipatests: Update expectations for test_detect_container
* 9148ca2e1ece4298ee399fecd5409c45d49bd8d0 azure: Add workaround for PhantomJS against OpenSSL 1.1.1
* b5fdba7a72009c52d4e2ffaf0dfe51afa66dc420 azure: Warn about memory issues
* 07c423afd51b9664733e941486cf13d039bd2e9c BIND: Setup logging
* 65700bf7436b82ad83d9d69d00eaa789f7a9c1ad ipatests: Setup and collect BIND logs
* fc0c6b44a807eb4e2cee1a6f68ba9e283372ec88 azure: Run Base and XMLRPC tests is isolated network
* cc72a988d6c1d483bd8f643397963ce4ebcfa406 ipatests: Handle network-isolated mode
* 4709aefb83e1bf396b2fd919c8c2ebb77d6df159 dnsutil: Improvements for IPA DNS Resolver
* 269c61a9a63321182e1b209bd506286f7b417038 dns: get_reverse_zone: Ignore resolver's timeout
* 3889d8654af56d2f0bf9e249ce4b6bc711a73b6b pytest: Show extra summary information for all except passed tests
* afef09ccbaa19f63cb8d498b37d7431abda8201f ipatests: Ignore warnings on failed to read files on tarring
* 4a4c078b806a31e313d4dc02f7d0bf1ceb4011a4 ipatests: Suppress list trust or certificates
* 611b49e42b0546f142707972e1290ee68f360fda azure: Collect installed packages
* 26ee44bcfd5d5ddaca226d5c1bf73729bfcf0dd9 ipatests: dnssec: Add alternative approach for checking chain of trust
* a893852b4f6178c14260593bf3b7f8cc344b41ce azure: Warn about extra and missing gating tests compared to PR-CI
* 01553572d4a775bc10b4205e3d6d9f3715dd8e1b azure: Re-balance tests envs
* 6c2db326f804f2268883be2714ad258c51536ea8 azure: coredump: Wait for systemd fully booted
* 10461b7091678e4950b57c2a6ef7fcef89792ae7 azure: Make it possible to adjust Docker resources per test env

**Comment by abbra** [comment]
@stanislavlevin I pushed to master and ipa-4-9 but automated backport to ipa-4-8 did not succeed. Could you please handle it?

**Comment by stanislavlevin** [comment]
Sure checking. Is ipa-4-8 not EOL?

**Comment by abbra** [comment]
I'd like us to move away from F32 where possible. ipa-4-8 is still in supported RHEL 8 releases and next step would be to start using CentOS 8 for the test purposes as there is now progress with -devel packages being published in build area: https://koji.mbox.centos.org/kojifiles/repos/dist-c8-build/latest/

**Pull request closed without merging**
