### PR TITLE
WIP: test against Rawhide

### PR DESCRIPTION
**Pull request by abbra**
We target FreeIPA 4.9.0 to Fedora 34 (Rawhide now).

Rawhide version of 389-ds-base has all required fixes for https://pagure.io/freeipa/issue/8538

Let's test that and also fix Rawhide issues we see.

### CODE REVIEW

**Comment by abbra** [comment]
Ok, now I've got to reliably failing to setup containers on Rawhide. I have no idea why that happens but it seems `docker-compose up` succeeds and then `python3 setup-containers.py` gets a failure (HTTP error 409).

@stanislavlevin any idea what's going on?

**Comment by stanislavlevin** [comment]
This means that containers first up and right after that down. I'm checking locally.

**Comment by stanislavlevin** [comment]
```
systemd v246.6-3.fc34 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified)
Detected virtualization docker.
Detected architecture x86-64.

Welcome to Fedora 34 (Container Image Prerelease)!

Set hostname to <a64acbe1ed3d>.
Failed to create /system.slice/docker-a64acbe1ed3d3a122f240ce1e5132ee66096a5f1769214ca8bb4c2895cf5b38b.scope/init.scope control group: Operation not permitted
Failed to allocate manager object: Operation not permitted
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...
```
Only `privileged` mode works for now, checking...

**Comment by stanislavlevin** [comment]
Recently the `faccessat2` syscall has been added to Linux kernel 5.8 [0].
The problem is that glibc switched its internal implementation of `faccessat` to `faccessat2` based on kernel headers existed at compile time [1]. Note, that Azure Ubuntu's kernel is too older than 5.8. This means that glibc (rawhide case) performs this syscalls and:
1) in case of priviliged container or unconfined seccomp (same things) kernel replies with ENOSYS
2) in case of unpriviliged container and strict seccomp filter `runc` replies with EPERM.

I don't see the options on how to allow this syscall via seccomp filter because of libseccomp doesn't know it.
It may be the option on apply the `deny` list instead of `allow` one(current).

https://lwn.net/Articles/817916/
https://sourceware.org/git/?p=glibc.git;a=commit;h=3d3ab573a5f3071992cbc4f57d50d1d29d55bde2

**Comment by abbra** [comment]
Thanks, @stanislavlevin. This also means Rawhide or anything new will not work in containers using Github Actions unless Microsoft and GitHub update their kernels... Interesting case. I am going to discuss this with Florian.

**Comment by stanislavlevin** [comment]
The first case works. But the second one(our) not.

**Comment by abbra** [comment]
Fedora bug that @adelton filed today for similar freeipa-container failures on Github Actions: https://bugzilla.redhat.com/show_bug.cgi?id=1897493.

**Comment by stanislavlevin** [comment]
Github can't update images immediately due to compatibility with user applications as well as docker and its dependencies. The right place to file a bug is glibc. But if we want to go ahead right now the denied list may be applied.

**Comment by abbra** [comment]
@stanislavlevin using `seccomp:unconfined` does not work either. We start the container but then services in it aren't able to communicate -- namely, d-bus daemon is not running.

**Comment by abbra** [comment]
Interesting that `dbus-daemon` is not installed anymore in this image. Nothing requires it. Let's see how it goes with explicit requirement.

**Comment by abbra** [comment]
It looks like I've got to `ipa-server-install` successful execution now:
- switch to privileged container (`seccomp:unconfined`)
- mask `chronyd` in the container again (because of the privileged container use)
- pull in `dbus-daemon` and make sure D-BUS is ready and running

We need to handle firewalld differently now with privileged container (I'll push once all tests succeed/fail in this run).

I suspect we will also need to add `dbus-daemon` dependency globally too as https://tiny.distro.builders/workload--sst_identity_management-freeipa-server--fedora-empty-base--repository-fedora-eln--x86_64.html shows nothing else pulls it in. May be I should add it to `oddjob`?

**Comment by abbra** [comment]
Looks like client deployments are unable to connect to LDAP now (DNS works). More investigations are needed.

**Comment by stanislavlevin** [comment]
There is another failure in the same test suite test_integration/test_dnssec.py::TestInstallDNSSECFirst::test_chain_of_trust.

**Comment by abbra** [comment]
There seem to be some permissions issues in `/var/lib/dnssec/tokens`

**Comment by stanislavlevin** [comment]
These errors can be treated as warnings.

**Comment by abbra** [comment]
I spent some time yesterday and utilized by launchpad's account to rebuild `libseccomp` from Debian Sid on Ubuntu 20.04 in the PPA https://launchpad.net/~abbra/+archive/ubuntu/freeipa-libseccomp. The pull request now uses Ubuntu 20.04 images and this PPA to provide a working environment.  At least, tests start and installation of IPA masters in containers does work.

**Comment by abbra** [comment]
All test failures I saw so far were in inability to enroll the clients and one of openldap configuration tests. The latter might be due to some changes in openldap in Rawhide, we'll need to investigate but it is less urgent. ipa-client-install failures might be related to DNS infrastructure -- I am going to look at that today. Interestingly enough, environments with replicas do succeed in the replica deployments.

**Comment by abbra** [comment]
```
2020-11-17T07:00:06Z DEBUG [IPA Discovery]
2020-11-17T07:00:06Z DEBUG Starting IPA discovery with domain=ipa.test, servers=['master1.ipa.test'], hostname=client1.ipa.test
2020-11-17T07:00:06Z DEBUG Server and domain forced
2020-11-17T07:00:06Z DEBUG [Kerberos realm search]
2020-11-17T07:00:06Z DEBUG Kerberos realm forced
2020-11-17T07:00:06Z DEBUG [LDAP server check]
2020-11-17T07:00:06Z DEBUG Verifying that master1.ipa.test (realm IPA.TEST) is an IPA server
2020-11-17T07:00:06Z DEBUG Init LDAP connection to: ldap://master1.ipa.test:389
2020-11-17T07:00:06Z DEBUG LDAP Error: cannot connect to 'ldap://master1.ipa.test:389':
2020-11-17T07:00:06Z WARNING Skip master1.ipa.test: LDAP server is not responding, unable to verify if this is an IPA server
2020-11-17T07:00:06Z DEBUG Discovery result: NO_LDAP_SERVER; server=None, domain=ipa.test, kdc=master1.ipa.test, basedn=None
2020-11-17T07:00:06Z DEBUG Validated servers:
2020-11-17T07:00:06Z ERROR Failed to verify that master1.ipa.test is an IPA Server.
2020-11-17T07:00:06Z ERROR This may mean that the remote server is not up or is not reachable due to network or firewall settings.

```

**Comment by abbra** [comment]
@stanislavlevin could you please look at these client failures?

**Comment by abbra** [comment]
Looks like firewalld is malfunctioning on the master. Perhaps it is not running at all as dbus reports it is not registering any service it:
```
Nov 17 06:59:49 master1.ipa.test dbus-daemon[66]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.11" (uid=0 pid=738 comm="/usr/bin/python3 -s /usr/sbin/firewalld --nofork -" label="unconfined") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.ServiceUnknown" requested_reply="0" destination=":1.20" (uid=0 pid=4897 comm="/usr/bin/python3 -s /usr/bin/firewall-cmd --add-se" label="unconfined")
Nov 17 06:59:49 master1.ipa.test dbus-daemon[66]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.11" (uid=0 pid=738 comm="/usr/bin/python3 -s /usr/sbin/firewalld --nofork -" label="unconfined") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.ServiceUnknown" requested_reply="0" destination=":1.20" (uid=0 pid=4897 comm="/usr/bin/python3 -s /usr/bin/firewall-cmd --add-se" label="unconfined")
Nov 17 06:59:49 master1.ipa.test dbus-daemon[66]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.11" (uid=0 pid=738 comm="/usr/bin/python3 -s /usr/sbin/firewalld --nofork -" label="unconfined") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.ServiceUnknown" requested_reply="0" destination=":1.20" (uid=0 pid=4897 comm="/usr/bin/python3 -s /usr/bin/firewall-cmd --add-se" label="unconfined")
Nov 17 06:59:49 master1.ipa.test dbus-daemon[66]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.11" (uid=0 pid=738 comm="/usr/bin/python3 -s /usr/sbin/firewalld --nofork -" label="unconfined") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.ServiceUnknown" requested_reply="0" destination=":1.20" (uid=0 pid=4897 comm="/usr/bin/python3 -s /usr/bin/firewall-cmd --add-se" label="unconfined")
Nov 17 06:59:49 master1.ipa.test dbus-daemon[66]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.11" (uid=0 pid=738 comm="/usr/bin/python3 -s /usr/sbin/firewalld --nofork -" label="unconfined") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.ServiceUnknown" requested_reply="0" destination=":1.20" (uid=0 pid=4897 comm="/usr/bin/python3 -s /usr/bin/firewall-cmd --add-se" label="unconfined")
Nov 17 06:59:49 master1.ipa.test dbus-daemon[66]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.11" (uid=0 pid=738 comm="/usr/bin/python3 -s /usr/sbin/firewalld --nofork -" label="unconfined") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.ServiceUnknown" requested_reply="0" destination=":1.20" (uid=0 pid=4897 comm="/usr/bin/python3 -s /usr/bin/firewall-cmd --add-se" label="unconfined")
Nov 17 06:59:49 master1.ipa.test dbus-daemon[66]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.11" (uid=0 pid=738 comm="/usr/bin/python3 -s /usr/sbin/firewalld --nofork -" label="unconfined") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.ServiceUnknown" requested_reply="0" destination=":1.20" (uid=0 pid=4897 comm="/usr/bin/python3 -s /usr/bin/firewall-cmd --add-se" label="unconfined")
Nov 17 06:59:49 master1.ipa.test dbus-daemon[66]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.11" (uid=0 pid=738 comm="/usr/bin/python3 -s /usr/sbin/firewalld --nofork -" label="unconfined") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.ServiceUnknown" requested_reply="0" destination=":1.20" (uid=0 pid=4897 comm="/usr/bin/python3 -s /usr/bin/firewall-cmd --add-se" label="unconfined")
Nov 17 06:59:49 master1.ipa.test dbus-daemon[66]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.11" (uid=0 pid=738 comm="/usr/bin/python3 -s /usr/sbin/firewalld --nofork -" label="unconfined") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.ServiceUnknown" requested_reply="0" destination=":1.20" (uid=0 pid=4897 comm="/usr/bin/python3 -s /usr/bin/firewall-cmd --add-se" label="unconfined")
Nov 17 06:59:49 master1.ipa.test dbus-daemon[66]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.11" (uid=0 pid=738 comm="/usr/bin/python3 -s /usr/sbin/firewalld --nofork -" label="unconfined") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.ServiceUnknown" requested_reply="0" destination=":1.20" (uid=0 pid=4897 comm="/usr/bin/python3 -s /usr/bin/firewall-cmd --add-se" label="unconfined")
Nov 17 06:59:49 master1.ipa.test dbus-daemon[66]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.11" (uid=0 pid=738 comm="/usr/bin/python3 -s /usr/sbin/firewalld --nofork -" label="unconfined") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.ServiceUnknown" requested_reply="0" destination=":1.21" (uid=0 pid=4913 comm="/usr/bin/python3 -s /usr/bin/firewall-cmd --add-se" label="unconfined")
Nov 17 06:59:49 master1.ipa.test dbus-daemon[66]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.11" (uid=0 pid=738 comm="/usr/bin/python3 -s /usr/sbin/firewalld --nofork -" label="unconfined") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.ServiceUnknown" requested_reply="0" destination=":1.21" (uid=0 pid=4913 comm="/usr/bin/python3 -s /usr/bin/firewall-cmd --add-se" label="unconfined")
Nov 17 06:59:49 master1.ipa.test dbus-daemon[66]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.11" (uid=0 pid=738 comm="/usr/bin/python3 -s /usr/sbin/firewalld --nofork -" label="unconfined") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.ServiceUnknown" requested_reply="0" destination=":1.21" (uid=0 pid=4913 comm="/usr/bin/python3 -s /usr/bin/firewall-cmd --add-se" label="unconfined")
Nov 17 06:59:49 master1.ipa.test dbus-daemon[66]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.11" (uid=0 pid=738 comm="/usr/bin/python3 -s /usr/sbin/firewalld --nofork -" label="unconfined") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.ServiceUnknown" requested_reply="0" destination=":1.21" (uid=0 pid=4913 comm="/usr/bin/python3 -s /usr/bin/firewall-cmd --add-se" label="unconfined")
Nov 17 06:59:49 master1.ipa.test dbus-daemon[66]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.11" (uid=0 pid=738 comm="/usr/bin/python3 -s /usr/sbin/firewalld --nofork -" label="unconfined") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.ServiceUnknown" requested_reply="0" destination=":1.21" (uid=0 pid=4913 comm="/usr/bin/python3 -s /usr/bin/firewall-cmd --add-se" label="unconfined")
Nov 17 06:59:49 master1.ipa.test dbus-daemon[66]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.11" (uid=0 pid=738 comm="/usr/bin/python3 -s /usr/sbin/firewalld --nofork -" label="unconfined") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.ServiceUnknown" requested_reply="0" destination=":1.21" (uid=0 pid=4913 comm="/usr/bin/python3 -s /usr/bin/firewall-cmd --add-se" label="unconfined")
Nov 17 06:59:49 master1.ipa.test dbus-daemon[66]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.11" (uid=0 pid=738 comm="/usr/bin/python3 -s /usr/sbin/firewalld --nofork -" label="unconfined") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.ServiceUnknown" requested_reply="0" destination=":1.21" (uid=0 pid=4913 comm="/usr/bin/python3 -s /usr/bin/firewall-cmd --add-se" label="unconfined")
Nov 17 06:59:49 master1.ipa.test dbus-daemon[66]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.11" (uid=0 pid=738 comm="/usr/bin/python3 -s /usr/sbin/firewalld --nofork -" label="unconfined") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.ServiceUnknown" requested_reply="0" destination=":1.21" (uid=0 pid=4913 comm="/usr/bin/python3 -s /usr/bin/firewall-cmd --add-se" label="unconfined")
Nov 17 06:59:49 master1.ipa.test dbus-daemon[66]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.11" (uid=0 pid=738 comm="/usr/bin/python3 -s /usr/sbin/firewalld --nofork -" label="unconfined") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.ServiceUnknown" requested_reply="0" destination=":1.21" (uid=0 pid=4913 comm="/usr/bin/python3 -s /usr/bin/firewall-cmd --add-se" label="unconfined")
Nov 17 06:59:49 master1.ipa.test dbus-daemon[66]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.11" (uid=0 pid=738 comm="/usr/bin/python3 -s /usr/sbin/firewalld --nofork -" label="unconfined") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.ServiceUnknown" requested_reply="0" destination=":1.21" (uid=0 pid=4913 comm="/usr/bin/python3 -s /usr/bin/firewall-cmd --add-se" label="unconfined")
Nov 17 06:59:49 master1.ipa.test dbus-daemon[66]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.11" (uid=0 pid=738 comm="/usr/bin/python3 -s /usr/sbin/firewalld --nofork -" label="unconfined") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.ServiceUnknown" requested_reply="0" destination=":1.21" (uid=0 pid=4913 comm="/usr/bin/python3 -s /usr/bin/firewall-cmd --add-se" label="unconfined")
Nov 17 06:59:49 master1.ipa.test dbus-daemon[66]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.11" (uid=0 pid=738 comm="/usr/bin/python3 -s /usr/sbin/firewalld --nofork -" label="unconfined") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.ServiceUnknown" requested_reply="0" destination=":1.21" (uid=0 pid=4913 comm="/usr/bin/python3 -s /usr/bin/firewall-cmd --add-se" label="unconfined")
Nov 17 06:59:49 master1.ipa.test dbus-daemon[66]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.11" (uid=0 pid=738 comm="/usr/bin/python3 -s /usr/sbin/firewalld --nofork -" label="unconfined") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.ServiceUnknown" requested_reply="0" destination=":1.21" (uid=0 pid=4913 comm="/usr/bin/python3 -s /usr/bin/firewall-cmd --add-se" label="unconfined")

```

**Comment by stanislavlevin** [comment]
Let me check locally(downloading Docker image).

**Comment by abbra** [comment]
I tried on a private Azure CI instance with a simplified setup and still get it failing on the firewall part, so it looks like this is the core of our problem.

Set of changes required so far to make things working against Rawhide and ELN:
- use Ubuntu 20.04 as a host
- use PPA abbra/freeipa-libseccomp to get seccomp 2.5 to support faccessat2 system call
- mask chronyd
- install and enable dbus-daemon for both system and user sessions
- various compile fixes to comply with newer GCC

**Comment by stanislavlevin** [comment]
As I see Fedora moved from dbus-daemon to dbus-broker:
https://fedoraproject.org/wiki/Changes/DbusBrokerAsTheDefaultDbusImplementation

It works with:
```
systemctl enable --now dbus-broker
```
Why it is OFF, I don't know.

**Comment by stanislavlevin** [comment]
```
systemctl status firewalld --no-pager -l

Nov 17 09:41:35 8847cb17e4a7 systemd[1]: Starting firewalld - dynamic firewall daemon...
Nov 17 09:41:35 8847cb17e4a7 systemd[1]: Started firewalld - dynamic firewall daemon.
Nov 17 09:41:35 8847cb17e4a7 firewalld[114]: ERROR: 'python-nftables' failed: internal:0:0-0: Error: Could not process rule: No such file or directory
                                             
                                             
                                             JSON blob:
                                             {"nftables": [{"metainfo": {"json_schema_version": 1}}, {"add": {"chain": {"family": "inet", "table": "firewalld", "name": "raw_PREROUTING", "type

...
```

I'll check in details later today, sorry.

**Comment by abbra** [comment]
Yes, I reproduced the firewall issue locally in podman too.

**Comment by abbra** [comment]
Interesting that in a plain fedora:34 container without systemd, nftables Python bindings do work in non-privileged mode:
```
$ podman run -ti --security-opt seccomp=seccomp.json fedora:34 /bin/bash
Trying to pull registry.fedoraproject.org/fedora:34...
Getting image source signatures
Copying blob cf938ebbeb6c done  
Copying config 34c81631ce done  
Writing manifest to image destination
Storing signatures
[root@9c478b18a2d1 /]# dnf install python3-nftables nftables
Fedora 34 openh264 (From Cisco) - x86_64                                                                                                                                                                                      2.3 kB/s | 2.5 kB     00:01    
Fedora - Modular Rawhide - Developmental packages for the next Fedora release                                                                                                                                                 4.0 MB/s | 4.1 MB     00:01    
Fedora - Rawhide - Developmental packages for the next Fedora release                                                                                                                                                         7.6 MB/s |  73 MB     00:09    
Dependencies resolved.
==============================================================================================================================================================================================================================================================
 Package                                                                Architecture                                           Version                                                          Repository                                               Size
==============================================================================================================================================================================================================================================================
Installing:
 nftables                                                               x86_64                                                 1:0.9.7-1.fc34                                                   rawhide                                                 355 k
 python3-nftables                                                       x86_64                                                 1:0.9.7-1.fc34                                                   rawhide                                                  17 k
Installing dependencies:
 iptables-libs                                                          x86_64                                                 1.8.6-2.fc34                                                     rawhide                                                 367 k
 jansson                                                                x86_64                                                 2.13.1-1.fc34                                                    rawhide                                                  45 k
 libibverbs-core                                                        x86_64                                                 32.0-1.fc34                                                      rawhide                                                  72 k
 libmnl                                                                 x86_64                                                 1.0.4-12.fc33                                                    rawhide                                                  28 k
 libnetfilter_conntrack                                                 x86_64                                                 1.0.7-5.fc33                                                     rawhide                                                  62 k
 libnfnetlink                                                           x86_64                                                 1.0.1-18.fc33                                                    rawhide                                                  29 k
 libnftnl                                                               x86_64                                                 1.1.8-1.fc34                                                     rawhide                                                  82 k
 libnl3                                                                 x86_64                                                 3.5.0-5.fc33                                                     rawhide                                                 325 k
 libpcap                                                                x86_64                                                 14:1.9.1-6.fc34                                                  rawhide                                                 173 k

Transaction Summary
==============================================================================================================================================================================================================================================================
Install  11 Packages

Total download size: 1.5 M
Installed size: 4.8 M
Is this ok [y/N]: y
Downloading Packages:
(1/11): libibverbs-core-32.0-1.fc34.x86_64.rpm                                                                                                                                                                                843 kB/s |  72 kB     00:00    
(2/11): jansson-2.13.1-1.fc34.x86_64.rpm                                                                                                                                                                                      493 kB/s |  45 kB     00:00    
(3/11): libmnl-1.0.4-12.fc33.x86_64.rpm                                                                                                                                                                                       892 kB/s |  28 kB     00:00    
(4/11): iptables-libs-1.8.6-2.fc34.x86_64.rpm                                                                                                                                                                                 2.5 MB/s | 367 kB     00:00    
(5/11): libnetfilter_conntrack-1.0.7-5.fc33.x86_64.rpm                                                                                                                                                                        1.2 MB/s |  62 kB     00:00    
(6/11): libnfnetlink-1.0.1-18.fc33.x86_64.rpm                                                                                                                                                                                 1.2 MB/s |  29 kB     00:00    
(7/11): libnftnl-1.1.8-1.fc34.x86_64.rpm                                                                                                                                                                                      2.8 MB/s |  82 kB     00:00    
(8/11): libpcap-1.9.1-6.fc34.x86_64.rpm                                                                                                                                                                                       1.5 MB/s | 173 kB     00:00    
(9/11): libnl3-3.5.0-5.fc33.x86_64.rpm                                                                                                                                                                                        2.4 MB/s | 325 kB     00:00    
(10/11): nftables-0.9.7-1.fc34.x86_64.rpm                                                                                                                                                                                     2.8 MB/s | 355 kB     00:00    
(11/11): python3-nftables-0.9.7-1.fc34.x86_64.rpm                                                                                                                                                                             460 kB/s |  17 kB     00:00    
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                                                                         1.9 MB/s | 1.5 MB     00:00     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                                                                                      1/1 
  Installing       : libmnl-1.0.4-12.fc33.x86_64                                                                                                                                                                                                         1/11 
  Installing       : libnftnl-1.1.8-1.fc34.x86_64                                                                                                                                                                                                        2/11 
  Installing       : libnl3-3.5.0-5.fc33.x86_64                                                                                                                                                                                                          3/11 
  Installing       : libibverbs-core-32.0-1.fc34.x86_64                                                                                                                                                                                                  4/11 
  Installing       : libpcap-14:1.9.1-6.fc34.x86_64                                                                                                                                                                                                      5/11 
  Installing       : libnfnetlink-1.0.1-18.fc33.x86_64                                                                                                                                                                                                   6/11 
  Installing       : libnetfilter_conntrack-1.0.7-5.fc33.x86_64                                                                                                                                                                                          7/11 
  Installing       : iptables-libs-1.8.6-2.fc34.x86_64                                                                                                                                                                                                   8/11 
  Installing       : jansson-2.13.1-1.fc34.x86_64                                                                                                                                                                                                        9/11 
  Installing       : nftables-1:0.9.7-1.fc34.x86_64                                                                                                                                                                                                     10/11 
  Running scriptlet: nftables-1:0.9.7-1.fc34.x86_64                                                                                                                                                                                                     10/11 
  Installing       : python3-nftables-1:0.9.7-1.fc34.x86_64                                                                                                                                                                                             11/11 
  Running scriptlet: python3-nftables-1:0.9.7-1.fc34.x86_64                                                                                                                                                                                             11/11 
  Verifying        : iptables-libs-1.8.6-2.fc34.x86_64                                                                                                                                                                                                   1/11 
  Verifying        : jansson-2.13.1-1.fc34.x86_64                                                                                                                                                                                                        2/11 
  Verifying        : libibverbs-core-32.0-1.fc34.x86_64                                                                                                                                                                                                  3/11 
  Verifying        : libmnl-1.0.4-12.fc33.x86_64                                                                                                                                                                                                         4/11 
  Verifying        : libnetfilter_conntrack-1.0.7-5.fc33.x86_64                                                                                                                                                                                          5/11 
  Verifying        : libnfnetlink-1.0.1-18.fc33.x86_64                                                                                                                                                                                                   6/11 
  Verifying        : libnftnl-1.1.8-1.fc34.x86_64                                                                                                                                                                                                        7/11 
  Verifying        : libnl3-3.5.0-5.fc33.x86_64                                                                                                                                                                                                          8/11 
  Verifying        : libpcap-14:1.9.1-6.fc34.x86_64                                                                                                                                                                                                      9/11 
  Verifying        : nftables-1:0.9.7-1.fc34.x86_64                                                                                                                                                                                                     10/11 
  Verifying        : python3-nftables-1:0.9.7-1.fc34.x86_64                                                                                                                                                                                             11/11 

Installed:
  iptables-libs-1.8.6-2.fc34.x86_64  jansson-2.13.1-1.fc34.x86_64    libibverbs-core-32.0-1.fc34.x86_64  libmnl-1.0.4-12.fc33.x86_64             libnetfilter_conntrack-1.0.7-5.fc33.x86_64  libnfnetlink-1.0.1-18.fc33.x86_64  libnftnl-1.1.8-1.fc34.x86_64 
  libnl3-3.5.0-5.fc33.x86_64         libpcap-14:1.9.1-6.fc34.x86_64  nftables-1:0.9.7-1.fc34.x86_64      python3-nftables-1:0.9.7-1.fc34.x86_64 

Complete!
[root@9c478b18a2d1 /]# echo <<END >t.py
> from nftables import nftables
> 
> t_json = {"nftables": [{"metainfo": {"json_schema_version": 1}}, {"add": {"table": {"family": "inet", "name": "firewalld"}}}, {"add": {"table": {"family": "ip", "name": "firewalld"}}}, {"add": {"table": {"family": "ip6", "name": "firewalld"}}}]}
> 
> t = nftables.Nftables()
> t.set_echo_output(True)
> t.set_handle_output(True)
> ret = t.json_cmd(t_json)
> print(ret)
> 
> END
[root@9c478b18a2d1 /]# python3 t.py
[root@9c478b18a2d1 /]# echo $?
0
[root@9c478b18a2d1 /]# 
```

The same test script fails in our Azure container:
```
[root@706740e7992c ~]# cat t.py 
from nftables import nftables

t_json = {"nftables": [{"metainfo": {"json_schema_version": 1}}, {"add": {"table": {"family": "inet", "name": "firewalld"}}}, {"add": {"table": {"family": "ip", "name": "firewalld"}}}, {"add": {"table": {"family": "ip6", "name": "firewalld"}}}]}

t = nftables.Nftables()
t.set_echo_output(True)
t.set_handle_output(True)
ret = t.json_cmd(t_json)
print(ret)

[root@706740e7992c ~]# python3 t.py
(-1, '', 'internal:0:0-0: Error: Could not process rule: Operation not permitted\n\ninternal:0:0-0: Error: Could not process rule: Operation not permitted\n\ninternal:0:0-0: Error: Could not process rule: Operation not permitted\n\n')
[root@706740e7992c ~]# echo $?
0

```

**Comment by stanislavlevin** [comment]
To go ahead I switched  `firewalld` to `iptables` mode.

This is debugging from the client:
1) trying to resolve ipa server - failed
```
getent ahosts master1.ipa.test
... can't resolve
```
2) name service switch order for `hosts`

no master - is OK, relying on DNS
```
cat /etc/hosts 
127.0.0.1 localhost
::1 localhost
172.19.0.3 client1.ipa.test
```

next is `systemd-resolved`
```
grep 'hosts:' /etc/nsswitch.conf
hosts:      files resolve [!UNAVAIL=return] myhostname dn
```
3) According to docs:
https://www.freedesktop.org/software/systemd/man/systemd-resolved.service.html#/etc/resolv.conf

our case is 4(managed by other packages)
```
cat /etc/resolv.conf 
nameserver 172.19.0.2
```
seems to be OK, but
```
resolvectl status
Global
       LLMNR setting: resolve             
MulticastDNS setting: no                  
  DNSOverTLS setting: no                  
      DNSSEC setting: no                  
    DNSSEC supported: no                  
  Current DNS Server: 127.0.0.11          
         DNS Servers: 127.0.0.11          
Fallback DNS Servers: 1.1.1.1             
                      8.8.8.8             
                      1.0.0.1             
                      8.8.4.4             
                      2606:4700:4700::1111
                      2001:4860:4860::8888
                      2606:4700:4700::1001
                      2001:4860:4860::8844
```
`127.0.0.11` is embedded NS of docker-compose.

4) So, on startup `systemd-resolved` caches the `/etc/resolv.conf`(docker-compose version), which is later changed by `setup_containers.py` script. It would be enough, for example,
```
systemctl restart systemd-resolved
```
to re-read `resolv.conf`.

**Comment by abbra** [comment]
Ok, thanks. So you are proposing to do following changes:
- switch firewalld to use iptables backend
- add restart of systemd-resolved to `setup_containers.py`?

Right?

**Comment by stanislavlevin** [comment]
> Ok, thanks. So you are proposing to do following changes:
> 
>     * switch firewalld to use iptables backend
> 
>     * add restart of systemd-resolved to `setup_containers.py`?
> 
> 
> Right?

Exactly.
```diff
--- a/ipatests/azure/scripts/setup_containers.py
+++ b/ipatests/azure/scripts/setup_containers.py
@@ -175,6 +175,12 @@ class Container:
             "echo {ns} > /etc/resolv.conf".format(ns=ns),
         ]
         self.execute_all(cmd)
+        cmd = [
+            "systemctl",
+            "try-restart",
+            "systemd-resolved"
+        ]
+        self.execute_all(cmd)
```

As for `firewalld` is a temporary workaround(may be added either in Dockerfile or setup_containers.py).

**Comment by stanislavlevin** [comment]
At least, I get `test_kerberos_flags` passed.

**Pull request closed without merging**
