### PR TITLE
[ipa-4-6] ipatests: backport tasks.ldapsearch_dm

### PR DESCRIPTION
**Pull request by flo-renaud**
This method is needed by the backport fix for
TestOTPToken::test_check_otpd_after_idle_timeout

Related: https://pagure.io/freeipa/issue/9044

### CODE REVIEW

**Comment by ssidhaye** [comment]
The changes look good to me

**Comment by flo-renaud** [comment]
For future ref, link to the successful run of `fedora-27/test_otp`: [Details](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/81c67426-2cf7-11ed-adb9-fa163eda45c5)

Removing temp commit.

**Comment by flo-renaud** [comment]
Adding ACK based on @ssidhaye comment.

**Comment by flo-renaud** [comment]
ipa-4-6:

* 4f7ea06093886bf55fea72630729e77273197211 ipatests: backport tasks.ldapsearch_dm

**Pull request closed without merging**
