### PR TITLE
[Backport][ipa-4-6] webui tests: fix test_host:test_crud failure

### PR DESCRIPTION
**Pull request by tiran**
This PR was opened automatically because PR #1737 was pushed to master and backport to ipa-4-6 is required.

### CODE REVIEW

**Comment by tiran** [comment]
PR was ACKed automatically because this is backport of PR #1737. Wait for CI to finish before pushing. In case of questions or problems contact @pvoborni who is author of the original PR.

**Comment by tiran** [comment]
@pvoborni The backport is failing with ``ipatests/test_webui/ui_driver.py:1351: [E1101(no-member), UI_driver.basic_crud] Instance of 'UI_driver' has no 'close_notifications' member)``

**Comment by pvoborni** [comment]
Backport PR #1765 was created to deliver the missing functionality to 4-6 branch.

**Comment by Tiboris** [comment]
ipa-4-6:

* ce274f73f1e1121718beb34e22fa2148df492a55 webui tests: fix test_host:test_crud failure

**Pull request closed without merging**
