### PR TITLE
Upgrade HTTPd's alias db to SQL

### PR DESCRIPTION
**Pull request by tiran**
https://pagure.io/freeipa/issue/7354

Signed-off-by: Christian Heimes <cheimes@redhat.com>

### CODE REVIEW

**Comment by rcritten** [comment]
Can you expand on the ticket and/or the commit message?

As I understand it this will have a very narrow focus: F-28 only until 4.7 ships and we switch to mod_ssl as the default crypto engine. So this really just applies to the ipa-4-6 branch right?

If not then this needs to be enhanced to recognize that the mod_ssl conversion is already done and not try to migrate the database.

**Comment by rcritten** [comment]
The installation failed for me. Server-Cert was added to cert9.db but cert8.db still exists and the installer tries to look there for the cert.

The certmonger tracking doesn't explicitly have the NSS database directory prefix, not sure if that is on purpose or not.

**Comment by rcritten** [comment]
Is this patch still needed since 4.6.0.pre1 was released to F28?

**Comment by tiran** [comment]
After a brief internal discussion with @rcritten, I decided to close and reject this PR. The update from F27 / FreeIPA 4.6 to F28 / FreeIPA 4.7 is working without this patch. Let's not complicate the code and add another potential source of regression.

**Pull request closed without merging**
