### PR TITLE
ipaplatform: add opencloudos/tencentos support

### PR DESCRIPTION
**Pull request by ZoeDong**
Fixes:https://pagure.io/freeipa/issue/9501

This PR provides support for opencloudos/tencentos

### CODE REVIEW

**Comment by rcritten** [comment]
You don't need to copy whole files. See nixos as a minimalist example. Class inheritance should cover most of the code.

**Comment by flo-renaud** [comment]
PR #7090 has been merged on the master branch and should fix the tox issue. Please rebase on top of the master branch to pull in the changes

**Comment by ZoeDong** [comment]
@rcritten @flo-renaud  I have completed the rebase and get all green. Please review and let me know if any further adjustments are needed.

**Comment by rcritten** [comment]
I'm inclined to merge this. Do you need it backported to an older branch, say ipa-4-11? I'm not sure what release these OS's are using.

**Comment by ZoeDong** [comment]
Yes, I would appreciate it if you could backport the changes to ipa-4-9, ipa-4-10, and ipa-4-11 branches.

**Comment by rcritten** [comment]
master:

* 2c0fe1dd924b428eef1fcc4ebf209a1f0dfe3de1 ipaplatform: add opencloudos/tencentos support

**Pull request closed without merging**
