### PR TITLE
Fix javascript 'errors' found by jslint

### PR DESCRIPTION
**Pull request by stanislavlevin**
There are several JavaScript errors, which have come with PRs:
#2362, #2371, #2372.

JavaScript code have to follow jsl requires.

Fixes: https://pagure.io/freeipa/issue/7718

### CODE REVIEW

**Comment by tiran** [comment]
Could you please combine this PR with #2397?

**Comment by stanislavlevin** [comment]
Yes, of course, you are right. Let me recheck locally and I'll merge it.

**Comment by stanislavlevin** [comment]
Done.

**Comment by tiran** [comment]
@serg-cymbaluk Thanks, good work!

**Comment by tiran** [comment]
master:

* 54765474167f70f6ac09c8a41dea7a242b34ff7e Fix javascript 'errors' found by jslint
* 54a0e9e96dc42c9d67e058f8c24de05141129467 Add jslint check to PR CI tests

**Pull request closed without merging**
