### PR TITLE
Issue 8407 - Support changelog integration into main database

### PR DESCRIPTION
**Pull request by marcus2376**
Description: Add support for both the old and new replication changelogs.
             First try to get and update the new entry, if it's not found
             then we know we need to update the old global changelog entry.

https://pagure.io/freeipa/issue/8407

Reviewed by: ?

### CODE REVIEW

**Comment by marcus2376** [comment]
I was not able to do an extensive testing besides a ipa-server-install.  We just need to sanity check that replication still works, and it should also be tested against this 389-ds-base build:  https://copr.fedorainfracloud.org/coprs/build/1567068

**Comment by abbra** [comment]
@marcus2376 thank you for the PR. It looks good and I have just few comments about markup, not the code:

- Please remove `Reviewed-by: ?` from the commit message, it will be added automatically by a script that will be used to push the PR
- Please add `Signed-off-by: name <email>` for yourself
- Please replace the long copyright header by a shorter one:
```
#
# Copyright (C) 2020  FreeIPA Contributors see COPYING for license
#
```

**Comment by marcus2376** [comment]
@abbra thanks for the review, changes made!

**Comment by abbra** [comment]
@marcus2376 thanks. Sorry, I forgot one more: we use `Fixes: <url>`, not just the `<url>`. This is used by the commit tools.

**Comment by marcus2376** [comment]
Added "Fixed", we use that too in DS/Pagure, but I wasn't sure about IPA so I skipped it.  Good to know for next time.

**Comment by abbra** [comment]
master:

* 44259e8e68582e7116f8d5bee6e2c454254de69f Issue 8407 - Support changelog integration into main database

**Pull request closed without merging**
