### PR TITLE
ipa-migrate - fix alternate entry search filter

### PR DESCRIPTION
**Pull request by mreynolds389**
Processing a filter like a DN can cause normalization issues that result in an invalid filter. Make sure the filter is encapsulated with parenthesis and we call replace_suffix_value() instead of replace_suffix()

Fixes: https://pagure.io/freeipa/issue/9658

### CODE REVIEW

**Comment by flo-renaud** [comment]
Hi @mreynolds389 
can you add a temp commit that runs the test `test_integration/test_ipa_ipa_migration.py`? You can cherry-pick the commit from this PR: https://github.com/freeipa/freeipa/pull/7475/commits/7b490da556a2fafdd0956364f06cfdc0dc8c8bd7

**Comment by flo-renaud** [comment]
Hi @mreynolds389 
the test is failing in test_ipa_migrate_stage_mode because the expected message is wrong:
```
        IPA_UPGRADE_LOG_MSG = (
            "Running ipa-server-upgrade ... (this make take a while)\n"
        )
```
There is a typo "this MAKE take" instead of "this may take"

**Comment by mreynolds389** [comment]
> Hi @mreynolds389 the test is failing in test_ipa_migrate_stage_mode because the expected message is wrong:
> 
> ```
>         IPA_UPGRADE_LOG_MSG = (
>             "Running ipa-server-upgrade ... (this make take a while)\n"
>         )
> ```
> 
> There is a typo "this MAKE take" instead of "this may take"

Fixed the typo in the test...

**Comment by rcritten** [comment]
There is a traceback in test_integration/test_ipa_ipa_migration.py::TestIPAMigrateScenario1::test_ipa_migrate_subtree_option

**Comment by flo-renaud** [comment]
@mreynolds389 
thanks for the patch, works for me. Tested with the following scenario:
1. install server1: `ipa-server-install --domain ipa.test --realm IPA.TEST --setup-dns --auto-forwarders -a Secret123 -p Secret123 -U`
2. create user and subid range for the new user on server1: `echo Secret123| kinit admin; ipa user-add testuser1 --first test --last user1; ipa subid-generate --owner=testuser1`
3. install server2: `ipa-server-install --domain ipa.test --realm IPA.TEST --setup-dns --forwarder 10.11.5.160 -a Secret123 -p Secret123 -U`
4. migrate data from server1 to server2: `ipa-migrate prod-mode oldserver.ipa.test -D "cn=directory manager" -w Secret123 -x`

Without the patch, the migration fails:
```
# ipa-migrate prod-mode oldserver.ipa.test -D "cn=directory manager" -w Secret123 -x
Initializing ...
Connecting to local server ...
IPA to IPA migration starting ...
Migrating schema ...
Migrating configuration ...
Migrating database ... (this may take a while)
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/ipapython/ipaldap.py", line 1096, in error_handler
    yield
  File "/usr/lib/python3.12/site-packages/ipapython/ipaldap.py", line 1608, in find_entries
    raise e
  File "/usr/lib/python3.12/site-packages/ipapython/ipaldap.py", line 1562, in find_entries
    id = self.conn.search_ext(
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/ldap/ldapobject.py", line 614, in search_ext
    return self._ldap_call(
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/ldap/ldapobject.py", line 128, in _ldap_call
    result = func(*args,**kwargs)
             ^^^^^^^^^^^^^^^^^^^^
ldap.FILTER_ERROR: {'result': -7, 'desc': 'Bad search filter', 'ctrls': [], 'matched': 'cn=groups,cn=accounts,dc=ipa,dc=test'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/sbin/ipa-migrate", line 10, in <module>
    ipa_migrate.run()
  File "/usr/lib/python3.12/site-packages/ipaserver/install/ipa_migrate.py", line 2147, in run
    self.do_migration()
  File "/usr/lib/python3.12/site-packages/ipaserver/install/ipa_migrate.py", line 2034, in do_migration
    self.migrateDB()
  File "/usr/lib/python3.12/site-packages/ipaserver/install/ipa_migrate.py", line 1672, in migrateDB
    self.processDBOnline()
  File "/usr/lib/python3.12/site-packages/ipaserver/install/ipa_migrate.py", line 1639, in processDBOnline
    self.process_db_entry(entry_dn, entry_attrs)
  File "/usr/lib/python3.12/site-packages/ipaserver/install/ipa_migrate.py", line 1499, in process_db_entry
    entries = self.local_conn.get_entries(DN(srch_base),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ipapython/ipaldap.py", line 1474, in get_entries
    entries, truncated = self.find_entries(
                         ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ipapython/ipaldap.py", line 1548, in find_entries
    with self.error_handler():
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/usr/lib/python3.12/site-packages/ipapython/ipaldap.py", line 1145, in error_handler
    raise errors.BadSearchFilter(info=info)
ipalib.errors.BadSearchFilter: Bad search filter
```

With the patch, the migration succeeds:
```
# ipa-migrate prod-mode oldserver.ipa.test -D "cn=directory manager" -w Secret123 -x
Initializing ...
Connecting to local server ...
IPA to IPA migration starting ...
Migrating schema ...
Migrating configuration ...
Migrating database ... (this may take a while)
Processed 509 entries.
Running ipa-server-upgrade ... (this may take a while)
Skipping ipa-server-upgrade in dryrun mode.
Running SIDGEN task ...
Skipping SIDGEN task in dryrun mode.
Migration complete!

Dry Run Summary:
===============================================================================

General Information
-------------------
 - Remote Host:             oldserver.ipa.test
 - Migration Duration:      0:00:03
 - Migration Log:           /var/log/ipa-migrate.log
 - Remote Host:             oldserver.ipa.test
 - Remote Domain:           ipa.test
 - Local Host:              newserver.ipa.test
 - Local Domain:            ipa.test
 - Remote Suffix:           dc=ipa,dc=test
 - Local Suffix:            dc=ipa,dc=test
 - Remote Realm:            IPA.TEST
 - Local Realm:             IPA.TEST
 - Schema Analyzed:         1882 definitions
 - Config Analyzed:         2 entries
 - Database Anaylzed:       509 entries

Schema Migration (migrated 0 definitions)
-----------------------------------------
 - Attributes:              0
 - Objectclasses:           0

DS Configuration Migration (migrated 2 entries)
-----------------------------------------------
 - DNA Plugin:              2

Database Migration (migrated 11 entries)
----------------------------------------
 - DNA Ranges:              1
 - Sysaccounts:             1
 - Admin:                   1
 - Users:                   1
 - Groups:                  5
 - Sub IDs:                 1
 - AD:                      1

Action Items (3 items)
----------------------
 - You will have to manually migrate IDM related configuration files.  Here are some, but not all, of the configuration files to look into:
    - /etc/ipa/*
    - /etc/sssd/sssd.conf
    - /etc/named.conf
    - /etc/named/*
    - ...
 - SSSD should be restarted after a successful migration
 - The admin password is not migrated from the remote server. Reset it manually if needed.
===============================================================================
```

You can remove the temp commit

**Comment by flo-renaud** [comment]
master:

* b98b4a886ee0a75c7cf2c1650e4a0c8a699ac808 ipa-migrate - fix alternate entry search filter

**Pull request closed without merging**
