### PR TITLE
Allow Apache user to access SSSD IFP for smart card auth

### PR DESCRIPTION
**Pull request by tiran**
* Remove dead code 
* Allow HTTPd user to access SSSD IFP
* Smart card auth advise: Allow Apache user
* Add tests for both smart card advise scripts
* Refactor installation to work with dnf

See: https://pagure.io/freeipa/issue/7751

### CODE REVIEW

**Comment by tiran** [comment]
re-run, OOM killer killed Dogtag

**Comment by tiran** [comment]
@rcritten Please take a look. The ``ipa-certupdate`` command has timed out again in job http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/16da78cc-f19d-11e8-8397-fa163ed5deab/ The certificate ``type=NSSDB,location='/etc/pki/pki-tomcat/alias',nickname='caSigningCert cert-pki-ca',token='NSS Certificate DB'`` is in ``status: SUBMITTING``. All remaining certs are in ``status: MONITORING``

**Comment by rcritten** [comment]
I don't understand the purpose of the re-issuance at all. AFAICT it just forces it to reload itself in this case. @frasertweedale do you know why this is done in ipaclient/install/ipa_certupdate.py::update_server()?

Unfortunately the journal has nothing from certmonger on what it did or why it is stuck in SUBMITTING. And if it really is just re-using the old cert I'd think this would be pretty quick.

This may be a coincidence but it looks like dhclient renews the IP address right before the failure is recorded.

**Comment by frasertweedale** [comment]
@rcritten et al: there will be no conflicts so before it falls off my radar, I added that doc and here's the PR: https://github.com/freeipa/freeipa/pull/2622.

**Comment by abbra** [comment]
I think we can merge this pull request. Tests are green and all the other comments were addressed.

**Comment by tiran** [comment]
master:

* d6fd2ad4f2f0a95740bf73819260f49b216e6b78 Remove dead code
* 917d81b83259ef8f4f21fda7dfeb4d32eac61f5f Allow HTTPd user to access SSSD IFP
* 0a2222ea26386edd7c4472d4da073fcec0375203 Smart card auth advise: Allow Apache user
* a86abd37e96d56e9be8d551042b449a8ba058da8 Log stderr in run_command
* f0e11dac2d0164d6fdd6947deb6d45a09b03b10d Test smart card advise scripts
* f330c59dd8946b649c0d44c17d86bce2b836e993 Add install/remove package helpers to advise

**Pull request closed without merging**
