### PR TITLE
Fixed incorrect sequence of method calls in tasks.py

### PR DESCRIPTION
**Pull request by ofayans**
https://fedorahosted.org/freeipa/ticket/6255

### CODE REVIEW

**Comment by mbasti-rh** [comment]
NACK
```
[Thu Aug 25 13:31:13.597940 2016] [wsgi:error] [pid 130658] Traceback (most recent call last):
[Thu Aug 25 13:31:13.597945 2016] [wsgi:error] [pid 130658]   File "/usr/lib/python2.7/site-packages/ipaserver/rpcserver.py", line 352, in wsgi_execute
[Thu Aug 25 13:31:13.597949 2016] [wsgi:error] [pid 130658]     result = self.Command[name](*args, **options)
[Thu Aug 25 13:31:13.597952 2016] [wsgi:error] [pid 130658]   File "/usr/lib/python2.7/site-packages/ipalib/frontend.py", line 449, in __call__
[Thu Aug 25 13:31:13.597955 2016] [wsgi:error] [pid 130658]     return self.__do_call(*args, **options)
[Thu Aug 25 13:31:13.597959 2016] [wsgi:error] [pid 130658]   File "/usr/lib/python2.7/site-packages/ipalib/frontend.py", line 477, in __do_call
[Thu Aug 25 13:31:13.597967 2016] [wsgi:error] [pid 130658]     ret = self.run(*args, **options)
[Thu Aug 25 13:31:13.597971 2016] [wsgi:error] [pid 130658]   File "/usr/lib/python2.7/site-packages/ipalib/frontend.py", line 799, in run
[Thu Aug 25 13:31:13.597974 2016] [wsgi:error] [pid 130658]     return self.execute(*args, **options)
[Thu Aug 25 13:31:13.597978 2016] [wsgi:error] [pid 130658]   File "/usr/lib/python2.7/site-packages/ipaserver/plugins/cert.py", line 629, in execute
[Thu Aug 25 13:31:13.597981 2016] [wsgi:error] [pid 130658]     result['cacn'] = ca_obj['cacn'][0]
[Thu Aug 25 13:31:13.597984 2016] [wsgi:error] [pid 130658] KeyError: 'cacn'
```

**Comment by mbasti-rh** [comment]
Please update tests

**Comment by ofayans** [comment]
@mbasti-rh, are these things related?

**Comment by mbasti-rh** [comment]
Sorry I commented wrong PR :D

**Comment by mbasti-rh** [comment]
This is still ACK

**Comment by mbasti-rh** [comment]
Fixed upstream
master:
https://fedorahosted.org/freeipa/changeset/fbc9179970ce30ba8c121a3d60b9550ef8f9c06c

**Comment by mbasti-rh** [comment]
@ofayans This is just mirror repo of fedorahosted , we cannot merge commits here, it has no effect.

**Comment by ofayans** [comment]
@mbasti-rh oh, I see. Thanks!

**Pull request merged**
