### PR TITLE
[Backport][ipa-4-6] ipatests: add test for sssd behavior with disabled trustdomains

### PR DESCRIPTION
**Pull request by wladich**
This is a manual backport of #3924

### CODE REVIEW

**Comment by flo-renaud** [comment]
Hi @wladich 
the backport needs to be adapted, there are pylint errors:
```
************* Module ipatests.test_integration.test_sssd

ipatests/test_integration/test_sssd.py:56: [E1101(no-member), TestSSSDWithAdTrust.install] Class 'TestSSSDWithAdTrust' has no 'ads' member; maybe 'ad'?)

ipatests/test_integration/test_sssd.py:57: [E1101(no-member), TestSSSDWithAdTrust.install] Class 'TestSSSDWithAdTrust' has no 'ad_subdomains' member)

ipatests/test_integration/test_sssd.py:70: [E1101(no-member), TestSSSDWithAdTrust.install] Class 'TestSSSDWithAdTrust' has no 'intermed_user' member)
```

**Comment by wladich** [comment]
Thank you @flo-renaud for the notice
Also the temp commit was missing.

**Comment by wladich** [comment]
test_ssd is [green](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/3915a186-75b4-11ea-9465-fa163e7f018b/report.html).
Removing temp commit

**Comment by wladich** [comment]
ACKing the PR as it is a backport

**Comment by wladich** [comment]
ipa-4-6:

* b2b070390d3515d206b49c7577db443f3ad604dd ipatests: add test for sssd behavior with disabled trustdomains
* 98297e6b5d004d783c3d2098886983abeb9c2213 update prci definitions for test_sssd.py
* 6e53b8799bb6a7ecb40fe0e8268a8a21629e64a5 ipatests: add utility for getting sssd version on remote host
* 08cfa52c05bd93d53cbdf1b9566f15b8684a3055 ipatests: add context manager for declaring part of test as xfail
* 73dfe1489a35121dbda31bcc533d5424b79cc3cd ipatests: mark test_trustdomain_disable test as expectedly failing

**Pull request closed without merging**
