### PR TITLE
WebUI: Remove offline version of WebUI

### PR DESCRIPTION
**Pull request by pvomacka**
Remove all json files which were used for testing WebUI offline and are no more useful. Also removes all lines in other files/scripts which refer to the offline version of WebUI.

https://pagure.io/freeipa/issue/6447

### CODE REVIEW

**Comment by pvomacka** [comment]
Self-NACK, build fails.

**Comment by pvomacka** [comment]
I returned back test files and removed only JSON files. I also created ticket which proposes fixing WebUI unit tests, as you mentioned. https://pagure.io/freeipa/issue/6974

**Comment by stlaz** [comment]
From what I've heard from @pvomacka, a rebase could solve the jslint error. If you guys could kindly rebase + review so that we can close this as it blocks https://github.com/freeipa/freeipa/issues/907.

**Comment by pvomacka** [comment]
master:

* 6ad92d3a4f0a4e9af0124fe457d2a3c646f15710 Revert "Web UI: Remove offline version of Web UI"
* 41a18bbbc8793335daa0583bddb2f8c775d2b6a2 Remove all old JSON files
* 0ee7db75e45573a8f16a3776c3e0d862b685c15c WebUI: Remove plugins symlink as it is unused
* 4eb37d7436bcb90991f56cd7e1cf75fa2d34fa22 WebUI: remove creating js/libs symlink from makefile

**Pull request closed without merging**
