### PR TITLE
ipatests: Bump PR-CI templates

### PR DESCRIPTION
**Pull request by netoarmando**
New templates with a previously working version of `geckodriver`.

Issue: https://pagure.io/freeipa/issue/8473

Signed-off-by: Armando Neto <abiagion@redhat.com>

### CODE REVIEW

**Comment by flo-renaud** [comment]
The change lGTM but could you add a temp commit that launches the webui tests?

**Comment by netoarmando** [comment]
> The change lGTM but could you add a temp commit that launches the webui tests?

Sure!

**Comment by flo-renaud** [comment]
The webui tests are green, you can remove the temp commit and I will ack

**Comment by flo-renaud** [comment]
master:

* 21186540f0425840e544a3cead8da909744aeac0 ipatests: Bump PR-CI templates

**Pull request closed without merging**
