### PR TITLE
Create IPA ssh client configuration and move ProxyCommand

### PR DESCRIPTION
**Pull request by rcritten**
Create IPA ssh client configuration and move ProxyCommand

The ProxyCommand is non-executable if the user does not have
a valid shell (like /sbin/nologin) so skip it in that case.

https://pagure.io/freeipa/issue/7676

Signed-off-by: Rob Crittenden <rcritten@redhat.com>

### CODE REVIEW

**Comment by abbra** [comment]
LGTM, please remove the temp commit.

**Comment by rcritten** [comment]
Removed temp commit and rebased

**Comment by rcritten** [comment]
Corrected test topology to master_1repl_1client for test_commands.

**Comment by flo-renaud** [comment]
master:

* 15b30e15a42b8adbbd4cf718e43406941e475db8 Create IPA ssh client configuration and move ProxyCommand
* 16616e576d6a2e52a9967a3a55a676dba56c6a77 ipatests: Test that Match ProxyCommand masks on no shell exec

**Comment by flo-renaud** [comment]
@rcritten a manual backport is needed for ipa-4-8 branch, can you handle it? thx

**Pull request closed without merging**
