### PR TITLE
 dns: prompt for missing record parts in CLI

### PR DESCRIPTION
**Pull request by jcholast**
Fix the code which determines if a record part is required and thus should
be prompted not to wrongfully consider all record parts to be optional.

Add a client-side fallback of the dnsrecord_split_parts command for old
servers to avoid CommandError in dnsrecord_add and dnsrecord_mod CLI
interactive mode.

https://fedorahosted.org/freeipa/ticket/6203

### CODE REVIEW

**Comment by mbasti-rh** [comment]
I really don't like to move definitions how to split params from classes to single function
```
def split_rrparam(name, value):
```

It doesn't look safe for me or easy to understand and maintain. When I want to add new DNS type, I have to check 3 different files, I'm sure I will overlook something.

**Comment by jcholast** [comment]
I'm afraid this can't be easily fixed due to the manner in which the dns plugin is implemented.

I'm open to suggestions if you have any.

**Comment by mbasti-rh** [comment]
Can we move DNS record classes to ipalib/dnsrecords.py and use it in both client and server?

IMO for server side code it should work just fine,  not sure about client.

**Comment by jcholast** [comment]
I have decided to instead copy & paste the code, as it exists solely for the purpose of supporting old servers, so it should not get any additional improvements in the future.

**Comment by mbasti-rh** [comment]
Fix works for me partially, it fixes issues reported in ticket. Do you want to open new ticket for this or should it be part of this ticket?

Expected:
```
[root@vm-058-080 ~]# ipa dnsrecord-add test. rec
Please choose a type of DNS resource record to be added
The most common types for this type of zone are: A, AAAA

DNS resource record type: srv
SRV Priority: 5
SRV Weight: 5
SRV Port: 5
SRV Target: host.example.com.
  Record name: rec
  SRV record: 5 5 5 host.example.com.
```

Got:
```
[root@vm-058-017 ~]# ipa dnsrecord-add test. rec
Please choose a type of DNS resource record to be added
The most common types for this type of zone are: A, AAAA

DNS resource record type: srv
ipa: ERROR: No options to add a specific record provided.
Command help may be consulted for all supported record types.
```

**Comment by mbasti-rh** [comment]
IMO api version should be incremented, otherwise works for me

**Comment by mbasti-rh** [comment]
Fixed upstream
master:
https://fedorahosted.org/freeipa/changeset/afea9616318fbbffc2c296b7c41890db8595e3cc
https://fedorahosted.org/freeipa/changeset/dce95a14595a37ce83bcf3e28f41feab715d0c81
https://fedorahosted.org/freeipa/changeset/38a51fa984a6aa92f383d7f8176057de8e057d52
ipa-4-4:
https://fedorahosted.org/freeipa/changeset/fa8a5c33b73398c731cf2a472c79bd9a51404fe2
https://fedorahosted.org/freeipa/changeset/b4c104ee9038d8d87a7e78137826e655ebb5d39b
https://fedorahosted.org/freeipa/changeset/47d6f49e53d27e1df1377a91789c072b11ccea31

**Pull request closed without merging**
