### PR TITLE
Fix "ipa vault-retrieve --shared $vault" does not work if IPA host is not a KRA (issue 7691)

### PR DESCRIPTION
**Pull request by fcami**
Standard users cannot determine services like KRA.
Using ldapsearch with (ipaConfigString=enabledService)
always fails.
Catch that.

Note that this is not the definitive fix for https://pagure.io/freeipa/issue/7691 (yet)

### CODE REVIEW

**Comment by tiran** [comment]
Good catch!

This is an excellent opportunity to clean up some code and remove duplicate code from the dogtag plugin. I totally forgot that we have two implementation of LDAP service discovery. With a little bit of extra work, you can easily remove ``host_has_service`` and ``select_any_master`` in favor of ``find_providing_servers``.

* The ``select_any_master`` function selects a random CA/KRA master, which is a good thing. Add ``random.shuffle`` to ``ipaserver.install.services.find_providing_servers``. This will ensure, that requests are distributed evenly across all servers. 
* in properties ``ca_host`` and ``kra_host``, use ``find_providing_servers`` to get a list of servers, then replace ``host_has_service`` with a simpler and faster ``if api.env.ca_host in servers`` etc.
* instead of raising the exception in ``select_any_master``, raise the exception in the final ``self._ca_host is None`` in the ``ca_host`` property and in the ``kra_host`` property.

You can also replace the ``object.__setattr__`` code with a simple ``self._ca_host`` assignment. The ``__setattr__`` code is not necessary.

**Comment by fcami** [comment]
As most of the requested changes are in https://github.com/freeipa/freeipa/pull/2144 I'll update this PR once #2144 is in.

**Comment by fcami** [comment]
from
http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/a76be11e-ec16-11e8-ab0b-fa163e5e1b8e/report.html
~~~
subprocess.CalledProcessError: Command '['ipa', 'ca-show', 'ipa']' returned non-zero exit status 1.
subprocess.CalledProcessError: Command '['/usr/sbin/ipa-cacert-manage', 'renew', '--self-signed']' returned non-zero exit status 1.~~~
from
http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/64a39ff6-ec17-11e8-a414-fa163ed5deab/report.html
~~~
 RemoteRetrieveError: Unable to determine master for CA
~~~

Not sure where these come from, as the commands above work:
~~~
# ipa ca-show ipa
  Name: ipa
  Description: IPA CA
  Authority ID: 33e343c7-76ad-4162-9cf0-fd67e02cd4c0
  Subject DN: CN=Certificate Authority,O=LAPTOP.EXAMPLE.ORG
  Issuer DN: CN=Certificate Authority,O=LAPTOP.EXAMPLE.ORG
  Certificate: MIIDoDCCAoigA(...)
# /usr/sbin/ipa-cacert-manage renew --self-signed
Renewing CA certificate, please wait
CA certificate successfully renewed
The ipa-cacert-manage command was successful
~~~

**Comment by fcami** [comment]
@tiran I've removed the exception code for now as it broke PR-CI and it'll be removed by your #2144.
I have changed the "Read access to masters" ACI entry according to the freeipa-devel thread - https://lists.fedorahosted.org/archives/list/freeipa-devel@lists.fedorahosted.org/thread/7SLDDH5HEIJZ7TRYGURU3DSOZJDS3RPN/

**Comment by tiran** [comment]
Please update the title and description of the PR to reflect the new changes. It's a bit confusing.

There are two additional ACIs that define read access to ``ipaConfigString``. Should we keep them or remove them?

* ``add:aci:(targetfilter = "(objectclass=nsContainer)")(targetattr = "ipaConfigString")(version 3.0; acl "Allow hosts to read masters service configuration"; allow(read, search, compare) userdn = "ldap:///fqdn=*,cn=computers,cn=accounts,$SUFFIX";)``
* ``add:aci:(targetfilter = "(objectClass=nsContainer)")(targetattr = "cn || objectClass || ipaConfigString")(version 3.0; acl "Read IPA Masters"; allow (read, search, compare) groupdn = "ldap:///cn=ipaservers,cn=hostgroups,cn=accounts,$SUFFIX";)``

**Comment by fcami** [comment]
@flo-renaud and I talked a bit about this yesterday, and we think we need to remove them.
I'm opening a pagure ticket so that we don't forget to.

**Comment by tiran** [comment]
I'm slightly worried that it is too broad. A more restrictive ACL should do the trick, too.

``aci:(targetfilter = "(ipaConfigString=enabledService)")(targetattrs = "ipaConfigString")(version 3.0; acl "Find enabled services"; allow(read, search, compare) userdn = "ldap:///all";)``

**Comment by tiran** [comment]
re-run, pki-tomcatd was killed by OOM killer.

**Comment by fcami** [comment]
test_vault is failing as it should be now:
transport.py               513 DEBUG    RUN ['ipa', 'vault-retrieve', '--shared', 'ci_test_shared_vault_replica_without_kra', '--out=test.txt']
transport.py               558 DEBUG    ipa: ERROR: an internal error has occurred
transport.py               214 ERROR    Exit code: 1

**Comment by fcami** [comment]
Test passes now:
~~~
transport.py 318 INFO RUN ['ipa', 'vault-add', 'ci_test_shared_vault_replica_without_kra', '--shared', '--type', 'standard'] transport.py 513 DEBUG RUN ['ipa', 'vault-add', 'ci_test_shared_vault_replica_without_kra', '--shared', '--type', 'standard'] transport.py 558 DEBUG ------------------------------------------------------ transport.py 558 DEBUG Added vault "ci_test_shared_vault_replica_without_kra" transport.py 558 DEBUG ------------------------------------------------------ transport.py 558 DEBUG Vault name: ci_test_shared_vault_replica_without_kra transport.py 558 DEBUG Type: standard transport.py 558 DEBUG Owner users: admin transport.py 558 DEBUG Shared vault: True transport.py 217 DEBUG Exit code: 0 transport.py 318 INFO RUN ['ipa', 'vault-archive', 'ci_test_shared_vault_replica_without_kra', '--shared', '--data', 'SSBsb3ZlIENJIHRlc3RzCg=='] transport.py 513 DEBUG RUN ['ipa', 'vault-archive', 'ci_test_shared_vault_replica_without_kra', '--shared', '--data', 'SSBsb3ZlIENJIHRlc3RzCg=='] transport.py 558 DEBUG ------------------------------------------------------------------- transport.py 558 DEBUG Archived data into vault "ci_test_shared_vault_replica_without_kra" transport.py 558 DEBUG ------------------------------------------------------------------- transport.py 217 DEBUG Exit code: 0 transport.py 318 INFO RUN ['ipa', 'user-add', 'vault_user', '--first', 'vault_user', '--last', 'vault_user', '--password'] transport.py 513 DEBUG RUN ['ipa', 'user-add', 'vault_user', '--first', 'vault_user', '--last', 'vault_user', '--password'] transport.py 558 DEBUG ----------------------- transport.py 558 DEBUG Added user "vault_user" transport.py 558 DEBUG ----------------------- transport.py 558 DEBUG User login: vault_user transport.py 558 DEBUG First name: vault_user transport.py 558 DEBUG Last name: vault_user transport.py 558 DEBUG Full name: vault_user vault_user transport.py 558 DEBUG Display name: vault_user vault_user transport.py 558 DEBUG Initials: vv transport.py 558 DEBUG Home directory: /home/vault_user transport.py 558 DEBUG GECOS: vault_user vault_user transport.py 558 DEBUG Login shell: /bin/sh transport.py 558 DEBUG Principal name: vault_user@IPA.TEST transport.py 558 DEBUG Principal alias: vault_user@IPA.TEST transport.py 558 DEBUG User password expiration: 20181121091401Z transport.py 558 DEBUG Email address: vault_user@ipa.test transport.py 558 DEBUG UID: 419900000 transport.py 558 DEBUG GID: 419900000 transport.py 558 DEBUG Password: True transport.py 558 DEBUG Member of groups: ipausers transport.py 558 DEBUG Kerberos keys available: True transport.py 217 DEBUG Exit code: 0 transport.py 318 INFO RUN ['ipa', 'vault-add-member', 'ci_test_shared_vault_replica_without_kra', '--shared', '--users', 'vault_user'] transport.py 513 DEBUG RUN ['ipa', 'vault-add-member', 'ci_test_shared_vault_replica_without_kra', '--shared', '--users', 'vault_user'] transport.py 558 DEBUG Vault name: ci_test_shared_vault_replica_without_kra transport.py 558 DEBUG Type: standard transport.py 558 DEBUG Owner users: admin transport.py 558 DEBUG Shared vault: True transport.py 558 DEBUG Member users: vault_user transport.py 558 DEBUG ------------------------- transport.py 558 DEBUG Number of members added 1 transport.py 558 DEBUG ------------------------- transport.py 217 DEBUG Exit code: 0 transport.py 318 INFO RUN ['kdestroy', '-A'] transport.py 513 DEBUG RUN ['kdestroy', '-A'] transport.py 217 DEBUG Exit code: 0 transport.py 318 INFO RUN ['kinit', 'vault_user'] transport.py 513 DEBUG RUN ['kinit', 'vault_user'] transport.py 558 DEBUG Password for vault_user@IPA.TEST: transport.py 558 DEBUG Password expired. You must change it now. transport.py 558 DEBUG Enter new password: transport.py 558 DEBUG Enter it again: transport.py 217 DEBUG Exit code: 0 transport.py 318 INFO RUN ['ipa', 'vault-retrieve', '--shared', 'ci_test_shared_vault_replica_without_kra', '--out=test.txt'] transport.py 513 DEBUG RUN ['ipa', 'vault-retrieve', '--shared', 'ci_test_shared_vault_replica_without_kra', '--out=test.txt'] transport.py 558 DEBUG -------------------------------------------------------------------- transport.py 558 DEBUG Retrieved data from vault "ci_test_shared_vault_replica_without_kra" transport.py 558 DEBUG -------------------------------------------------------------------- transport.py 217 DEBUG Exit code: 0
~~~

**Comment by tiran** [comment]
master:

* a709da674833a0c44cdca0c3431313a44bacb9dd Add a shared-vault-retrieve test
* dd0490e1d8f2021b3fad8f283a73bd7e63e2178c Add a "Find enabled services" ACI in 20-aci.update so that all users can find IPA servers and services. ACI suggested by Christian Heimes.

**Pull request closed without merging**
