### PR TITLE
azure tests: move to fedora 37

### PR DESCRIPTION
**Pull request by flo-renaud**
Signed-off-by: Florence Blanc-Renaud <flo@redhat.com>

### CODE REVIEW

**Comment by flo-renaud** [comment]
I'm failing to understand why pylint and tox report a cyclic-import error:
```
ipatests/prci_definitions/prci_checker.py:1: [R0401(cyclic-import), ] Cyclic import (ipaplatform._importhook -> ipaplatform.osinfo -> ipaplatform.tasks))
ipatests/prci_definitions/prci_checker.py:1: [R0401(cyclic-import), ] Cyclic import (ipalib -> ipalib.frontend))
ipatests/prci_definitions/prci_checker.py:1: [R0401(cyclic-import), ] Cyclic import (ipaclient.plugins.rpcclient -> ipalib.rpc -> ipalib -> ipaclient.remote_plugins))
ipatests/prci_definitions/prci_checker.py:1: [R0401(cyclic-import), ] Cyclic import (ipaclient.frontend -> ipalib -> ipaclient.remote_plugins -> ipaclient.remote_plugins.compat))
ipatests/prci_definitions/prci_checker.py:1: [R0401(cyclic-import), ] Cyclic import (ipalib -> ipalib.crud -> ipalib.frontend))
ipatests/prci_definitions/prci_checker.py:1: [R0401(cyclic-import), ] Cyclic import (ipaserver.install.installutils -> ipaserver.install.service -> ipaserver.install.ldapupdate))
ipatests/prci_definitions/prci_checker.py:1: [R0401(cyclic-import), ] Cyclic import (ipaserver.install.installutils -> ipaserver.install.service -> ipaserver.install.ldapupdate -> ipaserver.install.replication))
ipatests/prci_definitions/prci_checker.py:1: [R0401(cyclic-import), ] Cyclic import (ipaclient.plugins.rpcclient -> ipalib -> ipaclient.remote_plugins))
ipatests/prci_definitions/prci_checker.py:1: [R0401(cyclic-import), ] Cyclic import (ipaclient.frontend -> ipalib -> ipaclient.remote_plugins -> ipaclient.remote_plugins.schema))
ipatests/prci_definitions/prci_checker.py:1: [R0401(cyclic-import), ] Cyclic import (ipaclient.remote_plugins -> ipaclient.remote_plugins.schema -> ipalib.frontend -> ipalib))
ipatests/prci_definitions/prci_checker.py:1: [R0401(cyclic-import), ] Cyclic import (ipatests.pytest_ipa.integration.resolver -> ipatests.pytest_ipa.integration.tasks))
ipatests/prci_definitions/prci_checker.py:1: [R0401(cyclic-import), ] Cyclic import (ipatests.pytest_ipa.integration.config -> ipatests.pytest_ipa.integration.host -> ipatests.pytest_ipa.integration.env_config))
ipatests/prci_definitions/prci_checker.py:1: [R0401(cyclic-import), ] Cyclic import (ipatests.pytest_ipa.integration.config -> ipatests.pytest_ipa.integration.env_config))
ipatests/prci_definitions/prci_checker.py:1: [R0401(cyclic-import), ] Cyclic import (ipatests.pytest_ipa.integration.firewall -> ipatests.pytest_ipa.integration.tasks))
ipatests/prci_definitions/prci_checker.py:1: [R0401(cyclic-import), ] Cyclic import (ipatests.pytest_ipa.integration.host -> ipatests.pytest_ipa.integration.resolver -> ipatests.pytest_ipa.integration.tasks))
ipatests/prci_definitions/prci_checker.py:1: [R0401(cyclic-import), ] Cyclic import (ipatests.pytest_ipa.integration.config -> ipatests.pytest_ipa.integration.host -> ipatests.pytest_ipa.integration.resolver -> ipatests.pytest_ipa.integration.tasks -> ipatests.pytest_ipa.integration.env_config))

```
and 
```
lib/python3.11/site-packages/ipapython/session_storage.py:1: [R0401(cyclic-import), ] Cyclic import (ipalib -> ipalib.frontend))
lib/python3.11/site-packages/ipapython/session_storage.py:1: [R0401(cyclic-import), ] Cyclic import (ipaclient.frontend -> ipalib -> ipaclient.remote_plugins -> ipaclient.remote_plugins.schema))
lib/python3.11/site-packages/ipapython/session_storage.py:1: [R0401(cyclic-import), ] Cyclic import (ipaclient.plugins.rpcclient -> ipalib.rpc -> ipalib -> ipaclient.remote_plugins))
lib/python3.11/site-packages/ipapython/session_storage.py:1: [R0401(cyclic-import), ] Cyclic import (ipaclient.remote_plugins -> ipaclient.remote_plugins.compat -> ipalib.frontend -> ipalib))
lib/python3.11/site-packages/ipapython/session_storage.py:1: [R0401(cyclic-import), ] Cyclic import (ipaclient.remote_plugins -> ipaclient.remote_plugins.schema -> ipalib.frontend -> ipalib))
lib/python3.11/site-packages/ipapython/session_storage.py:1: [R0401(cyclic-import), ] Cyclic import (ipaclient.frontend -> ipalib -> ipaclient.remote_plugins -> ipaclient.remote_plugins.compat))
lib/python3.11/site-packages/ipapython/session_storage.py:1: [R0401(cyclic-import), ] Cyclic import (ipalib -> ipalib.crud -> ipalib.frontend))
```
Any idea would be welcome, otherwise I will simply disable the check on the files ipatests/prci_definitions/prci_checker.py and ipapython/session_storage.py

**Comment by stanislavlevin** [comment]
Disablement of pylint on reported files wouldn't help because of incorrect(confusing?) reports.
Let's look at report
`ipatests/prci_definitions/prci_checker.py:1: [R0401(cyclic-import), ] Cyclic import (ipaplatform._importhook -> ipaplatform.osinfo -> ipaplatform.tasks))`. 
This can be reproduced with:
`python3 -m pylint -d all -e cyclic-import ipaplatform`.
The report literally means that the import of `ipaplatform._importhook` may (or may not) lead to import error (due to a circular import).
To skip this warning:
```diff
--- a/ipaplatform/osinfo.py
+++ b/ipaplatform/osinfo.py
@@ -218,7 +218,7 @@ class OSInfo(Mapping):
     def container(self):
         if self._container is not None:
             return self._container
-        from ipaplatform.tasks import tasks
+        from ipaplatform.tasks import tasks  # pylint: disable=cyclic-import
         try:
             self._container = tasks.detect_container()
         except NotImplementedError:
```

Though I don't know why it's fired on Python3.11 (if it's related at all).

**Comment by stanislavlevin** [comment]
Ok, it's not related to Python3.11 at all.
Exactly the same errors can be observed on Python3.10 with pylint in the *single* process mode.
We are running `pylint` in `auto` process mode (`jobs=0` option in `pylintrc`) that should automatically detect number of cpu.
`Pylint` < 2.14.0 relies *only* on `os.sched_getaffinity` to get that number, while `pylint` 2.14.0 improved the logic for that (PyCQA/pylint@1de6da157c260c5a1398bc59c5f2b57abc4912a6) and actually gets the value based on `/sys/fs/cgroup/cpu/cpu.shares`. The default `cpu.shares` for Docker is `1024` (https://docs.docker.com/config/containers/resource_constraints/#configure-the-default-cfs-scheduler), that implies that `pylint` will always use *single* process in *auto* mode in such environments.
Though, it may be worth taking into account https://github.com/PyCQA/pylint/issues/3232.

**Comment by flo-renaud** [comment]
Hi @stanislavlevin 
> Awkward silence. @flo-renaud, would you expect that someone fixes the issue? Please let me know if I should fix it.

Sorry for the delay and lack of response, I was caught in other tasks :(
First of all, thanks for investigating and finding the root cause. If you have the bandwidth to fix the issue, sure, please go ahead (you can add commits to this PR or make a separate, as you prefer).

**Comment by flo-renaud** [comment]
@stanislavlevin thanks for the additional commits, LGTM.
Would be great to have an additional reviewer as I authored the first part of the PR and don't want to self-ack my code.

**Comment by stanislavlevin** [comment]
I wanted to replace deprecated `cgi` as well, but it can be done in another PR.
@flo-renaud, sure. I'll take a look on this week.

**Comment by stanislavlevin** [comment]
@flo-renaud, I added more commits addressing issues found during my review.
It's ready for review.

**Comment by flo-renaud** [comment]
@stanislavlevin your updates LGTM. I rebased onto the master branch to make sure that no additional lint issues are detected.
If you agree with my commits please add the ACK label and I will merge when PRCI completes.

**Comment by flo-renaud** [comment]
master:

* 232b5a9ddeb222035a9393bfc495b2ffba557801 azure tests: move to fedora 37
* cad06382a29f58dba544938f62f8541ec031a62c pylint: remove unneeded disable=unused-private-member
* 12067297d8040565fed7b76738109a933901c35e pylint: remove useless suppression
* a9c1c81a4669c71bf3c629b93ffce4b6018b36ca pylint: disable redefined-slots-in-subclass
* 2011d1a36ac17449affbbcebc1fbeff19b270a42 pylint: disable used-before-assignment
* d1f16120886647778d809599263a56729d9c8303 pylint: replace deprecated distutils module
* be7f0a6e5e05764cd7388522575319144f253eb5 pylint: disable modified-iterating-list
* 8cd9ddfdeb31cdbf907513e31ae71b9c3390a296 pylint: remove arguments-renamed warnings
* d6d8319ece323d3bff58e8dfc5fdd169613962df pylint: disable using-constant-test
* 026885748374a472f145b2b275c78831849687c3 pylint: disable unnecessary-dunder-call message
* 18fd448156d5f4160101405b110f3a34a27475d8 pylint: globally disable unnecessary-lambda-assignment message
* 139038c58b17c8f85556c11e730ff9c62bfaae14 pylint: disable missing-timeout message
* 2268ef4e3ca27b5f58adcd40a6ec3fd0278effcf pylint: fix implicit-str-concat
* 8e7e48dc78466496dd58b9202e6138e088f6661f pylint: fix duplicate-value
* 6518855c3499918cd42360b7938868dc838329d2 pylint: fix deprecated-class SafeConfigParser
* 372a5dc6b84586c1cf2d65328ccc067880843fe9 pylint: disable invalid-sequence-index
* 79153655d71a6522f923825aa50afda9106ffba6 pylint: disable unhashable-member
* 8fad897ee70a333b7d0e6c0fca8b212407e7e667 pylint: globally disable useless-object-inheritance
* fdd3dd29b7897d39d44e61e4a3f372d21896cac9 pylint: fix consider-iterating-dictionary
* 416c210fc3d000dae9978709fd8e996a76addf10 pylint: disable comparison-of-constants
* a4102b9960465e79709373005db260da75ee269d pylint: fix comparison-of-constants
* fa4b0540567c5a9b1932fc6e8241b8d03927454e pylint: disable deprecated-module message
* a1a3b90c48aa77219a6325590afcc8af03adeaf7 pylint: Lint in single process mode
* deaec9b31a9fed080e1fbbc38a7ac21bf2c5f364 pylint: More allowed C extensions
* ccdc94b0e1b234ce459eb2688077f3909652ae60 pylint: Replace deprecated extension-pkg-whitelist
* 4352bd5a50780e17c0e414fae8d76bfed9405f9d pylint: Fix cyclic-import
* a8dd0709927eae044f789bcd02bc75a9ae7258b5 pylint: Replace deprecated pipes
* 0e0331529921f9e7e436ef9d176d6fd12ec4cc46 pylint: Fix used-before-assignment
* 24db4dc8760bb2e2b544392431690d4e1663b58f pylint: Fix modified-iterating-list
* bf3083c3760797c466d4010d812755b9fc5aa2c9 pylint: Fix unnecessary-lambda-assignment
* c523e85835ff1e2e0a6c15f17b550587d3384541 pylint: Fix unhashable-member
* b8480549c65b6bec5bbe9848342e5af98f22dc5c pylint: Fix useless-object-inheritance
* 691b5d21af823f6119a65bde27b96e01a9573d1a pylint: Replace deprecated cgi module

**Pull request closed without merging**
