### PR TITLE
ipatests: allow to relax security of LDAP connection from controller to IPA host

### PR DESCRIPTION
**Pull request by wladich**
The Host.ldap_connect() method uses LDAPClient from ipapython package.
In a3934a21 we started to use secure connection from tests controller to
ipa server. And also 5be9341f changed the LDAPClient.simple_bind method
to forbid password based authentiction over insecure connection.
This makes it imposible to establish ldap connection in some test
configurations where hostnames known to ipa server do not match ones known
to tests controller (i.e. when host.hostname != host.external_hostname)
because TLS certificate is issued for host.hostname and test controller
tries to verify it against host.external_hostname.

A sublass of LDAPClient is provided which allows to skip certificate check.

Fixes: https://pagure.io/freeipa/issue/7960

### CODE REVIEW

**Comment by wladich** [comment]
@flo-renaud, good point about class name, changed it.
Also changed:
* added class docstring
* renamed new parameter ignore_certificate_errors -> no_certificate_check
* use constant instead of value in call to set_option

**Comment by flo-renaud** [comment]
Hi @wladich 
I tested on my env with external hostname different from hostname by running test_integration/test_simple_replication.py, works well.
If you rebase, PRCI should pick the latest fed 29 images and proceed smoothly, then I'll ACK when the test results are green.

**Comment by flo-renaud** [comment]
As tests are now green, ACK.

**Comment by wladich** [comment]
master:

* cd2b2443c5ba2f4885e3d85f98332b2fa8b30432 ipatests: allow to relax security of LDAP connection from controller to IPA host

**Pull request closed without merging**
