### PR TITLE
ipatests: unresolvable nested netgroups

### PR DESCRIPTION
**Pull request by apophys**
Adds a test case for issue in SSSD that manifested in
an inability to resolve nested membership in netgroups

The test case tests for direct and indirect membership.

https://fedorahosted.org/freeipa/ticket/6439

### CODE REVIEW

**Comment by apophys** [comment]
Ping for review.

**Comment by martbab** [comment]
Is there any particular reason why this is among XML RPC tests and not a separate integration test? IMHO it should be a CI test as it tests integration with SSSD. I get that it is easier to re-use existing fixtures but this is clearly out of scope of XML RPC test suites.

**Comment by alichbox** [comment]
Hello, Martin,
I got your point about bigger suite that should be definitely an integration module. For smaller parts we use singlehost test (XMLRPC) because they are faster and resource friendly.
I suggest to keep this test as it is (XMLRPC) and file a new issue - RFE for test coverage.

**Comment by martbab** [comment]
I am strongly opposed to keeping this particular test in XMLRPC suite since it actually does not test any XMLRPC calls but is, in fact, an integration test for SSSD netgroup resolution so the semantics do not match for me.

Arguments about speed and resource-friendliness do not seem to be blocker for this since you have to provision and install IPA server anyway to run our out-of-tree-tests, you just have another machine that needs to act as a controller but this one is much easier to setup that the slave itself.

**Comment by martbab** [comment]
Any update on this PR?

**Comment by apophys** [comment]
The rewrite to integration test is in my queue.

**Comment by martbab** [comment]
Since the re-implementation of this test suite is done by @celestian in https://github.com/freeipa/freeipa/pull/409 can I close this PR?

**Comment by apophys** [comment]
Yes.

**Pull request closed without merging**
