### PR TITLE
[master] gracefully handle setting replica bind dn group on old masters

### PR DESCRIPTION
**Pull request by martbab**
This is the version of https://github.com/freeipa/freeipa/pull/315 for master
branch only

https://fedorahosted.org/freeipa/ticket/6532

### CODE REVIEW

**Comment by martbab** [comment]
PR #322 was closed, it was agreed that this fix is better.

**Comment by martbab** [comment]
@flo-renaud I was able to reproduce the issue you observed when trying to test the patch. I have opened an upstream ticket for it https://fedorahosted.org/freeipa/ticket/6549. I think it is a regression caused by installer refactoring and is unrelated to this PR.

**Comment by flo-renaud** [comment]
Hi,
thanks for the patch. It works as expected.

**Comment by martbab** [comment]
Fixed upstream
master:
https://fedorahosted.org/freeipa/changeset/95e602598a481f9c4a3b69ce8a861bf3816aa8ba

**Pull request closed without merging**
