### PR TITLE
add missing tests to pr-ci definition files for nightly runs for ipa-4-8

### PR DESCRIPTION
**Pull request by wladich**

### CODE REVIEW

**Comment by wladich** [comment]
All tests passed, no failures and skipped tests.

**Comment by flo-renaud** [comment]
HI @wladich 
thanks for the PR. The list of tests LGTM, please remove the temp commit and I will ACK.

**Comment by flo-renaud** [comment]
All tests are green, ACK.

**Comment by wladich** [comment]
ipa-4-8:

* b55bdd21392895512de2a135aaa7f339236c5cd3 ipatests: run test_integration/test_cert.py in PR-CI
* d22d55dfb1eecc6060b4ce32c7eab5fa7c1713de ipatests: add missing classes from test_installation in nightly runs
* cc16712cc5e5d086f0d62304277911be9b276ee0 ipatests: add AD DC as a DNS forwarder before establishing trust
* 8e1d5244568bb409a2898b4c310392256380553d ipatests: explicitly save output of certutil
* e86558d1c7db43cb5d4def2bd77c0b24dee4c179 ipatests: run all cases from test_integration/test_idviews.py in nightlies

**Pull request closed without merging**
