### PR TITLE
[master] ipatests: Update PRCI Fedora 32 templates

### PR DESCRIPTION
**Pull request by netoarmando**
Updating templates with upgraded packages installed.

This is required by https://github.com/freeipa/freeipa/pull/5231

Signed-off-by: Armando Neto <abiagion@redhat.com>

### CODE REVIEW

**Comment by flo-renaud** [comment]
`test_dnssec_TestInstallDNSSECFirst` failure is a known issue: https://pagure.io/freeipa/issue/8496

**Comment by abbra** [comment]
@flo-renaud since that is a known issue, should we merge the template changes? I'm inclined to merge.

**Comment by flo-renaud** [comment]
@abbra yes, I think we can merge the template change. I will mark test_dnssec as a known failure in a separate PR, so that it doesn't preventing gating.

**Comment by netoarmando** [comment]
master:

* 3722013dcd6d03d3adbdfb518c733b1a90e5af39 ipatests: Update PRCI Fedora 32 templates

**Pull request closed without merging**
