### PR TITLE
ipatests: [WebUI] check if notification area doesn't intercept menu button

### PR DESCRIPTION
**Pull request by mrizwan93**
Notification used to intercep the click on page for some element.
This test ensures that element is clickable.

related: https://pagure.io/freeipa/issue/8120

Signed-off-by: Mohammad Rizwan Yusuf <myusuf@redhat.com>

### CODE REVIEW

**Comment by serg-cymbaluk** [comment]
@mrizwan93 
Could you please mention subsystem (WebUI), test module and PEP8 errors in the "PEP8 fix" commit message?

**Comment by mrizwan93** [comment]
> @mrizwan93
> Could you please mention subsystem (WebUI), test module and PEP8 errors in the "PEP8 fix" commit message?

Done

**Comment by tiran** [comment]
Please rebase the PR. ipatool is unable to merge it:
```
error: patch failed: ipatests/test_webui/test_user.py:179
error: ipatests/test_webui/test_user.py: patch does not apply
```

**Comment by tiran** [comment]
master:

* 4b83c2a9e4afdfddc45d639eaf0c3aa7f92eb2a4 webui: check if notification area doesn't intercept menu button
* 0c02920529306aaa1a8be1fae185390e2e115859 WebUI tests: fix PEP8 issues in test_webui/test_user.py

**Pull request closed without merging**
