### PR TITLE
CA: set ipaconfigstring:compatCA in cn=DOMAIN IPA CA

### PR DESCRIPTION
**Pull request by flo-renaud**
### CA: set ipaconfigstring:compatCA in cn=DOMAIN IPA CA
    
Commit fa50068 introduced a regression. Previously, the
upgrade plugin upload_cacrt was setting the attribute
ipaconfigstring: compatCA in the entry
cn=DOMAIN IPA CA,cn=certificates,cn=ipa,cn=etc,BASEDN
    
After commit fa50068, the value is not set any more. As a
consequence, the LDAP entry is not identified as the CA and
CA renewal does not update the entry
cn=CAcert,cn=certificates,cn=ipa,cn=etc,BASEDN.
    
RHEL 6 client rely on this entry to retrieve the CA and
client install fails because cn=CAcert is out-of-date.
    
The fix makes sure that upload_cacrt plugin properly sets
ipaconfigstring: compatCA in the entry
cn=DOMAIN IPA CA,cn=certificates,cn=ipa,cn=etc,BASEDN
    
Fixed: https://pagure.io/freeipa/issue/7928

### ipatests: CA renewal must refresh cn=CAcert
Add a test checking that the entry cn=CAcert,cn=ipa,cn=etc,BASEDN
is properly updated when the CA is renewed
The test also checks that the entry
cn=DOMAIN IPA CA,cn=certificates,cn=ipa,cn=etc,BASEDN properly
contains ipaconfigstring: compatCA
             ipaconfigstring: ipaCA
    
Related to https://pagure.io/freeipa/issue/7928

### CODE REVIEW

**Comment by rcritten** [comment]
Code looks good. Should there be an upgrade script to find and fix those broken by the original change?

**Comment by flo-renaud** [comment]
Hi @rcritten 
Thanks for your review. 

> Should there be an upgrade script to find and fix those broken by the original change?

The upload_cacrt plugin will add the compatCA value to the attribute  ipaconfigstring of the CA entry.

**Comment by rcritten** [comment]
Right, I didn't look hard enough. It's called in 90-post_upgrade_plugins.update

**Comment by rcritten** [comment]
Looks good.

**Comment by flo-renaud** [comment]
master:

* 9cd88587e45c4a588b4cbd9ce1eb31d4a0c711b0 CA: set ipaconfigstring:compatCA in cn=DOMAIN IPA CA
* 4804103315617bf1fab1db84a3ed4737418b4908 ipatests: CA renewal must refresh cn=CAcert

**Pull request closed without merging**
