### PR TITLE
Prci nightly fix

### PR DESCRIPTION
**Pull request by pavelpicka**
test_installation.py
- ticket 7008 closed so removing xfail
 - TestInstallWithCA1
 - TestInstallWithCA
 - TestInstallWithCA_DNS1
 - TestInstallWithCA_DNS2

### CODE REVIEW

**Comment by Rezney** [comment]
Please provide details about what was failing in test_replica_promotion test.

**Comment by Rezney** [comment]
LGTM

**Comment by pavelpicka** [comment]
removed temp commit

**Comment by Tiboris** [comment]
master:

* ad85cc8eae8544680bd083d76d7bf8997856d4a7 PRCI failures fix

**Pull request closed without merging**
