### PR TITLE
Generate same API.txt under Python 2 and 3

### PR DESCRIPTION
**Pull request by tiran**
Use Python 3's reprlib with customizations to create same API.txt under
Python 2 and 3. Some plugins have been slightly altered to use stable
sorting for dynamically created parameter lists.

Signed-off-by: Christian Heimes <cheimes@redhat.com>

### CODE REVIEW

**Comment by abbra** [comment]
LGTM. The order changes in the trust methods aren't significant as we don't depend on the order of StrEnum values to choose the defaults at all.

**Comment by tiran** [comment]
thanks @abbra 

I fixed some linting issues and added ACI + API tests to fastcheck and devcheck.

**Comment by abbra** [comment]
One tiny request, please split Makefile.am changes into a separate commit.

**Comment by abbra** [comment]
LGTM

**Comment by tiran** [comment]
master:

* 8ffa33c24ecae7be41421669ff6114ae56e9a6e7 Generate same API.txt under Python 2 and 3
* a319a378d7913ea7af5ce360fc0a18ae9b889da0 Run API and ACI under Python 2 and 3

**Pull request closed without merging**
