### PR TITLE
py3 spec: remove python2 dependencies for python3 packages

### PR DESCRIPTION
**Pull request by tomaskrizek**
py3 spec: use proper python2 package names

Package names for python2 were updated. Changed:
  dbus-python -> python2-dbus
  python -> python2
  python-devel -> python2-devel
  python-enum34 -> python2-enum34
  python-jwcrypto -> python2-jwcrypto
  python-kdcproxy -> python2-kdcproxy
  python-lesscpy -> python2-lesscpy
  python-netifaces -> python2-netifaces
  python-netaddr ->  python2-netaddr
  python-pytest-multihost -> python2-pytest-multihost
  python-pytest-sourceorder -> python2-pytest-sourceorder
  python-setuptools -> python2-setuptools
  python-six -> python2-six
  python-sssdconfig -> python2-sssdconfig
  samba-python -> python2-samba

Part of: https://pagure.io/freeipa/issue/7131
Signed-off-by: Tomas Krizek <tkrizek@redhat.com>

---

py3 spec: remove python2 dependencies from freeipa-server

When building the package with for python3, use only python3
dependencies. Changed:
  python -> python2 / python3
  python-gssapi -> python2-gssapi / python3-gssapi
  python-ldap -> python2-ldap / python3-pyldap
  systemd-python -> python2-systemd / python3-systemd

Part of: https://pagure.io/freeipa/issue/7131
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1489509
Signed-off-by: Tomas Krizek <tkrizek@redhat.com>

---

py3 spec: remove python2 dependencies from server-trust-ad

Use only python3 dependencies when building server-trust-ad for python3.

Part of: https://pagure.io/freeipa/issue/7131
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1489509
Signed-off-by: Tomas Krizek <tkrizek@redhat.com>

### CODE REVIEW

**Comment by rcritten** [comment]
error: Failed build dependencies:
        python2-ldap is needed by freeipa-4.6.90.dev201710311908+git0fc55179c-0.fc27.x86_64
        python2-lesscpy is needed by freeipa-4.6.90.dev201710311908+git0fc55179c-0.fc27.x86_64

**Comment by tomaskrizek** [comment]
@rcrit this is not an issue when you're using @freeipa/freeipa-master. Do we address this with a downstream patch for fedora, or should we create an if branch in the spec file?

**Comment by rcritten** [comment]
I guess I don't understand the purpose of this patch if it isn't going to change anything for users. Is it to test-drive the change? Is work underway to get similar changes done in Fedora?

**Comment by tomaskrizek** [comment]
There are couple of reasons.

In 1b8432f19c80359a2615f1f62cdde29cd2b28c62 and a7a09bd4c252677fec2e84af433f28fc1374c870 I'm removing rpm dependency on Python 2 for Python 3 freeipa packages (except `freeipa-server-dns`, where the dependency is justified).

In 7f932a882063a2b5e38af97c1f8d4408a766c6a7 I clean up all the package names to reflect their actual, current names in rawhide. They've been clarifying the python package names to explicitly include version of python, e.g. `python2-*` or `python3-*`.

**Comment by rcritten** [comment]
I understand the reasoning but it doesn't work in F-27 now, that's my point. I can try re-testing this in rawhide.

**Comment by rcritten** [comment]
Confirmed it works in rawhide. I'd be ok with conditionals in the spec file.

**Comment by tomaskrizek** [comment]
I've changed the `python2-lesscpy` and `python2-ldap` back to `python-lesscpy` and `python-ldap`, since they were in multiple places and I didn't want to keep so many if-elses in the spec.

**Comment by rcritten** [comment]
LGTM but patches 2 and 3 didn't apply cleanly for me.

**Comment by rcritten** [comment]
To demonstrate more clearly:

$ wget https://github.com/freeipa/freeipa/pull/1203.patch
$ patch -p1 --dry-run < 1203.patch
checking file freeipa.spec.in
checking file freeipa.spec.in
Hunk #1 FAILED at 143.
Hunk #2 succeeded at 175 with fuzz 1.
Hunk #9 succeeded at 385 with fuzz 1.
1 out of 12 hunks FAILED
checking file freeipa.spec.in
Hunk #1 succeeded at 493 (offset -7 lines).
Hunk #2 succeeded at 509 (offset -7 lines).

**Comment by tomaskrizek** [comment]
@rcritten That's not an issue with the code, but with the `--dry-run`. The subsequent patch can't modify the modified code, because well -- the code wasn't modified. If you actually try the patch, it applies cleanly.

```bash
$ patch -p1 < 1203.patch
patching file freeipa.spec.in
patching file freeipa.spec.in
patching file freeipa.spec.in
```

**Comment by rcritten** [comment]
I used the dry-run just to demonstrate the issue, the git am was failing in a similar way.

It must have been an issue on my end because I pulled a new copy of your branch and things apply cleanly, so ACK.

**Comment by tomaskrizek** [comment]
master:

* 3c84b0146b8ae12a836978df98d0f21142a7e7a4 py3 spec: use proper python2 package names
* e203e9f86e2abb49f6daafc76ad47dcb8a0022e3 py3 spec: remove python2 dependencies from freeipa-server
* 49c77d7781c7da6591851c3444bb4ed956656295 py3 spec: remove python2 dependencies from server-trust-ad

**Pull request closed without merging**
