### PR TITLE
Exclude installed policy module file from RPM verification

### PR DESCRIPTION
**Pull request by 5umm3r15**
selinux: Update based on latest packaging guide
https://fedoraproject.org/wiki/SELinux/IndependentPolicy

Signed-off-by: Nikola Knazekova <nknazeko@redhat.com>

### CODE REVIEW

**Comment by rcritten** [comment]
Thanks for the patch. It looks like the  %verify(not ...) was added to the SELinux independent policy page in April of last year.

@5umm3r15 do you know which RHEL and derivative releases need this as well? We'll need to determine how far to backport this.

**Comment by 5umm3r15** [comment]
@rcritten you are right. 
RHEL from 8.7 and 9.0

**Comment by rcritten** [comment]
The patch looks good. Can you add this to your commit to match our contribution policy? It helps us keep track of the origin of any given change.

`
Fixes: https://pagure.io/freeipa/issue/9254`

**Comment by flo-renaud** [comment]
@5umm3r15 all the CI tests are green and the commit msg follows our recommendations. Thanks for your contribution!

**Pull request closed without merging**
