### PR TITLE
Decouple integration tests from ipaserver package

### PR DESCRIPTION
**Pull request by tiran**
The integration test suite has weak dependencies on ipaserver. This PR replaces the few imports with copied constants and decouples integration tests from the server package.

### CODE REVIEW

**Comment by pvoborni** [comment]
By reading code it looks good. The delaying of SSSDConfig import is more a no-op for integration tests as test_sudo calls modify_sssd_conf. But the change is fined with me. 

Seems that this patch set helps with removing workarounds: https://github.com/pvoborni/freeipa/commit/d735fab3e64182e230a61df6be1f382d8a6a090f and https://github.com/pvoborni/freeipa/commit/b566b0226fc57c3e96ddaba57277c60cc0db0808 which I have in https://github.com/pvoborni/freeipa/commits/version-update-master . Thus will wait for one set of tests to finish. Rebase https://github.com/pvoborni/freeipa/commits/version-update-master on top of this, run all tests again and see if it fullfills the idea. Will report tomorrow (1 run takes 5-7hrs).

**Comment by tiran** [comment]
> By reading code it looks good. The delaying of SSSDConfig import is more a no-op for integration tests as test_sudo calls modify_sssd_conf. But the change is fined with me.

The deferred import is required to make PyPI package tests passing. Since ``SSSDConfig`` is only used in one place, it was easier to move the import into the function.

**Comment by abbra** [comment]
Looks good to me. 4 errors reported by ipa-run-tests in azure CI pipeline were already fixed in PR#3146.

**Comment by tiran** [comment]
master:

* 289f9c7e254180b6c28a724f0e840f89756c11de Delay import of SSSDConfig
* 4b7e81fbbe5ae0b0b4178f1a8ff5544346339ce1 Replace imports from ipaserver
* 8bd469c54ea3d00652d252f3c97a771515a965a8 Don't import ipaserver in conf.py
* 984a44a46a7a1aecdd26ea9b2c5e9bf19a84fe02 integration plugins import ldif
* 2d22fdafaa9c27327b55abec3ed9e96c5d51c1bd Forbid imports of ipaserver and install packages

**Pull request closed without merging**
