### PR TITLE
Update ipa.conf.template

### PR DESCRIPTION
**Pull request by zebraartefakt**
This is my first pull request, so please bear with me.

WebUI looked broken so I looked around and found a missing dash. You could of course also change the folder, but this fixes it :)

### CODE REVIEW

**Comment by tiran** [comment]
Thanks for the PR, what is your operating system?

Fedora and RHEL have ``/usr/share/fonts/fontawesome/fontawesome-webfont.ttf``. Are you on Debian/Ubuntu, perhaps?

**Comment by zebraartefakt** [comment]
Oh yeah, forgot to mention / didn't think this mattered, sorry. I'm on Ubuntu. I guess that breaks my first PR :(

**Comment by tiran** [comment]
Yes, Ubuntu uses a different layout.
```
# head -n2 /etc/os-release
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
# ls /usr/share/fonts/truetype/             
dejavu  font-awesome  open-sans
```

That means your PR is going to be a little bit more complicated:

* define ``FONTS_FONT_AWESOME`` and ``FONTS_OPEN_SAN`` with path to Fedora directorues in ``ipaplatform/base/paths.py``
* add an override for ``FONTS_FONT_AWESOME`` to ``ipaplatform/debian/paths.py``
* modify ``ipaserver/install/httpinstance.py`` and ``ipaserver/install/server/upgrade.py`` to pass the new constants to the templating call (look for ``FONTS_DIR``
* modify ``install/share/ipa.conf.template`` to use the new constants instead of ``"${FONTS_DIR}/open-sans"`` and ``"${FONTS_DIR}/fontawesome"``

**Comment by tiran** [comment]
Ubuntu downstream bug: https://bugs.launchpad.net/ubuntu/+source/freeipa/+bug/1772921

Please work with Timo to get the patch landed upstream

**Comment by abbra** [comment]
@tjaalton, please see this PR.

**Comment by rcritten** [comment]
Should we close this in favor of https://github.com/freeipa/freeipa/pull/3048 ?

**Comment by tjaalton** [comment]
yep, looks like #3048 covers this

**Comment by rcritten** [comment]
Ok, closing this one in favor of the other then.

**Pull request closed without merging**
