### PR TITLE
Fix ip address checks

### PR DESCRIPTION
**Pull request by MartinBasti**
Fix various checks of IP address in installers, removal of some unneeded checks that are not working correctly,  and mainly causes only false positive errors.

This PR also fixes regressions caused by bf9886a84393d1d1546db7e49b102e08a16a83e7

https://pagure.io/freeipa/issue/4317

### CODE REVIEW

**Comment by dkupka** [comment]
Changes look good to me. But it uncovers another unwanted behaviour: With --setup-dns the installer adds IP and FQDN into /etc/hosts. This results in all traffic from local system towards it's FQDN being routed over the external IP.
I believe this is not a good idea but don't have strong opinion about fixing it in this PR or separate one. It's time to stop touching /etc/hosts.

**Comment by MartinBasti** [comment]
@dkupka it is not aim of this PR to fix what you mentioned.

**Comment by dkupka** [comment]
@MartinBasti You're right.

**Comment by dkupka** [comment]
master:

* 82ad586f6cbf6e707add3c866ed4e37ade69b045 Fix local IP address validation
* cb48a49c80f4a11d2d16511e0f1366867320f153 ipa-dns-install: remove check for local ip address
* 0b69e44f16fbba6ab7ddef5a3e55bdabcfd6a8a6 refactor CheckedIPAddress class
* 6024165101677c844dc3bbb337e290df2e66eaf1 CheckedIPAddress: remove match_local param
* f9cba7d161f788c32336b66ff7c641f4a1ed2754 Remove ip_netmask from option parser
* 1b8dc1131c9ca7218efb8fe16dcce97f9f960be9 replica install: add missing check for non-local IP address
* f3537297bee2890c6b839750bb7a0a2cf904cdf9 Remove network and broadcast address warnings

**Comment by dkupka** [comment]
@MartinBasti please rebase for ipa-4-5

**Comment by MartinBasti** [comment]
Rebased in #881

**Pull request closed without merging**
