### PR TITLE
[Backport][ipa-4-9] x509: Replace removed register_interface with subclassing

### PR DESCRIPTION
**Pull request by flo-renaud**
This PR was opened automatically because PR #6455 was pushed to master and backport to ipa-4-9 is required.

### CODE REVIEW

**Comment by flo-renaud** [comment]
PR was ACKed automatically because this is backport of PR #6455. Wait for CI to finish before pushing. In case of questions or problems contact @stanislavlevin who is author of the original PR.

**Comment by rcritten** [comment]
ipa-4-9:

* 89fe83b03ac3b046685389ee1059ca75c73e53b0 x509: Replace removed register_interface with subclassing

**Comment by ciroiriarte** [comment]
which release for 4.9.x should include this?

**Comment by rcritten** [comment]
4.9.11+

**Pull request closed without merging**
