### PR TITLE
WebUI: Fix error "unknown command 'idoverrideuser_add_member'"

### PR DESCRIPTION
**Pull request by serg-cymbaluk**
There was wrong IPA.associator class used for 'Groups' -> 'User ID overrides' association,
as a result a wrong command was sent to the server.

Ticket: https://pagure.io/freeipa/issue/8416

### CODE REVIEW

**Comment by pvoborni** [comment]
The code looks good to me. But I have not tested it.  Might be good to cover it by tests.

**Comment by abbra** [comment]
ack

**Comment by serg-cymbaluk** [comment]
@abbra 

Thank for the review.
I would ask you to not merge the PR until I add a test case to test_trust.py for the idoverrideuser feature. It is almost ready.

**Comment by serg-cymbaluk** [comment]
@abbra @pvoborni 

I've added test for the case.
Unfortunately I can't provide test results here since we have no configuration for WebUI+AD in PR-CI. So it is tested only locally.

**Comment by abbra** [comment]
ACK, please push

**Comment by abbra** [comment]
master:

* 5d9d6348c17f683bf2bda986d2ca0d785a3def17 WebUI: Fix error "unknown command 'idoverrideuser_add_member'"
* bcae2094048609a6cfaecf73d9b611d3d90af44b WebUI tests: Add test case to cover user ID override feature

**Pull request closed without merging**
