### PR TITLE
rpcserver.py code cleaning

### PR DESCRIPTION
**Pull request by slaykovsky**
Hi!

I was going through `rpcserver` module code and just found out it's very hard to read. So I've made some style changes and string formatting related changes.

For my point of view, it's now more easy to read.

Any comments are welcomed.

Thanks.

### CODE REVIEW

**Comment by rcritten** [comment]
Reformatting text outside the context of another change is discouraged because it ends up polluting git history.

**Comment by slaykovsky** [comment]
Hi @rcritten , let's say then I've changed `%` string formatting style to `format` and as a side effect I've reformatted the whole module.

**Comment by rcritten** [comment]
Probably rejected for unrelated changes.

reformatting makes things like git blame less useful.

Style changes could be brought up to the team to be decided as a whole.

**Comment by slaykovsky** [comment]
@rcritten ok, will close.

**Pull request closed without merging**
