### PR TITLE
WebUI: Add confirmation dialog for changing default user/host group

### PR DESCRIPTION
**Pull request by serg-cymbaluk**
Changing default group on automember rules page is too easy.
Add a confirmation dialog to avoid misclick in the case.

Ticket: https://pagure.io/freeipa/issue/8322

### CODE REVIEW

**Comment by flo-renaud** [comment]
Hi @serg-cymbaluk 
thanks for the PR, works well for me.
I tested with Automember > User group rules and Automember > Host group rules, both are OK for changing the default group or cancelling the change.

**Comment by flo-renaud** [comment]
Please remove the temp commit to allow pushing.

**Comment by serg-cymbaluk** [comment]
@flo-renaud 
Thanks for your review.
Temp commit is removed. Tests passed.

**Comment by serg-cymbaluk** [comment]
master:

* 33ca0745585ae3fcd466631a069e244bea74be88 WebUI: Add confirmation dialog for changing default user/host group
* 3645854c11b0489215a27077a633755638f00268 WebUI tests: Add confirmation step after changing default group in automember tests

**Pull request closed without merging**
