### PR TITLE
Added plugins directory to paclient subpackages

### PR DESCRIPTION
**Pull request by olivergs**

### CODE REVIEW

**Comment by olivergs** [comment]
Continuation of PR #749

**Comment by MartinBasti** [comment]
Thank you! Just for the record, you could use `git push --force` and keep the original PR opened :-)

**Comment by MartinBasti** [comment]
master:

* 548014f03eeababfd1b49e4bc9ac608633cb9b98 Added plugins directory to paclient subpackages

**Comment by abbra** [comment]
Note that we want this fix in 4.4 branch as well -- it affects F25.

**Comment by MartinBasti** [comment]
Opened issue: https://pagure.io/freeipa/issue/6927

**Comment by olivergs** [comment]
I also opened this https://bugzilla.redhat.com/show_bug.cgi?id=1446744

**Pull request closed without merging**
