### PR TITLE
ipatests: adapt for new automembership fixup behavior

### PR DESCRIPTION
**Pull request by flo-renaud**
The automembership fixup task now needs to be called
with --cleanup argument when the user expects automember
to remove user/hosts from automember groups.
Update the test to call create a cleanup task equivalent to
dsconf plugin automember fixup --cleanup
when it is needed.

Fixes: https://pagure.io/freeipa/issue/9313
Signed-off-by: Florence Blanc-Renaud <flo@redhat.com>

### CODE REVIEW

**Comment by flo-renaud** [comment]
The backport to ipa-4-10 is not strictly required for now but if we release IPA 4.10 on f38 it will be needed.

**Comment by rcritten** [comment]
Will this affect users as well?  Should the automember plugin add an option for cleanup, or do it automatically?

**Comment by abbra** [comment]
The option was added and the default was changed to *not* use the option to speed up rebuilds. 

We decided to wait with adding an option to cleanup when a generic `ipa task-add-...` interface is added. See some discussion in https://github.com/freeipa/freeipa/pull/6403 for details.

**Comment by flo-renaud** [comment]
Dropping the temp commit. For future ref, link to successful runs:
- `fedora-latest/automember`: [Details](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/ca0f9bc6-a08e-11ed-870a-fa163e3eb16d)
- `fedora-rawhide/automember `: [Details](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/3388c4ce-a08f-11ed-94c1-fa163ed0f469)

**Comment by flo-renaud** [comment]
Rebased on top of master branch + re-added the temp commit to make sure the manual merge did not introduce any issue.

**Comment by flo-renaud** [comment]
Link to successful runs:
- `fedora-latest/automember`: [Details](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/c8512b72-b346-11ed-8113-fa163e4874fd)
- `fedora-rawhide/automember`: [Details](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/6a5b255e-b346-11ed-91f9-fa163e33b8c8)

Removing the temp commit.

**Comment by flo-renaud** [comment]
master:

* 5dba2aa4660e5eed11fe53f6f36b8226e8539df2 ipatests: adapt for new automembership fixup behavior

**Pull request closed without merging**
