### PR TITLE
rpc: don't decode cookie_string if it's None

### PR DESCRIPTION
**Pull request by stlaz**
This removes an ugly debug message from client installation

### CODE REVIEW

**Comment by frasertweedale** [comment]
@stlaz is there a ticket associated with this patch?  What are the step to reproduce
this issue that this patch addresses?

**Comment by stlaz** [comment]
I did not create a ticket as the change seemed small to me, although it might have been worth it.

I did see this in client installation when `ipa-server-install` was run (message like "'NoneType' has no 'decode` member."). Note that the failure is non-fatal due to the bare Exception, it's just that it probably should not appear in the logs as it may sound like something bad could have actually happened.

**Comment by frasertweedale** [comment]
@stlaz thanks, I see the error in the client install log.

When I have confirmed that this patch avoids it, you shall have my ACK.

**Comment by tomaskrizek** [comment]
master:

* 5acd4840903c7f290c1af7d6442e90bf4c0d19dd rpc: don't decode cookie_string if it's None

**Pull request closed without merging**
