### PR TITLE
ipaplatform: add initial nixos support

### PR DESCRIPTION
**Pull request by s1341**
This PR adds initial nixos support to freeipa.

Once this lands, we will modify https://github.com/NixOS/nixpkgs/pull/207115 to use the nixos ipaplatform from here, rather than patching in it's own support.

### CODE REVIEW

**Comment by s1341** [comment]
Opened an issue on the pagure repo: https://pagure.io/freeipa/issue/9299

**Comment by abbra** [comment]
Issues from the linter:

```
pycodestyle
-----------
local configuration: in /__w/1/s
checking ./ipaplatform/nixos/__init__.py
checking ./ipaplatform/nixos/constants.py
./ipaplatform/nixos/constants.py:32:1: E305 expected 2 blank lines after class or function definition, found 1
checking ./ipaplatform/nixos/paths.py
./ipaplatform/nixos/paths.py:11:1: E302 expected 2 blank lines, found 1
./ipaplatform/nixos/paths.py:21:1: E305 expected 2 blank lines after class or function definition, found 1
checking ./ipaplatform/nixos/services.py
checking ./ipaplatform/nixos/tasks.py
checking ./ipaplatform/setup.py
pycodestyle
-----------
local configuration: in /__w/1/s
checking ./ipaplatform/nixos/__init__.py
checking ./ipaplatform/nixos/constants.py
./ipaplatform/nixos/constants.py:32:1: E305 expected 2 blank lines after class or function definition, found 1
checking ./ipaplatform/nixos/paths.py
./ipaplatform/nixos/paths.py:11:1: E302 expected 2 blank lines, found 1
./ipaplatform/nixos/paths.py:21:1: E305 expected 2 blank lines after class or function definition, found 1
```

and

```
Python 3.10.8 (main, Nov 14 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-2)]
************* Module ipaplatform.nixos.constants
ipaplatform/nixos/constants.py:15: [W0611(unused-import), ] Unused osinfo imported from ipaplatform.osinfo)
```

**Comment by abbra** [comment]
@s1341 are you planning to work on this PR any more? You need to fix linting issues.
We have a bot that detects stale PRs and removes them after several months of inactivity.

**Comment by s1341** [comment]
I haven’t had a chance to get to it. I can try to manage it sometime in the next week or so.

**Comment by s1341** [comment]
@abbra I fixed the lint issues. I don't know why the build is failing... It looks unrelated.

**Comment by s1341** [comment]
Build still failing. I don't know why...

**Comment by Lindenk** [comment]
Any update on this?

**Comment by s1341** [comment]
The build is still failing for unrelated reasons... Otherwise, from my perspective, it's good to go.

**Comment by abbra** [comment]
@s1341 thanks. I do not see failures in Azure anymore. 
Please flatten the linting fixes into the two original commits. 

Please also update commit messages to include
```
Fixes: https://pagure.io/freeipa/issue/9299
Signed-off-by: your name <your.email>
```

**Comment by s1341** [comment]
I did the squash and sign-off, and the build failed again :(

**Comment by abbra** [comment]
No worries, the GATING upgrade test is known to have race conditions when running in Azure CI. I restarted it.
The docs build fails because ReadTheDocs theme does not support newer Sphinx version. I have opened https://github.com/freeipa/freeipa/pull/6812 to switch to 'Book' theme which also renders better tables in our design documents.

I'll let you know when to rebase once again when we merge the theme change. The rest should be just fine.

**Comment by s1341** [comment]
thanks @abbra

**Comment by s1341** [comment]
Ok. Rebased. Let's see how that works.

**Comment by s1341** [comment]
And the build failed again :(

**Comment by abbra** [comment]
I restarted the CI. Don't worry, this is not a big problem -- it is a known race condition in 389-ds which we reported and it is being fixed upstream: https://github.com/389ds/389-ds-base/issues/5704. Once it is fixed and Fedora packages updated, this test failure will go away.

It is unrelated to your PR.

**Comment by flo-renaud** [comment]
master:

* f66160fdc9e000db0191c21c51401256e2805cf4 ipaplatform: add initial nixos support

**Pull request closed without merging**
