### PR TITLE
fix miss translation in Chinese

### PR DESCRIPTION
**Pull request by shanyin**
Fix the missing translation in Chinese.

### CODE REVIEW

**Comment by mbasti-rh** [comment]
We automatically add translations to IPA from zanata before releasing. If it is translated in zanata it will appear in next release.

**Comment by shanyin** [comment]
Ok, it was already translated in zanata. But what do you mean about you said "what I meant was to send fixing of missing translations strings as separated PR" in #174?

**Comment by mbasti-rh** [comment]
This:
```
-            label='Group search fields',
￼ +            label=_('Group search fields'),
```

**Comment by shanyin** [comment]
Ok, I have just sent a PR.

**Comment by mbasti-rh** [comment]
Thanks

**Comment by mbasti-rh** [comment]
@shanyin Your translations will be released in FreeIPA 4.4.3 soon

**Comment by shanyin** [comment]
Ok, I see. Thanks!

**Pull request closed without merging**
