### PR TITLE
[Backport][ipa-4-6] Added a test to check if ipa host-find --pkey-only does not return SSH public key

### PR DESCRIPTION
**Pull request by flo-renaud**
This PR was opened automatically because PR #4181 was pushed to master and backport to ipa-4-6 is required.

### CODE REVIEW

**Comment by flo-renaud** [comment]
PR was ACKed automatically because this is backport of PR #4181. Wait for CI to finish before pushing. In case of questions or problems contact @ssidhaye who is author of the original PR.

**Comment by flo-renaud** [comment]
Hi @ssidhaye,

the test failed because it is executed with python2 and strings are not unicode:
```
E           AssertionError: assert_deepequal: type(expected) is not type(got).
E             
E             type(expected) = <type 'str'>
E             type(got) = <type 'unicode'>
E             expected = 'Test host <testhost5>'
E             got = u'Test host <testhost5>'
E             path = ('result', 'description', 0)
```
The code needs to use unicode, for instance:
```
        host5.update(dict(ipasshpubkey=sshpubkey),
                     expected_updates=dict(
                         description=[u'Test host <testhost5>'],
```

**Comment by ssidhaye** [comment]
@flo-renaud ok will fix it

**Comment by flo-renaud** [comment]
Closing this PR as @ssidhaye will make his own PR.

**Pull request closed without merging**
