### PR TITLE
Add a notice to restart ipa services after certs are installed

### PR DESCRIPTION
**Pull request by slaykovsky**
Adding notice for user to restart services after
ipa-server-certinstall.

https://pagure.io/freeipa/issue/7016

### CODE REVIEW

**Comment by abbra** [comment]
Looks good but I see a problem in that the other two methods (http and dirsrv) also don't restart corresponding services. We should do something about it.

**Comment by rcritten** [comment]
You should add back the and/or.

**Comment by flo-renaud** [comment]
Hi @slaykovsky,

pylint check is failing because of the print() function. You can add
`from __future__ import print_function`
to resolve the issue.

**Comment by flo-renaud** [comment]
Hi @slaykovsky 
thank you for the patch, works as expected and successfully passes the lint checks.

**Comment by Tiboris** [comment]
master:

* 59802d37d17a33fc2417aa68dd10b3373e1800bd Add a notice to restart ipa services after certs are installed

**Pull request closed without merging**
