### PR TITLE
ipatests: update the test definitions on ipa-4-11 branch

### PR DESCRIPTION
**Pull request by flo-renaud**
The tests are executed using a fedora 39 vagrant box. Available test suites:
- gating (triggered on every new PR against ipa-4-11 branch)
- nightly on latest fedora (f39 as of today)
- nightly on latest fedora + selinux enforcing mode

### CODE REVIEW

**Comment by flo-renaud** [comment]
The runners are too old and hit freeipa-pr-ci issue #[491](https://github.com/freeipa/freeipa-pr-ci/issues/491) _freeipa-pr-ci fails to run tests on rawhide machines_
We need to upgrade the runners before we can test on fedora39.

**Comment by rjeffman** [comment]
@flo-renaud, what does "fedora-latest-ipa-4-11" means? Is in "<distro>-<distro_version>-<branch>"?

Is it expected that we'll have tests some version that is not "fedora-latest"?

**Comment by flo-renaud** [comment]
@rjeffman If you are referring to the job name, it is just following a convention. The job names can be seen if you click on "Show all checks" and they contain the branch name, like `fedora-latest-ipa-4-11/build` or `fedora-latest-ipa-4-11/external_ca_templates`.
Some branches are supported on multiple fedora versions (for instance 4.10 is tested on f37 and f38, and on 4.10 latest means f38 and previous means f37).

**Comment by rjeffman** [comment]
LGTM.

**Comment by rjeffman** [comment]
@flo-renaud, this PR removes files that are modified by #7071, is this correct?

**Comment by rcritten** [comment]
7071 is against the master branch, this is against ipa-4-11, it's ok.

**Comment by rcritten** [comment]
ipa-4-11:

* 572809c77c4e0e76283616224557479b39852bd1 ipatests: update the test definitions on ipa-4-11 branch

**Pull request closed without merging**
