### PR TITLE
cert: do not limit internal searches in cert-find

### PR DESCRIPTION
**Pull request by HonzaCholasta**
Instead, apply the limits on the combined result.

This fixes (absence of) `--sizelimit` leading to strange behavior, such as
`cert-find --users user` returning a non-empty result only with
`--sizelimit 0`.

https://pagure.io/freeipa/issue/6716

### CODE REVIEW

**Comment by stlaz** [comment]
The tests obviously fail as they expect the `cert-find` command to respect the `sizelimit` option.

**Comment by HonzaCholasta** [comment]
The fix was incomplete, it should be OK now.

**Comment by stlaz** [comment]
Works for me.

**Comment by martbab** [comment]
master:

* 6de507c2cad255975665eca6dd6ef7c8f2458d51 cert: do not limit internal searches in cert-find
ipa-4-5:

* 6382f9eee335907362a5ccb44b892f59de7d3751 cert: do not limit internal searches in cert-find

**Pull request closed without merging**
