### PR TITLE
[Backport][ipa-4-6] ipa commands: print 'IPA is not configured' when ipa is not setup

### PR DESCRIPTION
**Pull request by tiran**
This PR was opened automatically because PR #2268 was pushed to master and backport to ipa-4-6 is required.

### CODE REVIEW

**Comment by tiran** [comment]
PR was ACKed automatically because this is backport of PR #2268. Wait for CI to finish before pushing. In case of questions or problems contact @flo-renaud who is author of the original PR.

**Comment by flo-renaud** [comment]
This one needs a manual backport because in ipa-4-6, installutils.check_server_configuration is raising RuntimeError instead of ScriptError. I will take care of this in a new PR.

**Comment by tiran** [comment]
I manually added 648d7c0d38ef99196531e94cd9803c630e7fb05c from ticket https://pagure.io/freeipa/issue/6843

**Comment by flo-renaud** [comment]
ipa-4-6:

* af2ee7ae345037a30164043bddb247b2bbeb60b6 ipa commands: print 'IPA is not configured' when ipa is not setup
* 95af5dc29ff775296d34cc5dc9260105457e0c80 Test: test ipa-* commands when IPA is not configured
* 9182917280a5c2590fa677729db54b38a9ac4d1f Disable message about log in ipa-backup if IPA is not configured

**Pull request closed without merging**
