### PR TITLE
Test external CA with DNS name constraints

### PR DESCRIPTION
**Pull request by tiran**
Verify that FreeIPA can be installed with an external CA that has a name
constraints extension.

Signed-off-by: Christian Heimes <cheimes@redhat.com>

### CODE REVIEW

**Comment by abbra** [comment]
The code LGTM. I'm waiting for fedora-30/external_ca_1 test to complete to see how it actually behaved.

**Comment by abbra** [comment]
Ok, according to http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/25b09a18-b824-11e9-ad80-fa163ea674f4/test_integration-test_external_ca.py-TestExternalCAConstraints/master.ipa.test/journal.gz certmonger was able to request IPA RA certificate with DNS name constraints and later was able to authenticate using this certificate to request other certificates.

**Comment by abbra** [comment]
More details from the signed audit log of IPA CA:

1. Issuance of CN=IPA RA certificate:
```
0.http-nio-8080-exec-16 - [06/Aug/2019:08:56:37 UTC] [14] [6] [AuditEvent=PROFILE_CERT_REQUEST][SubjectID=$NonRoleUser$][Outcome=Success][ReqID=6][ProfileID=caServerCert][CertSubject=CN=IPA RA,O=IPA.TEST] certificate request made with certificate profiles
0.https-jsse-nio-8443-exec-6 - [06/Aug/2019:08:56:38 UTC] [14] [6] [AuditEvent=AUTH][SubjectID=admin][Outcome=Success][AuthMgr=certUserDBAuthMgr] authentication success
0.https-jsse-nio-8443-exec-6 - [06/Aug/2019:08:56:38 UTC] [14] [6] [AuditEvent=AUTHZ][SubjectID=admin][Outcome=Success][aclResource=certServer.ca.request.profile][Op=read] authorization success
0.https-jsse-nio-8443-exec-6 - [06/Aug/2019:08:56:38 UTC] [14] [6] [AuditEvent=ROLE_ASSUME][SubjectID=admin][Outcome=Success][Role=Certificate Manager Agents, Administrators, Security Domain Administrators, Enterprise CA Administrators, Enterprise KRA Administrators, Enterprise OCSP Administrators, Enterprise TKS Administrators, Enterprise RA Administrators, Enterprise TPS Administrators] assume privileged role
0.https-jsse-nio-8443-exec-10 - [06/Aug/2019:08:56:40 UTC] [14] [6] [AuditEvent=AUTH][SubjectID=admin][Outcome=Success][AuthMgr=certUserDBAuthMgr] authentication success
0.https-jsse-nio-8443-exec-10 - [06/Aug/2019:08:56:40 UTC] [14] [6] [AuditEvent=AUTHZ][SubjectID=admin][Outcome=Success][aclResource=certServer.ca.request.profile][Op=approve] authorization success
0.https-jsse-nio-8443-exec-10 - [06/Aug/2019:08:56:40 UTC] [14] [6] [AuditEvent=ROLE_ASSUME][SubjectID=admin][Outcome=Success][Role=Certificate Manager Agents, Administrators, Security Domain Administrators, Enterprise CA Administrators, Enterprise KRA Administrators, Enterprise OCSP Administrators, Enterprise TKS Administrators, Enterprise RA Administrators, Enterprise TPS Administrators] assume privileged role
0.https-jsse-nio-8443-exec-10 - [06/Aug/2019:08:56:40 UTC] [14] [6] [AuditEvent=CERT_REQUEST_PROCESSED][SubjectID=admin][Outcome=Success][ReqID=6][CertSerialNum=6] certificate request processed
```

2. Issuance of a certificate using CN=IPA RA certificate for authentication:
```
0.https-jsse-nio-8443-exec-10 - [06/Aug/2019:08:58:38 UTC] [14] [6] [AuditEvent=AUTH][SubjectID=ipara : ipara][Outcome=Success][AuthMgr=raCertAuth] authentication success
0.https-jsse-nio-8443-exec-10 - [06/Aug/2019:08:58:38 UTC] [14] [6] [AuditEvent=PROFILE_CERT_REQUEST][SubjectID=ipara][Outcome=Success][ReqID=7][ProfileID=caIPAserviceCert][CertSubject=CN=master.ipa.test,O=IPA.TEST] certificate request made with certificate profiles
0.https-jsse-nio-8443-exec-10 - [06/Aug/2019:08:58:38 UTC] [14] [6] [AuditEvent=CERT_REQUEST_PROCESSED][SubjectID=ipara][Outcome=Success][ReqID=7][CertSerialNum=7] certificate request processed
```

**Comment by frasertweedale** [comment]
LGTM too.  FYI this probably works due to absense of `NSS_ENABLE_PKIX_VERIFY=1` in Dogtag environment.  This used to be set in earlier releases, but we removed it to avoid OCSP-related issues during startup self-test (chicken/egg with startup thread attempting to verify the certs and attempting to query the OCSP servers... which hasn't started yet).

**Comment by tiran** [comment]
master:

* 69138c848d605ddcb997c8d3f6d51ebdc561c8a6 Test external CA with DNS name constraints

**Comment by abbra** [comment]
@frasertweedale no, it works because we terminate with mod_ssl now, not mod_nss.

**Comment by frasertweedale** [comment]
Thank you @abbra.  To expand, we have observed that the NSS non-libpkix Name Constraints validation behaviour also enforces DNS name constraints against CN.  So `NSS_ENABLE_PKIX_VERIFY` doesn't make a different in this case.

**Pull request closed without merging**
