### PR TITLE
Ignore unlink error in ipa-otpd.socket

### PR DESCRIPTION
**Pull request by tiran**
Don't fail in case the file does not exist.

Signed-off-by: Christian Heimes <cheimes@redhat.com>

### CODE REVIEW

**Comment by martbab** [comment]
LGTM, but do we require this fix also in 4-4 branch?

**Comment by HonzaCholasta** [comment]
This will ignore all errors, not just file does not exist. Are we OK with that?

**Comment by tiran** [comment]
Would you rather use ```/usr/bin/rm -f``` to only ignore missing files but propagate permission errors? I'm not sure why unlink was used in favor of rm. @simo5 ?

**Comment by simo5** [comment]
@tiran I do not know, @npmccallum may know.

**Comment by npmccallum** [comment]
We shouldn't use either. We should use RemoveOnStop= now.

**Comment by npmccallum** [comment]
This PR can be closed.

**Pull request closed without merging**
