### PR TITLE
Fix and extend pki config override test

### PR DESCRIPTION
**Pull request by tiran**
* override ipa_ca_key_size
* test with SHA512withRSA

Related: https://pagure.io/freeipa/issue/5608
Signed-off-by: Christian Heimes <cheimes@redhat.com>

### CODE REVIEW

**Comment by abbra** [comment]
LGTM.

**Comment by tiran** [comment]
temp commit with pki config override test has successfully passed, http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/90e20926-6689-11e9-a98d-fa163ead0942/

**Comment by abbra** [comment]
Thanks!  looks fine.

**Comment by tiran** [comment]
master:

* dd58a705e5c92934604f8a0324125f2a77a50c54 Fix and extend pki config override test

**Pull request closed without merging**
