### PR TITLE
Move krb5 snippet into freeipa-client-common

### PR DESCRIPTION
**Pull request by frozencemetery**
Also move /usr/share/ipa into freeipa-common by necessity.

https://pagure.io/freeipa/issue/7524

I've also opened https://pagure.io/freeipa/issue/7525 to track how this got passed CI.

### CODE REVIEW

**Comment by frozencemetery** [comment]
Travis needs re-run, I think.

**Comment by flo-renaud** [comment]
Hi @frozencemetery 
thanks for the patch, works as expected.

**Comment by flo-renaud** [comment]
master:

- ce3819c Move krb5 snippet into freeipa-client-common

**Comment by flo-renaud** [comment]
master:

* ce3819c3b7fdb511b7e4c38a365629a187d65f75 Move krb5 snippet into freeipa-client-common

**Pull request closed without merging**
