### PR TITLE
Build system refactoring phase 3

### PR DESCRIPTION
**Pull request by pspacek**
This monster patch-set refactors most of build system and moves most of the logic from SPEC file to build system.

It is not yet complete, missing parts are:
- [ ] Python 3 support
- [ ] Client-only build is not supported
- [ ] IPA_VERSION_IS_GIT_SNAPSHOT does not work

These will be sorted out later on but the review of the patch set can begin.

### CODE REVIEW

**Comment by mbasti-rh** [comment]
Why are there these whitespace errors?
```
git am ...
...
Applying: Build: stop build when a step in web UI build fails
Applying: Build: fix distribution of static files for web UI
.git/rebase-apply/patch:413: space before tab in indent.
 	"./fs",
.git/rebase-apply/patch:414: space before tab in indent.
 	"./fileUtils",
.git/rebase-apply/patch:415: space before tab in indent.
 	"./process",
.git/rebase-apply/patch:418: space before tab in indent.
 	"./stringify",
.git/rebase-apply/patch:419: space before tab in indent.
 	"./version",
warning: squelched 49 whitespace errors
warning: 54 lines add whitespace errors.
Applying: Web UI: Remove offline version of Web UI

```

**Comment by mbasti-rh** [comment]
I cannot build rpms
```
./makerpms.sh
...
config.status: executing libtool commands

                    IPA Server 4.4.90.201611071629GITbcd4f03
                    ========================

        prefix:                   /usr/local
        exec_prefix:              ${prefix}
        libdir:                   ${exec_prefix}/lib
        bindir:                   ${exec_prefix}/bin
        sbindir:                  ${exec_prefix}/sbin
        sysconfdir:               ${prefix}/etc
        localstatedir:            ${prefix}/var
        datadir:                  ${datarootdir}
        krb5rundir:               ${prefix}/var/run/krb5kdc
        systemdsystemunitdir:     /usr/lib/systemd/system
        source code location:     .
        compiler:                 gcc
        cflags:                   -g -O2
        LDAP libs:                -lldap_r -llber
        KRB5 libs:                -lkrb5 -lk5crypto -lcom_err
        KRAD libs:                -lkrad
        OpenSSL crypto libs:      -lcrypto
        Maintainer mode:          no

make: *** No rule to make target 'rpms'.  Stop.

```

**Comment by mbasti-rh** [comment]
Build works for me, error was on my side

**Comment by mbasti-rh** [comment]
Works for me 

I read commits, it makes sense, works for me, but I'm not an autotools expert so I might miss something.

I'm curious about one commit:  Build: cleanup unused LDIFs from install/share
- do we have somewhere a documentation for Solaris that requires this file?

**Comment by pspacek** [comment]
- This version supports lint target and all configuration options for linters listed in the design document.
- Fixes in systemd-tmpfiles call from make install.
- Updates .travis.yml to account for new method of RPM build.

**Comment by mbasti-rh** [comment]
commit `Build: add rpms target and makerpms.sh script` misses makerpms.sh and ticket, and it looks like you forgot to squash this commit

**Comment by tiran** [comment]
The patch has some minor creases but works. Let's merge it to master and iron out the remaining small issues with PRs.

**Comment by tiran** [comment]
memo for me:

- [ ] /freeipa*.tar.gz is not removed
- [ ] ```MOSTLYCLEANFILES``` only cleans ipasetup.py[co] but keeps __pycache__ and other pyc/pyo. add ```clean-local: rm -rf *.pyc *.pyc __pycache__```
- [ ]:  ```Makefile.python.am``` clean-local has ```-delete``` and ```-exec```. AFAIK only one action is supported.
- [ ]: neither clean nor distclean removes  ```/dist``` and ```/rpmbuild```
- [ ]: autoconf and automake files are not removed (Makefile.in, /config.sub ...)

**Comment by pspacek** [comment]
I've fixed cases where make generated some build artifacts but make clean did not remove them. These were distinct from Christian comments, I will fix these later on.

**Comment by pspacek** [comment]
@tiran 
> add ipasetup.py to dist_noinst_SCRIPTS ?
`ipasetup.py` file is auto-generated from `ipasetup.py.in` so it should not be part of distibution tarball. I've marked this item as "done".

**Comment by pspacek** [comment]
@tiran 
I've tested the find command and it works. The trick is `-o` which acts like OR and allows you to specify different conditions and associate different actions to them. I'm going to check the checkbox as well :-)

**Comment by mbasti-rh** [comment]
ACK

**Comment by martbab** [comment]
Fixed upstream
master:
https://fedorahosted.org/freeipa/changeset/c48e5fd811326dc64e19490f88003e442815a052
https://fedorahosted.org/freeipa/changeset/0a17155e5b0434d4cab4d1696fac7f5ef88f0808
https://fedorahosted.org/freeipa/changeset/81da45ffb13d126c9b56a2022d88ba8bed2ee18c
https://fedorahosted.org/freeipa/changeset/8de11b091fc705f235b1304fb101c27a82dcda6f
https://fedorahosted.org/freeipa/changeset/3d6b8f8bdd5568c44d293cba960209941e4d2545
https://fedorahosted.org/freeipa/changeset/3a41b3bb8860cf73fef7efd54db2da5ecbd608d5
https://fedorahosted.org/freeipa/changeset/820fd4c7ce6ccc80272f45d6f64227567692dd39
https://fedorahosted.org/freeipa/changeset/24feae47f26f40f757fbdd711399128d88c9b62c
https://fedorahosted.org/freeipa/changeset/b8d81ba3a12d93c38c4a0a8d439845746a32ae35
https://fedorahosted.org/freeipa/changeset/fa8a468dba0ed866497669bd9c08b7de3a2cfbe3
https://fedorahosted.org/freeipa/changeset/7282776c05c2fb254ae65b63977ba604be316038
https://fedorahosted.org/freeipa/changeset/2f6712893be5e66260a169c367a4607be6043d11
https://fedorahosted.org/freeipa/changeset/021a52d6801b74ded03cfdf6c7fb73bd1cab978f
https://fedorahosted.org/freeipa/changeset/f95098b2b645a62497dc6e1d66be2b7397567d25
https://fedorahosted.org/freeipa/changeset/441acf7797b2069e8d9a123aa11bb33fd42d9187
https://fedorahosted.org/freeipa/changeset/24525fd086450616d4edd2aaf26dec868ff80ea9
https://fedorahosted.org/freeipa/changeset/b910683e19356390351a6b82240762969ecf89c0
https://fedorahosted.org/freeipa/changeset/04be25082c60da01552d5e7c73d12930b10bd02e
https://fedorahosted.org/freeipa/changeset/deec97abaec933709718464c4aa233a04de1844a
https://fedorahosted.org/freeipa/changeset/a125370becb045b6e757df88e520ef3f8ab4ca09
https://fedorahosted.org/freeipa/changeset/dabc65f6b1989fb8f938e4b7249fcf5d41706e17
https://fedorahosted.org/freeipa/changeset/886d9167eb939a3ab5226ca420c404a9810186cf
https://fedorahosted.org/freeipa/changeset/c951a491a9082b8b5931782f45f82e251eb93c3c
https://fedorahosted.org/freeipa/changeset/0d5fe1dba0459b09bc7518d34c58444c96435801
https://fedorahosted.org/freeipa/changeset/125bf25577e58d11252cb41d34065d49f581e0ac
https://fedorahosted.org/freeipa/changeset/684a2c6a58b99a72f68e4c7f827d6601007cea26
https://fedorahosted.org/freeipa/changeset/4fb2f535ca73dd16738ce4a3b692931fb26227aa
https://fedorahosted.org/freeipa/changeset/14bce67cf0cad1aecc132a2c67ad2dc686bcd2af
https://fedorahosted.org/freeipa/changeset/c1652f92af6bea13ecd96c0ad7be38784e2faeb5
https://fedorahosted.org/freeipa/changeset/278cda7ede3777f61f31ec77199d02954512e133
https://fedorahosted.org/freeipa/changeset/53cd71a63c7d6ba97a5593e5a8922af71c5a4b6f
https://fedorahosted.org/freeipa/changeset/74820fe3d8774244476357036406014680d54211
https://fedorahosted.org/freeipa/changeset/39b17ef2abd885ab87c1a39d3036f762b6b084c8
https://fedorahosted.org/freeipa/changeset/f229bb56b73487758ed9bd9c7f0a4cc74134992b
https://fedorahosted.org/freeipa/changeset/312e780041fc9025ca3c189e6c9fcb54c7340714
https://fedorahosted.org/freeipa/changeset/8ffd3bdf142f0f852918186ce0a338a7818bbe8e
https://fedorahosted.org/freeipa/changeset/d3cab75d7e79fbc89ef08df3e6d2b1e28b4ef163
https://fedorahosted.org/freeipa/changeset/a027bf739848371fa91b5ba9766e031c9003d322
https://fedorahosted.org/freeipa/changeset/288d624336d502a7df9856cdc2f6543b6e7c0b79
https://fedorahosted.org/freeipa/changeset/6cb0271509fe95ae38fc743f2a13faf32fe29a99
https://fedorahosted.org/freeipa/changeset/cc6382550fcf32bd4b843c922c10c5a5d247dd38
https://fedorahosted.org/freeipa/changeset/dc5699a8a40dd27ffd25d9ad3185ba40d93ec95b
https://fedorahosted.org/freeipa/changeset/4ce3aa3b12004ca4eb29e4bbca415a585fbd432f
https://fedorahosted.org/freeipa/changeset/75a944e980c64061e51f4ec7215033c118f39863
https://fedorahosted.org/freeipa/changeset/fee9bbd85afeac3593abd791de2d002bed300c8e
https://fedorahosted.org/freeipa/changeset/2df98772556de0d964028bbb78a9efbdd13ecd40
https://fedorahosted.org/freeipa/changeset/14c1c8dfd0aa894af2d60dfa4f2ce2510d791328
https://fedorahosted.org/freeipa/changeset/f31a489d246e01250536b7187225fb7ca6398ba5
https://fedorahosted.org/freeipa/changeset/b54e9e86dfaed1320f7ccce560f82c233f67bf1a
https://fedorahosted.org/freeipa/changeset/e3b537af18afa03b1f04530b42cdba5c1fc3ff97
https://fedorahosted.org/freeipa/changeset/4498998f1763d673056423a73d3b3ff22f94954f
https://fedorahosted.org/freeipa/changeset/c0674e89d1e6b5abd82cf3b7bf8054eec0fa6418

**Comment by pspacek** [comment]
@tiran 
> autoconf and automake files are not removed (Makefile.in, /config.sub ...)
According to [Automake manual section 13 What Gets Cleaned](https://www.gnu.org/software/automake/manual/html_node/Clean.html) we must not remove files necessary for `./configure`.

As far as I can tell from testing, make distclean + PR #220 leaves behind only files generated by `autoreconf` so we should not remove any of them. It would prevent users from running `configure` again.

**Pull request closed without merging**
