### PR TITLE
Use PyCA crypto provider for KRAClient

### PR DESCRIPTION
**Pull request by tiran**
The Dogtag KRA backend now uses CryptographyCryptoProvider instead of
NSSCryptoProvider for KRAClient connections. The
CryptographyCryptoProvider uses PyCA cryptography to provide wrapping
and unwrapping. The change will allow Dogtag to remove the
NSSCryptoProvider and drop python-nss as a dependency.

The code in ipaserver.plugins.dogtag creates a Certificate object to
work around a bug in Dogtag. Dogtag supports paths but passes the wrong
type to PyCA cryptography.

Fixes: https://pagure.io/freeipa/issue/8814
See: https://github.com/dogtagpki/pki/issues/3499
Signed-off-by: Christian Heimes <cheimes@redhat.com>

### CODE REVIEW

**Comment by rcritten** [comment]
LGTM, please remove temp commit

**Comment by tiran** [comment]
PR-CI didn't trigger

**Comment by edewata** [comment]
I'm fixing dogtagpki/pki#3499 in https://github.com/dogtagpki/pki/pull/3500, but I think it's better to provide a certificate object like in this PR rather than relying on `CryptographyCryptoProvider` to load the file anyway.

**Comment by flo-renaud** [comment]
master:

* 1d80048e056ff0e1aabccaacb453c9d8d63ae5b9 Use PyCA crypto provider for KRAClient

**Pull request closed without merging**
