### PR TITLE
[Backport][ipa-4-9]ipatests: ipa-client-install --subid adds entry in nsswitch.conf

### PR DESCRIPTION
**Pull request by menonsudhir**
This PR was opened automatically because PR https://github.com/freeipa/freeipa/pull/6335 was pushed to master and backport to ipa-4-9 is required.

### CODE REVIEW

**Review by flo-renaud — COMMENTED** [review]
Hi @menonsudhir 

thanks for the manual backport. Please remove the files `ipatests/prci_definitions/nightly_latest_testing.yaml` and `ipatests/prci_definitions/nightly_latest_testing_selinux.yaml` as they are not used on this branch.
Otherwise LGTM

**Comment by menonsudhir** [comment]
> thanks for the manual backport. Please remove the files `ipatests/prci_definitions/nightly_latest_testing.yaml` and `ipatests/prci_definitions/nightly_latest_testing_selinux.yaml` as they are not used on this branch.

@flo-renaud thank you for the review, the changes have been done.

**Comment by flo-renaud** [comment]
@menonsudhir thanks for the update, LGTM.
You will have to wait for PR #6405 to be merged, then rebase your ipa-4-9 branch to include the code from the PR. Then azure CI should complete successfully.

**Comment by flo-renaud** [comment]
@menonsudhir 
PR #6405 has been merged, can you rebase your branch onto ipa-4-9 ?

**Comment by flo-renaud** [comment]
ipa-4-9:

* a5762621ef3ed1e699306a8d2eef634bc927a6fc ipatests: ipa-client-install --subid adds entry in nsswitch.conf

**Pull request closed without merging**
