### PR TITLE
ipa-backup: restart services before compressing the backup

### PR DESCRIPTION
**Pull request by flo-renaud**
## ipa-backup: restart services before compressing the backup

ipa-backup gathers all the files needed for the backup, then compresses
the file and finally restarts the IPA services. When the backup is a
large file, the compression may take time and widen the unavailabity
window.
    
This fix restarts the services as soon as all the required files are
gathered, and compresses after services are restarted.
    
Fixes: https://pagure.io/freeipa/issue/7632

## ipatest: add functional test for ipa-backup
    
The test ensures that ipa-backup compresses the files after the
IPA services are restarted.

### CODE REVIEW

**Comment by rcritten** [comment]
Worked for me both in data-only and full backup modes.

**Comment by rcritten** [comment]
I guess just remove the test from gating.

**Comment by flo-renaud** [comment]
Temp commit removed.

**Comment by flo-renaud** [comment]
master:

* 4de5ea0930d6a9697668568b0b87a868e5cae285 ipa-backup: restart services before compressing the backup
* fa559808d7158a7de0f21446567c2961b27a1f19 ipatest: add functional test for ipa-backup

**Pull request closed without merging**
