### PR TITLE
Check if replica-s4u2proxy.ldif should be applied

### PR DESCRIPTION
**Pull request by felipevolpone**
Now, before applying replica-s3u2proxy.ldif, we check if the values are already there. The values can be
there, if a replica installation was done in the past and some info was left behind.

https://pagure.io/freeipa/issue/7174

### CODE REVIEW

**Comment by rcritten** [comment]
What about the off-chance that only one of the values exist? Is that possible?

**Comment by felipevolpone** [comment]
To be honest, I don't know :) I was hoping that someone could tell me that. If it is possible, we should also split the ldif file in two.

Also, will be an output with `enabling S4U2Proxy delegation` even if nothing will be done. Is that a problem?

**Comment by rcritten** [comment]
I'm not sure there is a need to do this via LDIF. It may be possible to do with direct LDAP commands and catch and ignore DuplicateEntry errors.

**Comment by pvoborni** [comment]
Could we consider an alternative approach? Identify several objects which are created when replica exists  and are removed on server-del. On next replica installation check for those in early stages and if the objects exists exit with error message stating that one must run `ipa-replica-manage del $replica --force --clean` for DL 0 and `ipa server-del --force` for DL 1.

**Comment by rcritten** [comment]
That works it just isn't very user-friendly, having the command halted. It is certainly a safer way to go though as it will require the user to examine the current state, and a similar test is already being done for host existence (which is why I know it isn't user friendly ;-) )

So it's a choice of:

1. Force the user to do proper clean-up
2. Do the clean-up on our own (we can internally call these I think)
3. Handle only this one case of lack-of-cldanup.

**Comment by felipevolpone** [comment]
TBH I would go with the case we have now. We know how many different ways a user can have a broken environment...

**Comment by pvoborni** [comment]
Some background of the issue. This might happen in situation:
* `ipa-replica-install ...`
* `ipa-replica-install --uninstall`
*  `ipa-replica-install ...`

I.e. explicit `ipa server-del` or `ipa-replica-manage del` are missing in the process.

 `ipa server-del` is run by  `ipa-replica-install --uninstall` but often fails to replica the changes because it effectively cut's a branch under itself (destroys replication credentials) therefore there are left overs which then causes issues like this. 

After looking at it again, +1 to the approach and if the patch works, we can go with it. But I'm afraid it won't solve the situation as the similar issue but elsewhere in the code might happen - different LDAP record not deleted.

**Comment by pvoborni** [comment]
Btw we cannot properly cleanup in uninstaller yet because uninstaller runs as directory manager on itself(LDAPI) but only with host credentials on other replica (GSSAPI). Host credentials doesn't have the permissions to delete every record.

**Comment by tomaskrizek** [comment]
@felipevolpone Could you please rebase the PR against current master? There's no conflict, but the ipatool fails (probably due to a 3-way merge).

**Comment by stlaz** [comment]
Author or reviewers ( @rcritten @pvoborni  ): please clean up your mess (`install/share/replica-s4u2proxy.lidf`)

**Comment by pvoborni** [comment]
@stlaz Could you write it more constructively and avoid using words like mess? From your comment I have no idea what should be cleaned or why.

**Comment by stlaz** [comment]
@pvoborni of course. Please remove the aforementioned file which is not used anywhere anymore as a result of this fix.

**Comment by felipevolpone** [comment]
PR https://github.com/freeipa/freeipa/pull/1240 removes the file.

**Pull request closed without merging**
