### PR TITLE
[Backport][ipa-4-8] azure: bump F32->F34

### PR DESCRIPTION
**Pull request by stanislavlevin**
This PR was opened manually because PR #5790 was pushed to master and backport to ipa-4-8 is required.

### CODE REVIEW

**Comment by stanislavlevin** [comment]
So, code from ipa-4-8 fails on F34.

**Comment by stanislavlevin** [comment]
More backports are required if possible.

**Comment by stanislavlevin** [comment]
It seems https://github.com/freeipa/freeipa/pull/5409

**Comment by stanislavlevin** [comment]
Changed 'named' -> 'named-pkcs11' for Azure base tests (no openssl-pkcs11 patches).

**Comment by stanislavlevin** [comment]
It's strange to have two SOA records for one zone(dnssec tests fail, may be there is some inconsistency between 'old' IPA code vs F34). I will debug it locally.

**Comment by stanislavlevin** [comment]
DNS tests are now passed. Based passed.

**Comment by stanislavlevin** [comment]
sudo tests fails with new sssd-2.5.0.
https://pagure.io/freeipa/issue/8844

**Comment by stanislavlevin** [comment]
depends on #5803

**Comment by stanislavlevin** [comment]
I think this is the reasonable patch set to get worked `ipa-4-8` in CI env based on F34.

**Comment by abbra** [comment]
LGTM. Thank you for this epic update!

**Comment by abbra** [comment]
ipa-4-8:

* c02544c07d040e4e96ed17233b479c958a68b8fa azure: bump F32->F34
* 7802e14f5e209512fc736af56972f572bc599bec freeipa.spec: do not use jsl for linting on Fedora 34+
* 7433be926c6e084f7f1f3bead060544a1334c86e azure: Collect systemd boot log
* 523a9f863815cccfa05f0f87269d6b448a5ab12a azure: Enforce multi-user.target as default systemd's target
* 677df148c7d606242ae14665e3d0580f12e972b3 azure: Wait for systemd booted
* 04c90fb4f2fb16e932f5d198cacb31c75dc9b955 azure: Remove no longer needed repo
* 8fea2f6f3573cd18f6d1cf2af5f95f0f5da2a643 azure: Mask systemd-resolved
* 976a3bf4c388e71c3dc85c8c50b9c727bc07de65 ipatests: Update expectations for test_detect_container
* e5731634a17aa96f4efa235f12bcca993726e6fc azure: Add workaround for PhantomJS against OpenSSL 1.1.1
* 01237953a21b80219ebd6665e0eb67558a951a83 azure: Warn about memory issues
* 835df314d65f42c2e36ac52737eecc1f4e9536e6 BIND: Setup logging
* 2a9dea81254accb08a114a0e853a4c485d1082e4 ipatests: Setup and collect BIND logs
* e23f9767ce2d509c00efa3c0fa5684e7a1fe1973 azure: Run Base and XMLRPC tests is isolated network
* 34e1f6ab3971468a0fa485fe7588e469632d3d0f ipatests: Handle network-isolated mode
* c8e5867d01e4a3a75f7abebf08caf29bbeae5eb6 dnsutil: Improvements for IPA DNS Resolver
* fe0b5ff449da473a69449f7c3267e4a17245a753 dns: get_reverse_zone: Ignore resolver's timeout
* d40306b90527337e504d019797ffb41b7c13d035 pytest: Show extra summary information for all except passed tests
* ff70aacbf8f9035ec496c5e8ea8b23ac6724a8c6 ipatests: Ignore warnings on failed to read files on tarring
* cb3b396fbbbf11462597a7289d5a89cb9fe2cbc9 ipatests: Suppress list trust or certificates
* 21a520181f0e8c2a1e19b3a9e559fd77d9df4b04 azure: Collect installed packages
* c65c7eb05779425355266486c02a30d9cc1f9659 ipatests: dnssec: Add alternative approach for checking chain of trust
* 6710ff42ea853a5dcee96ab64a72051fb4e3f6f7 azure: Warn about extra and missing gating tests compared to PR-CI
* a5730f5053a706c9ce93ef7ec4c52f44b32ca432 azure: Re-balance tests envs
* e66eb48ac43ec513b1e787dcb0da3ee7f7ea3908 azure: coredump: Wait for systemd fully booted
* 6561fc689800c390b8a05cec01e3e69e563edebb ipatests: re-add test_dnssec.py::TestInstallDNSSECFirst in gating
* 8bf95380f1e3608be993e90c0005742db1cb9090 azure: Make it possible to adjust Docker resources per test env
* 2a7f21a9c308cba33edf9ffa43c4aaf271e3a612 ipa-kdb: fix gcc complaints in kdb tests
* e94261f9d9a09dbeca581dfe77f0ae94d2cb1c0b Set client keytab location for 389ds
* ba6eb857ee7abf0fdead07a86e60b0308935ed38 dnssec: fix the key type with OpenDNSSEC 2.1
* 7daf47c83a11ee9cf63462bef8c34a4899054623 ipatests: add a test for ZSK/KSK keytype in DNSKEY record
* b8242e64ee7765d17746281192eaefc4f8fd7dcc handle Y2038 in timestamp to datetime conversions
* 5bfe16a8182f2a2903d12ddd93c9d86a20cae198 OpenDNSSEC: fix timezone in key creation date
* 56746ec0055803b8f6c73c382bed1132a950c0df freeipa.spec: bump the required version of 389ds
* 2b8ccc8a1ec00fe2b4054f169233092c12d78522 freeipa.spec: synchronize with Fedora for 389-ds and PKI versions
* a8686043a521ab115e21700c7782f3fad8ee9752 ipatests: collect config files for NetworkManager and systemd-resolved
* bc9ca47fbd006a533a5f520fe303913b56b13712 ipatests: add utility for managing domain name resolvers
* cdc78af9d77e22b27fc13d3a82e511f7693dff89 ipatests: setup resolvers during replica and client installations
* 549ef48c4bf749919fcd93a7ee71641c180b1687 ipatests: do not manually modify /etc/resolv.conf in tests
* 324ba203ebdd5e8ca5837d40a549c6f43e214d13 ipatests: disable systemd-resolved cache
* 9a28022e4792a905137da9b8a463057473a86499 ipatests: mock resolver factory
* 63a3cfff967eadc8b8ca07ab82ea47d876cc8491 ipatests: always try to create A records for hosts in IPA domain
* d9744e7fa3a9ada6af44b993047fde6521f9bac3 ipatests: do not configure nameserver when installing client and replica
* 47e9df18cd85295e02dd96c95d5888a84aaceaae ipatests: fix TestInstalDNSSECFirst::test_resolvconf logic
* bca86ced8dd4fc36685137b32361e311ba34c04f pr-ci: Run tests on F34
* 0b8517d6f1f09ce246ef2e6c5305099ceec8ac48 Revert "ipatests: configure client to use IPA server as DNS resolver"
* d43d9ca8afa20c83010a3e862e806936414631fc ipatests: Fetch sudo rules without time offset

**Comment by stanislavlevin** [comment]
@netoarmando, please, be aware the image is used for testing of ipa-4-8 is `ci-master-f34:0.0.4`.
If it is not appropriate could you please prepare  dedicated F34 image for ipa-4-8?

**Pull request closed without merging**
