### PR TITLE
[Azure] Add support for multi-envs tests

### PR DESCRIPTION
**Pull request by stanislavlevin**
#### Allow running integration tests in multi-IPA environments

Currently, only `base` and `xmlrpc` tests are launched in Azure.

This is not efficient because of Azure's agent has [0]:
- 6 GB of physical memory and 13 GB of total memory (Feb 2020),
- 2 cores CPU

This is enough to set up IPA environments consisted of not only master but also
replicas and clients and thus, run IPA integration tests. Even more, this is enough
to run multi-IPA environments within one Azure VM.

Here is the proposed Azure CI-flow:
1) `generate-matrix.py` script generates JSON from user's YAML [1]
2) Azure generate jobs using Matrix strategy
3) each job is run in parallel (up to 10) within its own VM (Ubuntu-18.04):
   1) downloads prepared Docker container image (artifact) from Azure cloud
       (built on Build Job) and loads the received image into the local pool
   2) GNU `parallel` launch each IPA environment in parallel:
       1) docker-compose creates the Docker environment having a required number
           of replicas and/or clients
       2) `setup_containers.py` script does the needed container's changes (DNS,
           SSH, etc.)
       3) launch IPA tests on tests' controller
   3) publish tests results in JUnit format to provide a comprehensive test
       reporting and analytics experience via Azure WebUI
   4) publish regular system logs as artifacts

#### Make it possible to configure distro-specific stuff

This allows running IPA tests on Azure using any distro:
1) put a platform-specific template on `ipatests/azure/templates/`
    and make a soft link from 'ipatests/azure/templates/variables.yml' to
    the new template.
2) put configuration templates on paths defined on the step before
3) templates have to answer questions such as:
      1) which Docker image to use to build IPA packages (rpm, deb, etc.)
      2) how to prepare Build environment
      3) how to build IPA packages
      4) how to prepare the environment to run Tox tests
      5) how to prepare the environment to run WebUI unittests
      6) which base Docker image to use to build the new image to run
         IPA tests within it

For example,
1) for testing against ALTLinux, I've prepared 2 Docker images
https://github.com/stanislavlevin/freeipa-altlinux-docker/commits/sisyphus, which are automatically weekly built (read as 'update') and published on the Docker hub using Azure Task.
2) then I added distro-specifics:
https://github.com/stanislavlevin/freeipa/commit/3293a13d56f658b9f94e6cb51b2d896eaf5592db

TODO:
1) add support for external DNS (just another container with some name server onboard)
2) migrate `setup_containers.py` to Ansible playbook

[0] https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
[1] https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#multi-job-configuration

Fixes: https://pagure.io/freeipa/issue/8202

### CODE REVIEW

**Comment by stanislavlevin** [comment]
Any feedback would be appreciated :wink:

**Comment by abbra** [comment]
I like what I see. :)
For the context, we've been discussing this with @stanislavlevin for quite some time and iterating over the changes. There are few failing tests right no but they are mostly about us finding out what we can and cannot easily run in a containerized environment.

**Comment by abbra** [comment]
LGTM

**Comment by abbra** [comment]
@stanislavlevin I think we should do 'ToDo' items in a separate pull request. This one is good to push.

**Comment by abbra** [comment]
master:

* ecc398c409e41ff4d1014e6e88bb5c82d6c19f75 Azure: Allow to not provide tests to be ignored
* 157fa59e7ce29ea3d7f254a102f7af1bfd77e237 Azure: Allow SSH for Docker environments
* 879855ce705770834d0be8182818ae672bc72063 Azure: Allow to run integration tests
* b82515562a9b33c2e0fe345a0cc0bdd8c3cc1688 Azure: Make it possible to configure distro-specific stuff
* fa104daf77902172f087c7026052fd9a59b4861a yamllint: Lint all the YAML files
* d3f1b9b43d55aafb59945ff9635abb4786e0b51a Azure: Don't collect twice systemd_journal.log
* 31d05650fbd784cf87e9dd325d2220c69d6f43ef Azure: Add support for testing multi IPA environments
* e280a2f06ae1e7e78bc86122fbb6d6ceded9e34c pylint: Run Pylint over Azure Python scripts
* 6daf4d2e10007b5c22a9e491e5372d25fd74fc88 Azure: Sync Gating definitions to current PR-CI
* 1fa033c32d4c94ea9456a2a728893e206957930e Azure: Preliminary check for provided limits
* e925148ad9d5d8e36a61c68d0d247283c109a37e Azure: Free Docker resources after usage
* 9203404cd5d9864bfcf6e5b1f4ae2c054464e757 Azure: Skip tests requiring external DNS
* 38e0a9f4c0bd38c204be5dde2d689308d9e153d6 Azure: Rebalance tests
* 0a1e98cdf055867d8a02ed6a8eb65eabe2442a67 Azure: Report elapsed time

**Comment by abbra** [comment]
@stanislavlevin manual backport to ipa-4-8 is needed.

**Comment by stanislavlevin** [comment]
@abbra, thank you. I'm checking.

**Pull request closed without merging**
