### PR TITLE
[Backport][ipa-4-10] Handle PAC signatures based on domain and server capabilities

### PR DESCRIPTION
**Pull request by flo-renaud**
This PR was opened automatically because PR #6846 was pushed to master and backport to ipa-4-10 is required.

### CODE REVIEW

**Comment by flo-renaud** [comment]
PR was ACKed automatically because this is backport of PR #6846. Wait for CI to finish before pushing. In case of questions or problems contact @jrisc who is author of the original PR.

**Comment by abbra** [comment]
Do not merge this PR yet. It has introduced a crash in early startup when LDAP server does respond well.

**Comment by abbra** [comment]
As we now have a fix for the crash in PR#6852, it is ok to merge this backport as soon as CI is green. Then we'll merge PR#6852's backport.

**Comment by flo-renaud** [comment]
ipa-4-10:

* 630cda5c06428825dd5604493621b9cbdab70073 kdb: Use krb5_pac_full_sign_compat() when available
* bbe545ff9feb972e549c743025e4a26b14ef8f89 Tolerate absence of PAC ticket signature depending of server capabilities
* 7ea3b86696f5451f1d227d365018ab7dc53024af Filter out constrained delegation ACL from KDB entry

**Pull request closed without merging**
