### PR TITLE
ipa-client-automount: call save_domain() for each change

### PR DESCRIPTION
**Pull request by fcami**
Call sssdconfig.save_domain(domain) after each configuration
change during ipa-client-automount --uninstall.
    
Previously, sssdconfig.save_domain(domain) was called only
outside of the domain detection loop which changed the domain
configuration. This introduced issues as this method's behavior
is only consistent when configuration items are removed in a
certain order: https://pagure.io/SSSD/sssd/issue/4149
Plus, it is more correct to save the configuration from within
the loop if ever we support multiple domains.
    
Fixes: https://pagure.io/freeipa/issue/8190
Signed-off-by: François Cami <fcami@redhat.com>

### CODE REVIEW

**Comment by fcami** [comment]
Failed test run (available)[http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/419513e8-4ce5-11ea-8797-fa163e168469/report.html].

**Comment by abbra** [comment]
LGTM. Please remove the temp commit.

**Comment by abbra** [comment]
ACK

**Comment by abbra** [comment]
master:

* e1b6e3ba9b174fbe86dc2567fb8429d2e6473640 ipa-client-automount: call save_domain() for each change
* 5f9d5281848a4de3acd669caa277d1b830722b71 ipatests: make sure ipa-client-automount reverts sssd.conf

**Pull request closed without merging**
