### PR TITLE
server: make sure we test for sss_nss_getlistbycert

### PR DESCRIPTION
**Pull request by abbra**
Fixes https://pagure.io/freeipa/issue/6828

### CODE REVIEW

**Comment by tiran** [comment]
AC_CHECK_LIB only checks for functions in libs. Compilation may still fail if header files and library are not in sync. IMHO we don't have to care about this broken case.

LGTM

**Comment by abbra** [comment]
On the systems where pkg-config is available, positive result from pkg-config check means headers are available because pkg-config files are part of development sub-packages. Symbol check in a library is enough then.

**Comment by tomaskrizek** [comment]
Works as expected.

**Comment by tomaskrizek** [comment]
master:

* 67e5244cad72bef76de1c4df47a0c77a672fa861 server: make sure we test for sss_nss_getlistbycert
ipa-4-5:

* 8be6987da72dff0ebd4e02c946b45b5b1705d880 server: make sure we test for sss_nss_getlistbycert

**Pull request closed without merging**
