### PR TITLE
Passdb private state

### PR DESCRIPTION
**Pull request by abbra**
This is a set of patches to allow FreeIPA to be built against Samba 4.7 when it will be released. The code should work just fine against Samba 4.6 already.

### CODE REVIEW

**Comment by MartinBasti** [comment]
I tried samba packages from https://copr.fedorainfracloud.org/coprs/pviktori/samba-py3/package/samba/  and build failed:

```
ipa_sam.c: In function 'priv2ld':
ipa_sam.c:349:25: error: dereferencing pointer to incomplete type 'struct smbldap_state'
  return priv->ldap_state->ldap_struct;
                         ^~
ipa_sam.c:350:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Makefile:601: recipe for target 'ipa_sam.lo' failed
```

**Comment by abbra** [comment]
Thanks, I missed one place there. However, this patch is not going to work aginst that samba build because py3 copr misses the patch I sent today to samba-technical@. Hopefully, Andreas will get it reviewed before 4.7.0-rc1 comes out tomorrow.

**Comment by abbra** [comment]
I've updated patches and tested them with Andreas `asn/samba_ad_dc` COPR repository. They now pass both compile and simple tests for me.

**Comment by abbra** [comment]
I've tested on F26. We need these patches in Rawhide because an update to Samba 4.7 is already there.

**Comment by abbra** [comment]
Note that rawhide build currently fails due to https://bugzilla.redhat.com/show_bug.cgi?id=1467526 (gcc bug on ppc64le). We still need to commit these changes upstream to make it possible to test with `asn/samba_ad_dc` COPR repo.

**Comment by MartinBasti** [comment]
master:

* 11d43a16035d9ce7970ddf757f17025289ec4854 ipa-sam: use own private structure, not ldapsam_privates
* 3ab6a68e91a4fad5af037a910fd4f6b6d8f7611f ipa-sam: use smbldap_set_bind_callback for Samba 4.7 or later

**Pull request closed without merging**
