### PR TITLE
Generate Python shebang lines from configure and make

### PR DESCRIPTION
**Pull request by tiran**
The shebang lines are no longer hard-coded but auto-generated with autoconf and make. configure is now able to detect a platform Python interpreter.

### CODE REVIEW

**Comment by abbra** [comment]
fedora-28/caless tests failed due to port 749 (kadmin) taken by NFS:
```
kadmind: Address already in use - Cannot bind server socket on 0.0.0.0.749
```

**Comment by abbra** [comment]
Travis build failed due to another issue:
```
make[1]: Leaving directory '/freeipa/ipaplatform'
(cd ./ipapython && make version.py)
make[1]: Entering directory '/freeipa/ipapython'
  GEN      .DEFAULT_PLUGINS
  GEN      version.py
make[1]: Leaving directory '/freeipa/ipapython'
cd .; /usr/bin/python2 ./makeaci --validate
/usr/bin/python2: can't open file './makeaci': [Errno 2] No such file or directory
make: *** [Makefile:1228: acilint] Error 2
```

**Comment by abbra** [comment]
LGTM.

**Comment by tiran** [comment]
master:

* e4a3942e89dd0e527a767b386e92d341b1a90e51 Detect and prefer platform Python
* a347c1165073e61572993a64c00b122cb49dabe1 Rename Python scripts and add dynamic shebang
* c8da61b92ac08ab206df260765c531e70d0342f5 Generate scripts from templates

**Pull request closed without merging**
