### PR TITLE
[KDB] various code hygiene fixes

### PR DESCRIPTION
**Pull request by frozencemetery**

### CODE REVIEW

**Comment by rcritten** [comment]
How important are these? We generally doing make these kinds of changes as it muddies the water, particularly with git blame.

**Comment by frozencemetery** [comment]
Rebased and added another commit with leak fixes.

**Comment by abbra** [comment]
Looks good.

**Comment by flo-renaud** [comment]
master:

* 3ccf73bfd6f87d7be1a156d276c22a81d1fac6b4 Make the coding style explicit
* ab4e910c52ae4bdf75eca85f8ff54508f6974fc3 Use separate variable for client fetch in kdcpolicy
* df6a89be51fa8bbc9ce292c9730f20a1e34674ac Fix several leaks in ipadb_find_principal

**Pull request closed without merging**
