### PR TITLE
Removing replica-s4u2proxy.ldif since it's not used anymore

### PR DESCRIPTION
**Pull request by felipevolpone**
Since commit 23a0453c4d33271376b2156f2e2b484e8b9708c9, the
replica-s4u2proxy.ldif file it's not used anymore.

### CODE REVIEW

**Comment by felipevolpone** [comment]
Should we have a Pagure ticket to this? I'm not sure...

**Comment by rcritten** [comment]
I think you can just reference the previous ticket and include the git commit msg there as well once this is approved.

**Comment by rcritten** [comment]
LGTM, the CI failure seems unrelated.

**Comment by felipevolpone** [comment]
Done, commit message updated.

**Comment by felipevolpone** [comment]
master:

* b84e8be5acf37d1778bfd91506859e6d04b7b83d Removing replica-s4u2proxy.ldif since it's not used anymore

**Pull request closed without merging**
