### PR TITLE
[Backport][ipa-4-10] Fontawesome spec changes

### PR DESCRIPTION
**Pull request by rcritten**
This PR was opened automatically because PR #6841 was pushed to master and backport to ipa-4-10 is required.

### CODE REVIEW

**Comment by flo-renaud** [comment]
@antoniotorresm are the patches related to contributors list and translations expected to land into ipa-4-10 branch also?
I am removing the ACK label until this gets sorted out. If they are expected, you can re-ack. Otherwise this backport needs to be cleaned a bit before it gets merged.

**Comment by antoniotorresm** [comment]
@flo-renaud the changes in the master and 4-9 branches may be different to the ones needed in 4-10. I would prefer to clean the PR instead.

**Comment by flo-renaud** [comment]
@antoniotorresm I removed the unwanted commits and kept only the fontawesome backport. Adding back the ACK.

**Comment by rcritten** [comment]
ipa-4-10:

* 58173c021388dd31b4501d1c7bc1e6747cea8bb8 Change fontawesome-fonts requires to match fontawesome 4.x

**Pull request closed without merging**
