### PR TITLE
Fix misc issues in C code

### PR DESCRIPTION
**Pull request by tiran**
* Fix ipadb_multires resource handling 
* Don't abuse strncpy() length limitation

See: https://pagure.io/freeipa/issue/7738

### CODE REVIEW

**Comment by abbra** [comment]
Both commits look good. Thanks!

**Comment by abbra** [comment]
While we are at it, please add a reference to the pagure issue to the second commit.

**Comment by tiran** [comment]
rerun, ``RunPytest Failed to publish artifacts``

**Comment by tiran** [comment]
master:

* 836e29591c2ea08c2fdf334c7095d36fe965f0f3 Fix ipadb_multires resource handling
* 5fe3198d808346dfb36a45c89784f0e3214a88f1 Don't abuse strncpy() length limitation

**Pull request closed without merging**
