### PR TITLE
[Backport][ipa-4-7] Added tests for 2FA prompting configurations

### PR DESCRIPTION
**Pull request by amore17**
Manual back-port of : #4272

### CODE REVIEW

**Comment by amore17** [comment]
http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/d2057cb8-5d5e-11ea-b9ed-fa163e8fbded/report.html
Traceback captured due to missing backport of : e8b98555fcbdc76c2e728d0c93cbbabeebad9a26

**Comment by flo-renaud** [comment]
Hi @amore17 
please rebase as the commit 4cddbfd  will fix the Travis issue

**Comment by amore17** [comment]
Test-results : http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/a9d8178c-5eb7-11ea-b77d-fa163e401a00/

**Comment by flo-renaud** [comment]
Hi @amore17 
the backport should backport the test only, not the changes to ipaclient/plugins/otptoken.py.
In the test file, you can take almost all the code from the previous commit dfa356e but I suspect that test_otptoken_sync will fail. If that's the case, just don't backport this specific test function.

**Comment by abbra** [comment]
LGTM. Please remove the temp commit.

**Comment by amore17** [comment]
Test results : http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/bf820b24-5ef3-11ea-9d73-fa163e53827b/

**Comment by abbra** [comment]
ipa-4-7:

* 85b595aefacd8a52ca9cadf53bdd74184aeb2ba8 Add test case for OTP login
* 40359d2e1a1c4038ac9fc1afa2841e55b11073d8 ipatests: Added test when 2FA prompting configurations is set.

**Pull request closed without merging**
