### PR TITLE
Add index for more trust-related attributes

### PR DESCRIPTION
**Pull request by rcritten**
Add index for ipaNTTrustPartner, ipaNTSecurityIdentifier and
krbprincipalname

https://pagure.io/freeipa/issue/8491

Signed-off-by: Rob Crittenden <rcritten@redhat.com>

### CODE REVIEW

**Comment by rcritten** [comment]
WIP since there is still one un-handled indexed search in the ticket.

**Comment by abbra** [comment]
LGTM.

**Comment by abbra** [comment]
We can ignore the remaining unindexed search because indexing `cn'` attribute is not going to make things fast, as you pointed out. So it is OK to go just with this PR.

**Comment by abbra** [comment]
master:

* 20b55f4017ab42113f1ced829a4b4afa17839b55 Add index for more trust-related attributes

**Pull request closed without merging**
