### PR TITLE
Change README to use Markdown

### PR DESCRIPTION
**Pull request by pvoborni**
So that it will be nicely formatted on FreeIPA Pagure landing page.
  https://pagure.io/freeipa

Some links were updated as other projects also moved to Pagure.io.

Temporary preview on: https://pagure.io/pvoborni-test

### CODE REVIEW

**Comment by stlaz** [comment]
https://github.com/freeipa/freeipa/pull/518 ?

**Comment by stlaz** [comment]
This makes our build fail (`./makerpms` in project folder).

**Comment by stlaz** [comment]
This patch should fix the build: https://transfer.sh/AgQWD/0001-readme-fixup.patch

**Comment by stlaz** [comment]
The build fails no more 😤, ACK.

**Comment by tomaskrizek** [comment]
master:

* 5e0ca17ca06ad26f291d4738766e194b3784c5bd Change README to use Markdown

**Pull request closed without merging**
