### PR TITLE
certmap: load certificate from file in certmap-match CLI

### PR DESCRIPTION
**Pull request by HonzaCholasta**
Load the certificate from a file specified in the first argument. Raw
certificate value can be specified using --certificate.

https://pagure.io/freeipa/issue/6646

### CODE REVIEW

**Comment by flo-renaud** [comment]
Hi @HonzaCholasta 
thank you for this patch. There is a minor issue when --certificate is specified multiple times:
```
ipa  certmap-match  --certificate $CERT1 --certificate $CERT2
ipa: ERROR: invalid 'certificate': must be binary data
```
Otherwise, it works as expected.

**Comment by HonzaCholasta** [comment]
@flo-renaud, looks like you have found an issue in the framework, but it is unrelated to this PR. It can be reproduced in other commands as well, e.g.:
```
$ ipa user-mod jcholast --uid a --uid b
ipa: ERROR: invalid 'uid': must be an integer
```

**Comment by HonzaCholasta** [comment]
@flo-renaud, is there anything else or is the PR good to push?

**Comment by flo-renaud** [comment]
@HonzaCholasta 
Sorry, I forgot to ACK. You can push the PR.
For the record, Issue [6746](https://pagure.io/freeipa/issue/6746) has been opened for the framework issue.

**Comment by HonzaCholasta** [comment]
master:

* 0298ecf441ba38858d7909b8c3b4cc2b4c4e53c4 certmap: load certificate from file in certmap-match CLI

**Pull request closed without merging**
