### PR TITLE
ipatests: Test to check ipa-healthcheck tool displays warning when run on ipa-client

### PR DESCRIPTION
**Pull request by menonsudhir**
The testcase checks that when ipa-healthcheck tool is run on ipa-client it will display 
warning message "IPA is not configured"

### CODE REVIEW

**Comment by rcritten** [comment]
It looks ok but this test will break with the next upstream release due to https://github.com/freeipa/freeipa-healthcheck/commit/a6897503d73e4d398dedbb713ee8d90d29a683d2

So I think the you should check for both strings. Something like:

valid_msg = ('IPA is not configured', 'IPA server is not configured',)
...
assert cmd.stdout_text in valid_msg

I assume you want this backported to ipa-4-9?

**Comment by rcritten** [comment]
re-running. It failed with the dbus teardown problem.

**Comment by menonsudhir** [comment]
dbus related error during uninstall is being tested in https://github.com/freeipa/freeipa/pull/5573

**Comment by flo-renaud** [comment]
@menonsudhir #5573 has been pushed, if you rebase to the master branch the issue shouldn't appear anymore.

**Comment by flo-renaud** [comment]
master:

* e86ff48b49d271905528c2ce352bd8665df2b164 ipatests: Test to check ipa-healthcheck tool displays warning when run on ipa-client

**Pull request closed without merging**
