### PR TITLE
ipatests: add KRB5_TRACE to kinit in test_adtrust_install.py

### PR DESCRIPTION
**Pull request by fcami**
The test test_adtrust_install.py::TestIpaAdTrustInstall::test_add_agent_not_allowed
sometimes fails at the kinit stage:
kinit: Password has expired while getting initial credentials
The only way to debug this further is to add debug information to the
client.

Related-to: https://pagure.io/freeipa/issue/8353
Related-to: https://pagure.io/freeipa/issue/8271
Signed-off-by: François Cami <fcami@redhat.com>

### CODE REVIEW

**Comment by fcami** [comment]
Good run: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/0c1eec22-a977-11ea-8b8f-fa163e045818/report.html
Will squash commits now.

**Comment by fcami** [comment]
Good run post squash: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/17d66ce8-a986-11ea-87d3-fa163e968362/report.html

```
INFO     ipatests.pytest_ipa.integration.host.Host.master.IPAOpenSSHTransport:transport.py:391 RUN KRB5_TRACE=/dev/stdout kinit nonadmin
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd66:transport.py:513 RUN KRB5_TRACE=/dev/stdout kinit nonadmin
(...)
```
I've generalized the approach to make it reusable.

**Comment by fcami** [comment]
Squashed a final time, thanks @frozencemetery

**Comment by miskopo** [comment]
As temp_commit is surpassed by gating, ACK

**Comment by abbra** [comment]
master:

* e7319f628fd70bb7abc77aff1a819326bf52cb5c tasks.py: add krb5_trace to create_active_user and kinit_as_user
* 8f8c560ffd37ea7c23a609fb0b3713a133d9f15f ipatests: add KRB5_TRACE to kinit in test_adtrust_install.py

**Pull request closed without merging**
