### PR TITLE
ipatests: Test healthcheck revocation checker

### PR DESCRIPTION
**Pull request by rcritten**
Revoke the Apache certificate and ensure that healthcheck properly
reports the problem.

### CODE REVIEW

**Comment by abbra** [comment]
Please remove temp commit. @mrizwan93 we typically do not add ACK before all PR CI tests passed.

**Comment by mrizwan93** [comment]
@abbra Ahh, sorry for that.

**Comment by rcritten** [comment]
Temp patch removed.

**Comment by rcritten** [comment]
Since the board is green again after removing the temp commit I'll add back the ack.

**Comment by rcritten** [comment]
master:

* 61db3527e31b1d7c7cda15c034c666cc95c17775 ipatests: Test healthcheck revocation checker

**Pull request closed without merging**
