### PR TITLE
[ipa-4-5] Test: fix definition of template for dnssec

### PR DESCRIPTION
**Pull request by flo-renaud**
The template used for dnssec does not exist, the test
should use ci-ipa-4-5-f26 instead of ci-master-f26

### CODE REVIEW

**Comment by Tiboris** [comment]
https://github.com/freeipa/freeipa/pull/2206 has commit https://github.com/freeipa/freeipa/pull/2206/commits/967ee17e98332974cb114df62c3c5cf37835657d we found this issue last week with @Rezney

**Comment by Tiboris** [comment]
Let us remove commit from there and use your PR @flo-renaud.
Thanks for the patch and sorry for not creating PR myself, it would be more transparent.

**Comment by flo-renaud** [comment]
After investigations, I realized that test_dnssec was not run in ipa-4-5 branch because of the wrong template used in yaml file. Fixing the template shows that test_dnssec still had issues, which were fixed on the master branch but not backported to ipa-4-5.
In this specific PR I also backport the test fixes required for test_dnssec to run properly.

**Comment by Tiboris** [comment]
Thanks for investigation and backports @flo-renaud ! 
LGTM

**Comment by Tiboris** [comment]
ipa-4-5:

* a4502fe35afdc44a7f2a5dde84e659c8aed7b6ee Test: fix definition of template for dnssec
* 6700f89cffc41310fb9b5e0ecd8dcd0102a91143 test_dnssec: re-add named-pkcs11 workarounds
* 8cbc97111e1ab1d30f03f889e32a9429298582a9 Tests: Set default TTL for DNS zones to 1 sec
* 8ae69a43cc507086fe9ad5d9c1e5f7a9ae0c4e4e Remove restarted_named and xfail

**Pull request closed without merging**
