### PR TITLE
ipatests: new tests for ipa-winsync-migrate utility

### PR DESCRIPTION
**Pull request by wladich**
Fixes https://pagure.io/freeipa/issue/7857

### CODE REVIEW

**Comment by wladich** [comment]
@abbra 
I have executed in manually on Fedora 28 and RHEL 8.0, the test is passing.

**Comment by abbra** [comment]
LGTM. Let's get the final test in PR CI to complete and then push.

**Comment by netoarmando** [comment]
@wladich Could you please rebase your branch? After an investigation I believe I found the reason why PR-CI is hanging here. Explanation: https://github.com/freeipa/freeipa-pr-ci/issues/264

**Comment by tiran** [comment]
master:

* f5912d0099ebb9a7cfcb4197367593717b9e8efe ipatests: new tests for ipa-winsync-migrate utility

**Pull request closed without merging**
