### PR TITLE
Fix translation of 'Add dialog for 'association' facet

### PR DESCRIPTION
**Pull request by stanislavlevin**
As for now the 'Add' dialog title, which is initialized within the details of the entity, contains translatable concatenated texts, like:
```
'Add ${other_entity} into ${entity} ${primary_key}'
```
where 'other_entity' and 'entity' are also translatable texts.

This construction is used via method 'show_add_dialog' of association_facet as well as 'create_add_dialog' method of 'association_table' widget for the all 'Add' actions within the details of entities.

The concatenation leads to a bad quality translation and should be changed to an entire sentence.
    
From now a mentioned title is taken from a spec and should be specified explicitly.
    
Fixes: https://pagure.io/freeipa/issue/7712
Fixes: https://pagure.io/freeipa/issue/7714

### CODE REVIEW

**Comment by serg-cymbaluk** [comment]
@stanislavlevin please rebase this branch and fix conflicts on it.

**Comment by stanislavlevin** [comment]
Rebased.

**Comment by stanislavlevin** [comment]
Morning, just now rebased again.

**Comment by stanislavlevin** [comment]
I did PRs (last 6, related to dialog's titles) which are actually dependent on each other.
But GitHub doesn't provide a mechanism to create PR with dependencies (for example, PR3 requires PR2, which requires PR1).

That's why I opened PRs which has no formal deps to any other PR, but of course, this leads to merging conflicts.

**Comment by serg-cymbaluk** [comment]
> I did PRs (last 6, related to dialog's titles) which are actually dependent on each other.
> But GitHub doesn't provide a mechanism to create PR with dependencies (for example, PR3 requires PR2, which requires PR1).
> 
> That's why I opened PRs which has no formal deps to any other PR, but of course, this leads to merging conflicts.

In this case a better solution is to combine all related changes into one PR.

**Comment by stanislavlevin** [comment]
But it will introduce so many changes.
It is harder to a reviewer.
Isn't it?

**Comment by stanislavlevin** [comment]
Very good, I just care about a reviewer.

**Comment by stanislavlevin** [comment]
Already rebased.
Please, try.

**Comment by serg-cymbaluk** [comment]
> @stanislavlevin please rebase this branch and I'll merge it.

Also, if it possible, you could add changes from #2389 to this PR, so we could save a time.

**Comment by stanislavlevin** [comment]
Of course, merged.

**Comment by stanislavlevin** [comment]
Added.

**Comment by serg-cymbaluk** [comment]
master:

* a502fa939f7e0bc9212ac102202a0ba23a7ff75c Drop concatenated title of 'Add' dialog for details of entity
* dda488efc26aa10718b751852deb87b4478d0ca9 Add title to 'add' dialog for details of 'Certificate' entity
* d588d3e9e4494e0750c4dd05b3195954ca5bf149 Add title to 'add' dialog for details of 'Users' entity
* dc9e5c57d575e215afba42078c662ccfe9dd0f0b Add title to 'add' dialog for details of 'Hosts' entity
* ac52facac26f466e3997661a84f527454ad68f33 Add title to 'add' dialog for details of 'Services' entity
* 9e4de506cb4403da9c556f77487b72eb6d01fb30 Add title to 'add' dialog for details of 'Groups' entity
* 01eba53c80d9b1cf8a10057b5665c00cba752698 Add title to 'add' dialog for details of 'ID Views' entity
* 30094d8212e1a8159916fffb62172f3a660246e1 Add title to 'add' dialog for details of 'HBAC' entity
* 35b1b65a542e62c763d68eea60684c3a0cc35957 Add title to 'add' dialog for details of 'Sudo' entity
* 958b10576172d2a73c491fcd97a51f7c46960375 Add title to 'add' dialog for details of 'OTP Tokens' entity
* b3ac23041814213d50db646c37079f4f9dd54d4e Add title to 'add' dialog for details of 'RBAC' entity
* 171c6a01d8a7be0960fe76cd9a6bd67f41506f2e Drop concatenated title of add dialog for association_table widget
* 3c81e170f9117fc9b18e953d3f51b4e67edd942d Add title to 'add' dialog for 'association_table' widget of Hosts entity
* 20688f0fa717cf1613e09c30dc848289c39ce290 Add title to 'add' dialog for 'association_table' widget of Services entity
* c14ef57307da188d57ec9ea0dda5f6ea3f93ed62 Add title to 'add' dialog for 'association_table' widget of Groups entity
* 1ccafd487039e97ee9498bbe972d298dcbf960a4 Add title to 'add' dialog for 'association_table' widget of HBAC entity
* 2ea8f088ba59bdb232e75d21fa3d210c18d7723c Add title to 'add' dialog for 'association_table' widget of Sudo entity
* 0e1accdab4e3fe29bec4085ee4a2a87d545d9c96 Add title to 'add' dialog for 'association_table' widget of SELinux User Maps entity
* 073eac085a17fd4d80d476bb6b1f383dd69ed78b Add title to 'add' dialog for 'association_table' widget of Certificates entity
* 29ca7bf30886e80e682bb7fc0ccdd2be0d226d4a Add title to 'add' dialog for 'association_table' widget of Vaults entity
* 0f30fd834576ab6e83247b1c2741e21e5ebeb8a5 Add title to 'add' dialog for 'association_table' widget of Topology entity

**Pull request closed without merging**
