### PR TITLE
doc: generate API Reference

### PR DESCRIPTION
**Pull request by antoniotorresm**
Extend the 'make api' target so that we also build an API Reference in
Markdown format. One template for each command gets generated. These
templates include all of the command details (arguments, options and
outputs), and then a section for manually-added notes such as semantics
or version differences. Every time the docs are regenerated, these notes
will be added if they exist.

Signed-off-by: Antonio Torres <antorres@redhat.com>

### CODE REVIEW

**Comment by abbra** [comment]
Thank you, @antoniotorresm!

This is an example how output looks like for `user_add` API command: https://freeipa--6423.org.readthedocs.build/en/6423/api/user_add.html

I guess, immediate improvements we could get are:
- convert `<class 'str'>` and similar classes that we can know about into a readable Python class name
- add a column for IPA option class name and ideally reference it to that option class documentation, when created. For example,  `gecos` uses `ipalib.parameters.Str` class which accepts Python `str`.
- may be turn the table of options into somewhat different format to allow displaying parameters of each option separately? This would allow to show defaults, limits, etc.

I am not sure how many of those would be easily introspected as limits are often derived through lambdas but it would be nice to find out those and have them covered in the semantics section.

**Comment by rcritten** [comment]
Currently makeapi ignores a whole ton of options which is probably one of the restricting factors (max, min, etc). The only default values appear to be boolean.

**Comment by antoniotorresm** [comment]
Just updated the option list, now it shows as a bullet list instead of a table. If there's a default it will show it, and for Enum options the list of values is shown.

@rcritten I access the options just by iterating `api.Command()` and then `cmd.options()`. Maybe there are filters applied by default?

**Comment by antoniotorresm** [comment]
Improved the format of data types as well. I'm not sure if we can link IPA types to a page in the reference since currently we only process commands under `api.Command().` Is there any way to list available data types?

**Comment by rcritten** [comment]
I didn't look in detail at how you're creating the text. I was referring to makeapi.PARAM_IGNORED_KW_ATTRIBUTES

You may be able to use introspection to find all the Param subclasses in ipalib.parameters. But you can probably get away with faking it. You should have a Param type. We know those are all defined in ipalib.parameters, so I think a "cheat" here would be fine. I don't know how you could link it to the source code though.

See the param_repr() function for how makeapi writes the Param name in API.txt.

**Comment by antoniotorresm** [comment]
Updated to show IPA Parameters as well. I added links to their pages but I'm not sure about which info we should use to fill these.

**Comment by rcritten** [comment]
I have mixed feelings on including the type with Default and Values. On one hand being explicit about things is good. On the other it seems distracting, especially when the value type is different from the option type StrEnum/str, Flag/bool. I don't have anything constructive to offer other than this observation.

For example:
```
ipauserauthtype : [StrEnum](https://freeipa--6423.org.readthedocs.build/en/6423/api/StrEnum.html#strenum)

    Values: (‘password’, ‘radius’, ‘otp’, ‘pkinit’, ‘hardened’, ‘idp’) (str)

...

nsaccountlock : [Bool](https://freeipa--6423.org.readthedocs.build/en/6423/api/Bool.html#bool)

    Default: False (bool)
```

**Comment by antoniotorresm** [comment]
That makes sense. Removed the type from Default/Values. Still unsure about what to add to type pages.

**Comment by abbra** [comment]
LGTM as a starting point. Let's handle improvements in separate pull requests.

**Comment by rcritten** [comment]
Is/should there be an upstream ticket associated with this to track the work and the remaining work?

It looks like at least:
* the parameters need to be filled out
* In a lot of cases the top-level plugin __doc__contains most of the documentation but that isn't represented here. Perhaps each command should be below each plugin type.

**Comment by antoniotorresm** [comment]
>  In a lot of cases the top-level plugin __doc__contains most of the documentation but that isn't represented here. Perhaps each command should be below each plugin type.

We already include `__doc__` at command level, but we can't do so at plugin level since it mainly includes info about the CLI usage. See user plugin, for example:

https://github.com/freeipa/freeipa/blob/38728dd518fbdfef692aa94230298901f42e6071/ipaserver/plugins/user.py#L102-L121

**Comment by rcritten** [comment]
That's true, then we should create a note to expand on the plugin commands to more than "Add <object name>"

**Comment by rcritten** [comment]
master:

* 988cb5a5357171e509ae5d346c96216a1c5325a3 doc: generate API Reference
* 4caa5ca5773bd239b27e0b2a4af8e06ba0e1f782 Add basic API usage guide

**Pull request closed without merging**
