### PR TITLE
WebUI: Apply jQuery patch to fix htmlPrefilter issue

### PR DESCRIPTION
**Pull request by serg-cymbaluk**
Manually backport corresponding changes from jQuery 3.5.0:
jquery/jquery@1d61fd9

A complete upgrade to jQuery 3.5 is impossible at the moment due incompatibility
with Bootstrap 3.4.1 which we currently use.

Ticket: https://pagure.io/freeipa/issue/8325

### CODE REVIEW

**Comment by serg-cymbaluk** [comment]
@flo-renaud @rcritten
Hi
Could you please take a quick look at the PR?

**Comment by serg-cymbaluk** [comment]
@pvoborni @flo-renaud 

I've added an explanation to commit message about a reason of choosing the patch instead of a full upgrade.

**Comment by flo-renaud** [comment]
@serg-cymbaluk 
thanks for the update, LGTM.

**Comment by flo-renaud** [comment]
Hi @serg-cymbaluk 
tests are green, you can remove the temp commit.

**Comment by flo-renaud** [comment]
master:

* bc9f3e0557c6a0a5901fff956f9cb1362085375f WebUI: Apply jQuery patch to fix htmlPrefilter issue

**Pull request closed without merging**
