### PR TITLE
Tests: Fix cert revocation tests

### PR DESCRIPTION
**Pull request by mirielka**
A bunch of certplugin tests were testing number of revoked certificates with
various revocation reasons. Since existence of revoked certificates often
depends on other parts of IdM than IPA, it is not really valid to check their
presence unless creation of revoked certificate is intentionally tested.

https://fedorahosted.org/freeipa/ticket/6349

### CODE REVIEW

**Comment by pvomacka** [comment]
I think that it is not good idea to remove tests, because we are lowering coverage. Therefore NACK. 

Could we rather rewrite these tests? For example issue certain certificates, revoke them and then test whether there are revoked certs with correct revocation reason. I think that our Tracker could help with it.

**Comment by mirielka** [comment]
Hi, I discussed this with Rob who authored the tests and he said that these tests were there just as a kind of checking that no extra revoked certificates get in. Tests are cca 4 years old, revoked certificates do get in e.g. due to changes in Dogtag (they can be created by other tests and can't be deleted) and cert tests fail. Creating new tests as you described (create cert, revoke it and check it's in the database with correct info) could be separate task, since these tests didn't do such think, they just checked what's already in regardless of how it got there.

**Comment by pvomacka** [comment]
Yes, that's true and I understand that these tests depend on previous actions. 

What I actually wanted to say is that I think that we should rather rewrite these tests right now instead of just removing them.

**Comment by alichbox** [comment]
Ok, I would vote for the new tests and when we have them merged we can safely delete this part of code that is not relevant anymore. The reason we would leave the current (not relevant tests) here is to not loose the information that we need to cover that part.
So my proposal: 1) leave these tests here as they are; 2) write new test suite; 3) delete the old tests; Does it make sense?

**Comment by mirielka** [comment]
Ok, I will do it like Ales proposed and will sync this PR when new tests are ready.

**Comment by pvomacka** [comment]
Hi alichbox, 
I agree with steps you are proposing, it does make sense.

**Comment by pvomacka** [comment]
Works correctly. ACK

**Comment by mbasti-rh** [comment]
`Tests: Certificate revocation` doesn't apply to ipa-4-4 branch, please open separate PR against IPA 4.4

**Comment by mbasti-rh** [comment]
Fixed upstream
master:
https://fedorahosted.org/freeipa/changeset/c9c92e3a7f4961d91e0395daf17f5aeb34c20178
https://fedorahosted.org/freeipa/changeset/8f04d1a793b8ff01804bc03eac9b7aaa4f7a7f78

**Pull request closed without merging**
