### PR TITLE
Fix for test TestInstallMasterReservedIPasForwarder

### PR DESCRIPTION
**Pull request by gkaihorodova**
Minor fix to enable test case for proper run in our testing environment

### CODE REVIEW

**Comment by slaykovsky** [comment]
Hello @gkaihorodova 

I believe the `ipatests/test_integration/test_trust.py` got in this PR by mistake :)

**Comment by stlaz** [comment]
Could you please describe more thoroughly in the commit message what exactly you're fixing? Something like:
```
trust test: adding input to nanana

Previously, the test tralala was failing because nahnahnah. This commit
fixes it by providing pffft to the installer so that tahdahdah.
```

**Comment by gkaihorodova** [comment]
Yes, sure will do. Thank you guys for your comments.

**Comment by slaykovsky** [comment]
Hi @gkaihorodova 

Will ack after CI is ok.

**Comment by tiran** [comment]
master:

* 518e3578d12c1189ef4c7e6c60eef8fe762ef786 Fix for test TestInstallMasterReservedIPasForwarder

**Pull request closed without merging**
