### PR TITLE
authconfig.py: restore user-nsswitch.conf at uninstall time

### PR DESCRIPTION
**Pull request by fcami**
authconfig.py: restore user-nsswitch.conf at uninstall time
    
Calling authselect at uninstall time before restoring user-nsswitch.conf
would result in a sudoers entry in nsswitch.conf which is not activated
in the default sssd authselect profile.
Make sure user-nsswitch.conf is restored before calling authselect.
    
Fixes: https://pagure.io/freeipa/issue/8054

### CODE REVIEW

**Comment by fcami** [comment]
link to nfs test results: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/56dfa73c-ca5d-11e9-94f2-fa163e643683/
link to nfs_nsswitch_restore test results: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/692a3092-ca5d-11e9-a12e-fa163edb55d0/

**Comment by t-woerner** [comment]
LGTM
Please remember to remove the temporary commit before merging.

**Comment by t-woerner** [comment]
LGTM

**Comment by fcami** [comment]
Temp commit removed.

**Comment by fcami** [comment]
master:

* 03a228aaf6418a93b2a59bef46a94c9bf7528077 ipatests: remove xfail in TestIpaClientAutomountFileRestore
* 73f049c75f0b1ed269cb8ebcb5c2158d2bc8b614 authconfig.py: restore user-nsswitch.conf at uninstall time

**Pull request closed without merging**
