### PR TITLE
Py3: fix fetching of tar files

### PR DESCRIPTION
**Pull request by tiran**
pytest_multihost does not support binary stdout stream yet,
https://pagure.io/python-pytest-multihost/issue/7 . Write logs to
temporary file and use host.get_file_content() to fetch them.

https://pagure.io/freeipa/issue/7131

Signed-off-by: Christian Heimes <cheimes@redhat.com>

### CODE REVIEW

**Comment by tiran** [comment]
PEP 8 error is unrelated to this PR: ``./ipalib/util.py:391:80: E501 line too long (81 > 79 characters)``

**Comment by Rezney** [comment]
Thanks for the patch. Run 2 tests, the errors are gone and the logs are available. LGTM.

**Comment by stlaz** [comment]
LGTM.

**Comment by stlaz** [comment]
master:

* 3ca77456ee9de86ae70fb3fa287151d7d4e9b89a Py3: fix fetching of tar files

**Pull request closed without merging**
