### PR TITLE
add missing tests to pr-ci definition files for nightly runs

### PR DESCRIPTION
**Pull request by wladich**

### CODE REVIEW

**Comment by wladich** [comment]
@tiran 
Temp commit removed, tests are green.

**Comment by wladich** [comment]
The PR have peen amended, temp commit added

**Comment by wladich** [comment]
All tests passed, no failures and skipped tests.

**Comment by flo-renaud** [comment]
Hi @wladich 
thanks for the PR. The list of tests to be added LGTM, please remove the temp commit and I will ack.

**Comment by flo-renaud** [comment]
Re-running `fedora-latest/test_membermanager` which failed while installing the server, random failure already reported in [8096](https://pagure.io/freeipa/issue/8096)

**Comment by flo-renaud** [comment]
All tests are green, ACK.

**Comment by wladich** [comment]
master:

* 5e44fc80b8e0ca09a57fad854fb70e616b1c41d2 ipatests: add test_fips to testing-fedora nightly run
* e927396851a2d24409ca3972d21804c83c14e502 ipatests: add test_automember to "previous" nightly run
* a2dee05b168ca1651c145d239da7bb5c1a8b3865 ipatests: add AD DC as a DNS forwarder before establishing trust
* 98b6326a8e4c906ef267f838eb755898305186ce ipatests: explicitly save output of certutil
* b8e1a7d5ae73bffa745e8417968cef0b77892cc3 ipatests: run all cases from test_integration/test_idviews.py in nightlies
* 99a322a4ae3c6a66d1e52517ee17c9b9c1b902e0 ipatests: run test_integration/test_cert.py in PR-CI
* 1c4aa66b3cdf56a14f01c6750c494914e4d651eb ipatests: add missing classes from test_installation in nightly runs
* 9b3c3202ca14da9be13bd976ea82d02f614b319c ipatests: add missing classes from test_nfs in nightly_previous run

**Pull request closed without merging**
