### PR TITLE
Fix grammar in login screen

### PR DESCRIPTION
**Pull request by tiran**
https://pagure.io/freeipa/issue/7263
https://pagure.io/freeipa/issue/7258

Signed-off-by: Christian Heimes <cheimes@redhat.com>

### CODE REVIEW

**Comment by flo-renaud** [comment]
Hi @tiran,

thank you for the patch. There is also a "Login" button in the login screen, and help text (for instance "To login with username and password...." that should be updated, too.

**Comment by tiran** [comment]
Thanks Flo, I replaced some ``To login with`` with ``To log in with``.

**Comment by pvoborni** [comment]
This PR seems stuck. @pvomacka or @flo-renaud , do you plan to look at it?

**Comment by pvomacka** [comment]
@tiran @pvoborni I will do the review.

**Comment by tiran** [comment]
master:

* 3756dbf964364c527454041d3501c1c96ed817a1 Fix grammar in login screen
* ae3160fdd78546f0859522f05677309e149a2715 Fix grammar error: Log out
* dca9f84961bdcde7ee062b2cb2fee9013814b568 Address more 'to login'
* b32a4aef8656319dd07e697871187693e6679b0d More log in verbs

**Pull request closed without merging**
