### PR TITLE
PR-CI extend timeouts

### PR DESCRIPTION
**Pull request by Rezney**
extend timeout with one hour as timed out many times in PRCI nightly
- test_dnssec
- test_replication_layouts_TestLineTopologyWithCA
- test_replication_layouts_TestLineTopologyWithCAKRA
- test_replication_layouts_TestStarTopologyWithCAKRA
- test_server_del
- test_webui

Signed-off-by: Pavel Picka <ppicka@redhat.com>

### CODE REVIEW

**Comment by Tiboris** [comment]
There should not be anything to argue about here :+1:

**Comment by flo-renaud** [comment]
+1 to @Tiboris comment

**Comment by Tiboris** [comment]
And thanks @Rezney for looking at PR-CI

**Comment by Tiboris** [comment]
master:

* b5fa64edbc562d545ac1d3d6adbc31484330eeb3 PR-CI extend timeouts

**Pull request closed without merging**
