### PR TITLE
Set client keytab location for 389ds

### PR DESCRIPTION
**Pull request by frozencemetery**
Handles behavior change in
https://github.com/389ds/389-ds-base/pull/4523

Fixes: https://pagure.io/freeipa/issue/8656

(It may be preferable to wait until the 389ds PR is closed, but I wanted to show the change needed for that.)

### CODE REVIEW

**Comment by rcritten** [comment]
This needs to be rebased to fix the Azure failures. Looks like the other two failures are known issues and a re-run usually passes.

**Comment by frozencemetery** [comment]
Rebased.  389ds change has merged, so this is ready.

**Comment by abbra** [comment]
LGTM

**Comment by abbra** [comment]
master:

* 9b2f5fe6df84de74801a24802fd5882c969a1edd Set client keytab location for 389ds

**Pull request closed without merging**
