### PR TITLE
[Backport][ipa-4-8] ipatests: test Samba mount with NTLM authentication

### PR DESCRIPTION
**Pull request by wladich**
This PR was opened automatically because PR #5570 was pushed to master and backport to ipa-4-8 is required.

### CODE REVIEW

**Comment by wladich** [comment]
PR was ACKed automatically because this is backport of PR #5570. Wait for CI to finish before pushing. In case of questions or problems contact @wladich who is author of the original PR.

**Comment by flo-renaud** [comment]
FYI, PR-CI tests for ipa-4-8 branch are installing 4.9.2 packages, see freeipa/freeipa-pr-ci#419. We can't rely currently on the test results on this branch.

**Comment by wladich** [comment]
So removing ACK for now

**Comment by wladich** [comment]
Waiting for #5594 and https://github.com/freeipa/freeipa-pr-ci/pull/421

**Comment by wladich** [comment]
Since FreeIPA is now installed from test repo again and all test results are green, I am restoring ACK label.

**Comment by wladich** [comment]
ipa-4-8:

* fc7bcc673a1f43b981e478f2ffff15188dce42fb ipatests: test Samba mount with NTLM authentication

**Pull request closed without merging**
