### PR TITLE
[Backport][ipa-4-9] ipatests: increase timeout for test_commands up to 1.5 hours

### PR DESCRIPTION
**Pull request by wladich**
This is a manual backport of #5748

### CODE REVIEW

**Comment by rcritten** [comment]
Should this be seen as irony? Is 90 minutes not enough?

**Comment by wladich** [comment]
@rcritten 
The test suite did not timeout, it ran for 45 minutes. It is a normal test failure.

**Comment by wladich** [comment]
The observed failure is a known [issue](https://pagure.io/freeipa/issue/8785)

ACKing the PR as it is a backport.

**Comment by wladich** [comment]
ipa-4-9:

* a1ed05d7f91cf78e6d704dbf6051c72314973140 ipatests: increase timeout for test_commands up to 1.5 hours

**Pull request closed without merging**
