### PR TITLE
removed unused function export_pem_p12

### PR DESCRIPTION
**Pull request by frasertweedale**
Noticed the def was unreferenced so here's a drive-by cleanup PR.

### CODE REVIEW

**Comment by rcritten** [comment]
This needs a rebase to pass pylint.

The removal looks ok to me. The fn was moved in 2017 from CertDB and nobody complained about that breaking anything so it should be fine to drop.

**Comment by frasertweedale** [comment]
Finally revived this PR.  @rcritten I can haz ACK?

**Comment by flo-renaud** [comment]
Hi @frasertweedale 
Thanks for the PR, LGTM.

**Comment by flo-renaud** [comment]
master:

* aa9340cfdb5408176e8274aeb9aeba9132b5031d removed unused function export_pem_p12

**Comment by frasertweedale** [comment]
@flo-renaud thanks for review + merge!

**Pull request closed without merging**
