### PR TITLE
WebUI: Add support for AD users short name resolution

### PR DESCRIPTION
**Pull request by pvomacka**
https://pagure.io/freeipa/issue/6372

### CODE REVIEW

**Comment by pvoborni** [comment]
LGTM

**Comment by pvoborni** [comment]
ACK if backend won't change

**Comment by pvomacka** [comment]
@simo5 I changed the subject, do you have any suggestion what you would like to see in commit message? I think that this is quite easy and self-explanatory patch.

**Comment by MartinBasti** [comment]
master:

* 2c194d793cd588d595c5ff639fbf5dac93e50e23 WebUI: Add support for management of user short name resolution

**Pull request closed without merging**
