### PR TITLE
CAless installation: set the perms on KDC cert file

### PR DESCRIPTION
**Pull request by flo-renaud**
###  CAless installation: set the perms on KDC cert file

In CA less installation, the KDC certificate file does not have
the expected 644 permissions. As a consequence, WebUI login
fails.

The fix makes sure that the KDC cert file is saved with 644 perms.

Fixes: https://pagure.io/freeipa/issue/8440

###  ipatests: check KDC cert permissions in CA less install

The KDC certificate file must be stored with 644 permissions.
Add a test checking the file permissions on server + replica.

Related: https://pagure.io/freeipa/issue/8440

### CODE REVIEW

**Comment by flo-renaud** [comment]
As the issue is also present on ipa-4-6 branch, adding relevant labels.

**Comment by rcritten** [comment]
Looks good. I noticed that /etc/ipa/ca.crt gets different permissions in a CA-less installation as well, 0444 rather than 0644 in a  dogtag install. I'll investigate that separately.

Please remove the temp commit and I'll ack.

**Comment by flo-renaud** [comment]
@rcritten thanks for the review. Temp commit removed.

**Comment by rcritten** [comment]
master:

* 9335bd9299e54928a057cbd31de40aca0ef207b2 CAless installation: set the perms on KDC cert file
* a26e0ba558aa76323d90b807f2201992d6ee58b4 ipatests: check KDC cert permissions in CA less install

**Pull request closed without merging**
