### PR TITLE
[Azure] Add rawhide definitions

### PR DESCRIPTION
**Pull request by stanislavlevin**
- allow override variables template file with an externally provided one. This allows adding new Azure Pipeline which will point to a custom platform definition. Note: Azure's WebUI variables are runtime variables and not available at parsing time, that's why it's impossible to override template from WebUI in this case.

- add Rawhide templates

- add Dockerfile for build Docker image for tests phase
Note: 'fedora:rawhide' is too old, use for now 'registry.fedoraproject.org/fedora:rawhide'. See, https://bugzilla.redhat.com/show_bug.cgi?id=1869612

Use case:
- make it possible to trigger several CIs with different definitions on a push to a branch.
The Pipeline configuration file and tests definitions should be in a target branch.

### CODE REVIEW

**Comment by stanislavlevin** [comment]
Results are far from success:
https://dev.azure.com/slev0400/slev/_build/results?buildId=1846&view=results
At least, build passed.

**Comment by abbra** [comment]
Thanks. Rawhide is currently failing due to dogtag using JDK11 which it is not prepared for. This is going to be reverted, tracked with https://bugzilla.redhat.com/show_bug.cgi?id=1866570 which is F33 blocker.

**Comment by stanislavlevin** [comment]
Related issues:
https://pagure.io/freeipa/issue/8468
https://pagure.io/freeipa/issue/8469

There is Tox failure(didn't dig into, but it looks like `virtualenv` issue).

**Comment by cipherboy** [comment]
@stanislavlevin -- I believe I've fixed the JDK11 issues in Rawhide+F33. Do you mind rebasing this PR to see if I caught everything? Thanks!

**Comment by abbra** [comment]
Failures due to this:
```
2020-08-27T10:23:34.6456452Z 1	[2020-08-27 10:23:33]   [error] AttributeError: 'NSSDatabase' object has no attribute 'secdir'
2020-08-27T10:23:34.6457423Z 1	[2020-08-27 10:23:33] 'NSSDatabase' object has no attribute 'secdir'
2020-08-27T10:23:34.6458789Z 1	[2020-08-27 10:23:33] The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information
2020-08-27T10:23:34.6459904Z 1	[2020-08-27 10:23:33] Exception ignored in: <function CertDB.__del__ at 0x7f91b943e310>
2020-08-27T10:23:34.6460560Z 1	[2020-08-27 10:23:33] Traceback (most recent call last):
2020-08-27T10:23:34.6461464Z 1	[2020-08-27 10:23:33]   File "/usr/lib/python3.8/site-packages/ipaserver/install/certs.py", line 233, in __del__
2020-08-27T10:23:34.6462153Z 1	[2020-08-27 10:23:33]     if self.reqdir is not None:
2020-08-27T10:23:34.6463027Z 1	[2020-08-27 10:23:33] AttributeError: 'CertDB' object has no attribute 'reqdir'

```

**Comment by stanislavlevin** [comment]
> Failures due to this:
> 
> ```
> 2020-08-27T10:23:34.6456452Z 1	[2020-08-27 10:23:33]   [error] AttributeError: 'NSSDatabase' object has no attribute 'secdir'
> 2020-08-27T10:23:34.6457423Z 1	[2020-08-27 10:23:33] 'NSSDatabase' object has no attribute 'secdir'
> 2020-08-27T10:23:34.6458789Z 1	[2020-08-27 10:23:33] The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information
> 2020-08-27T10:23:34.6459904Z 1	[2020-08-27 10:23:33] Exception ignored in: <function CertDB.__del__ at 0x7f91b943e310>
> 2020-08-27T10:23:34.6460560Z 1	[2020-08-27 10:23:33] Traceback (most recent call last):
> 2020-08-27T10:23:34.6461464Z 1	[2020-08-27 10:23:33]   File "/usr/lib/python3.8/site-packages/ipaserver/install/certs.py", line 233, in __del__
> 2020-08-27T10:23:34.6462153Z 1	[2020-08-27 10:23:33]     if self.reqdir is not None:
> 2020-08-27T10:23:34.6463027Z 1	[2020-08-27 10:23:33] AttributeError: 'CertDB' object has no attribute 'reqdir'
> ```
Yes, my bad, fixed.

**Comment by stanislavlevin** [comment]
So, for now, 1 issue remains:
https://dev.azure.com/slev0400/slev/_build/results?buildId=1941&view=logs&j=c3b3beac-3142-545b-181b-8ae72407437a
Will try to check tomorrow morning.

**Comment by stanislavlevin** [comment]
For now, all of the new errors were fixed.
https://dev.azure.com/slev0400/slev/_build/results?buildId=1983&view=logs&j=c3b3beac-3142-545b-181b-8ae72407437a

**Comment by abbra** [comment]
Thanks! LGTM.

**Comment by abbra** [comment]
master:

* 0d326a9097c6fe5f1eb6d30340aedbe9200c3d37 Azure: Add Rawhide definitions
* 60ff2841cd74706a5ebd40924f11ad3defaa1750 Azure: Drop dependency on UsePythonVersion task
* a5b23287aeddd32b129d4c97e6354900c8b931ec Azure: base: Collect both install and uninstall logs
* a102cfe5faf28b801d2ad3570477ef9dd5c0d5f1 nss: Raise exception earlier on unsupported DB type
* f3d10871300498150c41f3acc154688f1ee48ceb deps: Require `nss-tools` for make's fasttest target
* 30cf59d0ae39e83f3590152aec19e466dbc3623a Azure: Increase verbosity for Tox task
* fdb227e55ab976fb26ef417df1e4a842d3280f5c tox: Don't expand symlinks
* 49e643783d22ded7a44d84599020af4e8a3d4d5a dnspython: Add compatibility shim

**Comment by abbra** [comment]
@stanislavlevin Since ipa-4-8 doesn't have ACME support yet, please do a manual backport:

```
Applying to ipa-4-8: Azure: Add Rawhide definitions
Applying to ipa-4-8: Azure: Drop dependency on UsePythonVersion task
Applying to ipa-4-8: Azure: base: Collect both install and uninstall logs
Applying to ipa-4-8: nss: Raise exception earlier on unsupported DB type
Applying to ipa-4-8: deps: Require `nss-tools` for make's fasttest target
Applying to ipa-4-8: Azure: Increase verbosity for Tox task
Applying to ipa-4-8: tox: Don't expand symlinks
Applying to ipa-4-8: dnspython: Add compatibility shim
Failure to apply patches: error: client/certbot-dns-ipa.in: does not exist in index
hint: Use 'git am --show-current-patch=diff' to see the failed patch

Failed to apply patches onto origin/ipa-4-8. Manual backport is needed.
Cleaning up

```

**Comment by stanislavlevin** [comment]
@abbra, thank you for the review.
backport for `ipa-4-8`: https://github.com/freeipa/freeipa/pull/5069

**Pull request closed without merging**
