### PR TITLE
replication: check remote ds version before editing attributes

### PR DESCRIPTION
**Pull request by flo-renaud**
When the remote server has an old DS version, update of the
replication attributes nsds5ReplicaReleaseTimeout nsds5ReplicaBackoffMax
and nsDS5ReplicaBindDnGroupCheckInterval fails even if the remote
schema has been updated.

Check first the remote server version and update the attributes only if
the version is high enough.
A previous fix was already performing this check (commit 02f4a7a),
but not in all the cases. This fix also handles when the remote server
already has a cn=replica entry (for instance because it has already
established replication with another host).

Fixes https://pagure.io/freeipa/issue/7796

### CODE REVIEW

**Comment by tiran** [comment]
Thanks for the fix!

**Comment by flo-renaud** [comment]
Setting WIP as I would like to test when deploying a new replica with an old master (for instance rhel 6.8 master).

**Comment by flo-renaud** [comment]
Removing WIP. I did a build with the same patch on ipa-4-6, installed 2 replicated RHEL 6.8 masters and created a replica file for my new 4.6 replica with ipa-replica-prepare. Install went successfully.
(Note: I backported to ipa-4-6 in order to have domain level 0 support).

**Comment by tiran** [comment]
Thanks for fixing my mess, Flo! :100:

**Comment by tiran** [comment]
master:

* faa122a8b8fc9a6850811ed1466166a7bff13be3 replication: check remote ds version before editing attributes

**Pull request closed without merging**
