### PR TITLE
Tox testing support for client wheel packages

### PR DESCRIPTION
**Pull request by tiran**
Add tox infrastructure to test client wheel packages workflow:

* build client packages
* install client packages
* ipa-run-tests --ipaclient-unittests under Python 2 and 3
* pylint of client packages under Python 2 and 3
* placeholder packages work as expected

### CODE REVIEW

**Comment by tiran** [comment]
Tox testing should also be integrated into Travis CI to catch bugs like https://pagure.io/freeipa/issue/6816. The tox script will automatically test features like ```./configure --disable-server```, ```bdist_wheel``` and ```wheel_bundle```.

**Comment by MartinBasti** [comment]
I ran `tox` and I received following output:

```
ERROR:   py27: could not install deps [ipaclient, ipatests]; v = InvocationError('/tmp/freeipa/.tox-install.sh wheel_bundle /tmp/freeipa/.tox/py27/bin/python /tmp/freeipa/.tox/py27/lib/python2.7/site-packages ipaclient ipatests (see /tmp/freeipa/.tox/py27/log/py27-1.log)', 2)
ERROR:   py35: could not install deps [ipaclient, ipatests]; v = InvocationError('/tmp/freeipa/.tox-install.sh wheel_bundle /tmp/freeipa/.tox/py35/bin/python /tmp/freeipa/.tox/py35/lib/python3.5/site-packages ipaclient ipatests (see /tmp/freeipa/.tox/py35/log/py35-1.log)', 2)
ERROR:   py36: could not install deps [ipaclient, ipatests]; v = InvocationError('/tmp/freeipa/.tox-install.sh wheel_bundle /tmp/freeipa/.tox/py36/bin/python /tmp/freeipa/.tox/py36/lib/python3.6/site-packages ipaclient ipatests (see /tmp/freeipa/.tox/py36/log/py36-1.log)', 2)
ERROR:   pylint2: could not install deps [ipaclient, ipapython[certmonger], pylint]; v = InvocationError('/tmp/freeipa/.tox-install.sh wheel_bundle /tmp/freeipa/.tox/pylint2/bin/python /tmp/freeipa/.tox/pylint2/lib/python2.7/site-packages ipaclient ipapython[certmonger] pylint (see /tmp/freeipa/.tox/pylint2/log/pylint2-1.log)', 2)
ERROR:   pylint3: could not install deps [ipaclient, ipapython[certmonger], pylint]; v = InvocationError('/tmp/freeipa/.tox-install.sh wheel_bundle /tmp/freeipa/.tox/pylint3/bin/python /tmp/freeipa/.tox/pylint3/lib/python3.5/site-packages ipaclient ipapython[certmonger] pylint (see /tmp/freeipa/.tox/pylint3/log/pylint3-1.log)', 2)
  pypi: commands succeeded
```

Is it expected?

I had applied following patches:

* Correct PyPI package dependencies
* Stabilize make pypi_packages
* Replace hard-coded kdcproxy path with WSGI script

**Comment by tiran** [comment]
Why are you mixing PRs? Don't mix PRs.

**Comment by tiran** [comment]
I've rebased the branch on master, just in case. Tox works for me before and after rebase.

```
$ git clean -xdf
$ tox
...
  py27: commands succeeded
  py35: commands succeeded
  py36: commands succeeded
  pylint2: commands succeeded
  pylint3: commands succeeded
  pypi: commands succeeded
  congratulations :)
```

**Comment by tiran** [comment]
I added tox to wheel build requirements. Now you can install all dependencies with dnf builddep.

```
$ sudo dnf copr enable @freeipa/freeipa-master
$ sudo dnf install redhat-rpm-config
$ sudo dnf builddep --spec freeipa.spec.in --define "with_wheels 1"
$ tox
```

**Comment by MartinBasti** [comment]
Thanks, I'll try again, it needs rebase again

**Comment by MartinBasti** [comment]
Thnks, works for me.

**Comment by MartinBasti** [comment]
master:

* 3a5b3be8b92a509d207d814c9fe294ee7b4e81c4 tox testing support for client wheel packages

**Pull request closed without merging**
