### PR TITLE
Py3 adtrust

### PR DESCRIPTION
**Pull request by MartinBasti**

### CODE REVIEW

**Comment by abbra** [comment]
I think you also can explicitly raise samba dependency version to 4.7.0 or above. Nothing else provides python3-samba subpackage.

**Comment by MartinBasti** [comment]
We will need to bump samba to even higher version anyway to a newer version because not everything what we need is accessible in py3 (`samba.dcerpc` for example)

**Comment by stlaz** [comment]
The troubled imports do not show on my Fedora 26 machine. Could we speed up the review of https://github.com/freeipa/freeipa/pull/992 to finally get f26 into our testing containers?
I suppose this might be some kind of pylint screw up which might be fixed in later versions.

**Comment by stlaz** [comment]
Since Travis build is constantly failing, I tried to work around that including this in another PR: https://github.com/freeipa/freeipa/pull/1052

**Pull request closed without merging**
