### PR TITLE
WebUI: Fix object class evaluator for user details facet

### PR DESCRIPTION
**Pull request by Carbenium**
Use data adapter in evaluator to be able to deal with batch
RPC responses.

Related: https://pagure.io/freeipa/issue/8336

### CODE REVIEW

**Comment by abbra** [comment]
LGTM. @serg-cymbaluk @pvoborni could you please review as well?

**Comment by pvoborni** [comment]
Hi, thanks for the contribution. 

Patch: "WebUI: Unify adapter property definition for state evaluators " looks good to me. And I'm fine with merging it.

This PR is implementing only first part of https://pagure.io/freeipa/issue/8336 but I don't think that it is needed for the indented functionality (hiding the section of user doesn't have rights for it / having no value there). 

Hiding the section can be accomplished by: 
```javascript
diff --git a/install/ui/src/freeipa/user.js b/install/ui/src/freeipa/user.js
index 48b4e676f..c3232c802 100644
--- a/install/ui/src/freeipa/user.js
+++ b/install/ui/src/freeipa/user.js
@@ -367,36 +367,39 @@ return {
                 {
                     name: 'smb_attributes',
                     label: '@i18n:objects.smb_attributes.title',
-                    show_cond: ['oc_ipantuserattrs'],
                     fields: [{
                             name: 'ipantlogonscript',
                             tooltip: {
                                 title: '@i18n:objects.smb_attributes.ipantlogonscript_tooltip'
-                            }
+                            },
+                            hidden_if_empty: true
                         },
                         {
                             name: 'ipantprofilepath',
                             tooltip: {
                                 title: '@i18n:objects.smb_attributes.ipantprofilepath_tooltip'
-                            }
+                            },
+                            hidden_if_empty: true
                         },
                         {
                             name: 'ipanthomedirectory',
                             tooltip: {
                                 title: '@i18n:objects.smb_attributes.ipanthomedirectory_tooltip'
-                            }
+                            },
+                            hidden_if_empty: true
                         },
                         {
                             name: 'ipanthomedirectorydrive',
                             $type: 'select',
                             options: IPA.create_options([
-                                'A:', 'B:', 'C:', 'D:', 'E:', 'F:', 'G:', 'H:', 'I:',
-                                'J:', 'K:', 'L:', 'M:', 'N:', 'O:', 'P:', 'Q:', 'R:',
-                                'S:', 'T:', 'U:', 'V:', 'W:', 'X:', 'Y:', 'Z:'
+                                '', 'A:', 'B:', 'C:', 'D:', 'E:', 'F:', 'G:', 'H:',
+                                'I:', 'J:', 'K:', 'L:', 'M:', 'N:', 'O:', 'P:', 'Q:',
+                                'R:', 'S:', 'T:', 'U:', 'V:', 'W:', 'X:', 'Y:', 'Z:'
                             ]),
                             tooltip: {
                                 title: '@i18n:objects.smb_attributes.ipanthomedirectorydrive_tooltip'
-                            }
+                            },
+                            hidden_if_empty: true
                         }
                     ]
                 }
@@ -482,11 +485,6 @@ return {
                     IPA.user.self_service_other_user_evaluator,
                     IPA.user.preserved_user_evaluator,
                     IPA.user.is_locked_evaluator,
-                    {
-                        $factory: IPA.object_class_evaluator,
-                        name: 'object_class_evaluator',
-                        adapter: { $type: 'batch', result_index: 0 }
-                    },
                     IPA.cert.certificate_evaluator
                 ],
                 summary_conditions: [

```
The code above is also fixing the issue that `ipanthomedirectorydrive` is an optional param but the Web UI code is not offering "empty" (no) value. Given that it is a completely different approach, I opened a PR with it: https://github.com/freeipa/freeipa/pull/4787 (it also explains why it works)

Also there is a bug on CLI part: https://github.com/freeipa/freeipa/pull/4786

**Comment by Carbenium** [comment]
@pvoborni I'm fine with dropping `object_class_evaluator` from the user spec. I would rebase this PR once yours is merged.

**Comment by Carbenium** [comment]
@pvoborni rebased

**Comment by abbra** [comment]
PR 4722 is merged, so this one can be rebased.

**Comment by Carbenium** [comment]
@abbra The rebase is already done.

**Comment by Carbenium** [comment]
@pvoborni @abbra Is anything missing from this PR before it can be merged?

**Comment by abbra** [comment]
@Carbenium please rebase again so that pylint changes would be picked up and I will be able to run full set of tests. The PR looks OK itself.

**Comment by Carbenium** [comment]
@abbra rebase done

**Comment by abbra** [comment]
LGTM.

**Comment by flo-renaud** [comment]
master:

* df5526fbc71e9215456287dac396ca8a4d8082e3 WebUI: Make object_class_evaluator evaluator compatible with batch responses
* 2d87cd4ae1bf0bd7814fb53bcfb8540e479d842b WebUI: Unify adapter property definition for state evaluators

**Pull request closed without merging**
