### PR TITLE
Allow dnsrecord-add --force on clients

### PR DESCRIPTION
**Pull request by tiran**
See: https://pagure.io/freeipa/issue/8317
Signed-off-by: Christian Heimes <cheimes@redhat.com>

### CODE REVIEW

**Comment by abbra** [comment]
Another part that will fail is the test `test_permission_flags` which calls `_make_permission_flag_tests()` with `SYSTEM` permission flag. The test creates and then deletes the permission and without `--force` one cannot delete the system permissions.

I think we should actually move these tests to a normal test that can clean up resulting system permissions via direct LDAP modification. Perhaps, this could be a combined test of permission and upgrade plugin? Because upgrade plugin can return DNs of entries to remove.

**Comment by tiran** [comment]
I've reduced the PR to only allow force for dnsrecord-add.

**Comment by abbra** [comment]
LGTM.

**Comment by flo-renaud** [comment]
master:

* ad8e0af0770caf039ff6c431a3182238c1952f8f Allow dnsrecord-add --force on clients

**Pull request closed without merging**
