### PR TITLE
ipatests: smbclient "-k" => "--use-kerberos=required"

### PR DESCRIPTION
**Pull request by fcami**
As of Samba 4.15rc1, smbclient does not accept -k anymore.
The -k|--kerberos option ("Try to authenticate with kerberos."
has been replaced with "--use-kerberos=required|desired|off".

Change documentation:
https://download.samba.org/pub/samba/rc/samba-4.15.0rc1.WHATSNEW.txt

Fixes: https://pagure.io/freeipa/issue/8926
Signed-off-by: François Cami <fcami@redhat.com>

### CODE REVIEW

**Comment by fcami** [comment]
WIP label set: this needs a way to detect the samba version on the target system or try/except clause.

**Comment by fcami** [comment]
Detection code added using "smbclient -h".
Note two stacked temp commits, one for rawhide and one for f34.

**Comment by fcami** [comment]
Green run for rawhide: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/06497d02-e8d8-11eb-b1f1-5254007adcf0/

**Comment by fcami** [comment]
Green run for f34: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/c274fb16-e903-11eb-bcc0-525400be55b5/

**Comment by miskopo** [comment]
ACK, changes and runs are nice

**Comment by fcami** [comment]
master:

* cbe5151e1278cf0894e7f860745f8c77c9b6bdd9 ipatests: smbclient "-k" => "--use-kerberos=desired"

**Pull request closed without merging**
