### PR TITLE
ipaldap: remove do_bind from LDAPClient

### PR DESCRIPTION
**Pull request by tomaskrizek**
Remove do_bind() method that was a relict used in IPAdmin. Replace
its uses with simple / external binds.

https://fedorahosted.org/freeipa/ticket/6461

### CODE REVIEW

**Comment by mbasti-rh** [comment]
Fixed upstream
master:
https://fedorahosted.org/freeipa/changeset/a68c95d11612108375877ff45bdb53ce6fc8fbe4

**Comment by jcholast** [comment]
DM password may be `None` in `dns_container_exists()` and `dnssec_container_exists()` (for example in `BindInstance.setup()`), so you can't simple bind unconditionally.

**Comment by mbasti-rh** [comment]
```
ipaserver/install/ca.py:226: [W0612(unused-variable), install_step_1] Unused variable 'dm_password')
```

**Comment by martbab** [comment]
The fix works as expected. ACK.

Fixed upstream
master:
https://fedorahosted.org/freeipa/changeset/f183f70e0183e51d569ada972bd3ec73cad76a30

**Pull request closed without merging**
