### PR TITLE
[Backport][ipa-4-10] Include supported migration scenarios in the ipa-to-ipa docs

### PR DESCRIPTION
**Pull request by rcritten**
This PR was opened automatically because PR #7078 was pushed to master and backport to ipa-4-10 is required.

### CODE REVIEW

**Comment by rcritten** [comment]
PR was ACKed automatically because this is backport of PR #7078. Wait for CI to finish before pushing. In case of questions or problems contact @rcritten who is author of the original PR.

**Comment by rcritten** [comment]
@flo-renaud seems like we need to backport the switch to f39 to the 4.10 branch as well?

**Comment by flo-renaud** [comment]
> @flo-renaud seems like we need to backport the switch to f39 to the 4.10 branch as well?

@rcritten I have opened an issue for the tox failure: https://pagure.io/freeipa/issue/9507
and a smaller PR: https://github.com/freeipa/freeipa/pull/7143 so that we remain on f38 for ipa-4-10 branch

**Comment by rcritten** [comment]
ipa-4-10:

* 20e35d053bc6c90730d20f128bfa71dd3b278895 Include supported migration scenarios in the ipa-to-ipa docs

**Pull request closed without merging**
