### PR TITLE
Replace nose with unittest and pytest

### PR DESCRIPTION
**Pull request by tiran**
* Replace raise nose.SkipTest with raise unittest.SkipTest
* Replace nose.tools.assert_equal(a, b) with assert a == b
* Replace nose.tools.raises with pytest.raises
* Convert raises decorator to pytest.raises() but just for relevant lines
* Remove nose dependency

I left the nose_compat pytest plugin in place. It can be removed in
another request in case it is no longer used.

https://pagure.io/freeipa/issue/7301

Signed-off-by: Christian Heimes <cheimes@redhat.com>

### CODE REVIEW

**Comment by rcritten** [comment]
Can you include some of the verbiage from the ticket in the commit message so one won't need to dereference it?

**Comment by tiran** [comment]
Sure, I've to fix some PEP 8 violations any way.

```
./ipatests/test_integration/test_legacy_clients.py:394:80: E501 line too long (81 > 79 characters)
./ipatests/test_ipalib/test_text.py:105:80: E501 line too long (103 > 79 characters)
./ipatests/test_ipaserver/test_ldap.py:90:80: E501 line too long (83 > 79 characters)
./ipatests/test_ipaserver/test_ldap.py:114:80: E501 line too long (83 > 79 characters)
./ipatests/test_webui/ui_driver.py:154:80: E501 line too long (80 > 79 characters)
./ipatests/test_webui/ui_driver.py:206:80: E501 line too long (86 > 79 characters)
./ipatests/test_webui/ui_driver.py:208:80: E501 line too long (85 > 79 characters)
./ipatests/test_webui/ui_driver.py:221:80: E501 line too long (86 > 79 characters)
./ipatests/test_webui/ui_driver.py:223:80: E501 line too long (85 > 79 characters)
./ipatests/test_xmlrpc/test_dns_plugin.py:440:80: E501 line too long (101 > 79 characters)
./ipatests/test_xmlrpc/test_dns_plugin.py:3216:80: E501 line too long (101 > 79 characters)
./ipatests/test_xmlrpc/test_hbac_plugin.py:397:80: E501 line too long (85 > 79 characters)
./ipatests/test_xmlrpc/test_hbac_plugin.py:408:80: E501 line too long (80 > 79 characters)
./ipatests/test_xmlrpc/test_hbac_plugin.py:419:80: E501 line too long (94 > 79 characters)
./ipatests/test_xmlrpc/test_hbac_plugin.py:430:80: E501 line too long (83 > 79 characters)
./ipatests/test_xmlrpc/test_netgroup_plugin.py:1402:80: E501 line too long (85 > 79 characters)
```

**Comment by abbra** [comment]
LGTM.

**Comment by tiran** [comment]
master:

* d7426ccbe74e2868836f29d4f016cbeb8524f273 Replace nose with unittest and pytest

**Pull request closed without merging**
