### PR TITLE
Only apply warning to the local ID range

### PR DESCRIPTION
**Pull request by abbra**

### CODE REVIEW

**Comment by abbra** [comment]
@flo-renaud We need to apply the warnings to restart servers to the local ID range type only. This is continuation of the fix for https://pagure.io/freeipa/issue/9558. Please review.

**Comment by flo-renaud** [comment]
A few test changes are required, you can see a tentative patch at https://github.com/flo-renaud/freeipa/commit/3385f9de8ca0c60c311ca9f36aec339f6928c380

**Comment by flo-renaud** [comment]
Tested on fedora 39, idrange-add and idrange-del now correctly print the warning only for domain-local ranges.

**Comment by flo-renaud** [comment]
master:

* a57b665be027bd67b582cba784aca5f2f8399459 idrange: only issue warning to restart services for a local range
* 6cc668ffeb7ddd4ebd75304f14adaa3aaf3b4cb0 xmlrpc: adapt range plugin test

**Pull request closed without merging**
