### PR TITLE
ensuring 389-ds plugins are enabled after install

### PR DESCRIPTION
**Pull request by akokshar**
To avoid problems caused by desabled plugins on 389-ds side
explicitly enable plugins required by IPA

https://pagure.io/freeipa/issue/7271

### CODE REVIEW

**Comment by Firstyear** [comment]
Hey mate, this is great. I'm happy with this, because it means you can safely trust all plugins will work on upgrade, even if change 389 code.

I'm happy to ack this from the 389 side :) Thanks you so much for the fast patch given we only had this idea monday!

**Comment by Firstyear** [comment]
PS: I think you can eliminate 7-bit check, , HTTP Client,, Internationalization Plugin, Schema Reload, and Views.

**Comment by tiran** [comment]
Should we also ensure plugins in ``ipaserver.install.server.upgrade.upgrade_configuration()``?

**Comment by Firstyear** [comment]
Yes @tiran that's a great idea.

**Comment by akokshar** [comment]
@abbra, thank you. Will try to transform it into an update file.

This was one of my main question too. As I unerstood we want to make sure that IPA is not impacted in case 389-ds guys switch off some of the plugins which were previously enabled by default. So, 
- I interrupted installer at the point it just installed and started ldap
- checked what plugins are enabled 
- explicitly reenable them as a first step of the installer.

This way, we can be sure that all plugins we want (and might be more) are enabled.

**Comment by abbra** [comment]
I think you can re-use updater's infrastructure (e.g. loading and applying update files) in installer too. This way we could have both goals achieved.

**Comment by abbra** [comment]
@akokshar  please don't use merge to update your tree to master. Instead, use 'git rebase' and force push. Right now your commit 3227f6b includes a lot of unrelated changes.

**Comment by akokshar** [comment]
@abbra, my bad. cleaned it already.

I did transform the patch to use update file. Could you take a look please?

**Comment by abbra** [comment]
Looks good now. Thank you!

**Comment by tiran** [comment]
@Firstyear @abbra The PR looks ready to me.

**Comment by abbra** [comment]
I did LGTM already and as it passed all tests, ACK.

**Comment by tiran** [comment]
master:

* fbb188976637ac64e9661fec6cc51fa7215290a4 ensuring 389-ds plugins are enabled after install

**Pull request closed without merging**
