### PR TITLE
IPA-EPN: Test that EPN can be installed, uninstalled and re-installed

### PR DESCRIPTION
**Pull request by rcritten**
Verify that no cruft is left over that will prevent reinstallation
if it is uninstalled.

### CODE REVIEW

**Comment by rcritten** [comment]
Ok, so the package I download during install is deleted in the tests themselves by...something? The directory is still there but not the package.

**Comment by fcami** [comment]
You might want to copy it somewhere safe (/root/whatever) and use it from there. Any successful dnf invocation will clean the package cache for instance.

**Comment by rcritten** [comment]
Saving a copy of the downloaded package to /tmp works. Did some cleanup, added comments and squashed all changes.

**Comment by abbra** [comment]
The test works, please remove the temp commit.

**Comment by rcritten** [comment]
Thanks, temp commit removed.

**Comment by flo-renaud** [comment]
The temp commit has been removed, the tests are green, ACK.

**Comment by flo-renaud** [comment]
master:

* af5138c2aa80c85b9994eb2891d2f1ec1e2cad01 IPA-EPN: Test that EPN can be install, uninstalled and re-installed

**Pull request closed without merging**
