### PR TITLE
ipa-client-automount: fix '--idmap-domain DNS' logic

### PR DESCRIPTION
**Pull request by fcami**
Previously '--idmap-domain DNS' would assume the Domain
parameter of idmapd.conf was already absent. With this
fix, the Domain parameter is always removed and the
configuration file is always backuped.
    
Related-to: https://pagure.io/freeipa/issue/7918
Fixes: https://pagure.io/freeipa/issue/7988

### CODE REVIEW

**Comment by rcritten** [comment]
LGTM, remove temporary commit and I'll add ack.

**Comment by fcami** [comment]
@rcritten Thanks for the review, however I'll wait until PR-CI runs the temporary commit-defined test first.

**Comment by fcami** [comment]
hi @netoarmando / @dhnunes could you please have a look why CI does not pick up this one? Thanks

**Comment by netoarmando** [comment]
@fcami PR-CI is picking the wrong commit, could you please rebase your changes?

**Comment by fcami** [comment]
Fails with memory errors in collect_logs

**Comment by fcami** [comment]
All nfs test cases worked. The only error is in teardown within paramiko.
http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/922113d6-97d5-11e9-bae0-5254001c7b40/report.html

**Comment by tiran** [comment]
Temp commit with NFS tests has passed successfully.

**Comment by tiran** [comment]
master:

* cc348b990e607cb574d6eb70b6a9e35f14e8700c ipa-client-automount: fix '--idmap-domain DNS' logic
* 694c3667c7226d893617358a4161f6d754bb5db9 ipatests: add proper timeouts to nfs.py

**Pull request closed without merging**
