### PR TITLE
[Backport][ipa-4-8] Add fips-mode-setup to ipaplatform.paths to determine FIPS status

### PR DESCRIPTION
**Pull request by rcritten**
This PR was opened automatically because PR #4942 was pushed to master and backport to ipa-4-8 is required.

### CODE REVIEW

**Comment by rcritten** [comment]
PR was ACKed automatically because this is backport of PR #4942. Wait for CI to finish before pushing. In case of questions or problems contact @rcritten who is author of the original PR.

**Comment by rcritten** [comment]
Rebase to kick CI

**Comment by rcritten** [comment]
Azure isn't reporting results, it is successful at https://dev.azure.com/freeipa/freeipa/_build/results?buildId=5391&view=results

**Comment by flo-renaud** [comment]
ipa-4-8:

* cc06361907c8fdb986a581eb3e20abf8a7c1c476 Add fips-mode-setup to ipaplatform.paths to determine FIPS status

**Pull request closed without merging**
