### PR TITLE
Fix /doc/workshop subtree merge

### PR DESCRIPTION
**Pull request by tiran**
Something went wrong with git subtree merge of the external
freeipa-workshop repository. A couple of files accidently ended up
in / instead of /doc/workshop/.

Signed-off-by: Christian Heimes <cheimes@redhat.com>

### CODE REVIEW

**Comment by abbra** [comment]
LGTM. ipatool couldn't even retrieve the patches from the original pull request so I had to do manual merge and add few more changes to move files around. I don't think subtree information is recorded anywhere in the tree.

**Comment by tiran** [comment]
Ah, I see. AFAIK it is necessary to ``git remote add`` the source repo first.

**Comment by abbra** [comment]
The question is how we can do that.

**Comment by abbra** [comment]
LGTM. I still need to understand how to handle import of subtrees.

**Comment by tiran** [comment]
master:

* d34db063774952814e0cae7e4499c7462ef04687 Fix /doc/workshop subtree merge

**Pull request closed without merging**
