### PR TITLE
Fix typo in idrange.py docstring

### PR DESCRIPTION
**Pull request by smartsammler**
In my opinion the sentence makes more sense if one replaces this `id` with a `is`.
If this is not what was meant, then I would be pleased if the sentence could be rephrased, so that I get it right. Thank you.

### CODE REVIEW

**Comment by abbra** [comment]
LGTM but please use correct email for contribution.

**Comment by flo-renaud** [comment]
Hi @smartsammler 
Shouldn't the modification be done in ./ipaserver/plugins/idrange.py?

**Comment by abbra** [comment]
@flo-renaud is correct -- we have it in the server plugin side. There are more places where it needs to be modified, btw:
```
ipaclient/remote_plugins/2_114/idrange.py:this domain has the SID S-1-5-21-123-456-789-1010 then 1010 id the RID of the
ipaclient/remote_plugins/2_156/idrange.py:this domain has the SID S-1-5-21-123-456-789-1010 then 1010 id the RID of the
ipaclient/remote_plugins/2_164/idrange.py:this domain has the SID S-1-5-21-123-456-789-1010 then 1010 id the RID of the
ipaclient/remote_plugins/2_49/idrange.py:this domain has the SID S-1-5-21-123-456-789-1010 then 1010 id the RID of the
ipaserver/plugins/idrange.py:this domain has the SID S-1-5-21-123-456-789-1010 then 1010 id the RID of the
````
(and translation strings in PO files but those will need a special handling during transition from Zanata to Weblate anyway)

**Comment by smartsammler** [comment]
Sorry for the delay and thanks for the input.

**Comment by abbra** [comment]
master:

* 273ff2708cb99dded5e7ef51504cc8de9a4496db Fix typo in idrange.py docstring

**Pull request closed without merging**
