### PR TITLE
[Backport][ipa-4-6] Add test case for allow-retrieve-keytab

### PR DESCRIPTION
**Pull request by tiran**
This PR was opened automatically because PR #1964 was pushed to master and backport to ipa-4-6 is required.

### CODE REVIEW

**Comment by tiran** [comment]
PR was ACKed automatically because this is backport of PR #1964. Wait for CI to finish before pushing. In case of questions or problems contact @tiran who is author of the original PR.

**Comment by stlaz** [comment]
```
[<SNIP>] [remote 172.17.0.2:38968] ipa: ERROR: non-public: AttributeError: 'Principal' object has no attribute 'decode'
[<SNIP>] [remote 172.17.0.2:38968] Traceback (most recent call last):
[<SNIP>] [remote 172.17.0.2:38968]   File "/usr/lib/python2.7/site-packages/ipaserver/rpcserver.py", line 369, in wsgi_execute
[<SNIP>] [remote 172.17.0.2:38968]     result = command(*args, **options)
[<SNIP>] [remote 172.17.0.2:38968]   File "/usr/lib/python2.7/site-packages/ipalib/frontend.py", line 450, in __call__
[<SNIP>] [remote 172.17.0.2:38968]     return self.__do_call(*args, **options)
[<SNIP>] [remote 172.17.0.2:38968]   File "/usr/lib/python2.7/site-packages/ipalib/frontend.py", line 478, in __do_call
[<SNIP>] [remote 172.17.0.2:38968]     ret = self.run(*args, **options)
[<SNIP>] [remote 172.17.0.2:38968]   File "/usr/lib/python2.7/site-packages/ipalib/frontend.py", line 800, in run 
[<SNIP>] [remote 172.17.0.2:38968]     return self.execute(*args, **options)
[<SNIP>] [remote 172.17.0.2:38968]   File "/usr/lib/python2.7/site-packages/ipaserver/plugins/baseldap.py", line 1339, in execute 
[<SNIP>] [remote 172.17.0.2:38968]     self.obj.convert_attribute_members(entry_attrs, *keys, **options)
[<SNIP>] [remote 172.17.0.2:38968]   File "/usr/lib/python2.7/site-packages/ipaserver/plugins/baseldap.py", line 657, in convert_attribute_members
[<SNIP>] [remote 172.17.0.2:38968]     memberdn = DN(member.decode('utf-8'))
[<SNIP>] [remote 172.17.0.2:38968] AttributeError: 'Principal' object has no attribute 'decode'
[<SNIP>] [remote 172.17.0.2:38968] ipa: INFO: [jsonserver_session] admin@IPA.TEST: service_show/1(u'HTTP/testhost1.ipa.test@IPA.TEST', all=True, version=u'2.229'): InternalError

```

**Comment by abbra** [comment]
I don't see which packages did Travis CI use for this test...

**Comment by tiran** [comment]
The 4.6 builds had the wrong version of python3-ldap installed. Since ``3.0.0-beta`` is ``>= 2.4.37-4``, the tests were using a broken version. I have added ``Conflicts: python3-ldap < 3.1.0``. Let's hope this fixed the bug.

**Comment by rcritten** [comment]
@tiran CI is failing because of conflicts with the updated python-ldap.

**Comment by flo-renaud** [comment]
Addin re-run label because of `Process "vagrant provision" exited with error code 1 ` issues

**Comment by tiran** [comment]
@slaykovsky The tests are still failing because python3-ldap >= 3.0 is installed on the machine and Ansible cannot downgrade it to 2.4.37-4.

> package freeipa-server-4.6.3test-0.fc27.x86_64 conflicts with python3-ldap < 3.1.0 provided by python3-ldap-3.0.0-0.2.b2.fc27.x86_64

**Comment by tiran** [comment]
@Rezney created a new PR-CI image for the 4.6 branch. Tests are passing with the new image.

**Comment by tiran** [comment]
ipa-4-6:

* 13567efd955a3320e26caa9f214ee8e115589ef0 Add test case for allow-create-keytab
* 5bc650a92a180e5418d60f74f7125dbbf8128070 Require python-ldap with fix for ref counting bug
* b1df5fe2b1e2a5e64b2f2b7a48f34750e76513be Use freeipa/ci-ipa-4-6-f27 for PR-CI

**Pull request closed without merging**
