### PR TITLE
Add cgroup v2 support to the minimum RAM checker

### PR DESCRIPTION
**Pull request by rcritten**
It is similar to the v1 checking in that there is a set of files to use but if the value of the maximum available is 'max' then fall back to using psutil since all host memory is available.

https://pagure.io/freeipa/issue/8635

### CODE REVIEW

**Comment by abbra** [comment]
LGTM, please remove temp commit.

**Comment by rcritten** [comment]
Rebased and removed temp commit

**Comment by abbra** [comment]
LGTM

**Comment by flo-renaud** [comment]
master:

* 176fe83a01f249f214e031dbb7029f9e0944a4ad Add support for cgroup v2 to the installer memory checker
* 573d66e1f969143fa8c491a2308a8a893558810b ipatests: test the cgroup v2 memory restrictions

**Pull request closed without merging**
