### PR TITLE
[master] ipatests: update PR-CI templates to Fedora 33

### PR DESCRIPTION
**Pull request by netoarmando**
"previous" updated to Fedora 32
"latest" updated to Fedora 33

389ds, testing and pki definitions updated to Fedora 33

Signed-off-by: Armando Neto <abiagion@redhat.com>

### CODE REVIEW

**Comment by netoarmando** [comment]
All nightly jobs can be checked here: https://github.com/freeipa-pr-ci2/freeipa/pull/461

**Comment by abbra** [comment]
`test_upgrade` failed because the test is incomplete, it does not take into account a case when installation forces switching off dnssec validation due to broken DNSSEC situation with systemd-resolved:

```
2020-10-09T19:40:42Z INFO Checking DNS domain ipa.test., please wait ...
2020-10-09T19:40:43Z DEBUG Name master.ipa.test resolved to {UnsafeIPAddress('192.168.122.3')}
2020-10-09T19:40:43Z DEBUG Searching for an interface of IP address: 192.168.122.3
2020-10-09T19:40:43Z DEBUG Testing local IP address: 127.0.0.1/255.0.0.0 (interface: lo)
2020-10-09T19:40:43Z DEBUG Testing local IP address: 192.168.122.3/255.255.255.0 (interface: eth0)
2020-10-09T19:40:43Z DEBUG IP address 192.168.122.3 belongs to a private range, using forward policy only
2020-10-09T19:40:43Z DEBUG Checking DNS server: 127.0.0.53
2020-10-09T19:40:43Z WARNING DNS server 127.0.0.53 does not support DNSSEC: answer to query '. SOA' is missing DNSSEC signatures (no RRSIG data)
2020-10-09T19:40:43Z WARNING Please fix forwarder configuration to enable DNSSEC support.

2020-10-09T19:40:43Z DEBUG will use DNS forwarders: [CheckedIPAddressLoopback('127.0.0.53')]

2020-10-09T19:40:43Z INFO Reverse record for IP address 192.168.122.3 already exists
....
2020-10-09T19:46:14Z DEBUG dnssec-validation 'no' command line overwrite
2020-10-09T19:46:14Z INFO dnssec-validation no
```

**Comment by abbra** [comment]
`simple_replication` also failed due to systemd-resolved enforcement:

```
Oct 09 19:42:04 master.ipa.test NetworkManager[1708]: <info>  [1602272524.4735] audit: op="reload" arg="0" pid=20014 uid=0 result="success"
Oct 09 19:42:04 master.ipa.test NetworkManager[1708]: <info>  [1602272524.4760] config: signal: SIGHUP,config-files,values,values-user,dns-mode,global-dns-config (/etc/NetworkManager/NetworkManager.conf (etc: zzz-ipa.conf))
Oct 09 19:42:04 master.ipa.test NetworkManager[1708]: <info>  [1602272524.4773] dns-mgr: init: dns=default,systemd-resolved rc-manager=symlink

```

and it has the same signature of failing to interoperate with systemd-resolved during installation:
```
2020-10-09T19:36:57Z INFO Checking DNS domain ipa.test., please wait ...
2020-10-09T19:36:58Z DEBUG Name master.ipa.test resolved to {UnsafeIPAddress('192.168.122.108')}
2020-10-09T19:36:58Z DEBUG Searching for an interface of IP address: 192.168.122.108
2020-10-09T19:36:58Z DEBUG Testing local IP address: 127.0.0.1/255.0.0.0 (interface: lo)
2020-10-09T19:36:58Z DEBUG Testing local IP address: 192.168.122.108/255.255.255.0 (interface: eth0)
2020-10-09T19:36:58Z DEBUG IP address 192.168.122.108 belongs to a private range, using forward policy only
2020-10-09T19:36:58Z DEBUG Checking DNS server: 127.0.0.53
2020-10-09T19:36:58Z WARNING DNS server 127.0.0.53 does not support DNSSEC: answer to query '. SOA' is missing DNSSEC signatures (no RRSIG data)
2020-10-09T19:36:58Z WARNING Please fix forwarder configuration to enable DNSSEC support.

2020-10-09T19:36:58Z DEBUG will use DNS forwarders: [CheckedIPAddressLoopback('127.0.0.53')]

2020-10-09T19:36:58Z INFO Reverse record for IP address 192.168.122.108 already exists
2020-10-09T19:36:58Z DEBUG Loading StateFile from '/var/lib/ipa/sysrestore/sysrestore.state'
```

**Comment by abbra** [comment]
Few more details: we detect NetworkManager and set up an override for its DNS support but since NetworkManager is configured to use systemd-resolved, this configuration is not taken into account. We never detect systemd-resolved during the installation:
```
2020-10-09T19:42:04Z DEBUG Network Manager is enabled, write /etc/NetworkManager/conf.d/zzz-ipa.conf
2020-10-09T19:42:04Z DEBUG Starting external process
2020-10-09T19:42:04Z DEBUG args=['/bin/systemctl', 'reload-or-restart', 'NetworkManager.service']
2020-10-09T19:42:04Z DEBUG Process finished, return code=0
2020-10-09T19:42:04Z DEBUG stdout=
2020-10-09T19:42:04Z DEBUG stderr=
2020-10-09T19:42:04Z DEBUG Starting external process
2020-10-09T19:42:04Z DEBUG args=['/bin/systemctl', 'is-active', 'NetworkManager.service']
2020-10-09T19:42:04Z DEBUG Process finished, return code=0
2020-10-09T19:42:04Z DEBUG stdout=active

2020-10-09T19:42:04Z DEBUG stderr=
2020-10-09T19:42:04Z DEBUG Restart of NetworkManager.service complete
2020-10-09T19:42:04Z DEBUG step duration: named setup_resolv_conf 0.11 sec
```

**Comment by abbra** [comment]
@tiran please see comments above.

**Comment by flo-renaud** [comment]
- `test_acme` failure is a known issue (https://pagure.io/freeipa/issue/8581)
- `test_dnssec_TestInstallDNSSECFirst` is a known issue (https://pagure.io/freeipa/issue/8496)
- `test_upgrade` and `test_simple_replication` failures are related to systemd-resolved

**Comment by flo-renaud** [comment]
- simple_replication is a known issue https://pagure.io/freeipa/issue/8611
- test_acme is a known issue https://pagure.io/freeipa/issue/8602

**Comment by flo-renaud** [comment]
@netoarmando 
The azure pipeline failure has been fixed with https://pagure.io/freeipa/c/800bafe0a8dfe8d2cf852eb583a73037ce806ba5?branch=master, if you rebase the test should be green now.

**Comment by netoarmando** [comment]
Closing this is favour of https://github.com/freeipa/freeipa/pull/5416.

**Pull request closed without merging**
