### PR TITLE
py3: ipa-dnskeysyncd: fix bytes issues

### PR DESCRIPTION
**Pull request by MartinBasti**
LDAP client returns values as bytes, thus ipa-dnskeysyncd must work with
bytes properly.

https://pagure.io/freeipa/issue/4985

### CODE REVIEW

**Comment by flo-renaud** [comment]
Hi @MartinBasti,

Thank you for the patch. There are a few places left that need to be converted to bytes:
- in _get_signing_attr the default value should be [b'FALSE'] instead of ['FALSE']
- in __is_dnssec_enabled the comparison should use b'TRUE" instead of 'TRUE'
Otherwise it looks good to me.

**Comment by MartinBasti** [comment]
Thank you @flo-renaud , I updated the PR

**Comment by flo-renaud** [comment]
Thank you @MartinBasti for the PR update. I also noticed an issue in bindmgr.py in get_zone_dir_name():
```
        for label in zone:
            for char in label:
                c = ord(char)
```
In python3, char will be an int while in python 2 it is a string. Because of that, ord() will fail in python3.

**Comment by stlaz** [comment]
@tomaskrizek to kindly finish this PR to get more familiar to DNSSEC

**Comment by tomaskrizek** [comment]
Superseded by #1011

**Pull request closed without merging**
