### PR TITLE
ipa-backup: backup the PKCS module config files setup by IPA

### PR DESCRIPTION
**Pull request by flo-renaud**
### ipa-backup: backup the PKCS module config files setup by IPA
    
ipa installer creates /etc/pkcs11/modules/softhsm2.module in order
to disable global p11-kit configuration for NSS.
This file was not included in the backups, and not restored.
    
The fix adds the file to the list of files to include in a backup.
    
Fixes: https://pagure.io/freeipa/issue/8073

### ipatests: ensure that backup/restore restores pkcs 11 modules config file
    
In the test_backup_and_restore, add a new test:
- before backup, save the content of /etc/pkcs11/modules/softhsm2.module
- after restore, ensure the file is present with the same content.
    
Related: https://pagure.io/freeipa/issue/8073

### CODE REVIEW

**Comment by rcritten** [comment]
Confirmed that the file was included in the backup:
-rw-r--r-- root/root           94 2019-09-19 13:15 etc/pkcs11/modules/softhsm2.module

And properly restored.

**Comment by rcritten** [comment]
We probably want this in ipa-4-8 branch at least but I'll let @flo-renaud set the flags.

**Comment by flo-renaud** [comment]
Adding the ipa-4-7 label as the module files were added also in ipa-4-7 branch (commit 74e0908 + backported to ipa-4-7 with ae5831b)

**Comment by rcritten** [comment]
Ok looks good, can you remove the temp commit?

**Comment by rcritten** [comment]
Removing ack until temp commit is removed so I don't accidentally push it.

**Comment by flo-renaud** [comment]
Hi @rcritten 
thanks for the review. Temp commit removed.

**Comment by abbra** [comment]
master:

* 055ea253dfe0182671cba16916840a013daa8b74 ipa-backup: backup the PKCS module config files setup by IPA
* 2919237753e031810f5b6e7d645bc126ebc8f7b5 ipatests: ensure that backup/restore restores pkcs 11 modules config file

**Comment by abbra** [comment]
@flo-renaud, automatic backport to ipa-4-7 branch failed, please do manual one.

**Pull request closed without merging**
