### PR TITLE
Improve PKI subsystem detection

### PR DESCRIPTION
**Pull request by flo-renaud**
### Improve PKI subsystem detection

The dogtaginstance.is_installed() method currently relies on
the presence of the directory /var/lib/pki/pki-tomcat/{ca|kra},
even if it is empty.
An unwanted consequence is ipa-server-upgrade wrongly assuming the KRA
is installed and crashing when trying to upgrade a not-installed
component.

The fix relies on the command "pki-server subsystem-show {ca|kra}" to
detect if a subsystem is installed. The command does not require PKI
to be running (hence can be called anytime) and is delivered by
the pki-server package which is already required by ipa server pkg.

Fixes: https://pagure.io/freeipa/issue/8596

### ipatests: add test for PKI subsystem detection

Add a new upgrade test. Scenario:
- create an empty /var/lib/pki/pki-tomcat/kra directory
- call ipa-server-upgrade

With issue 8596, the upgrade fails because it assumes KRA is
installed. With the fix, ipa-server-upgrade completes successfully.

Related: https://pagure.io/freeipa/issue/8596

### CODE REVIEW

**Comment by flo-renaud** [comment]
I need to rework the patch because the behavior of the command `pki-server subsystem-show` has changed between RHEL7.9 and fedora 32.
Previously when the KRA was not configured and there was a /var/lib/pki/pki-tomcat/kra directory, the commands exited with 1.
Now it prints 
```
  Subsystem ID: kra
  Instance ID: pki-tomcat
  Enabled: False
```

**Comment by flo-renaud** [comment]
The issue will also need an additional fix in dogtag: when the directory /var/lib/pki/pki-tomcat/kra exists but is empty, pki fails to start:
```
Nov 27 15:32:05 master.ipa.test systemd[1]: Starting PKI Tomcat Server pki-tomcat...
Nov 27 15:32:05 master.ipa.test pki-server[32161]: ERROR: [Errno 2] No such file or directory: '/var/lib/pki/pki-tomcat/kra/conf/CS.cfg'
Nov 27 15:32:05 master.ipa.test audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=pki-tomcatd@pki-tomcat comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Nov 27 15:32:05 master.ipa.test systemd[1]: pki-tomcatd@pki-tomcat.service: Control process exited, code=exited, status=1/FAILURE
Nov 27 15:32:05 master.ipa.test systemd[1]: pki-tomcatd@pki-tomcat.service: Failed with result 'exit-code'.
Nov 27 15:32:05 master.ipa.test systemd[1]: Failed to start PKI Tomcat Server pki-tomcat.
```
Will discuss this next week with dogtag team.

**Comment by flo-renaud** [comment]
Opened an issue against dogtag: https://github.com/dogtagpki/pki/issues/3397  pki fails to start if empty dir /var/lib/pki/pki-tomcat/kra exists

**Comment by flo-renaud** [comment]
Because of https://github.com/dogtagpki/pki/issues/3397 the automated test must be skipped if pki 10.10.0 is installed. A temp commit was run
- on fedora 32 with only updates enabled (pki 10.10.0-2 installed): test skipped as expected ([report](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/fb6cfe70-3628-11eb-bd53-fa163e05ce82/report.html))
- on fedora 32 with @pki/master enabled (pki 10.11.0-0.1.alpha1.20201202235940UTC.8791f5d7): test executed and successful ([report](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/34058482-3629-11eb-ae46-fa163e147d19/report.html))

Removing the temp commit and WIP label.

**Comment by abbra** [comment]
LGTM. I verified against pki git source and the code there prints `Enabled: {value}` for each subsystem. `{value}` is string version of a Python boolean. Since Python always produces `False` and `True`, the current check is enough.

**Comment by flo-renaud** [comment]
master:

* 930453b65ea17e190a46208763d366739646264b Improve PKI subsystem detection
* 526686ec1c6f0fa018c4ffd61ef091783a48163f ipatests: add test for PKI subsystem detection

**Pull request closed without merging**
