### PR TITLE
[Backport][ipa-4-7] Missing translations

### PR DESCRIPTION
**Pull request by serg-cymbaluk**
Manual backport for #2362, #2371 and #2372 PRs.

Tickets:
https://pagure.io/freeipa/issue/7699
https://pagure.io/freeipa/issue/7702
https://pagure.io/freeipa/issue/7704

### CODE REVIEW

**Comment by stanislavlevin** [comment]
After pushing the changes, related to 'Add' and 'Remove' dialogs, it needs to update Zanata because of a huge amount of new untranslated texts.

**Comment by abbra** [comment]
Yes, there is a plan to update Zanata.

**Comment by tiran** [comment]
Tests are failing with
```
freeipa/install/ui/src/freeipa/radiusproxy.js(111): warning: trailing comma is not legal in ECMA-262 object initializers
```

**Comment by serg-cymbaluk** [comment]
> Tests are failing with
> 
> ```
> freeipa/install/ui/src/freeipa/radiusproxy.js(111): warning: trailing comma is not legal in ECMA-262 object initializers
> ```

It is strange because for master with the [same code](https://github.com/freeipa/freeipa/blob/master/install/ui/src/freeipa/radiusproxy.js#L111) Travis-CI is green...

**Comment by stanislavlevin** [comment]
Ah, 
21f14e98939d5b17d0bf9bc6b96e97cf82f7c3af removes jslint from ci tests. 
Thus CI on master branch passed.
But now tests run on ipa-4-7 branch (without that commit) and catch JS 'issue'.

**Comment by stanislavlevin** [comment]
> Tests are failing with
> 
> ```
> freeipa/install/ui/src/freeipa/radiusproxy.js(111): warning: trailing comma is not legal in ECMA-262 object initializers
> ```

As i've already posted,
trailing comma is allowed in ECMAScript 5.1 (ECMA-262).
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas

jsl as a javascript linter is slightly outdated ( ~2008 year).
May be it's time to replace it?

**Comment by tiran** [comment]
ipa-4-7:

* 850eea357b49d7c140107cf5908579e0c7503d6d Drop concatenated title of remove dialog
* 72e97f2e24b0065feb998412fd6f73ae0d17cb90 Add title to remove dialog of 'Users' entity
* b8af0b3287e32042c31e2c335b003b364ea7fd6f Add title to remove dialog of 'Hosts' entity
* 4357ac540a6261ad50960306d1f2a5debdb8e6ba Add title to remove dialog of 'Services' entity
* 6a1c3633ceb5314f9c5d5a120ad035d61783b743 Add title to remove dialog of 'Groups' entity
* abdcfeb7c31c86ef1a57d3490df93604f00d261b Add title to remove dialog of 'ID Views' entity
* 19f194d617e4ebda3ec19aa0e582456d75a10da3 Add title to remove dialog of 'Automember' entity
* 2c45a745f871321eae37356a74113b2e7ddf70b4 Add title to remove dialog of 'HBAC' entity
* 46e3be4009442568945dfc3d3fa847c298deba0e Add title to remove dialog of 'Sudo' entity
* 6a8a9bcc1b47f402814e8041c351edbcd1ee38a2 Add title to remove dialog of 'SELinux User Maps' entity
* ff7dc517d7582623f8287e21bc605c9c4c1bad1b Add title to remove dialog of 'Password Policies' entity
* d5eb7831400dedace78cf4544afff4b303b45117 Add title to remove dialog of 'Certificates' entity
* b13d825e99b56c829fe2e58808f56f93a7f4b980 Add title to remove dialog of 'OTP Tokens' entity
* 6461d9c3aa2bd35d16c63e0b34f5e47c788bdd9e Add title to remove dialog of 'RADIUS Servers' entity
* 97fd70ee8d41fe82a30c2c820fe2b364be8dc86a Add title to remove dialog of 'Certificate Identity Mapping Rules' entity
* e7ff1982b6481930ef9fd4dc055b0bc2576fa9e6 Add title to remove dialog of 'Automount Locations' entity
* 9e85373c1abd0a2bb454d859f7059c25215634ca Add title to remove dialog of 'DNS' entity
* a06d410ec365c687ffaae18d2ed6d64e03909dbb Add title to remove dialog of 'RBAC' entity
* 68a1279091b2a97f784c1691619fa227510c5dab Add title to remove dialog of 'ID Ranges' entity
* afbaea15dede0a4272b27407c814ac129e180a3f Add title to remove dialog of 'Topology' entity
* ee9645202016c24bfc381c1fdee49852ffd1a4c2 Add title to remove dialog of 'Trusts' entity
* d6d11bef46a197e2609319537473b7fa98f99017 Drop concatenated title of remove dialog
* cc3c38a72d2b1a87a0d3aa82d7f6a0ab42aba6b5 Add a title to 'remove' dialog for details of 'Users' entity
* b64b0aa69402e9f237565d4e9620a71ced051897 Add a title to 'remove' dialog for details of 'Hosts' entity
* 65427f9412f5b69cb9f22fd8b0cc3b6d94a0a135 Add a title to 'remove' dialog for details of 'Services' entity
* dcf1803c961d7c00fddd7f87472dd674f8933baf Add a title to 'remove' dialog for details of 'Groups' entity
* 6ec6dafa783870a076b44734a5fd70471f5c943c Add a title to 'remove' dialog for details of 'HBAC' entity
* 865bbea73e12d312a1a1f33fbb3e638664a49e33 Add a title to 'remove' dialog for details of 'Sudo' entity
* 20d9b21fa11a1533d122a1e3d186fe6140f26c37 Add a title to 'remove' dialog for details of 'OTP Tokens' entity
* 881a67395be0ea90f8e2c7592f5d787df39de16e Add a title to 'remove' dialog for details of 'RBAC' entity
* 1785168ab7b0947ac1d319f97cfaeca7c768967e Add a title to 'remove' dialog for details of 'Trusts' entity
* f72aa37e363dc50090e82a54304daa921de11240 Drop concatenated title of remove dialog
* 6e8c6a4e79cabef8c54b275b30541a3beb1eb512 Add title to 'remove' dialog for 'association_table' widget of 'Hosts' entity
* db5e0f8029a7e225246724f56f11049dd0338012 Add title to 'remove' dialog for 'association_table' widget of 'Services' entity
* f0f2f44325c8558b05d6e3a701d6aa4cd41ec954 Add title to 'remove' dialog for 'association_table' widget of 'Groups' entity
* cdc605f14e55c70ea1740b3bde3e83e0a032f086 Allow having a custom title of 'Remove' dialog for 'attribute_table' widget
* 31f5db2873e1e673d65b532953663f3a1b3f46bc Add title to 'Remove' dialog for 'association_table' widget of 'Automember' entity
* 14acf96e66d71a16a8189d02dbdc7d2d5f5fe73c Add title to 'Remove' dialog for 'association_table' widget of 'HBAC' entity
* b56ff7f4b947a1cd1a508f3a3e40e4a76e9e3dd6 Add title to 'Remove' dialog for 'association_table' widget of 'Sudo' entity
* 14aa7bfd5e337aaef8bad90ffb8ce729f7facea6 Add title to 'Remove' dialog for 'association_table' widget of 'SELinux' entity
* 176ec4a8c30df4109ad927a37d86f6afdbbcd60a Add title to 'Remove' dialog for 'association_table' widget of 'CA' entity
* 3890280e85f139ab8b2acc37a69494152266e645 Add title to 'Remove' dialog for 'association_table' widget of 'Topology' entity
* 9e4f6857f98d96f6432d9bbf0102074ed47b19bd Add title to 'Remove' dialog for 'association_table' widget of 'Vault' entity
* 85a96ddcb8fa94939f19ee955994cd37aa3c02d5 Add title to 'unprovision' dialog
* 9cccf6ae8fb96654046cba3e4df9dba22f5f00ef Add title to remove dialog of 'DNS' entity
* 2bb4fc20dd191791f43170522f125fd3c8fae198 Fix javascript 'errors' found by jslint
* 042cf811578f5a40d90fc1bceb779a1fe99c3565 Add jslint check to PR CI tests

**Pull request closed without merging**
