### PR TITLE
prci: add external_ca test

### PR DESCRIPTION
**Pull request by tomaskrizek**
Add external_ca to the PR CI test suite.

Signed-off-by: Tomas Krizek <tkrizek@redhat.com>

### CODE REVIEW

**Comment by pvoborni** [comment]
Is there a way to convince pytest to save complete console output (both stdout and stderr) into a file which can be then analyzed? The output which pytest prints in a failure of integration tests often seems quite useless to me.

**Comment by tomaskrizek** [comment]
@pvoborni I recall py.test used to report the output of called subprocess (e.g. ipa-server-install) in the past. However, Standa tried to execute py.test manually in console and he also didn't see the command output, so this is most likely not related to properly handling stdout/stderr. Perhaps py.test changed the behavior, perhaps we changed something in the testing framework that causes it -- anyway, it'd be really helpful to have the output of the subcommand available. See https://github.com/freeipa/freeipa-pr-ci/issues/76

**Comment by felipevolpone** [comment]
[This freeipa/freeipa-pr-ci PR](https://github.com/freeipa/freeipa-pr-ci/pull/118) fixes the problem.

**Comment by tomaskrizek** [comment]
master:

* 0033e0933924e856719cbbca5b5bc706eb9708c5 prci: add external_ca test
* 1d190092d3c386d83bc54e5d0f7e369f81127354 ipatests: collect logs for external_ca test suite

**Pull request closed without merging**
