### PR TITLE
Fix and refactor test_trust.py

### PR DESCRIPTION
**Pull request by wladich**
Multiple problems were found in trust tests and trust-related test utility functions.

Detailed description of changes provided in commit messages
Issues with test described in https://pagure.io/freeipa/issue/7889

### CODE REVIEW

**Comment by abbra** [comment]
LGTM

**Comment by tiran** [comment]
The patchset doesn't apply:

```
$ ipatool pr-push 2956 -r abok -B ipa-4-7
Reviewer: Alexander Bokovoy <abokovoy@redhat.com>
Will apply 9 patches to: master
Fetching...
Aplying to master: Revert "Tests: Remove DNS configuration from trust tests"
Aplying to master: ipatests: in test_trust.py fix prameters in invocation of tasks.configure_dns_for_trust
Aplying to master: ipatests: disable bind dns validation when preparing to establish AD trust
Aplying to master: ipatests: in test_trust.py fix parent class
Aplying to master: ipatests: fix expectations of `ipa trust-find` output for trust with root domain
Aplying to master: ipatests: relax requirements for time server quality
git am
Applying: ipatests: relax requirements for time server quality
Patch failed at 0001 ipatests: relax requirements for time server quality
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
error: patch failed: ipatests/pytest_ipa/integration/tasks.py:778
error: ipatests/pytest_ipa/integration/tasks.py: patch does not apply
```

**Comment by rcritten** [comment]
master:

* cc1fb2fac565827291feda986c663c1b06e7b16e Revert "Tests: Remove DNS configuration from trust tests"
* 3e01d2619e87141b6d6078d818c7394aa6b63281 ipatests: in test_trust.py fix prameters in invocation of tasks.configure_dns_for_trust
* 14f27d299e4ef3a9fc0deb642e6cd4e48796364d ipatests: disable bind dns validation when preparing to establish AD trust
* 1d0a612a0fd9d5682bb7e0793d4c1c56d3365517 ipatests: in test_trust.py fix parent class
* e8955cc7966b767415e2c9da6169f109c9c2119c ipatests: fix expectations of `ipa trust-find` output for trust with root domain
* 03e2693a7dc6cae292b80f83fe6a295b66f3e3df ipatests: relax requirements for time server quality
* 35a4642ad0defb5564009c0a09185a9a96d88919 ipatests: allow AD hosts to be placed in separate domain config objects
* 94a6cb11eaffaff2790d7d56f092ed20111bc604 ipatests: adapt test_trust.py for changes in multihost fixture
* c81971652144e6c17503bdc38ff62c7fd5aa2d7d ipatests: refactor test_trust.py

**Comment by rcritten** [comment]
Manual backport is needed for ipa-4-6

**Pull request closed without merging**
