### PR TITLE
WebUI: update favicon.ico

### PR DESCRIPTION
**Pull request by vashirov**
I noticed that FreeIPA favicon is a bit squished. I would like to unsquish it.
And resize it to 32x32 pixels as it would look a bit better on HiDPI screens.

Fixes: https://pagure.io/freeipa/issue/9449

### CODE REVIEW

**Comment by rcritten** [comment]
I think the commit message should include why the change was made along with the pointer to the ticket to avoid a dereference in the future.

IMHO the issue from the ticket can be include verbatim:

`I noticed that FreeIPA favicon is a bit squished. I would like to unsquish it. And resize it to 32x32 pixels as it would look a bit better on HiDPI screens.`

**Comment by rcritten** [comment]
Any suggestion on how far back to port this?

**Comment by vashirov** [comment]
@rcritten, I've updated the commit message.

> Any suggestion on how far back to port this?

The favicon was like this since the new logo was added, so all current releases are affected. But I'm fine with leaving it in the master branch.

**Comment by rcritten** [comment]
This looks fine to me. @carma12 can you provide a second opinion?

**Comment by carma12** [comment]
@rcritten  @vashirov - Looks good to me.

**Comment by flo-renaud** [comment]
master:

* fe005dd3880baff72bda2c2857f9445d3b129b87 WebUI: update favicon.ico

**Pull request closed without merging**
