### PR TITLE
[ipa-4-8] ipatests: update PR-CI templates to Fedora 33

### PR DESCRIPTION
**Pull request by netoarmando**
"previous" updated to Fedora 32
"latest" updated to Fedora 33

Signed-off-by: Armando Neto <abiagion@redhat.com>

### CODE REVIEW

**Comment by netoarmando** [comment]
All nightly jobs can be checked here: https://github.com/freeipa-pr-ci2/freeipa/pull/463

**Comment by flo-renaud** [comment]
`test_dnssec_TestInstallDNSSECFirst` is a known issue (https://pagure.io/freeipa/issue/8496)
`test_upgrade` and `test_simple_replication` failures are related to systemd-resolved

**Comment by flo-renaud** [comment]
- rerunning test_replica_promotion_TestSubCAkeyReplication because the test timed out
- simple_replication issue is a known failure, https://pagure.io/freeipa/issue/8611
- test_installation_TestInstallMaster is a known failure https://pagure.io/freeipa/issue/8506

**Comment by flo-renaud** [comment]
@netoarmando the azure pipeline issue has been fixed with https://pagure.io/freeipa/c/23bf98e710a49f51a617cf96b56eaa5db0513558?branch=ipa-4-8, if you rebase the test should be green now.

**Comment by netoarmando** [comment]
Closing this in favour of https://github.com/freeipa/freeipa/pull/5417.

**Pull request closed without merging**
