### PR TITLE
Fix replica connection check for use with idoverrideuser admins

### PR DESCRIPTION
**Pull request by t-woerner**
The current check in ipaserver/plugins/server.py class server_conncheck that is used in ipa-replica-conncheck to verify that the given principal has the needed privilege "Replication Administrators" is only working for IPA users that are part of the "admins" group.

To be able to use an AD administrator to deploy a replica it is needed to extend this check to idoverride users that are in the "admins" group using the principal as the ipaOriginalUid.

Fixes: https://pagure.io/freeipa/issue/9542

### CODE REVIEW

**Comment by abbra** [comment]
This fix is wrong. I'm back from vacation next week and will go into more details. Please do not merge this PR.

**Comment by abbra** [comment]
A correct fix would be to add support for a search of an id override in `ipaserver.plugins.privilege.principal_has_privilege()`.

I think it could be a second search in the `except errors.NotFound:` part that would do a search for the
```
ldap.make_filter(
                {
                    'objectClass': ['ipaOverrideAnchor', 'nsmember'],
                    'ipaanchoruuid': principal,
                    'memberof': privilege_dn
                },
                rules=ldap.MATCH_ALL
```

in the subtree of `DN(('cn', idviews.DEFAULT_TRUST_VIEW_NAME), api.env.container_views)`.

**Comment by abbra** [comment]
We probably don't want to add explicit dependency between `idviews.py` and `privilege.py`, so one can use runtime discovery:
`DN(('cn', api.packages[0].idviews.DEFAULT_TRUST_VIEW_NAME), api.env.container_views+api.env.basedn`

`api.packages[0]` should be a module `ipaserver.plugins` which gives access to all plugins within the `ipaserver/plugins` space.

**Comment by abbra** [comment]
```
>>> from ipapython.dn import DN
>>> DN(('cn', api.packages[0].idviews.DEFAULT_TRUST_VIEW_NAME), api.env.container_views+api.env.basedn)
ipapython.dn.DN('cn=default trust view,cn=views,cn=accounts,dc=example,dc=test')
```

**Comment by t-woerner** [comment]
> ```
> >>> from ipapython.dn import DN
> >>> DN(('cn', api.packages[0].idviews.DEFAULT_TRUST_VIEW_NAME), api.env.container_views+api.env.basedn)
> ipapython.dn.DN('cn=default trust view,cn=views,cn=accounts,dc=example,dc=test')
> ```

Thank you, that was helping a lot to get it done.

**Comment by abbra** [comment]
I am thinking -- may be we should integrate the call to `_ipaoriginaluid_has_privilege()` into `principal_has_privilege()`? This way it would work for all other checks automatically.

**Comment by f-trivino** [comment]
> I am thinking -- may be we should integrate the call to `_ipaoriginaluid_has_privilege()` into `principal_has_privilege()`? This way it would work for all other checks automatically.

what do you think @t-woerner ?

**Comment by flo-renaud** [comment]
Hi @t-woerner 
thanks for the PR, works for me.

I tested the promotion of a client to replica with the following steps:
- create an idoverrideuser for AD administrator: `ipa idoverrideuser-add 'Default Trust View' administrator@ADDOMAIN.TEST`
- grant the "Enrollment Administrator" and "IT Specialist" roles: `ipa role-add-member "Enrollment Administrator" --idoverrideuser administrator@ADDOMAIN.TEST; ipa role-add-member "IT Specialist" --idoverrideuser administrator@ADDOMAIN.TEST`
- Add the host to the ipaservers hostgroup: `ipa hostgroup-add-member ipaservers --hosts client.ipadomain.test`
- Create a role containing "Replication Administrators privilege" and grant the role to the AD admin: `ipa role-add repl; ipa role-add-privilege repl --privilege "Replication Administrators"; ipa role-add-member repl --idoverrideuser administrator@ADDOMAIN.TEST`
- on the client check connectivity: `/usr/sbin/ipa-replica-conncheck --master master.ipadomain.test --auto-master-check --realm IPADOMAIN.TEST --hostname client.ipadomain.test --principal administrator@ADDOMAIN.TEST --ca-cert-file /etc/ipa/ca.crt`
- on the client, kinit as AD administrator and promote to replica: `kinit administrator@ADDOMAIN.TEST; ipa-replica-install -U`

The promotion works well.

It is also possible to enroll a client as administrator@ADDOMAIN.com.
I also tested direct replica install (client enrollment + replica promotion in a single command) if the administrator@ADDOMAIN is a member of the admins group: `ipa group-add-member admins --idoverride-user administrator@ADFLO.TEST`

**Comment by flo-renaud** [comment]
@t-woerner Which branches do you need to backport to?

**Comment by t-woerner** [comment]
@flo-renaud I would like to have a backport for older releases like 4-11 and 4-10 also, but I think that @abbra did not like this idea.

**Comment by abbra** [comment]
@t-woerner no problem with backports to 4.11 and 4.10. I think this code is rather stable.

**Comment by t-woerner** [comment]
@flo-renaud Ok, I added the labels for 4.10 and 4.11.

**Comment by flo-renaud** [comment]
master:

* 182dca38c2bb84acce8ab5dcfab6fb5e4abf31da principal_has_privilege: Check also idoverriseuser (ipaOriginalUid)

**Pull request closed without merging**
