### PR TITLE
Remove unused Knob function

### PR DESCRIPTION
**Pull request by mbasti-rh**
`Knob` function is outdated and was replaced by `knob`. Make explicit
note in code about this.

https://fedorahosted.org/freeipa/ticket/6392

### CODE REVIEW

**Comment by stlaz** [comment]
ACK, there should be note about this deprecation somewhere. Deleting Knob might be worth a ticket as well.

**Comment by mbasti-rh** [comment]
I would wait with ACK, I realized that Knobs with capital K are not used anymore, so we can remove it instead of deprecating

**Comment by stlaz** [comment]
From our offline discussion I got the impression the Knob function was still used somewhere, therefore the ACK. I'm not sure what was the reason of keeping Knob there even if unused, you may need checking with @jcholast.

**Comment by mbasti-rh** [comment]
@jcholast ping

**Comment by jcholast** [comment]
There was no reason, I just forgot, so go ahead.

**Comment by mbasti-rh** [comment]
Fixed upstream
master:
https://fedorahosted.org/freeipa/changeset/55b14abcb561422cf48755dae6b0638656535fe5

**Pull request closed without merging**
