### PR TITLE
Check that CADogtagCertsConfigCheck can handle cert renewal

### PR DESCRIPTION
**Pull request by ckelleyRH**
Renewal causes two certs to have the same nickname. Dogtag is patched to allow for N certs with the same nickname, and this test is to verify that CADogtagCertsConfigCheck still passes.

Corresponding Dogtag change: https://github.com/dogtagpki/pki/pull/4285

The bug itself is targeting older branches. I will backport the fix but I don't think it is necessary to backport this test (you can if you like, of course).

### CODE REVIEW

**Comment by ckelleyRH** [comment]
The new test should fail until the Dogtag PR is merged.

**Comment by rcritten** [comment]
I can duplicate the behavior manually. The test isn't being run by CI by default hence no failure here (besides a transient failure in Azure).

You need to create a temp commit for it to run:

*  edit `ipatests/prci_definition/temp_commit.yaml` and add the test case you want to run
*  from the root of your repository, run:
    ```
    ln -sf ipatests/prci_definitions/temp_commit.yaml .freeipa-pr-ci.yaml
    git add ipatests/prci_definitions/temp_commit.yaml .freeipa-pr-ci.yaml
    git commit
    ```
With these steps, .freeip-pr-ci.yaml will point to the temp_commit.yaml file. PRCI extracts the list of tests from .freeipa-pr-ci.yaml, and will execute only the ones specified in temp_commit.yaml.

So in this case the meat of temp_commit.yaml should look something like:

```
  fedora-latest/test_ipahealthcheck:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_ipahealthcheck.py::TestIpaHealthCheck
        template: *ci-master-flatest
        timeout: 5400
        topology: *master_1repl_1client
```

You only need to update the bottom of the file, the temp_commit bit, not the headers.

**Comment by ckelleyRH** [comment]
@rcritten - thanks! Hopefully I've done it right :+1:

**Comment by ckelleyRH** [comment]
@rcritten - ...so the test-commit test failed, but for some other job and not the one I have added. Are you happy with it?

**Comment by rcritten** [comment]
You need to increase the timeout to 5400.

The Azure jobs can be flakey sometimes. I can re-run those if the fail next time but we'd like to see all green on the temp commit.

**Comment by ckelleyRH** [comment]
> You need to increase the timeout to 5400.

OK, done.

> The Azure jobs can be flakey sometimes. I can re-run those if the fail next time but we'd like to see all green on the temp commit.

:crossed_fingers:

**Comment by ckelleyRH** [comment]
@rcritten OK, so this time it definitely failed on my new test. I don't think it did the previous attempt though? I can't check, I only have permission to view the current run.

The report says that  `ipa-cacert-manage renew --self-signed` failed, I think because certmonger timed out. Another transient failure, do you think?

**Comment by rcritten** [comment]
The DNS system records failure is a known issue, https://pagure.io/freeipa/issue/9291
I'm not sure about the CA cert update failure. It appears that certmonger is having trouble communicating with the CA.

**Comment by rcritten** [comment]
certmonger isn't logging much about the failure, just this in the journal:

[Jan 30 15:43:23 master.ipa.test dogtag-ipa-ca-renew-agent-submit[30605]: Updating renewal certificate failed: Operations error: . Sleeping 30s

**Comment by ckelleyRH** [comment]
That's unfortunate. Can you see the previous runs, to know whether this is transient? Or run just this part again please?

Not sure what to suggest to fix this if it is not transient. I tried to copy the reproducer steps in the bug, I think I got that right?

**Comment by rcritten** [comment]
Can you rebase this on current master? That will pull in some other recent healthcheck test fixes.

**Comment by rcritten** [comment]
Try moving the test above test_nsscheck_cert_expired(). Time is being moved in that test and I suspect that is the problem.

**Comment by rcritten** [comment]
The failure is in the pki healthchecks:

{
     "source": "pki.server.healthcheck.meta.csconfig",
     "check": "CADogtagCertsConfigCheck",
     "result": "ERROR",
     "uuid": "d8e400da-173d-4a0d-8944-085210c6faf6",
     "when": "20230202141836Z",
     "duration": "0.200640",
     "kw": {
       "key": "ca_signing",
       "nickname": "caSigningCert cert-pki-ca",
       "directive": "ca.signing.cert",
       "configfile": "/var/lib/pki/pki-tomcat/ca/conf/CS.cfg",
       "msg": "Certificate 'caSigningCert cert-pki-ca' does not match the value of ca.signing.cert in /var/lib/pki/pki-tomcat/ca/conf/CS.cfg"
     }
}

I wonder if your fixed code is being executed.

**Comment by ckelleyRH** [comment]
> the first one is expected to fail, the 2nd to succeed

Ah, that would explain a lot! I have added the second test with the package update, let's see what happens.

**Comment by ckelleyRH** [comment]
@flo-renaud @rcritten
/o/ :tada:  \o/ :tada:  \o\
Party time! The first temp commit fails with the F37 packages, so renewal breaks the test. The second one, taking the latest bits, gracefully handles the renewal and succeeds. Everything else passes, permission to drop the temp commits and push again?

**Comment by rcritten** [comment]
[Test failing with previous healthcheck](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/a98cebc0-a3a3-11ed-87b7-fa163eab4448)
[Test passing with updated healthcheck](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/c408382e-a3a3-11ed-8573-fa163ea4a9f1)

Do we want to add a version wrapper around this so the test is skipped or xfail if that version requirement isn't met?

**Comment by flo-renaud** [comment]
> Do we want to add a version wrapper around this so the test is skipped or xfail if that version requirement isn't met?

That would be nice.
@ckelleyRH you can add something similar to the following to your test:
```
from ipatests.pytest_ipa.integration import tasks
...

def test_ipa_healthcheck_renew_internal_cert(self):
        """
        This testcase checks that CADogtagCertsConfigCheck can handle
        cert renewal, when there can be two certs with the same nickname
        """
        if (tasks.get_pki_version(self.master)
           < tasks.parse_version('11.3.0')):
            raise pytest.skip("PKI known issue #2022561")
...
```
Don't forget to replace 11.3.0 with the right version containing the fix.

**Comment by ckelleyRH** [comment]
Ack, I have modified so it will run the tests from `v11.4.0` onwards, i.e. next version of PKI.

**Comment by ckelleyRH** [comment]
@rcritten looks like intermittent error connecting to DS?

**Comment by rcritten** [comment]
This gating test has been flaky lately in Azure, re-running.

**Comment by ckelleyRH** [comment]
@flo-renaud @rcritten - great, it passed this time :smile:

**Comment by ckelleyRH** [comment]
@rcritten - is this OK to merge now?

**Comment by rcritten** [comment]
@ckelleyRH what IPA release(es) do you want to see this in? We tend to backport to 4-9 and 4-10 for fixes to current code, but since the fix may only be in rawhide maybe 4-10 and master is enough?

**Comment by rcritten** [comment]
Addendum: given it's only a test and version-sensitive it really doesn't make that much of a difference but why test for something that a branch will never see, is the reason for my question.

**Comment by ckelleyRH** [comment]
I think 4.10 and master is probably enough? The fix is in all PKI branches back to v10.13, so in principle you could go further back if you wanted to but I leave it to you to decide whether you think that is necessary.

**Comment by rcritten** [comment]
master:

* 614d3bd9c009204920406b791057fe3646d640bc Check that CADogtagCertsConfigCheck can handle cert renewal

**Pull request closed without merging**
