### PR TITLE
[Backport][ipa-4-8] ipa-client-samba: remove and restore smb.conf only on first uninstall

### PR DESCRIPTION
**Pull request by fcami**
This PR was opened automatically because PR #3435 was pushed to master and backport to ipa-4-8 is required.

### CODE REVIEW

**Comment by fcami** [comment]
PR was ACKed automatically because this is backport of PR #3435. Wait for CI to finish before pushing. In case of questions or problems contact @fcami who is author of the original PR.

**Comment by flo-renaud** [comment]
Temporarily removing the ACK as PRCI tests were not triggered. Investigating PRCI infra issues in the mean time...

**Comment by flo-renaud** [comment]
My bad, the test results can be seen if you click on the green tick next to the commit hash.

**Comment by flo-renaud** [comment]
ipa-4-8:

* b9b98097a47f27b56500edc972c438597e6609b1 ipatests: test multiple invocations of ipa-client-samba --uninstall
* 256a6a879061d2b97c11e9cd97b2427579610fa1 ipa-client-samba: remove and restore smb.conf only on first uninstall
* 00ba2ae6681dafa92d3f00f2a4e11adaa477ea0e ipatests: test ipa-client-samba after --uninstall
* 551cd68d0959b1ee761ead6338dc06c544c0c5da ipa-client-samba: remove state on uninstall

**Pull request closed without merging**
