### PR TITLE
ap fixes

### PR DESCRIPTION
**Pull request by stanislavlevin**
- raised DBus call timeout (25sec => 50sec) for `hostnamectl`
- disabled azure's security daemon (clamav)
- rearranged overloaded jobs
- constrained supported `docutils`

Fixes:
- https://pagure.io/freeipa/issue/9207
- https://pagure.io/freeipa/issue/9208

### CODE REVIEW

**Comment by stanislavlevin** [comment]
Fixed typos.

**Comment by stanislavlevin** [comment]
Failures are not related to changes (crash and crash). This is annoying, need to fix CI (I punish myself).

**Comment by rcritten** [comment]
This looks good, just a couple of questions:
* What does "ap" stand for? Azure platform?
* Do we want to retain the top and process output? I guess it's a double-check that things are working.

**Comment by stanislavlevin** [comment]
> This looks good, just a couple of questions:
> 
> * What does "ap" stand for? Azure platform?

azure pipelines, I can disclose it if needed
> * Do we want to retain the top and process output? I guess it's a double-check that things are working.

They are similar but I use them with different purposes:
- `top` makes noticeable resource-consuming processes (sorted by memory)
- `ps` shows process hierarchy (ps can't output process' forest sorted by memory, at least I don't know how to achieve it)

**Comment by rcritten** [comment]
Ok, I think it's fine as-is then. It's obvious enough when one looks at the patches that this involves Azure.

Thanks for addressing this for us!

**Comment by rcritten** [comment]
master:

* 0e8bde317505d57f2160e7ae4d4df01970f4b478 ap: Raise dbus timeout
* dd094e3889a62a863bf951e879e8dbd98adb3470 ap: Disable azure's security daemon
* 8542fd3012942814045f9603d6982f5601941ffb ap: Rearrange overloaded jobs
* e9b232fcf44bbf57deb9eb6de762cbc43d9e7e5d ap: Constrain supported docutils

**Comment by stanislavlevin** [comment]
@rcritten, thanks for looking at this :)

**Pull request closed without merging**
