### PR TITLE
ipatests: refactor test_ipa_cert_fix with tasks

### PR DESCRIPTION
**Pull request by fcami**
Fixes: https://pagure.io/freeipa/issue/8932
Signed-off-by: François Cami <fcami@redhat.com>

### CODE REVIEW

**Comment by rcritten** [comment]
LGTM, ack when tests are green.

**Comment by miskopo** [comment]
LGTM, let's just wait for greener runs.

**Comment by fcami** [comment]
@miskopo @rcritten we have a green run.

**Comment by miskopo** [comment]
Ack

**Comment by miskopo** [comment]
Sorry, on mobile, didn't see there is still temp commit. Removing ack not to accidentally merge it

**Comment by netoarmando** [comment]
@fcami test is timing out, `['getcert', 'list']` is being executed in loop.

**Comment by fcami** [comment]
@netoarmando thanks for looking, I think this is due to https://pagure.io/freeipa/issue/8815 ...

**Review by mrizwan93 — APPROVED** [review]
LGTM. I'll drop my changes in https://github.com/freeipa/freeipa/pull/5738/commits/0a8e77b0d469507ae211e2fc151a678fbc87b5e8

**Comment by fcami** [comment]
Thanks @mrizwan93 !

**Comment by fcami** [comment]
master:

* 8a4a338c09cfde7472f6c1a0b0151cc1b33df2aa ipatests: refactor test_ipa_cert_fix with tasks

**Pull request closed without merging**
