### PR TITLE
Tests: Verify that cert-find show CA without --all

### PR DESCRIPTION
**Pull request by mirielka**
https://fedorahosted.org/freeipa/ticket/6151

### CODE REVIEW

**Comment by tomaskrizek** [comment]
The same check should be also performed for `cert-show`.

The patch also added CA to `cert-request` command, but testing it is probably not worth the effort, since it requires a CSR file.

**Comment by pvoborni** [comment]
that reminds me this regression in cert-show: https://fedorahosted.org/freeipa/ticket/6022#comment:6

**Comment by mirielka** [comment]
I added check for cert-show and cert-request (it was quite easy to add it to existing test). I'd prefer to add test for #6022 separately when bugfix is provided.

**Comment by pvoborni** [comment]
Right, I only wanted to highlight the issue in #6022. It should be a separate patch.

**Comment by mbasti-rh** [comment]
Ticket is in already closed milestone, please change ticket in the commit message.

**Comment by mirielka** [comment]
Sorry for that, I created new ticket and changed commit message.

**Comment by tomaskrizek** [comment]
Ticket/commit msg seems to be correct now.

**Comment by mbasti-rh** [comment]
Fixed upstream
master:
https://fedorahosted.org/freeipa/changeset/42d1a06bd1e856c14110c06ba0d9d946df36331d
ipa-4-4:
https://fedorahosted.org/freeipa/changeset/7fde0982610cdc19ac4e85a6759820130c66a233

**Pull request closed without merging**
