### PR TITLE
Improve Terminology and use better words

### PR DESCRIPTION
**Pull request by tiran**
See https://tools.ietf.org/id/draft-knodel-terminology-01.html

### CODE REVIEW

**Comment by abbra** [comment]
In `migrate_ds` `oc_blacklist_option` and `attr_blacklist_option` are internal elements, they can be freely changed to `oc_blocklist_option` and `attr_blocklist_option`.

**Comment by rcritten** [comment]
+1 on Alexander's suggestion.

**Comment by tiran** [comment]
> In `migrate_ds` `oc_blacklist_option` and `attr_blacklist_option` are internal elements, they can be freely changed to `oc_blocklist_option` and `attr_blocklist_option`.

Thanks Alexander and Rob. I didn't realize that the attributes are only just internally. Fixed!

**Comment by abbra** [comment]
Should this be for git master only?

**Comment by flo-renaud** [comment]
master:

* 523f70ae46127161556a0881fc9a01e138a90666 Terminology improvements: CA renewal
* 5c09dcdb981df7837ac1bb75547d23fc7d8946d0 Grammar: whitespace is a word
* 3ce816ba772ffae6b0bd05e4589727513fa76e3c Terminology improvements: use allow list
* 3ec1b77f6a03886936299a9d34ed8fd640c3984d Terminology improvements: use block list

**Pull request closed without merging**
