### PR TITLE
upgrade: add missing DN suffix when enabling KDC proxy

### PR DESCRIPTION
**Pull request by tomaskrizek**
This issue prevented from upgrading from IPA 4.1.

I also discovered a missing python dependency when I was running the ipa-server-upgrade manually. For packagers: the Python version that has the required symbols in CentOS is 2.7.5-24

https://pagure.io/freeipa/issue/6920

### CODE REVIEW

**Comment by martbab** [comment]
This makes me wonder why don't we just use `self.api.env.basedn` in the ldap_enable/enable_kdcproxy/enable_pkinit methods but instead rely on 3 ways how to construct the root DN.

LGTM as a quick fix, but we need to overhaul this part service installers in the future.

**Comment by MartinBasti** [comment]
Works for me

**Comment by martbab** [comment]
A separate PR will be needed for ipa-4-5 branch.

**Comment by MartinBasti** [comment]
master:

* 999706fcdfa7fd4206a2399aa578fb00753d9978 python2-ipalib: add missing python dependency
* 4b8ab77dd4800bd9c6b822502462ee649c88c663 installer service: fix typo in service entry
* ebefb281775d5bd5f32459ac597af78781d7dbf5 upgrade: add missing suffix to http instance

**Pull request closed without merging**
