### PR TITLE
Add support for Hardware Security Module (HSM)

### PR DESCRIPTION
**Pull request by rcritten**
Implement the design for HSM support.

This PR set adds options for HSM token, library path and token password to the CA/KRA-related installers.

The intention is to test this in CI using a SoftHSM2 token. This is not recommended for production since it lacks the Hardware part of HSM.

It has additionally been smoke-tested using an nCipher HSM with CA installation.

The HSM code requires PKI 11.3.0+.

Non-HSM installations should not be affected.

### CODE REVIEW

**Comment by rcritten** [comment]
HSM-specific tests are still being written and the code is testable with rawhide.

**Comment by rcritten** [comment]
link to successful HSM tests: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/b3f48b20-b70a-11ed-9a3d-fa163ea4a9f1

**Comment by rcritten** [comment]
Purposely left off which branch to backport too until we decide if we want a new branch for this or not. I think 4.10 will be fine.

**Comment by mrizwan93** [comment]
More test is being written and will pushed.

**Comment by mrizwan93** [comment]
test_hsm.py::TestHSMInstallADTrustBase :: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/7d878786-b994-11ed-901d-fa163e46d29b

**Comment by rcritten** [comment]
TestHSMcertRenewal is failing with:

0.main - [03/Mar/2023:15:21:21 UTC] [20] [1] SystemCertsVerification: system certs verification failure: Certificate USnFgmpPPj:auditSigningCert cert-pki-kra is invalid: Invalid certificate: (-8101) Certificate type not approved for application.

The CA debug log shows it used the expected profile to issue it: CertProcessor: Submitting certificate request to caAuditSigningCert profile

and it was issued

enrollment reqID 0xf fromAgent userID: ipara authenticated by certUserDBAuthMgr is completed DN requested: CN=KRA Audit,O=IPA.TEST cert issued serial number: 0xf time: 34

The old and new certs look identical beyond serial number, before/after and signature.

The audit certificates should have a P trust flag. Can you add a certutil -L after each issuance so we can see what flags the certificates have?

**Comment by mrizwan93** [comment]
For future reference:
TestHSMACME :: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/e06472b8-bda6-11ed-899a-fa163ef13402

TestHSMBackupRestore :: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/ed5db4e6-bdbc-11ed-8453-fa163e998a26

TestADTrustInstallWithDNS_KRA_ADTrust :: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/ce12b7e0-bdd4-11ed-9f89-fa163e04db38

TestHSMCALessToExternalToSelfSignedCA :: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/ff0a2166-bda3-11ed-84fd-fa163e8572d3

TestHSMExternalToSelfSignedCA :: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/3d3ad1ea-bda1-11ed-ba5a-fa163e46d29b

TestHSMInstallADTrustBase :: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/942598d4-bdb8-11ed-ae58-fa163e33b8c8

**Comment by mrizwan93** [comment]
TestHSMcertRenewal :: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/1d23e244-be5e-11ed-a1ab-fa163e4874fd/

**Comment by mrizwan93** [comment]
TestHSMInstall  :: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/3a33e050-c386-11ed-866e-fa163ea4a9f1

TestHSMNegative :: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/e1f4372a-c342-11ed-83ed-fa163e383601

**Comment by rcritten** [comment]
The tests were stuck. Rebased and forced push to restart.

**Comment by mrizwan93** [comment]
TestHSMNegative: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/6cc5ad1c-d8aa-11ed-a313-fa163e2095e3

TestHSMcertRenewal: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/bfd28098-d8aa-11ed-9b7c-fa163ec85172

**Comment by rcritten** [comment]
The temp commit failures in rawhide are due to:

Problem: The operation would result in removing the following protected packages: dnf

**Comment by abbra** [comment]
FYI. Nitrokey's NetHSM can be run as a container: https://docs.nitrokey.com/nethsm/integration#development-and-testing. This is a proper opensource networking HSM that has integration with OpenSSL and other tools. May be we can use it for running our upstream CI tests?

**Comment by rcritten** [comment]
Closing this PR. Will replace it with a new one. It is ready for review now.

**Pull request closed without merging**
