### PR TITLE
ipatests: use python3 if built with python3

### PR DESCRIPTION
**Pull request by stlaz**
Change the default python version for test scripts

https://pagure.io/freeipa/issue/7131

### CODE REVIEW

**Comment by Rezney** [comment]
Tried a test run and the job automatically started running python3 version when issuing just "ipa-run-tests".

**Comment by felipevolpone** [comment]
hey @stlaz, I've uploaded a new template  (0.1.4), could you change your pr to use it?

**Comment by stlaz** [comment]
Of course, sorry I did not do this earlier, I was offline on Friday.

**Comment by stlaz** [comment]
@felipevolpone We also need a template which would have a python3-paramiko. Could you please test this before pushing a new template so that we don't have to create a new template for every missing dependency?

**Comment by felipevolpone** [comment]
@stlaz sure, I can update the template to have it. 
yeah, I'm trying to test it before releasing a new version, but as you can see here  https://github.com/felipevolpone/freeipa/pull/9 it's being quite complicated :/

**Comment by felipevolpone** [comment]
After fixing dependencies problems, the error related in https://pagure.io/freeipa/issue/7180 appears.
More info in the ticket.

**Comment by felipevolpone** [comment]
Please change the box version to [0.1.6](https://app.vagrantup.com/freeipa/boxes/ci-master-f26/versions/0.1.6)

**Comment by stlaz** [comment]
Ready for a review.

**Comment by felipevolpone** [comment]
Tested and works properly.
The tests runs fine now, however we are getting some warnings:
```
test_integration/test_simple_replication.py::TestSimpleReplication::()::test_user_replication_to_replica
  /usr/lib/python3.6/site-packages/paramiko/sftp_client.py:344: BytesWarning: str() on a bytes instance
    'open(%r, %r) -> %s' % (filename, mode, hexlify(handle)))
  /usr/lib/python3.6/site-packages/paramiko/sftp_file.py:86: BytesWarning: str() on a bytes instance
    self.sftp._log(DEBUG, 'close(%s)' % hexlify(self.handle))

test_integration/test_simple_replication.py::TestSimpleReplication::()::test_replica_removal
  /usr/lib/python3.6/site-packages/paramiko/sftp_client.py:344: BytesWarning: str() on a bytes instance
    'open(%r, %r) -> %s' % (filename, mode, hexlify(handle)))
  /usr/lib/python3.6/site-packages/paramiko/sftp_file.py:86: BytesWarning: str() on a bytes instance
    self.sftp._log(DEBUG, 'close(%s)' % hexlify(self.handle))
```

IMO we can address them in another PR/ticket.

**Comment by tomaskrizek** [comment]
master:

* a93592a739465429e5e87de2154cf42ce010de88 PRCI: use a new template for py3 testing
* d39456a882efacbfefcc1f987ebf89ceeb761f61 ipatests: use python3 if built with python3
* 71a80264966070fb2e43c838e27875efca035a17 py3: pass raw entries to LDIFWriter

**Pull request closed without merging**
