### PR TITLE
Fontawesome spec changes

### PR DESCRIPTION
**Pull request by abbra**
This is a small fix from Fedora to allow installing on Rawhide

### CODE REVIEW

**Comment by rcritten** [comment]
Are the additional, unrelated patches expected?

**Comment by abbra** [comment]
Sadly, yes. We have broken mirroring from Pagure at the moment. These are what is in master already but not in github's tree.

**Comment by rcritten** [comment]
nit: no sign-off on the font patch, and no real description what this Requires magic does.

**Comment by abbra** [comment]
@rcritten I added a bit of description in the commit message and also added sign-offs.

**Comment by rcritten** [comment]
Thanks, LGTM.

It looks like the pagure -> github sync is working again. Is a rebase needed to make merging easier?

**Comment by rcritten** [comment]
master:

* da65cc35bdac530eec6c62307a48d76d582c177c Change fontawesome-fonts requires to match fontawesome 4.x

**Pull request closed without merging**
