### PR TITLE
[Backport][ipa-4-8] [ipatests][Azure Pipelines] Populate containers with self-AAAA records

### PR DESCRIPTION
**Pull request by stanislavlevin**
This PR was opened manually because PR #5486 was pushed to master and backport to ipa-4-8 is required.

### CODE REVIEW

**Comment by netoarmando** [comment]
PR-CI tests for `ipa-4-8` branch are installing latest release from stable repos, https://github.com/freeipa/freeipa-pr-ci/issues/419.

**Comment by wladich** [comment]
@stanislavlevin 
As https://github.com/freeipa/freeipa-pr-ci/issues/419 is closed, package installation should be working now.
Please rebase the PR to re-run the tests. Adding "re-run" label is not enough as current green results are for IPA version  from Fedora repo.

**Comment by stanislavlevin** [comment]
@wladich, great, thank you! Rebased.

**Comment by stanislavlevin** [comment]
Rebased to Pylint fixes.

**Comment by flo-renaud** [comment]
ipa-4-8:

* af96a07c01bc60ec8668751a80fb14b19d8d7481 Azure: Populate containers with self-AAAA records
* 11e4e159339d37d136e8d06eb991498aed3861e1 ipatests: Handle AAAA records in test_ipa_dns_systemrecords_check
* e9a5c8af6854c2b4fbe8dfa59da504795a6e73b9 rpm-spec: Require crypto-policies-scripts

**Pull request closed without merging**
