### PR TITLE
ipatests: healthcheck: Sync the expected system RRs

### PR DESCRIPTION
**Pull request by stanislavlevin**
The support for the DNS URI RRs has been added in freeipa-healthcheck:
https://github.com/freeipa/freeipa-healthcheck/issues/222

Fixes: https://pagure.io/freeipa/issue/9054

### CODE REVIEW

**Comment by stanislavlevin** [comment]
This PR can be held until the new release of freeipa-healthcheck.
I've checked it on ALTLinux because I made the downstream release of the latter with several cherrypicks from `master`.

**Comment by rcritten** [comment]
Adding re-run to run full CI.

**Comment by stanislavlevin** [comment]
:-) gating CI triggered.

**Comment by rcritten** [comment]
I'm preparing a new healthcheck upstream release now.

**Comment by rcritten** [comment]
I tested this with the new upstream release and it works there as well. Ack.

**Comment by rcritten** [comment]
@stanislavlevin I assume we want to backport this to the ipa-4-9 branch?

**Comment by stanislavlevin** [comment]
@rcritten, `ipa-4-9` was added, thank you!

**Comment by rcritten** [comment]
ack, thanks for the patch.

**Comment by rcritten** [comment]
master:

* 54f8733f4a01da6a681177ec9e6ee6120d65c5f2 ipatests: healthcheck: Sync the expected system RRs

**Pull request closed without merging**
