### PR TITLE
[Backport][ipa-4-6] Use the user-provided CA chain file in connections & check for file existence

### PR DESCRIPTION
**Pull request by rcritten**
This PR was opened automatically because PR #1047 was pushed to master and backport to ipa-4-6 is required.

### CODE REVIEW

**Comment by rcritten** [comment]
PR was ACKed automatically because this is backport of PR #1047. Wait for CI to finish before pushing. In case of questions or problems contact @rcritten who is author of the original PR.

**Comment by tiran** [comment]
The ipa-4-6 also uses the ``@freeipa/freeipa-master `` COPR, which contains python-ldap 3.0.0. The 4.6 branch is blocked by PR #1371

**Comment by tiran** [comment]
@rcritten CI is failing, please ``git rebase upstream/ipa-4-6``

**Comment by tiran** [comment]
ipa-4-6:

* 806b76b650da1d2b7c2fe135dfe3691355e1e849 Use the CA chain file from the RPC context
* cd0066a5de7bb58e0169917ec4eeb6d4b96055cf Add test to ensure that properties are being set in rpcclient
* 6273ec612b1318fbab2208b39d5855909c38e983 If the cafile is not present or readable then raise an exception

**Pull request closed without merging**
