### PR TITLE
Migrate OTP import script to python-cryptography

### PR DESCRIPTION
**Pull request by tiran**
Supersedes @npmccallum PR #486

### CODE REVIEW

**Comment by tiran** [comment]
The importer uses RSAES-PKCS1 v1.5 to decrypt a session key. PKCS1 v1.5 is potentially vulnerable to CCA Bleichenbacher. In my professional opinion, the OTP importer cannot be abused as an oracle. The script is used as a one-shot importer and not run as an interactive service.

**Comment by MartinBasti** [comment]
@stlaz Why is this closed? I don't see any push/commit here

**Comment by stlaz** [comment]
This is tested by our tests and the code is fine => ACK.

**Comment by MartinBasti** [comment]
master:

* d00ae870dda2889545c9d93e82e44526bfd4f431 Migrate OTP import script to python-cryptography
* 135d0b5dd111d40632e2cd5be8f5315684b45fc6 Finish port to PyCA cryptography

**Pull request closed without merging**
