### PR TITLE
[Backport][ipa-4-6] ipa otptoken-sync: return error when sync fails

### PR DESCRIPTION
**Pull request by rcritten**
This PR was opened automatically because PR #6472 was pushed to master and backport to ipa-4-6 is required.

### CODE REVIEW

**Comment by rcritten** [comment]
PR was ACKed automatically because this is backport of PR #6472. Wait for CI to finish before pushing. In case of questions or problems contact @flo-renaud who is author of the original PR.

**Comment by flo-renaud** [comment]
The build is failing because of the python version that does not support f-strings:
```
Compiling /builddir/build/BUILDROOT/freeipa-4.6.9.dev-0.fc27.x86_64/usr/lib/python2.7/site-packages/ipatests/test_integration/test_otp.py ...
  File "/usr/lib/python2.7/site-packages/ipatests/test_integration/test_otp.py", line 213
    stdin_text=f"invalidpwd\n{otp2}\n{otp3}\n", raiseonerr=False
                                             ^
SyntaxError: invalid syntax
```
I will adapt the patch as soon as possible.

**Comment by flo-renaud** [comment]
Removing the ACK as the test is failing (see this [run](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/fb43c342-409a-11ed-82fa-fa163e57b5d2/)). Investigating...

**Comment by flo-renaud** [comment]
An old backport was missing in the branch: https://pagure.io/freeipa/c/e8b98555fcbdc76c2e728d0c93cbbabeebad9a26

With this additional backport, the test is green, see the run at http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/9affbf08-40af-11ed-82fa-fa163e57b5d2/

**Comment by rcritten** [comment]
Do we need to disable readthedocs in ipa-4-6? It's blocking the push (I mean, I can force it surely, but should I)

**Comment by flo-renaud** [comment]
ipa-4-6:

* e2238fdf92b1df15e510d190cf3c4201dd51cbee ipa otptoken-sync: return error when sync fails
* 0c62aef1482ea97aaa04af667980a99faa0071a8 ipatests: add negative test for otptoken-sync
* 69c376b9e62c39f73bc9dbce081c29a0c448f3ca ipatests: python2 does not support f-strings
* d587d0f48b488e862674bdd8c2b6d0a75eee0612 Fix otptoken_sync plugin

**Comment by flo-renaud** [comment]
> Do we need to disable readthedocs in ipa-4-6? It's blocking the push (I mean, I can force it surely, but should I)

I force-pushed but we need to disable readthedocs on this branch. @abbra agreed to have a look at it.

**Pull request closed without merging**
