### PR TITLE
[Experimental] Sandbox and secure systemd services

### PR DESCRIPTION
**Pull request by tiran**
Signed-off-by: Christian Heimes <cheimes@redhat.com>

### CODE REVIEW

**Comment by tiran** [comment]
```
# systemd-analyze security ipa-otpd@.service ipa-custodia.service krb5kdc.service kadmin.service named-pkcs11.service httpd.service pki-tomcatd@pki-tomcat.service smb.service winbind.service ipa-dnskeysyncd.service dirsrv@IPA-EXAMPLE.service
...
UNIT                           EXPOSURE PREDICATE HAPPY
ipa-otpd@test-instance.service      9.6 UNSAFE    😨    
ipa-custodia.service                9.2 UNSAFE    😨    
krb5kdc.service                     9.6 UNSAFE    😨    
kadmin.service                      9.6 UNSAFE    😨    
named-pkcs11.service                9.2 UNSAFE    😨    
httpd.service                       9.2 UNSAFE    😨    
pki-tomcatd@pki-tomcat.service      9.1 UNSAFE    😨    
smb.service                         9.7 UNSAFE    😨    
winbind.service                     9.7 UNSAFE    😨    
ipa-dnskeysyncd.service             8.8 EXPOSED   🙁    
dirsrv@IPA-EXAMPLE.service          9.7 UNSAFE    😨 
```

**Comment by abbra** [comment]
So, where do you want to go with this? Should we expand it to all our services (as snippets?)

**Comment by tiran** [comment]
Yes, that's the idea. I like to upstream most of the hardening settings, too.

**Comment by tiran** [comment]
I'll finish this another time with proper design.

**Pull request closed without merging**
