### PR TITLE
smartcard: make the ipa-advise script compatible with authselect/auth…

### PR DESCRIPTION
**Pull request by flo-renaud**
…config

"ipa-advise config-client-for-smart-card-auth" is run on a server and
creates a script that needs to be copied and executed on a client.
The client may be of a different version and use authconfig instead of
authselect. The generated script must be able to handle both cases
(client using authselect or client using authconfig).

The patch checks whether authselect is available and calls the proper
configuration command (authselect or authconfig) depending on its
availability on the client.

Fixes: https://pagure.io/freeipa/issue/8113

### CODE REVIEW

**Comment by rcritten** [comment]
I think a dependency on which may be required.

**Comment by flo-renaud** [comment]
@rcritten 
thanks for the suggestion. I replace the `if which authselect` check with `if [ -f /usr/bin/authselect ]`.

**Comment by rcritten** [comment]
I hadn't really thought this through last night but I guess these scripts are already broken on non-redhat/fedora bases anyway since they use authselect/authconfig directly so this is probably ok. On non-redhat platforms paths.AUTHSELECT == None.

LGTM.

**Comment by flo-renaud** [comment]
master:

* 87c24ebd34d4524b73d878f1298232547cafc5ba smartcard: make the ipa-advise script compatible with authselect/authconfig

**Pull request closed without merging**
