### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by rffontenelle**
Same as #7004, but including one last commit that fixes syntax error in Georgian translation. I manual obtained the fix from Weblate.

### CODE REVIEW

**Comment by rcritten** [comment]
FWIW the Tox failure was addressed so if this patch is rebased the CI should pass.

**Comment by abbra** [comment]
@rffontenelle could you please rebase? We have merged fixes that prevented some of CI from successfully passing.

**Comment by rffontenelle** [comment]
I initially based this pull request in Weblate's translation branch, but then I noticed I failed to solve the rebase issue present in the aforementioned pull request.

Then I chose to download the PO file and recommit them setting the proper author credits for each language. This is merge-conflict-free and will successfully store the current translation contributions.

Once merged, I'll be able to do destructive operation in Weblate to clean all attempts to push contributions, because they are already in the repository.

Now, to the root to the issue: I see in the [po/ directory's commit history](https://github.com/freeipa/freeipa/commits/master/po) that the PO files are being updated along with the POT file. This is what is causing the conflicts commit after commit. Is it possible to update only the POT file? Once the POT is updated, Weblate will see it and will run msgmerge to update the PO files in Weblate. This presents no impact to freeipa, except for avoiding conflicts like that.

**Comment by abbra** [comment]
Sounds good. We can try to do separate commits, for sure.

**Comment by flo-renaud** [comment]
master:

* 41bc6fc3825644cf3d7fc29dd4c5575a94c6caa7 Translated using Weblate (Georgian)
* abc48e285e1a12efc953d51533b1aed3a212fe36 Translated using Weblate (Korean)
* c3cb63e5823b59213f9968449319807bd667dfda Translated using Weblate (Finnish)
* 9e31e7043499cfb6f3f3fc0a12bb17df0c2c1dc2 Translated using Weblate (Polish)
* 591bbee847f03450540e54101bbf07475c61f303 Translated using Weblate (Ukrainian)
* b9552bcb71085cb963553a56eba2938e6ec2dc85 Translated using Weblate (Indonesian)

**Pull request closed without merging**
