### PR TITLE
Parse cert chain as JSON not XML

### PR DESCRIPTION
**Pull request by ckelleyRH**
On `dogtagpki/pki` master XML is being replaced by JSON in PKI 11.0+

The PR for `dogtagpki/pki` that makes this change necessary is:
https://github.com/dogtagpki/pki/pull/3677

### CODE REVIEW

**Comment by ckelleyRH** [comment]
@rcritten while I was making this change I noticed that there are CA `get_status()/_parse_ca_status()` methods in this script, which are still expecting XML responses. From what I can tell, they're only called by methods from the `SuseCAService` and `RedHatCAService` classes. The CI didn't pick this up, so I guess this is a gap in the coverage. Would you like me to fix this while I'm in here, otherwise someone is going to step on this landmine in the future?

**Comment by ckelleyRH** [comment]
@rcritten FYI the [copr repo](https://copr.fedorainfracloud.org/coprs/ckelley/pki/) from #5932 contains an updated build with the dogtag patch in dogtagpki/pki#3677.

**Comment by rcritten** [comment]
Yes, I think it's worth fixing this as well.

**Comment by rcritten** [comment]
CI tests pass in the other PR and code LGTM.

**Comment by flo-renaud** [comment]
master:

* 6e2ca193a1bdf6895eeb2ea89abb6636379f7bbc Parse cert chain as JSON not XML

**Pull request closed without merging**
