### PR TITLE
man: fix a couple of instances of the "no-break control character" being used inadvertently

### PR DESCRIPTION
**Pull request by yrro**
Fixes https://pagure.io/freeipa/issue/9665

### CODE REVIEW

**Comment by abbra** [comment]
LTGM.

**Comment by abbra** [comment]
I am not running the whole CI set of tests because the change is limited to the two man pages only.

**Comment by flo-renaud** [comment]
Checked the man pages with `man -l client/man/ipa-client-install.1` and `man -l client/man/ipa.1`, both are rendered as expected.

**Comment by flo-renaud** [comment]
master:

* 2df2066a4ea5113187039371adc25fcd1d4ab7b5 Fix a couple of instances of the "no-break control character" being used inadvertently

**Pull request closed without merging**
