### PR TITLE
[ipa-4-10] ipatests: update vagrant boxes

### PR DESCRIPTION
**Pull request by flo-renaud**
Use new versions of vagrant boxes:
ci-ipa-4-10-f36 0.0.2
ci-ipa-4-10-f37 0.0.2

Signed-off-by: Florence Blanc-Renaud <flo@redhat.com>

### CODE REVIEW

**Comment by flo-renaud** [comment]
The boxes were tested with the test `simple_replication`. Link to successful results:
- `fedora-latest-ipa-4-10/simple_replication`: [Details](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/4092a838-6723-11ed-a345-fa163e390eb7)
- `fedora-previous-ipa-4-10/simple_replication`: [Details](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/6781af2a-6723-11ed-ac1a-fa163eeee9dc)

Removing the temp commit.

**Comment by abbra** [comment]
LGTM. ACK when all tests green.

**Comment by flo-renaud** [comment]
The test failures are related to xfail annotations that can be removed, should be handled by PR #6500 and PR #6561

**Comment by flo-renaud** [comment]
Tests are green, ack'ing per @abbra's comment

**Comment by flo-renaud** [comment]
ipa-4-10:

* f5fb8b05a75c4b88534cddd4aa298a741d221b59 ipatests: update vagrant boxes

**Pull request closed without merging**
