### PR TITLE
cert-request: simplify request processing

### PR DESCRIPTION
**Pull request by frasertweedale**
Currently the cert-request execution is complicated and cannot
handle aliases in the --principal argument.

Implement the following simplifications:

- Search all user/host/service accounts at once, by krbPrincipalName
  (error if no account found).  Use principal canonical name to
  determine the type of the principal.

- Update subject principals userCertificate attribute uniformly,
  instead of dispatching to user/host/service-mod based on type of
  principal.

Fixes: https://fedorahosted.org/freeipa/ticket/6531

---

This patch has been ageing in oak for months; it was written and
tested before the PKINIT changes landed, so I have just rebased it,
with minor tweaks, and haven't throughly tested it yet.

Anyway I publish it now to entice review and get CI to do some of
the testing for me... and to reduce bus factor.

Edit: tests all pass so let's get this reviewed and merged.

### CODE REVIEW

**Comment by felipevolpone** [comment]
LGTM. I've tested it and it works properly.

**Comment by frasertweedale** [comment]
@felipevolpone thanks for reviewing!

**Comment by tomaskrizek** [comment]
master:

* d84510abe82795cb45c84c46b81a1121bdda7d33 cert-request: simplify request processing

**Comment by tomaskrizek** [comment]
I accidentally pushed this PR to a mirror repo instead of upstream. Sorry about that. I'm re-opening the PR and pushing it to the proper repo.

**Comment by tomaskrizek** [comment]
master:

* 227cf8d4e98178212386eca0a1ac21459436e63f cert-request: simplify request processing

**Pull request closed without merging**
