### PR TITLE
[WIP] Refactor LDAPClient

### PR DESCRIPTION
**Pull request by tiran**
**WORK IN PROGRESS**

Simplify LDAPClient construction and ensure that LDAP connections are always secure (LDAP + STARTTLS, LDAPI, LDAPS) unless explicitly stated otherwise.

### CODE REVIEW

**Comment by rcritten** [comment]
Just a note that moving functions around is exactly that kind of thing that breaks external users of the API. It makes logic sense but is is really needed?

**Comment by tiran** [comment]
@rcritten That makes sense. I have added aliases with deprecation warnings to ``installutils``. The previous function locations still work, but users will be informed that they are using a deprecated name.

**Comment by rcritten** [comment]
Was this replaced by https://github.com/freeipa/freeipa/pull/2697 ?

**Comment by tiran** [comment]
Mostly, PR #2697 doesn't have https://github.com/freeipa/freeipa/pull/2628/commits/d1041ab3d0296825f86112de4befe2312f831cea and https://github.com/freeipa/freeipa/pull/2628/commits/ca7e5c87a55bb25aa2a66dc16293754198cc77f3. The commits add ``nsslapd-require-secure-binds: on`` and strong SSF.

**Comment by tiran** [comment]
PRs #2812 and #2813 replace this PR.

**Pull request closed without merging**
