### PR TITLE
selinux: Fix/waive issues reported by SELint

### PR DESCRIPTION
**Pull request by vmojzis**
- order permissions alphabeticaly
- do not use semicollon after interfaces
- gen_require should only be used in interfaces
-- to resolve this issue, corresponding changes have to be made in
distribution policy instead of ipa module - disabling check for now

### CODE REVIEW

**Comment by abbra** [comment]
LGTM. I kicked full CI as Azure CI does not run SELinux operations.

**Comment by fcami** [comment]
Temporary removing ack.
The changes LGTM, please bear with me.

**Comment by abbra** [comment]
master:

* b9d3860c8a7111b503fe2660fa8d2241125f6f4a selinux: Fix/waive issues reported by SELint
* f83195f5c1bf6d3fae1073c72521f4b6cd0788d4 set SELinux to Enforcing in gating.xml

**Comment by abbra** [comment]
@fcami could you please do a manual backport to ipa-4-8?

**Comment by fcami** [comment]
@abbra yes, when I'm back if you do not mind.

**Pull request closed without merging**
