### PR TITLE
dsinstance: Restore context after changing dse.ldif

### PR DESCRIPTION
**Pull request by abbra**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1490762

### CODE REVIEW

**Comment by rcritten** [comment]
What isn't obvious to me is what changed. This code has been around since 2015. Was it a fluke that it worked up to now?

**Comment by abbra** [comment]
That's a good question. No, I don't have an answer. But since we have two bugs where this is manifested in two different SELinux contexts, there must be something different now in F27.

**Comment by rcritten** [comment]
LGTM

**Comment by stlaz** [comment]
It's working. I'd ACK it but we really need a ticket to decide which branches it should be pushed into.

**Comment by lslebodn** [comment]
>It's working. I'd ACK it but we really need a ticket to decide which branches it should be pushed into.

Ideally to all branches which introduced this regression (from SELinux POV) :-)

**Comment by lslebodn** [comment]
>It's working. I'd ACK it but we really need a ticket to decide which branches it should be pushed into.

Ideally to all branches which introduced this regression (from SELinux POV) :-)

**Comment by stlaz** [comment]
I created an issue for this: https://pagure.io/freeipa/issue/7150
If you please add it to the ticket, I can at least push this to master + ipa-4-6 for now and we'll decide the other branches on the next devel meeting.

**Comment by abbra** [comment]
Rebased and added upstream issue references.

**Comment by stlaz** [comment]
master:

* 473ddbdb66e563d93a30ac51b1ac559adbd18190 dsinstance: Restore context after changing dse.ldif

**Pull request closed without merging**
