### PR TITLE
re-enable test_sss_ssh_authorizedkeys

### PR DESCRIPTION
**Pull request by fcami**
test_sss_ssh_authorizedkeys was disabled but recent test runs show it might be working properly.
Run in multiple times to see if it works.

Note two commits: I'd rather keep the -v even if we end up disabling the test again, so these commits should not be squashed.

### CODE REVIEW

**Comment by fcami** [comment]
Got three failures:
http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/132deab6-cfda-11ea-a3e4-fa163e2dc507/
http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/08df6756-cfda-11ea-aab9-fa163e23289d/
http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/f1bb1912-cfd9-11ea-921b-fa163e670c62/
All are unrelated.
PR for failures at: https://github.com/freeipa/freeipa/pull/4947
Adding re-run

**Comment by fcami** [comment]
Another failure due to the same, unrelated cause: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/e4c5e1c0-d023-11ea-bce3-fa163ee1d49c/

**Comment by fcami** [comment]
@netoarmando could you please have a look?

**Comment by netoarmando** [comment]
> @netoarmando could you please have a look?

This is new to me, it doesn't look like a CI issue, since a SSHClient connection is successfully made twice before that failure and host _is_ reachable.
I wonder if it's something flaky related to SSSD, but it's beyond my knowledge. @mrizwan93 do you have any insight on this?


```
Jul 27 07:46:07 master.ipa.test krb5_child[33275][33275]: Preauthentication failed
Jul 27 07:46:07 master.ipa.test audit[33272]: USER_AUTH pid=33272 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=PAM:authentication grantors=? acct="testuser" exe="/usr/sbin/sshd" hostname=192.168.122.165 addr=192.168.122.165 terminal=ssh res=failed'
Jul 27 07:46:07 master.ipa.test krb5_child[33275][33275]: Preauthentication failed
Jul 27 07:46:07 master.ipa.test sshd[33272]: pam_sss(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=192.168.122.165 user=testuser
Jul 27 07:46:07 master.ipa.test sshd[33272]: pam_sss(sshd:auth): received for user testuser: 7 (Authentication failure)
Jul 27 07:46:09 master.ipa.test sshd[33272]: Failed password for testuser from 192.168.122.165 port 36718 ssh2
```
[master.ipa.test/journal.gz](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/f1bb1912-cfd9-11ea-921b-fa163e670c62/test_integration-test_commands.py-TestIPACommand-test_login_wrong_password/master.ipa.test/journal.gz)

```
(2020-07-27  7:46:07): [pam] [pam_dp_send_req] (0x0100): Sending request with the following data:
(2020-07-27  7:46:07): [pam] [pam_print_data] (0x0100): command: SSS_PAM_AUTHENTICATE
(2020-07-27  7:46:07): [pam] [pam_print_data] (0x0100): domain: ipa.test
(2020-07-27  7:46:07): [pam] [pam_print_data] (0x0100): user: testuser@ipa.test
(2020-07-27  7:46:07): [pam] [pam_print_data] (0x0100): service: sshd
(2020-07-27  7:46:07): [pam] [pam_print_data] (0x0100): tty: ssh
(2020-07-27  7:46:07): [pam] [pam_print_data] (0x0100): ruser: not set
(2020-07-27  7:46:07): [pam] [pam_print_data] (0x0100): rhost: 192.168.122.165
(2020-07-27  7:46:07): [pam] [pam_print_data] (0x0100): authtok type: 1
(2020-07-27  7:46:07): [pam] [pam_print_data] (0x0100): newauthtok type: 0
(2020-07-27  7:46:07): [pam] [pam_print_data] (0x0100): priv: 1
(2020-07-27  7:46:07): [pam] [pam_print_data] (0x0100): cli_pid: 33272
(2020-07-27  7:46:07): [pam] [pam_print_data] (0x0100): logon name: testuser
(2020-07-27  7:46:07): [pam] [pam_print_data] (0x0100): flags: 2
(2020-07-27  7:46:07): [pam] [pam_dom_forwarder] (0x0100): pam_dp_send_req returned 0
(2020-07-27  7:46:07): [pam] [pam_dp_send_req_done] (0x0200): received: [7 (Authentication failure)][ipa.test]
(2020-07-27  7:46:07): [pam] [filter_responses] (0x0100): [pam_response_filter] not available, not fatal.
(2020-07-27  7:46:07): [pam] [pam_reply] (0x0200): blen: 25
(2020-07-27  7:46:07): [pam] [pam_reply] (0x0200): Returning [7]: Authentication failure to the client
(2020-07-27  7:46:09): [pam] [client_recv] (0x0200): Client disconnected!
```
[sssd_pam.log.gz](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/f1bb1912-cfd9-11ea-921b-fa163e670c62/test_integration-test_commands.py-TestIPACommand-test_login_wrong_password/master.ipa.test/var/log/sssd/sssd_pam.log.gz)

**Comment by fcami** [comment]
hi @netoarmando sorry, I was not clear, the above issue is fully expected.
What I meant to ask: could you please have a look at the proposed change which re-enables test_sss_ssh_authorizedkeys? I was not able to find a failure and as the temp_commit above shows, it is able to run without issue (or at least, without any issue that I could spot).

**Comment by netoarmando** [comment]
@fcami makes total sense. :-D I didn't remember being involved in skipping this test :-)

Looks good to me!
We still get the message: `Could not chdir to home directory /home/testsshuser: No such file or directory`, but since it was displayed when I manually ssh'd into the host, I guess it's fine. 

You can remove the temp commit now.

**Comment by fcami** [comment]
Temp commit removed, thank you @netoarmando

**Comment by fcami** [comment]
master:

* f7ed159769de26b24a0df86786eecdd07fe5e224 ipatests: re-enable test_sss_ssh_authorizedkeys
* 178d80969c52fbd0c6de28729d9c5281e9ca2578 ipatests: test_sss_ssh_authorizedkeys

**Pull request closed without merging**
