### PR TITLE
ipa-cert-fix: improve handling of 'pki-server cert-fix' failure

### PR DESCRIPTION
**Pull request by frasertweedale**
'pki-server cert-fix' has a known and expected failure when the DS
certificate is expired.  'ipa-cert-fix' handles this by
optimistically ignore the CalledProcessError and continuing when the
DS certificate was up for renewal.

This heuristic is a bit too optimistic.  If 'pki-server cert-fix'
fails due and returns nonzero due to some other, more serious error
(as has been seen in the wild[1]), 'ipa-cert-fix' continues then
fails later with a more confusing error, for example:

    [Errno 2] No such file or directory:
      '/etc/pki/pki-tomcat/certs/27-renewed.crt'

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1930586

Improve the heuristic by also checking whether output files
corresponding ot all of the "extra" certificate that we asked
'ipa-cert-fix' to renew, do indeed exist and are X.509 certificates.

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1779984

### CODE REVIEW

**Comment by frasertweedale** [comment]
Fixed typos in the commit message, and added temp commit for running `test_ipa_cert_fix`.

**Comment by frasertweedale** [comment]
`test_cert_fix` integration test passes: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/de3a06b4-74c5-11eb-af26-fa163e462157/ .

Removing temp commit.

**Comment by flo-renaud** [comment]
Hi @frasertweedale 
thanks for the PR, works for me:
- [x] all the certs are expired and IPA-issued, `ipa-cert-fix` completes successfully
- [x] all the certs are expired, LDAP cert is 3rd part, `ipa-cert-fix` prints that it won't renew LDAP cert and renews all the other certs, completes successfully
- [x] all the certs are expired and IPA-issued but the directive `selftests.container.order.startup` is missing from CS.cfg, `ipa-cert-fix` fails as expected (because `pki-server cert-fix` exits on error) and prints the error log from pki-server cert-fix.

The azure pipeline is failing in the tox check but this doesn't look related to your fix:
```
************* Module ipaclient.plugins.vault
lib/python3.8/site-packages/ipaclient/plugins/vault.py:559: [R1710(inconsistent-return-statements), _TransportCertCache.load_cert] Either all return statements in a function should return an expression, or none of them should.)
lib/python3.8/site-packages/ipaclient/plugins/vault.py:659: [R1710(inconsistent-return-statements), ModVaultData._do_internal] Either all return statements in a function should return an expression, or none of them should.)
************* Module ipalib.rpc
lib/python3.8/site-packages/ipalib/rpc.py:687: [R1710(inconsistent-return-statements), KerbTransport.single_request] Either all return statements in a function should return an expression, or none of them should.)

```

**Comment by flo-renaud** [comment]
FYI PR https://github.com/freeipa/freeipa/pull/5582 should fix the pylint issue.

**Comment by frasertweedale** [comment]
@flo-renaud thank you.  I rebased, and now we're green.

**Comment by flo-renaud** [comment]
Hi @frasertweedale 
I noticed a bit late that the commit msg refers to a BZ. As we need a pagure ticket, I cloned the BZ into https://pagure.io/freeipa/issue/8721.
Could you update the commit msg with a link to the pagure ticket? Thanks

**Comment by frasertweedale** [comment]
@flo-renaud thank you, I updated the `Fixes: ` line in the commit message.  The commit message still has a *reference* to the pki-core BZ, because there is no corresponding upstream Dogtag ticket yet.

**Comment by flo-renaud** [comment]
Thanks for the updated commit msg, everything is in order now and ready to be committed.

**Comment by flo-renaud** [comment]
@frasertweedale do you want a backport to ipa-4-9? IMO the fix is worth inclusion.

**Comment by frasertweedale** [comment]
Sure, I'll backport it to ipa-4-9.

**Comment by frasertweedale** [comment]
master:

* 8c2c6f825337aebc3bbd07ffa875547f4bb6a40b (HEAD) ipa-cert-fix: improve handling of 'pki-server cert-fix' failure

**Pull request closed without merging**
