### PR TITLE
ipa-replica-install: password and admin-password options mutually exclusive

### PR DESCRIPTION
**Pull request by flo-renaud**
## ipa-replica-install: make password and admin-password options mutually exclusive
Currently it is possible to run ipa-replica-install in one step, and provide --password and --admin-password simultaneously.
This is confusing as --password is intended for one-time pwd when the ipa-replica-install command is delegated to a user who doesn't know the admin password.

The fix makes --password and --admin-password options mutually exclusive.
    
Fixes https://pagure.io/freeipa/issue/6353

## ipatests: add test for ipa-replica-install options
Add a test checking that --password and --admin-password options are mutually exclusive.

### CODE REVIEW

**Comment by tiran** [comment]
Thanks for the patch and for the really fast test -- just 20 seconds.

**Comment by flo-renaud** [comment]
Also adding ipa-4-6 label as a backport will be required.
Temp commit removed.

**Comment by Tiboris** [comment]
master:

* 23306a28c9181065ab3f2828ab2df56c152e2c62 ipa-replica-install: password and admin-password options mutually exclusive
* 26e35dca413ecfa68df0b6115bed17ea4421fe31 ipatests: add test for ipa-replica-install options

**Comment by Tiboris** [comment]
Failed to apply patches onto origin/ipa-4-6. Manual backport is needed.

**Pull request closed without merging**
