### PR TITLE
WebUI: Clarify purpose of OTP field in password reset form on login 

### PR DESCRIPTION
**Pull request by Carbenium**
Fixes: https://pagure.io/freeipa/issue/5628

### CODE REVIEW

**Comment by abbra** [comment]
The changes look good but commits are in dire need of expanded messages. ;)
Please think about the changes and add explanation in the commit messages. For example, you might want to say for the commit that moves OTP field to be after the new password field solves a usability issue with OTP value expiration while user types a new password. This would help a lot in future as it would make the reasoning self-evident.

**Comment by Carbenium** [comment]
@abbra I gave it a shot. :wink:

**Comment by abbra** [comment]
LGTM.

**Comment by flo-renaud** [comment]
master:

* 13b177822ea8382c9c5986862424f8ff8f08f16f WebUI: move OTP to be the last field in the PW reset form
* d63a91da4bb1b20b2cb0601bcb3a640ab8511151 WebUI: reword OTP info message displayed during PW reset
* ea5c0a1f7c1b2902a74731787710bee40542330f Unify spelling of "One-Time Password"

**Pull request closed without merging**
