### PR TITLE
Apply validate_doc() to NO_CLI commands

### PR DESCRIPTION
**Pull request by stanislavlevin**
For now validate_doc() checks NO_CLI commands only.

From validate_doc:
```
 * Every command must have documentation
and it must be marked for international translation

* Every module hosting a command must have documentation
and it must be marked for international translation

* Every module topic must be marked for international translation
```

So, to prevent from NO_CLI commands have no translatable
description or have no one at all in Web UI API Browser 
validation of ```__doc__``` is required.

https://pagure.io/freeipa/issue/7592
Additionally, 
```
1 commands without doc, 0 commands whose doc is not i18n
1 modules without doc, 2 modules whose doc is not i18n
```
are fixed.

### CODE REVIEW

**Comment by Tiboris** [comment]
Hello @stanislavlevin,

thank you for the patch, it will be pushed upstream.

**Comment by Tiboris** [comment]
Could you please add link to the pagure issue to second commit ?

**Comment by stanislavlevin** [comment]
Hello @Tiboris ,
thank you for review!

Commit message was updated.

**Comment by tiran** [comment]
master:

* 32ed10caf95973a0103d1257a1074e0343a91f47 Apply validate_doc() to NO_CLI commands
* c1f7a14c95fbf1d247f63c343fdd6a5773e1ab16 Fix some untranslatable commands in Web UI API Browser

**Pull request closed without merging**
