### PR TITLE
Restore selinux states if they exist at uninstall time

### PR DESCRIPTION
**Pull request by abbra**
Related: https://pagure.io/freeipa/issue/9434

### CODE REVIEW

**Comment by flo-renaud** [comment]
Thanks for the PR, I was investigating and came to the same fix.
ACK for  when prci completes.

**Comment by rcritten** [comment]
master:

* 6aa3c3b6284967bd7d4d27afd9f82d3f7f679428 Restore selinux states if they exist at uninstall time

**Comment by rcritten** [comment]
The automatic backport to ipa-4-11 branch failed. A manual backport is needed.

**Comment by rcritten** [comment]
Oh, it failed because the backport of the original patch hasn't been merged yet.

**Comment by flo-renaud** [comment]
This commit has been added on top of the backport of the original patch in https://github.com/freeipa/freeipa/pull/6994

**Pull request closed without merging**
