### PR TITLE
[Backport][ipa-4-6] prci: bump ci-master-f27 template to 1.0.2

### PR DESCRIPTION
**Pull request by tomaskrizek**
Signed-off-by: Tomas Krizek <tkrizek@redhat.com>

### CODE REVIEW

**Comment by stlaz** [comment]
Need rebase.

**Comment by tomaskrizek** [comment]
Rebased.

**Comment by tiran** [comment]
Re-ACKing @felipevolpone ACK...

**Comment by tiran** [comment]
ipa-4-6:

* 889bb73ad22855cafd11378a6486e5d6ff9bd73a prci: bump ci-master-f27 template to 1.0.2

**Pull request closed without merging**
