### PR TITLE
dns: Fix support for dnspython 1.1x

### PR DESCRIPTION
**Pull request by stanislavlevin**
`nameservers` was transformed into the property in dnspython 2: https://github.com/rthalley/dnspython/commit/bbf0cfd239ffa6deeb67a4787bd292e9a972af74

This causes
> AttributeError: type object 'Resolver' has no attribute 'nameservers'

on the previous dnspython 1.1x.

Fixes: https://pagure.io/freeipa/issue/9339

### CODE REVIEW

**Comment by rcritten** [comment]
Is this a practical problem? Do current distributions still require an older dnspython?

**Comment by stanislavlevin** [comment]
ALTLinux has stable branch shipping dnspython 1.16.

The reasons I upstream this:
- distros may still sit on old dnspython
- DNSResolver is a shim compatible with both dnspython < 2 and dnspython > 2
- requirements:
  - PyPi users: 'dnspython >= 1.15'
  - Fedora users: python3-dns >= 1.15

**Comment by stanislavlevin** [comment]
For example,
https://repology.org/project/dnspython/versions

ubuntu 20.04 ships dnspython 1.16.

Its EOL in 2030:
https://wiki.ubuntu.com/Releases

**Comment by abbra** [comment]
Yeah, given that this fix is small and concise, I think it makes sense to keep supporting dnspython < 2.

**Comment by stanislavlevin** [comment]
@rcritten, thank you, I'm packaging 4.9.x branch.

**Comment by rcritten** [comment]
master:

* 1420599165a1d95b83b2099d7f65c04c6e25285a dns: Fix support for dnspython 1.1x

**Pull request closed without merging**
