### PR TITLE
Remove pkinit from ipa-replica-prepare

### PR DESCRIPTION
**Pull request by stlaz**
The PKINIT feature is not available on domain level 0 so any
options about pkinit are false.

https://pagure.io/freeipa/issue/6759

### CODE REVIEW

**Comment by MartinBasti** [comment]
Works for me. @abbra @simo5 do you have any objections?

**Comment by abbra** [comment]
LGTM.

**Comment by HonzaCholasta** [comment]
The options were available since forever, so I guess you should just hide them instead of removing them.

The same options are still available in domain level 0 `ipa-server-install` - is this intentional?

**Comment by abbra** [comment]
They were in DL0 in `ipa-server-install` for very long time and never worked. We left them there to make sure we can get them back to work sometime later. We did but in new design `ipa-replica-prepare` does not need to use these options, unlike `ipa-server-install`.

**Comment by MartinBasti** [comment]
master:

* 46d4d534c08d14756b989e157e87a078d174ad5c Remove pkinit from ipa-replica-prepare

**Pull request closed without merging**
