### PR TITLE
Server affinity: Retain user-requested remote server

### PR DESCRIPTION
**Pull request by rcritten**
We want to avoid splitting a replica server installation between two hosts where possible so if a CA or KRA is requested then we only try to install against a remote server that also provides those capabilities. This avoids race conditions.

If a CA or KRA is not requested and the user has provided a server to install against then use that instead of overriding it.

Fixes: https://pagure.io/freeipa/issue/9491
Related: https://pagure.io/freeipa/issue/9289

note that automated testing is hard because there are so many scenarios, as in the original change in https://github.com/freeipa/freeipa/pull/6787

I did manual testing with an initial server, a replica with no optional services and a new replica with options:

1. ipa-replica-install -P admin --admin-password password -N (picked either server, alternating)
2. ipa-replica-install -P admin --admin-password password -N --setup-ca (resulted in connection with master)
3. ipa-replica-install -P admin --admin-password password -N --domain example.test --server replica1.example.test (stuck with replica1)
4. ipa-replica-install -P admin --admin-password password -N --domain example.test --server replica1.example.test --setup-ca (failed because replica1 doesn't provide a CA)

### CODE REVIEW

**Comment by miskopo** [comment]
Hello @rcritten , do you need a review for this PR?

**Comment by rcritten** [comment]
> Hello @rcritten , do you need a review for this PR?

Yes

**Comment by flo-renaud** [comment]
Tested with the following setup: 3 servers, one with dns only (noca.ipa.test), the 2nd with dns + CA (ca.ipa.test), the 3rd with dns + CA + KRA (cakra.ipa.test).

I'm seeing an issue with ipa-replica-install --setup-ca with no specified server (single step installing client + doing promotion), sometimes the client installer picks noca.ipa.test, the replication picks cakra.ipa.test but the install fails in the part retrieving the keys from custodia:
```
Discovery was successful!
Client hostname: server.ipa.test
Realm: IPA.TEST
DNS Domain: ipa.test
IPA Server: noca.ipa.test
BaseDN: dc=ipa,dc=test
```
but in the replica install log we see the server used for replication:
```
2023-12-14T17:57:15Z DEBUG args=['/usr/sbin/ipa-replica-conncheck', '--master', 'cakra.ipa.test', '--auto-master-check', '--realm', 'IPA.TEST', '--hostname', 'server.ipa.test', '--principal', 'admin', '--password', XXXXXXXX, '--ca-cert-file', '/etc/ipa/ca.crt'] 
```
and finally the keys are retrieved from noca.ipa.test:
```
2023-12-14T17:58:26Z DEBUG Custodia client for '<CustodiaModes.KRA_PEER: 'Custodia KRA peer'>' with promotion yes.
2023-12-14T17:58:26Z INFO Custodia uses 'noca.ipa.test' as master peer.
...
023-12-14T17:58:30Z DEBUG Starting new HTTPS connection (1): noca.ipa.test:443
2023-12-14T17:58:30Z DEBUG https://noca.ipa.test:443 "GET /ipa/keys/ca/caSigningCert%20cert-pki-ca?type=kem&value=eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkEyNTZDQkMtSFM1MTIiLCJraWQiOm51bGx9.TDluinp1oLG9hb-tuMcDw2WaZG6y1iV807ObZJSyz_oYqVwBjiEP4jbGziWfZbgtN_AEwcMNk3rmdUIu_Ck5sIMnQIV2PXwGyPRD-eW_oYdhUy8Z08-GnGmmUtrRi-tgEkaPA39e9EBrzhgK8SyhLVbKhtlVwQnB_NUEUTdZ6NtR62rs2U1UQmxaFjes7nXtHfrRZH3uY5Ha8nkfU-9lYJ1Tf1tcedcZ5O-m_UGgPUTbC46lIwWpveeOcw72Bjl_hEHVib1WzqRhTuSDs0QJgR9mpradAtSuS1ABisuL8C0HJnAmEaDOBSXg9wGkxql62sA1cbyv26_wLWu2IRGrlw.MB-fnrwYmbihETCQThyCdA.aKv7GpASYS4jKcVZckdFR7_z6ZRfV5m_47qFRlFRTYEEW6Gjcr2sMJHeyd7JennFJGtkOWx68KcGGCoNdH12nwgCSwunSqlcET4WW3E5b0w9LXsYfpEHMBPVQh1TWhW0IQAsGgHGMP5FVDh-eUtGx_ssIxnv0dHMYl3g97_J5WG-oNaysZmhBOY8TbUsEZyQidNanqbAljSdlV_up8XeQJSM6BeiaoyszWHeQNqgh5viRgdPSpn3y7m6H3dktwoMbkaaUT2vE0fOyBdNLM7WhgI7ebPmySAmHzuHunGpjU-2aVkhBuFd8zcLzadxEMgbcS9o4tEX5F_4Tui73W_cDLS7eysokRBGRKW3ZdrpHCxOhwp3ylouyRvRSbKenct1cdT70UOd05IeAYqzUuBDCwgkYezZfONy1DOIMde5fhE_BmsrKjtwWzozs2dbYTAylBIdRILsgQUmuFqi9s9lbHgNcdOZPoVBAfD84n2gKl42BTeuTWGwN3PQNQoplxob3JArghCRNl3JnzvKf6eOblOOrbj0pvSKJxy5fSx0fbAfY4wFTL03iXuOxHP23QDysCQt2LPbNcmo9Rwe86J-Qhi7THolHItgeegtXbTQDbs1gU0bJLihIPbcF0dF1qUMERh74Tv7xPUgE8jJ8kC2yg.HDcs8WdrDnLZHsUNtVceBVP8_Dw11Q5dNd4l6gDU6gM HTTP/1.1" 404 330
2023-12-14T17:58:30Z DEBUG   File "/usr/lib/python3.11/site-packages/ipapython/admintool.py", line 180, in execute
    return_value = self.run()
```

So it looks like the server used for the client part is reused for custodia client instance, and may be different from the server used for replica setup.

**Comment by flo-renaud** [comment]
[ipaclient-install.log](https://github.com/freeipa/freeipa/files/13688494/ipaclient-install.log)
[ipareplica-conncheck.log](https://github.com/freeipa/freeipa/files/13688495/ipareplica-conncheck.log)
[ipareplica-install.log](https://github.com/freeipa/freeipa/files/13688496/ipareplica-install.log)

**Comment by flo-renaud** [comment]
For full ref, I tried the master branch without this patch and could not reproduce the issue with Custodia picking a different server. So it's likely that the problem got introduced with this patch :(

**Comment by rcritten** [comment]
Thanks, the logs are very helpful. Looking into it but I'm a bit stumped. custodia should use config.master_host_name and I think should be updated to ca_host so it's a bit perplexing.

**Comment by rcritten** [comment]
Ok, I've got it, and it's a doozy.

By default both config.ca_host_name and config.kra_host_name are set to the initial value of the server as picked by ipa-client-install. This will be important later.

Ok so in your scenario you have 2 CAs, one of which has a KRA.

The new replica only requires a CA.

Discovery finds two CA's and by chance happens to pick the CA that also has a KRA. It sets ca_enabled to True and the hostnames as appropriate.

Discovery finds one KRA server.

It sees that a KRA is available in the environment so sets kra_enabled to True. It does not tweak the value of config.kra_host_name because --setup-kra was not requested.

The value of config.kra_host_name remains the value of the originally enrolled client, in this case noca.

When we go to configure custodia we look at kra_enabled and pick KRA_PEER as the value. This points to noca leading to failure.

We should use at least options.setup_ca and options.setup_kra to pick the custodia mode instead of ca/kra_enabled. I hope we can drop the ca_enabled/kra_enabled variables altogether. I'm also going to zap the value of config.kra_host_name if there is no KRA available. Things are a bit different with the CA so I'll have to leave that variable alone.

**Comment by flo-renaud** [comment]
Thanks for the patch, LGTM. I tested the same scenario as in my previous comment and it works fine. Also tested --server with a server that does not provide the required services, properly refused.

**Comment by flo-renaud** [comment]
@rcritten if you rebase on top of the master branch, the tox issue should be fixed

**Comment by flo-renaud** [comment]
master:

* 2a95a05f9e2b965d0a5f5946d59f614d8baea8e2 Server affinity: Retain user-requested remote server

**Pull request closed without merging**
