### PR TITLE
9450 - Replace instances of del os.environ with os.environ.pop

### PR DESCRIPTION
**Pull request by ianbrown78**
Explanation:
Five instances of `del os.environ` found and changed to use pop.

Fixes: https://pagure.io/freeipa/issue/9450

### CODE REVIEW

**Comment by abbra** [comment]
@ianbrown78 thank you for the PR. Could you please add a sign-off to the commit?

Please use `git commit -s --amend' to update existing commit.

**Comment by ianbrown78** [comment]
@abbra, Hopefully the first of many!
I have amended my last commit as requested.

**Comment by abbra** [comment]
Somehow, your current PR has two separate commits: one without sign-off and one with a sign-off, otherwise they are the same.

Could you please do

```
$ git rebase -i origin/master
```
and make sure those two commits are fixed up into a single one?

We also don't use 'merge' commits, we always rebase.

**Comment by ianbrown78** [comment]
Thanks @abbra. This was a setting in my git config to pull.rebase=false. Changed to true from here on it.

**Comment by abbra** [comment]
Thank you. One more fix in the commit message: please add 'Fixes: https://pagure.io/freeipa/issue/9450' there, not just in the PR description. Our commit merging tooling will pick that up and will automatically handle pagure tickets.

**Comment by ianbrown78** [comment]
All done.
Thanks for your help getting this across the line.

**Comment by abbra** [comment]
@ianbrown78 I am sorry to ask for one more change. Please move 'Fixes: ..' part lower in the commit message, not in the first line. First line will be used as a 'Subject: ..' in the commit.

It needs to look something like this when you'd view a commit with `git show`

```
Author: Ian Brown <ian.brown@templeandwebster.com.au>
Date:     Fri, 4 Oct 2024 13:25:32 +1000

    Replace  instances of del os.environ with os.environ.pop

    Fixes: https://pagure.io/freeipa/issue/9450 

Signed-off-by: Ian Brown <ian.brown@templeandwebster.com.au>
```

**Comment by ianbrown78** [comment]
@abbra Hopefully this last commit is the way you want it structured. Thanks again for your help getting the PR in the correct style for the project. (Might need to update the contributor docs to reflect this too.)

**Comment by rcritten** [comment]
@ianbrown78 what was missing from the contributors doc? I'd like to make it clearer if we've missed something.

**Comment by rcritten** [comment]
master:

* f3ec6ae8d000add0d2af648645d22191012541a4 Replace instances of del os.environ with os.environ.pop

**Pull request closed without merging**
