### PR TITLE
[Backport][ipa-4-6] Hidden replica feature

### PR DESCRIPTION
**Pull request by tiran**
Manual backport of PR #2923 on top of PR #2948

### CODE REVIEW

**Comment by tiran** [comment]
I have cancelled TravisCI for this build. Travis is overloaded and I have to drop the temp commit any way.

**Comment by t-woerner** [comment]
LGTM

**Comment by t-woerner** [comment]
Granting ack. Please wait with push till the tests are passed again.

**Comment by tiran** [comment]
ipa-4-6:

* cb8534280ab90ac3ef768972a2382b053ae0b9f5 Add hidden replica feature
* 016c47fa1f644eaa30e78bccb9ad795cb4285929 ipatests: Exercise hidden replica feature
* 76911627a5ae3957c027ca9a0bd1e96f6d98c3c8 Simplify and improve tests
* da9f62d7bbe3a4a22698374dd9b5b03236058611 Implement server-state --state=enabled/hidden
* d12cca47fbd28ea9da09b2b84cd1bdbcf28ac0a5 Consider hidden servers as role provider
* ed0046664699e2b3880ca46c1e4404246735e005 Improve config-show to show hidden servers
* 131c1ab6e929de80d4e473994cacf48a2706026b More test fixes
* bcf70c5fa96f2dd90d3f385c3caa14a0a07ff090 Don't allow to hide last server for a role
* d8d6799de0654153145390bd0a01ec6a467b9057 Synchronize hidden state from IPA master role
* e40d92f0f90bd436a5d92cf8d22702afb09d1f42 Test replica installation from hidden replica
* d1eb4c7395229f99f50d46d28edc7f97f82666bb Add design draft
* a0f00e60f19df15fced2956b6f0b1c42ae477525 Don't fail if config-show does not return servers

**Pull request closed without merging**
