### PR TITLE
[ipa-4-4] ipa-kdb: support KDB DAL version 6.1

### PR DESCRIPTION
**Pull request by tomaskrizek**
Rebased patch for ipa-4-4. It's already in F26/rawhide.

Oiginal PR: #410

### CODE REVIEW

**Comment by martbab** [comment]
Since the original ticket is in already closed milestone open a separate one for backport to 4-4 branch please.

**Comment by tomaskrizek** [comment]
Created the ticket and linked it in the commit message.

**Comment by MartinBasti** [comment]
works for me

**Comment by MartinBasti** [comment]
ipa-4-4:

* 95daecbae86f51271f5ea48cb628ace72e676351 ipa-kdb: support KDB DAL version 6.1

**Pull request closed without merging**
