### PR TITLE
[Backport][ipa-4-8] ipatests: redesign sssd config editor

### PR DESCRIPTION
**Pull request by wladich**
This PR was opened automatically because PR #4313 was pushed to master and backport to ipa-4-8 is required.

### CODE REVIEW

**Comment by wladich** [comment]
PR was ACKed automatically because this is backport of PR #4313. Wait for CI to finish before pushing. In case of questions or problems contact @wladich who is author of the original PR.

**Comment by wladich** [comment]
Removing ACK as a temp commit has been added

**Comment by wladich** [comment]
Tests with temp commit are green:
* commands: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/9439c24a-621d-11ea-bb17-fa163e23289d
* sssd: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/a51caa96-621d-11ea-97cb-fa163ebb6b2b
* sudo: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/1f01363e-621d-11ea-b0eb-fa163e401a00
* trust: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/a29cc924-622f-11ea-a66a-fa163e0a82d3

**Comment by abbra** [comment]
LGTM

**Comment by wladich** [comment]
ipa-4-8:

* 9cb8984112ff31721b71dcdd4febcc23c2641691 ipatests: update docstring to reflect changes in FileBackup.restore()
* 5ff9b6e2a506c3ef1179655ae2d2e479005ec99e ipatests: replace utility for editing sssd.conf
* 32584ed34f466e8f474e22d778e3e964d0fcd2c4 ipatests: use remote_sssd_config to modify sssd.conf
* a1695722125674204b6e880b6ac652d78b783c88 ipatests: remove invalid parameter from sssd.conf

**Pull request closed without merging**
