### PR TITLE
Support trust in FIPS mode

### PR DESCRIPTION
**Pull request by abbra**
## ipaserver/dcerpc.py: enforce SMB encryption on LSA pipe if available
    
We want to always use SMB encryption if it is possible on LSA pipe as we are going to pass what accounts to a plain-text content within CreateTrustedDomainEx2 call.
    
The catch is that older Samba version might not have a way to enforce this and we need fall back to work with existing connection then.
    
## ipaserver/dcerpc.py: use Kerberos authentication for discovery
    
In FIPS mode we cannot rely on NTLMSSP at all, so we have ensure Kerberos is used by Samba Python libraries. This is achieved by requiring credentials objects to always use Kerberos authentication.
    
Additionally, we have to normalize the principal used to authenticate. In case it was passed without realm, add forest root domain as a realm. In case it was passed with NetBIOS domain name, remove it and replace with a realm. Since we only know about the forest root domain as a realm, require that for other domains' users a real Kerberos principal is specified.

## ipaserver/dcerpc: use Samba-provided trust helper to establish trust
    
When establishing trust to Active Directory forest, RC4 is used to encrypt trusted domain object credentials as an application-specific material in a secure channel based on AES session key.
    
In FIPS mode it is not possible to use RC4 directly.
    
Samba 4.14 and backports to 4.13 in Fedora 33+ and RHEL 8.4+ now provide a helper that wraps LSA RPC call CreateTrustedDomainEx2.  This helper ensures that in FIPS mode we first check that LSA session key is AES before allowing RC4 use internally in Samba bindings. Thus, it becomes possible to establish trust to Active Directory forest in
FIPS mode.
    
Adopt FreeIPA code to use the helper provided by Samba when it is available. If neither the helper nor unprotected arcfour_encrypt utility is available from Samba bindings, fail import of the ipaserver.dcerpc module.
    
Fixes: https://pagure.io/freeipa/issue/8655
Signed-off-by: Alexander Bokovoy <abokovoy@redhat.com>

### CODE REVIEW

**Comment by abbra** [comment]
Tested on RHEL 8.4 nightly in FIPS mode and without it:
```
[root@master ~]# sysctl crypto.fips_enabled
crypto.fips_enabled = 1
[root@master ~]# ipa trust-add win2016.test --admin Administrator --password 
Active Directory domain administrator's password: 
-----------------------------------------------------
Added Active Directory trust for realm "win2016.test"
-----------------------------------------------------
  Realm name: win2016.test
  Domain NetBIOS name: WIN2016
  Domain Security Identifier: S-1-5-21-3674478510-3489545405-2687489055
  Trust direction: Trusting forest
  Trust type: Active Directory domain
  Trust status: Established and verified
[root@master ~]# systemctl restart sssd
[root@master ~]# sssctl domain-list
implicit_files
ipa.test
win2016.test
sub1.win2016.test
[root@master ~]# sssctl domain-status win2016.test
Online status: Online

Active servers:
AD Global Catalog: not connected
AD Domain Controller: not connected
IPA: master.ipa.test

Discovered AD Global Catalog servers:
None so far.
Discovered AD Domain Controller servers:
None so far.
Discovered IPA servers:
- master.ipa.test

[root@master ~]# id administrator@win2016.test
uid=117200500(administrator@win2016.test) gid=117200500(administrator@win2016.test) groups=117200500(administrator@win2016.test),117200519(enterprise admins@win2016.test),117200518(schema admins@win2016.test),117200513(domain users@win2016.test),117200520(group policy creator owners@win2016.test),117200512(domain admins@win2016.test)
[root@master ~]# sssctl domain-status win2016.test
Online status: Online

Active servers:
AD Global Catalog: ad2.sub1.win2016.test
AD Domain Controller: ad1.win2016.test
IPA: master.ipa.test

Discovered AD Global Catalog servers:
- ad2.sub1.win2016.test
- ad1.win2016.test

Discovered AD Domain Controller servers:
- ad1.win2016.test

Discovered IPA servers:
- master.ipa.test
[root@master ~]# kdestroy
[root@master ~]# kinit Administrator@WIN2016.TEST
Password for Administrator@WIN2016.TEST: 
[root@master ~]# ssh -k -l Administrator@WIN2016.TEST master.ipa.test
Activate the web console with: systemctl enable --now cockpit.socket

This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Could not chdir to home directory /home/win2016.test/administrator: No such file or directory
[administrator@win2016.test@master /]$

```

**Comment by rcritten** [comment]
The code looks ok to me and the commit messages very clear.

I don't mean to bikeshed but the trust_utils naming doesn't seem like it is going to age well. IPA is assuming that because the trust_utils import exists that FIPS-compatible wrapping is supported. Should it instead import CreateTrustedDomainRelax directly? I'm assuming that the trust_utils import was added specifically to solve this problem?

It's also curious that trust_utils has its own arcfour_encrypt. Does that also infer that wrapped-RC4 happens?

**Comment by abbra** [comment]
It is the same `arcfour_encrypt`, we import it from the same location in Samba Python bindings. I added an import guard for missing `arcfour_encrypt` in case it will disappear from Samba Python bindings and will not be directly accessible _and_ we are not able to use CreateTrustedDomainRelax.

Samba code imports `CreateTrustedDomainRelax` from `trust_utils`:

```
$ git grep trust_utils
python/samba/netcmd/domain.py:from samba.trust_utils import CreateTrustedDomainRelax
python/samba/tests/dcerpc/createtrustrelax.py:from samba.trust_utils import CreateTrustedDomainRelax
```
I updated the code. ;)

**Comment by rcritten** [comment]
Perfect, thanks. It is very clear what the code is doing now. ack.

**Comment by abbra** [comment]
master:

* cf17b7af5a8cd835ae20fe23a57fe656481e27a3 ipaserver/dcerpc: use Samba-provided trust helper to establish trust
* e157ea1e14edd239c58847957fe0ae7c7fa5c9ab ipaserver/dcerpc.py: use Kerberos authentication for discovery
* fd15f60216b4098d0423fc39a0ad62293df5d116 ipaserver/dcerpc.py: enforce SMB encryption on LSA pipe if available

**Pull request closed without merging**
