### PR TITLE
ipatests: do not set dns_lookup to true

### PR DESCRIPTION
**Pull request by wladich**
dns_lookup was set to false during ipa client installation which prevented
searches for SRV records for Kerberos servers.
Since https://pagure.io/freeipa/issue/6523 is fixed, dns_lookup is always True
now and the fixture is not needed anymore.

### CODE REVIEW

**Review by fcami — COMMENTED** [review]
LGTM

**Comment by wladich** [comment]
test_smb results in temp commit: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/5604ca00-5025-11eb-ac6c-fa163e95e74a

**Review by fcami — APPROVED** [review]
ACK from me

**Comment by wladich** [comment]
master:

* b707af1c687839764774370dcf2acdbb21b0b413 ipatests: do not set dns_lookup to true

**Pull request closed without merging**
