### PR TITLE
[Backport][ipa-4-9] Always define the path DNSSEC_OPENSSL_CONF

### PR DESCRIPTION
**Pull request by flo-renaud**
This PR was opened automatically because PR #5292 was pushed to master and backport to ipa-4-9 is required.

### CODE REVIEW

**Comment by flo-renaud** [comment]
PR was ACKed automatically because this is backport of PR #5292. Wait for CI to finish before pushing. In case of questions or problems contact @flo-renaud who is author of the original PR.

**Comment by rcritten** [comment]
The ACME failure means that mod_md never got a certificate from the ACME server and is serving up the locally generated self-signed certificate. I'm going to add a re-run to see if this is an intermittent failure.

**Comment by rcritten** [comment]
The mod_md test seems to be failing with some regularity.

**Comment by flo-renaud** [comment]
@rcritten thanks for checking / re-running the test_acme during my night :)
Now that everything is green we can push the backport.

**Comment by flo-renaud** [comment]
ipa-4-9:

* 06a7db1838ad9b9ebbe565dbbde126968f9c296f Always define the path DNSSEC_OPENSSL_CONF

**Pull request closed without merging**
