### PR TITLE
cryptography 38.0 removed register_interface

### PR DESCRIPTION
**Pull request by AlbertoBoldrini**
This change works in my tests, however I don't know if there was a reason to use register_interface instead simply derive from the class.

### CODE REVIEW

**Comment by tiran** [comment]
The class is an ABC. It's better to use `crypto_x509.Certificate.register` here, either post class creation or as a class decorator. The function won't verify the correctness of the class, though.

**Comment by netoarmando** [comment]
@AlbertoBoldrini thanks for this, could you please squash your commits into one and use [this template](https://github.com/freeipa/freeipa/blob/master/.git-commit-template)? The issue you are fixing is: https://pagure.io/freeipa/issue/9160

**Comment by rcritten** [comment]
bump

**Comment by stanislavlevin** [comment]
Upstream recommend subclassing to make it working for all versions of cryptography.
New python-cryptography landed in my distro and has broken IPA, I can take over this PR if the author can do it for any reason.

**Comment by stanislavlevin** [comment]
About `register` https://docs.python.org/3/library/abc.html
> Use this metaclass to create an ABC. An ABC can be subclassed directly, and then acts as a mix-in class. You can also register unrelated concrete classes (even built-in classes) and unrelated ABCs as “virtual subclasses” – these and their descendants will be considered subclasses of the registering ABC by the built-in issubclass() function, but the registering ABC won’t show up in their MRO (Method Resolution Order) nor will method implementations defined by the registering ABC be callable (not even via super())

It's up to the caller to check class's abstract methods.

See original `register_interface` that verified its abstract methods:
https://github.com/pyca/cryptography/commit/f70e334a52fdf5bd1ad42460efb78d989f8535d9#diff-c9ed41cf466f7643671839013ae11d8315b34fcacde992483edca84d6b2dfe04L54

via `verify_interface`:
https://github.com/pyca/cryptography/blob/ab952d05c02d52924e95efcb8829e7be83468523/src/cryptography/utils.py#L59

Thereby, I consider this change incomplete.

**Comment by flo-renaud** [comment]
@stanislavlevin if you have time for this issue, please go ahead  (the issue is blocking our gating CI). Thanks!

**Comment by stanislavlevin** [comment]
The alternative version of the fix:
https://github.com/freeipa/freeipa/pull/6455
that is backward compatible and require that all of `Certificate`'s (ABC) abstract methods/properties are overridden.

**Pull request closed without merging**
