### PR TITLE
ipatests: fix the method adding ifp to sssd.conf

### PR DESCRIPTION
**Pull request by flo-renaud**
The test TestCertsInIDOverrides enables the ifp service in
sssd.conf by a sed command. If the service is already enabled,
the ifp service appears multiple times in the section
[sssd]
services = ..ifp...ifp
and sssd fails to start.

Use tasks.remote_sssd_config to properly configure the
services as this API properly handles the case when the
service is already configured.

Fixes: https://pagure.io/freeipa/issue/8371

### CODE REVIEW

**Comment by flo-renaud** [comment]
The test also failed on ipa-4-8 branch in PR #[246](https://github.com/freeipa-pr-ci2/freeipa/pull/246), hence adding ipa-4-8 label

**Comment by amore17** [comment]
Hi @flo-renaud 
Changes LGTM Is it also required for ipa-4-6 ?

**Comment by flo-renaud** [comment]
@amore17 
thanks for the review.
The same test is succeeding in ipa-4-6 branch: [logs of latest [testing_ipa-4.6] Nightly PR #251](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/315072fc-b46e-11ea-87d1-fa163e4bccbe/report.html), hence no need to backport to ipa-4-6.

Temp commit removed.

**Comment by rcritten** [comment]
LGTM as well, adding ack.

**Comment by rcritten** [comment]
master:

* a3c648bd926224c53f96602ea3ec7213a3caa22d ipatests: fix the method adding ifp to sssd.conf

**Pull request closed without merging**
