### PR TITLE
[Backport][ipa-4-7] Check pager's executable before subprocess.Popen

### PR DESCRIPTION
**Pull request by xxblx**
This PR was opened automatically because PR #2629 was pushed to master and backport to ipa-4-7 is required.

### CODE REVIEW

**Comment by xxblx** [comment]
PR was ACKed automatically because this is backport of PR #2629. Wait for CI to finish before pushing. In case of questions or problems contact @xxblx who is author of the original PR.

**Comment by rcritten** [comment]
Pylint on /usr/bin/python2 is running, please wait ...
************* Module ipatests.test_ipalib.test_util
ipatests/test_ipalib/test_util.py:8: [E0611(no-name-in-module), ] No name 'mock' in module 'unittest')
************* Module ipalib.util
ipalib/util.py:1214: [E1101(no-member), get_pager] Module 'shutil' has no 'which' member)

**Comment by tiran** [comment]
I'd prefer if the code uses ``shutil.which`` with Python 3:

```
if six.PY3:
    which = shutil.which
else:
    def which(cmd):
        ...
```

**Comment by xxblx** [comment]
ipa-4-7:

* e0315a601feaee2e4aeb7db33bcf87de8ac4a4f7 Check pager's executable before subprocess.Popen
* c646f8adc32b16a0f7066d217a41a1930c9fd5ac Fix python2 compatibility

**Pull request closed without merging**
