### PR TITLE
Fix some resource leaks identified by a static analyzer

### PR DESCRIPTION
**Pull request by rcritten**
Fixes: https://pagure.io/freeipa/issue/9367

### CODE REVIEW

**Comment by abbra** [comment]
LGTM

**Comment by abbra** [comment]
Are you going to add more fixes? These ones are fine.

**Comment by rcritten** [comment]
There is one more in the ticket I need to address:

daemons/ipa-kdb/ipa_kdb_principals.c:1096: alloc_arg: "ipadb_ldap_attr_to_strlist" allocates memory that is stored into "acl_list".

**Comment by rcritten** [comment]
I think that will cover it. The elements of acl_list were being freed but not the calloc()'d acl_list itself.

**Review by f-trivino — APPROVED** [review]
I did a manual OpenScanHub scan, and the warnings are gone.

**Comment by flo-renaud** [comment]
master:

* 15de71ae61b0f97689bc8cf38256446f3e7922c1 Fix some resource leaks identified by a static analyzer

**Pull request closed without merging**
