### PR TITLE
libotp: add libraries after objects

### PR DESCRIPTION
**Pull request by tiran**
https://pagure.io/freeipa/issue/7189

Original patch by Rob Crittenden

Signed-off-by: Christian Heimes <cheimes@redhat.com>

### CODE REVIEW

**Comment by abbra** [comment]
LGTM.

**Comment by stlaz** [comment]
The commit message does not say anything useful, please fix it.

**Comment by tiran** [comment]
@stlaz There isn't anything useful to say. The title of the commit contains all relevant information.

**Comment by rcritten** [comment]
Can we compromise and add something about linker and libotp to the first line?

If you want to expand on linker ordering or something that's fine too I guess. What I suspect happens is the default linker options were different for this guy's distribution hence this working for many years before this popping up.

**Comment by stlaz** [comment]
@rcritten thanks. @tiran a commit which only tells you the original patch was made by someone else does not say you much when browsing history, this is much better.

**Comment by tiran** [comment]
master:

* ba037a3551feb835b4e0880c4ba19d68214a1b96 libotp: add libraries after objects

**Pull request closed without merging**
