### PR TITLE
WebUI tests: Fix timeout issues for reset password tests

### PR DESCRIPTION
**Pull request by serg-cymbaluk**
- Increase wait timeout after password reset
- Wait for server response after login in TestLoginScreen.test_reset_password_and_login_view

Ticket: https://pagure.io/freeipa/issue/8012

### CODE REVIEW

**Comment by tiran** [comment]
Test [passed](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/61f36310-a9fc-11e9-a698-52540084c9e9) in temp commit.

**Comment by flo-renaud** [comment]
Hi @serg-cymbaluk 
could you update the commit message because it does not match the fix any more? Thanks

**Comment by serg-cymbaluk** [comment]
@flo-renaud 
Yes, sure. The message has been fixed.

**Comment by serg-cymbaluk** [comment]
master:

* 6316a006327426af9365f865633cf6767ff699a9 WebUI tests: Fix timeout issues for reset password tests

**Pull request closed without merging**
