### PR TITLE
Switch Azure CI to Fedora 36 pre-release

### PR DESCRIPTION
**Pull request by abbra**

### CODE REVIEW

**Comment by abbra** [comment]
Tox is failing because it is unable to compile python-ldap against OpenLDAP 2.6. There is upstream discussion about it which is complicated by the fact that Python setuptools is unable to detect a presence of a library and fall back to another one. Most of Linux distributions for good part of last decade were building OpenLDAP with threaded support already so libldap is effectively the same as libldap_r but for python-ldap it needs to be a proper detection nevertheless.

Web UI tests are failing as they cannot use openssl without a configuration. I am going to look at that later. All gating tests in Azure CI passed.

**Comment by rcritten** [comment]
As workarounds these are fine IMHO. I think I'd rather you add some extra text around the OPENSSL_CONF workaround, that it is no longer necessary. I'm not sure if we need to leave breadcrumbs or not but it won't hurt I suppose.

**Comment by abbra** [comment]
Yes, I'll add comments. This is not yet complete fix. Removing the bogus config is not enough, PhantoJS still failed but with a error code that was silenced and ignored, hence success of the task. So it not really fixed yet.

**Comment by abbra** [comment]
Still needed.

**Comment by abbra** [comment]
I think this is ready for merge. Web UI tests succeeded. Here is the output from the test run:
```
2022-05-05T08:19:56.8556853Z ##[section]Starting: WebUI Unit Tests
2022-05-05T08:19:56.8565000Z ==============================================================================
2022-05-05T08:19:56.8565517Z Task         : Command line
2022-05-05T08:19:56.8565897Z Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
2022-05-05T08:19:56.8566286Z Version      : 2.201.1
2022-05-05T08:19:56.8566560Z Author       : Microsoft Corporation
2022-05-05T08:19:56.8566939Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
2022-05-05T08:19:56.8567392Z ==============================================================================
2022-05-05T08:19:57.1539474Z Generating script.
2022-05-05T08:19:57.1541557Z ========================== Starting Command Output ===========================
2022-05-05T08:19:57.1547722Z [command]/usr/bin/bash --noprofile --norc /__w/_temp/a27e763e-4f3e-4546-9aa1-40f55716615e.sh
2022-05-05T08:19:57.1611544Z Running WebUI unit tests
2022-05-05T08:19:57.1612442Z sed						\
2022-05-05T08:19:57.1613225Z 	-e 's|@API_VERSION[@]|2.246|g'		\
2022-05-05T08:19:57.1613825Z 	-e 's|@NUM_VERSION[@]|41000|g'		\
2022-05-05T08:19:57.1614249Z 	loader.js.in > loader.js
2022-05-05T08:20:07.4584950Z npm WARN deprecated puppeteer@9.1.1: Version no longer supported. Upgrade to @latest
2022-05-05T08:20:13.8525846Z 
2022-05-05T08:20:13.8527351Z added 153 packages, and audited 154 packages in 16s
2022-05-05T08:20:13.8531620Z 
2022-05-05T08:20:13.8532432Z 15 packages are looking for funding
2022-05-05T08:20:13.8533233Z   run `npm fund` for details
2022-05-05T08:20:13.8562654Z 
2022-05-05T08:20:13.8563502Z 2 high severity vulnerabilities
2022-05-05T08:20:13.8563922Z 
2022-05-05T08:20:13.8564432Z Some issues need review, and may require choosing
2022-05-05T08:20:13.8564994Z a different dependency.
2022-05-05T08:20:13.8565337Z 
2022-05-05T08:20:13.8565814Z Run `npm audit` for details.
2022-05-05T08:20:14.3570147Z Initializing
2022-05-05T08:20:14.3581953Z Command-line options: --verbose, --gruntfile=/__w/1/s/install/ui/Gruntfile.js
2022-05-05T08:20:14.3587352Z 
2022-05-05T08:20:14.3592715Z Reading "Gruntfile.js" Gruntfile...OK
2022-05-05T08:20:14.3597470Z 
2022-05-05T08:20:14.3597952Z Registering Gruntfile tasks.
2022-05-05T08:20:14.3604243Z Initializing config...OK
2022-05-05T08:20:14.3609164Z 
2022-05-05T08:20:14.3610078Z Registering "grunt-qunit-junit" local Npm module tasks.
2022-05-05T08:20:14.3684312Z Reading /__w/1/s/install/ui/node_modules/grunt-qunit-junit/package.json...OK
2022-05-05T08:20:14.3688872Z Parsing /__w/1/s/install/ui/node_modules/grunt-qunit-junit/package.json...OK
2022-05-05T08:20:14.3782569Z Loading "qunit-junit.js" tasks...OK
2022-05-05T08:20:14.3783480Z + qunit_junit
2022-05-05T08:20:14.3783824Z 
2022-05-05T08:20:14.3784537Z Registering "grunt-contrib-qunit" local Npm module tasks.
2022-05-05T08:20:14.3785397Z Reading /__w/1/s/install/ui/node_modules/grunt-contrib-qunit/package.json...OK
2022-05-05T08:20:14.3790052Z Parsing /__w/1/s/install/ui/node_modules/grunt-contrib-qunit/package.json...OK
2022-05-05T08:20:14.4560385Z Loading "qunit.js" tasks...OK
2022-05-05T08:20:14.4563961Z + qunit
2022-05-05T08:20:14.4565231Z Loading "Gruntfile.js" tasks...OK
2022-05-05T08:20:14.4565850Z + test
2022-05-05T08:20:14.4566204Z 
2022-05-05T08:20:14.4566706Z Running tasks: test
2022-05-05T08:20:14.4571678Z 
2022-05-05T08:20:14.4572489Z Running "test" task
2022-05-05T08:20:14.4578511Z 
2022-05-05T08:20:14.4579216Z Running "qunit_junit" task
2022-05-05T08:20:14.4589317Z Options: dest="_build/test-reports", fileNamer=undefined, classNamer=undefined, testNamer=undefined
2022-05-05T08:20:14.4603248Z >> XML reports will be written to _build/test-reports
2022-05-05T08:20:14.4603847Z 
2022-05-05T08:20:14.4604331Z Running "qunit" task
2022-05-05T08:20:14.4608033Z 
2022-05-05T08:20:14.4608783Z Running "qunit:all" (qunit) task
2022-05-05T08:20:14.4618626Z Verifying property qunit.all exists in config...OK
2022-05-05T08:20:14.4649569Z Files: test/all_tests.html -> all
2022-05-05T08:20:14.4656392Z Options: timeout=5000, inject="/__w/1/s/install/ui/node_modules/grunt-contrib-qunit/chrome/bridge.js", urls=[], force=false, console, httpBase=false, summaryOnly=false
2022-05-05T08:20:17.0128225Z ##[section]Finishing: WebUI Unit Tests
```

**Comment by flo-renaud** [comment]
@abbra thanks for the PR, LGTM.
The PR is now using the latest grunt pkg for the webui tests but it doesn't introduce any regression (I checked in https://github.com/freeipa-pr-ci2/freeipa/pull/1687 and all the webui tests are green).

**Comment by abbra** [comment]
master:

* 64bbf31fd860519fe33650701b32df28b9e01932 Switch Azure CI to Fedora 36 pre-release
* 6a086eb2208cfa0626065b8be691f57a90abcc6c Azure CI: temporarily add libldap_r.so symlink for python-ldap PIP use
* 53d9dafe2fdfe27b38d67546809e0474a140fe56 Azure CI: don't force non-existing OpenSSL configuration anymore
* 862340a3a1c5b50daba517fcb1d6fab0f10dfae9 js tests: use latest grunt

**Pull request closed without merging**
