### PR TITLE
WebUI: update Patternfly and Bootstrap

### PR DESCRIPTION
**Pull request by pvomacka**
Current versions:
    PatternFly: 3.9.0
    Boostrap: 3.3.7
    Bootstrap-select: 1.4.3
    Font-Awesome: 4.0.3

https://fedorahosted.org/freeipa/ticket/6394

### CODE REVIEW

**Comment by redhatrises** [comment]
@pvomacka should this use the patternfly RPM rather than having the code copied here as well? See https://www.redhat.com/archives/patternfly/2014-July/msg00017.html

**Comment by pvomacka** [comment]
@redhatrises  Thank you for the comment and the link. I agree that it would be really nice, but unfortunately there is no PatternFly package in Fedora. 

Anyway, I would be happy to do a review of a PatternFly package.

**Comment by redhatrises** [comment]
> @redhatrises Thank you for the comment and the link. I agree that it would be really nice, but unfortunately there is no PatternFly package in Fedora. 

@pvomacka  you're right. I should have checked. They do exist in the Patternfly Copr repos: https://copr.fedorainfracloud.org/coprs/patternfly/

Not sure if those can be used or a request needs to be made to include those RPMs into Fedora?

**Comment by pvoborni** [comment]
I don't think the patternfly package can be included in Fedora as is. It internally bundles several packages, some of them already packaged (jquery, fontawesome-fonts, OpenSans-fonts). 

Additionally tha package puts files on non-standard place. 

Some info about Fedora packaging:
* https://fedoraproject.org/wiki/Packaging:JavaScript
* https://fedoraproject.org/wiki/Packaging:Web_Assets

**Comment by mbasti-rh** [comment]
works for me

**Comment by pvomacka** [comment]
I added minimized patternfly and boostrap javascript files instead of classic ones.

**Comment by mbasti-rh** [comment]
Bump for review

**Comment by pvoborni** [comment]
works for me

**Comment by pvoborni** [comment]
Fixed upstream
master:
https://fedorahosted.org/freeipa/changeset/18425dbbe7b7c311cf947074d505225b235df769

**Pull request closed without merging**
