### PR TITLE
[ipa-4-6] ipatests: fix covscan issue in test_otp.py

### PR DESCRIPTION
**Pull request by flo-renaud**
Fixes: https://pagure.io/freeipa/issue/8255

### CODE REVIEW

**Comment by flo-renaud** [comment]
@amore17 could you review? Thanks.

**Comment by netoarmando** [comment]
PR-CI fetched the wrong yaml file for serveral pull requests, including this one, it added tasks from gating definitions found in ipa-4-6 branch.

`test_otp` is defined in temp_commit, it passed, you can remove the temp commit or rebase and force push just to clear the list of tasks.

**Comment by flo-renaud** [comment]
test_otp logs are available [here](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/a2d4819c-74f5-11ea-93ab-fa163e23289d). Removing the temp commit.

**Comment by flo-renaud** [comment]
ipa-4-6:

* 8774460274ce6e7de1bf1f2080878c01ed37ad07 ipatests: fix covscan issue in test_otp.py

**Pull request closed without merging**
