### PR TITLE
Remove ipa-nis-manage as we aim to disable NIS server support

### PR DESCRIPTION
**Pull request by abbra**
RHEL 8.3+ already deprecated support for NIS protocol.
  RHEL 9 does not ship NIS client side
  RHEL 10 removes NIS server emulator support

Fixes: https://pagure.io/freeipa/issue/9363

### CODE REVIEW

**Comment by abbra** [comment]
FYI, slapi-nis change that makes NIS server build optional is https://pagure.io/slapi-nis/c/446b64425c8db462d48ff651be15e5a00706f719?branch=master. I am planning to push that to Fedora rawhide next week.

**Comment by rcritten** [comment]
Do we want a test for the new "The NIS plugin is configured, cannot disable compatibility" scenario?

So it looks like if an install has NIS enabled this won't touch that. This is about preventing future enablement.

Do we want/need a tool to eventually disable NIS altogether? What happens if slapi-nis disables NIS support and slapi-nis is enabled in IPA? I assume lookups will stop functioning? Is there a way we can alert users? A healthcheck maybe?

**Comment by rcritten** [comment]
The warning related to ipa-compat-manage disable works correctly but it makes me wonder.

When slapi-nis stops shipping the shared library will cause 389-ds to fail:

 ERR - symload_report_error - Could not open library "/usr/lib64/dirsrv/plugins/nisserver-plugin.so" for plugin NIS Server

dsconf requires a running server so it won't be able to disable the plugin. Something, slapi-nis I presume, will need to disable this plugin on upgrade. Since the 389 config is an ldif perhaps the ldif module can parse, disable, then save the config.

**Comment by abbra** [comment]
Thanks. Yes, Thierry told me the same but I haven't had time to look into this to fix.
Regarding 'slapi-nis disables NIS support and slapi-nis is enabled in IPA' case, this is what slapi-nis supposed to handle in its spec file but I didn't finish fixing that script yet.

**Comment by abbra** [comment]
I decided to use `ldapdelete` in a trigger in slapi-nis spec to remove NIS server plugin configuration from existing deployment. So when we'll update to that slapi-nis version, it will automatically remove NIS server configuration and restart dirsrv.

Updated this PR to also remove NIS server integration in the migration tooling.

**Comment by abbra** [comment]
I released slapi-nis 0.70.0 which now defaults to disabling NIS server. RPM spec removes NIS server plugin configuration during installation.

I'll plan to do a build for Fedora together with FreeIPA with this PR soon.

**Comment by abbra** [comment]
Fedora updates: 
- F41: https://bodhi.fedoraproject.org/updates/FEDORA-2024-f62eda62b5, pushed to testing
- F42: https://bodhi.fedoraproject.org/updates/FEDORA-2024-42d8c5bd2d, pushed to stable Rawhide

FreeIPA default configuration is to not enable NIS server plugin so the upgrade test in slapi-nis is not really executed. However, new installations of these Fedora builds will not have NIS server support anymore.

**Comment by flo-renaud** [comment]
Tested on rawhide with the test_sudo.py and test_commands.py tests (with slapi-nis-0.70.0-3.fc42.x86_64), works well.
```
# IPATEST_YAML_CONFIG=~/ipa-test-config.yaml ipa-run-tests --logging-level=DEBUG --logfile-dir=/tmp/tests test_integration/test_sudo.py
...
                                      [100%]

==================================================================== warnings summary ====================================================================
../ipapython/version.py:20
  /usr/lib/python3.13/site-packages/ipapython/version.py:20: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    from pkg_resources import parse_version

../pytest_sourceorder.py:31
  /usr/lib/python3.13/site-packages/pytest_sourceorder.py:31: PytestUnknownMarkWarning: Unknown pytest.mark.source_order - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    cls = pytest.mark.source_order(cls)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
====================================================== 79 passed, 2 warnings in 1129.52s (0:18:49) =======================================================

# IPATEST_YAML_CONFIG=~/ipa-test-config.yaml ipa-run-tests --logging-level=DEBUG --logfile-dir=/tmp/tests test_integration/test_commands.py
...
[100%]

==================================================================== warnings summary ====================================================================
../ipapython/version.py:20
  /usr/lib/python3.13/site-packages/ipapython/version.py:20: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    from pkg_resources import parse_version

../pytest_sourceorder.py:31
  /usr/lib/python3.13/site-packages/pytest_sourceorder.py:31: PytestUnknownMarkWarning: Unknown pytest.mark.source_order - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    cls = pytest.mark.source_order(cls)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
====================================================== 43 passed, 2 warnings in 2527.52s (0:42:07) =======================================================

**Comment by rcritten** [comment]
master:

* e98a80827bcc42dc16b516355077fed844220107 Remove NIS server support

**Pull request closed without merging**
