### PR TITLE
Web UI: Upgrade jQuery version 2.0.3 -> 3.4.1

### PR DESCRIPTION
**Pull request by serg-cymbaluk**
Ticket: https://pagure.io/freeipa/issue/8284

### CODE REVIEW

**Comment by abbra** [comment]
LTGM to me. Did you try it against Chrome/Safari/Edge?

**Comment by abbra** [comment]
Ok, other than the Edge test, things look good to me.
Please remove the temp commit.

**Comment by serg-cymbaluk** [comment]
@abbra 

The patch has been tested with Edge 44. No visible regressions were found.
Temp commit is removed.

**Comment by abbra** [comment]
ACK

**Comment by serg-cymbaluk** [comment]
master:

* a0494bc3f39e1a26f52b430e4b8f07b28accbf72 Web UI: Upgrade jQuery version 2.0.3 -> 3.4.1

**Pull request closed without merging**
