### PR TITLE
Use https to get security domain from Dogtag

### PR DESCRIPTION
**Pull request by tiran**
Signed-off-by: Christian Heimes <cheimes@redhat.com>

### CODE REVIEW

**Comment by pvoborni** [comment]
What is a context of this patch? Is something broken only in master. Or also 4.4, Fedora, RHEL,...?

**Comment by pvoborni** [comment]
I.e. I want to know if something needs to be or should be backported.

**Comment by tiran** [comment]
The patch hardens the installer a bit. It would be a good idea to backport the patch to 4.4.

It's not critical since it's a read operation on localhost.

**Comment by tomaskrizek** [comment]
master:

* d1c5d92897d3e262edd2e43295c1270590aebd3d Use https to get security domain from Dogtag

**Comment by tomaskrizek** [comment]
If backport for 4.4 is needed, please open another PR against `ipa-4-4`. Thanks.

**Pull request closed without merging**
