### PR TITLE
[Backport][ipa-4-8] WebUI: Fix certificate serial number representation

### PR DESCRIPTION
**Pull request by serg-cymbaluk**
This PR was opened automatically because PR #5844 was pushed to master and backport to ipa-4-8 is required.

### CODE REVIEW

**Comment by serg-cymbaluk** [comment]
PR was ACKed automatically because this is backport of PR #5844. Wait for CI to finish before pushing. In case of questions or problems contact @serg-cymbaluk who is author of the original PR.

**Comment by rcritten** [comment]
I don't know what's going on but the Azure test is failing to install with:

[2021-06-25 17:26:51] Failed to restart the directory server (CalledProcessError(Command ['/bin/systemctl', 'restart', 'dirsrv@IPA-TEST.service'] returned non-zero exit status 1: 'Job for dirsrv@IPA-TEST.service failed because the control process exited with error code.\nSee "systemctl status dirsrv@IPA-TEST.service" and "journalctl -xeu dirsrv@IPA-TEST.service" for details.\n')). See the installation log for details.
[2021-06-25 17:26:51]   [error] NetworkError: cannot connect to 'ldapi://%2Frun%2Fslapd-IPA-TEST.socket': Connection refused
[2021-06-25 17:26:51] cannot connect to 'ldapi://%2Frun%2Fslapd-IPA-TEST.socket': Connection refused

**Comment by flo-renaud** [comment]
The azure installation errors probably happen because of a mismatch between ipa and 389ds. The 4-8 branch does not contain the fix for multi master / multi supplier plugin name.

**Comment by abbra** [comment]
Should we backport those changes as well? Otherwise, ipa-4-8 needs to be disconnected from the Azure CI.

**Comment by flo-renaud** [comment]
@abbra I am preparing a backport of #5836 + #5798 to ipa-4-8 branch, this should unblock the issue: #5865

**Comment by flo-renaud** [comment]
@serg-cymbaluk can you rebase this backport? PR #5865 has been merged and should fix the CI issues

**Comment by flo-renaud** [comment]
@serg-cymbaluk could you rebase? This should pick commit e7a12b8 _Constrain pylint to supported versions_ and fix the lint and tox issues

**Comment by flo-renaud** [comment]
The 14th run of azure GATING advise_1_to_3 works like a charm :tada:

**Comment by flo-renaud** [comment]
ipa-4-8:

* 1374f899584693d6a1397e6d5f9a1b3bd038c2a6 WebUI: Fix certificate serial number representation

**Pull request closed without merging**
