### PR TITLE
csrgen: Allow some certificate fields to be specified by the user

### PR DESCRIPTION
**Pull request by LiptonB**
These patches allow CSR generation rules to contain a "prompt," which will cause data to be requested from the user and interpolated into the CSR.

The second commit runs the prompt through gettext. As I asked about [here](https://www.redhat.com/archives/freeipa-devel/2016-August/msg00823.html), I'm not sure if this is useful because the prompt strings in the rule files won't be recognized as translatable. But I decided to include the commit for discussion.

### CODE REVIEW

**Comment by MartinBasti** [comment]
```
************* Module ipaclient.csrgen
ipaclient/csrgen.py:376: [E1101(no-member), CSRGenerator.get_user_prompts] Module 'ipalib.errors' has no 'CertificateMappingError' member)
ipaclient/csrgen.py:380: [E1101(no-member), CSRGenerator.get_user_prompts] Module 'ipalib.errors' has no 'CertificateMappingError' member)
ipaclient/csrgen.py:385: [E1101(no-member), CSRGenerator.get_user_prompts] Module 'ipalib.errors' has no 'CertificateMappingError' member)
ipaclient/csrgen.py:367: [W0612(unused-variable), CSRGenerator.get_user_prompts] Unused variable 'syntax_rules')
************* Module ipatests.test_ipaclient.test_csrgen
ipatests/test_ipaclient/test_csrgen.py:322: [W0612(unused-variable), test_rule_handling.test_userdata_included] Unused variable 'script')
ipatests/test_ipaclient/test_csrgen.py:324: [W0612(unused-variable), test_rule_handling.test_userdata_included] Unused variable 'expected_script'm)
```

**Comment by LiptonB** [comment]
Sorry for submitting this with lint errors - fixed now.

**Comment by tiran** [comment]
@LiptonB please resolve conflicts

**Comment by LiptonB** [comment]
Rebased, thanks.

**Comment by rcritten** [comment]
Closing due to inactivity.

**Pull request closed without merging**
