### PR TITLE
[Backport][ipa-4-6] wgi/plugins.py: ignore empty plugin directories

### PR DESCRIPTION
**Pull request by rcritten**
This PR was opened automatically because PR #5230 was pushed to master and backport to ipa-4-6 is required.

### CODE REVIEW

**Comment by rcritten** [comment]
PR was ACKed automatically because this is backport of PR #5230. Wait for CI to finish before pushing. In case of questions or problems contact @abbra who is author of the original PR.

**Comment by abbra** [comment]
For ipa-4-6, we need to use a different method as `ipaplatform.paths` does not exist there:
```
Pylint on /usr/bin/python2 is running, please wait ...
************* Module ipatests.test_ipaserver.test_jsplugins
ipatests/test_ipaserver/test_jsplugins.py:8: [E0611(no-name-in-module), ] No name 'paths' in module 'ipatests.test_ipaserver.ipaplatform.paths')
ipatests/test_ipaserver/test_jsplugins.py:8: [W0403(relative-import), ] Relative import 'ipaplatform.paths', should be 'ipatests.test_ipaserver.ipaplatform.paths')
------------------------------------
Your code has been rated at 10.00/10
make: *** [Makefile:1237: pylint] Error 6
```

**Comment by rcritten** [comment]
I think this just needs ```from __future__ import absolute_import```

I'll push this as an additional commit to see if it helps and if so we can decide to merge it in or not (I'd prefer to merge it in)

**Comment by rcritten** [comment]
Tests are green, let me know what you want to do with the other changes:

1. squash all together
2. clean up with proper commit msgs and tickets, etc.

**Comment by abbra** [comment]
Great. I guess squashing would make sense -- if you'd add that this commit was cherry-picked from the commit 91706690e0c894864c93716c4fbecb285722e77d and adopted to Python 2 environment it should be enough to understand the differences.

**Comment by rcritten** [comment]
ipa-4-6:

* 45802f19789d560634046dc6fb48f3bbc13fafb9 wgi/plugins.py: ignore empty plugin directories

**Pull request closed without merging**
