### PR TITLE
[Backport][ipa-4-8] Don't restart certmonger after stopping tracking in uninstall

### PR DESCRIPTION
**Pull request by rcritten**
This PR was opened automatically because PR #5197 was pushed to master and backport to ipa-4-8 is required.

### CODE REVIEW

**Comment by rcritten** [comment]
PR was ACKed automatically because this is backport of PR #5197. Wait for CI to finish before pushing. In case of questions or problems contact @rcritten who is author of the original PR.

**Comment by abbra** [comment]
Ok, all Azure CI tests will fail until https://bodhi.fedoraproject.org/updates/FEDORA-2020-9765318e8b is pushed into stable updates on Fedora 32. This is a bug in libdnf!

**Comment by rcritten** [comment]
ipa-4-8:

* a9aad493ae0f0d0758cbdd651c980402c131b58a Don't restart certmonger after stopping tracking in uninstall

**Pull request closed without merging**
