### PR TITLE
uninstall: Don't fail on missing /var/lib/samba

### PR DESCRIPTION
**Pull request by stanislavlevin**
On some distros `freeipa-server` package may not depend on `/var/lib/samba` directory. In this case, an uninstallation of ipaserver fails.
    
Fixes: https://pagure.io/freeipa/issue/8461

### CODE REVIEW

**Comment by abbra** [comment]
Please rebase to rebuild a container in Azure Pipelines so that new krb5 package is used instead of a faulty one.

**Comment by abbra** [comment]
LGTM

**Comment by flo-renaud** [comment]
master:

* 89d86dac0a13063a11deaa8ef31f9fb2fcbc1ff7 uninstall: Don't fail on missing /var/lib/samba
* 5c1e44830048f5b13656349c63b5319a536e3a8d uninstall: Clean up no longer used flag
* 03a5e5f35ff09b34474d28b5ec3704a2aa0b31b8 spec: Move ipa-cldap plugin out to freeipa-server-trust-ad package

**Comment by flo-renaud** [comment]
@stanislavlevin a manual backport is required for ipa-4-8 branch, can you do it? thanks

**Comment by stanislavlevin** [comment]
backport for ipa-4-8: https://github.com/freeipa/freeipa/pull/5043

**Comment by flo-renaud** [comment]
@stanislavlevin thanks :)

**Pull request closed without merging**
