### PR TITLE
Bump pki min version and add commentary about sub-CA revocation on delete

### PR DESCRIPTION
**Pull request by frasertweedale**
https://fedorahosted.org/freeipa/ticket/6256

### CODE REVIEW

**Comment by mbasti-rh** [comment]
I don't think that bumping BuildRequires is needed

Also you are changing strings used for translations, so I'd use this change and rather add new things to doc string using http://www.freeipa.org/page/Coding_Best_Practices#Split_long_translatable_strings It will help translators in future

**Comment by frasertweedale** [comment]
@mbasti-rh I think the BuildRequires bump is appropriate.  If we say (in the doc) that
such and such will happen, we want to be sure that they are using the version of
Dogtag that actually implements it.

**Comment by mbasti-rh** [comment]
IMO for that there is 'Requires' statement. We don't need 10.3.5-6 during build time and IIRC Honza is working on 'Fix IPA dependencies' patch and he will even decrease BuildRequires for pki'

**Comment by frasertweedale** [comment]
On Tue, Oct 04, 2016 at 11:41:39PM -0700, mbasti-rh wrote:
> IMO for that there is 'Requires' statement. We don't need 10.3.5-6 during build time and IIRC Honza is working on 'Fix IPA dependencies' patch and he will even decrease BuildRequires for pki'
> 
Ah right, yeah.  Misunderstood earlier comment.  I'll cut a new
patch that doesn't touch BuildRequires (neither bumping it, nor
removing).

Thanks,
Fraser

**Comment by mbasti-rh** [comment]
Fixed upstream
master:
https://fedorahosted.org/freeipa/changeset/6b3f4984296f3caff8f29490eae3ed1dca64b8c3
https://fedorahosted.org/freeipa/changeset/2b8163ab5dfcf28a9eba319ef685046ae9d8b5e8
ipa-4-4:
https://fedorahosted.org/freeipa/changeset/358e50b2e194d3ae3d0e8c22c774a24ab84d8be1
https://fedorahosted.org/freeipa/changeset/810c38efce6a3911b39e29b7aac010e467ef25a7

**Pull request closed without merging**
