### PR TITLE
WebUI: Fix "IPA Error 3007: RequirmentError" while adding idoverrideuser association

### PR DESCRIPTION
**Pull request by serg-cymbaluk**
Add builder for association adder dialog which allows to override behavior of the component.
Replace default implementation with a custom one for idoverrideuser.
Replace text filter with 'ID view' select box in the idoverrideuser dialog.

Ticket: https://pagure.io/freeipa/issue/8335

### CODE REVIEW

**Comment by serg-cymbaluk** [comment]
@abbra @pvoborni 

The patch fixes only adder dialog and, as result, allows to add a association with idoverrideuser.

But in other hand it disclose a couple of issues which I couldn't solve:

1) After adding idoverrideuser to group, it is not possible to navigate to the item.
The reason is I have only `ipaanchoruuid` values in `member_idoverrideuser` field (`group-show` call). But it is not enough to even get the object, because I need to have specify an ID view.

2) The anchor field is presented as `:SID:S-***-***-***`
As a result it is not possible to remove the idoverrideuser member due to a server error.

```
# ipa group-remove-member admins --idoverrideusers=Administrator@win.test
  Group name: admins
  Description: Account administrators group
  GID: 559600000
  Member users: admin
---------------------------
Number of members removed 1
---------------------------
```

but

```
# ipa group-remove-member admins --idoverrideusers=':SID:S-1-5-21-4064286453-263327960-3213440627-500'
ipa: ERROR: an internal error has occurred
```

**Comment by pvoborni** [comment]
What is in httpd error log for the internal error?

**Comment by abbra** [comment]
Please look at https://github.com/freeipa/freeipa/pull/4728 where I tried to merge all the changes required to make idoverrideuser membership working. I think with that one changes on Web UI side should be limited -- at least, I have no problem discussed here in my tests anymore.

**Comment by serg-cymbaluk** [comment]
@abbra thanks
I checked my changes together with your patch and it works good. User ID override is displayed properly and 'delete' action is fixed.

@pvoborni 
I didn't find solution for the navigation issue, so for now I'm keeping plain text in the table instead of links.

**Comment by abbra** [comment]
Please remove temp commit.

**Comment by serg-cymbaluk** [comment]
@abbra 

Temp commit is removed.

**Comment by serg-cymbaluk** [comment]
master:

* c2ba333b9681d008d9c528a79dbdd76ce11a3ecd WebUI: Fix "IPA Error 3007: RequirmentError" while adding idoverrideuser association

**Pull request closed without merging**
