### PR TITLE
Make test_external_ca.py compatible with crypto 41.0.0

### PR DESCRIPTION
**Pull request by flo-renaud**
The integration test test_external_ca.py is not compatible with python-cryptography 41.0.0+.

The test is installing ipa server with an externally-signed CA cert using a Microsoft Certificate Service profile:
ipa-server-install --external-ca --external-ca-type ms-cs
                    --external-ca-profile "1.2.3.4:10:200"
The command generates a CSR in /root/ipa.csr. The test reads the CSR, extracts the extensions and compares with the requested extension for the Microsoft Template.
With python-cryptography 41.0.0+, the extension can be decoded as cryptography.x509.MSCertificateTemplate while with older version the extension is decoded as cryptography.x509.UnrecognizedExtension.

Handle both cases properly.

Fixes: https://pagure.io/freeipa/issue/9490

### CODE REVIEW

**Comment by flo-renaud** [comment]
Links to various runs of test_external_ca.py:
- on the "old" f32 runners with fedora 38 vagrant images: [report](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/dc49fd3e-936f-11ee-9229-fa163ea4a9f1/report.html)
- on the new f39 runner with fedora 38 vagrant images: [report](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/35c8247a-9380-11ee-927c-fa163ed4f71a/report.html)
- on the new f39 runner with fedora 39 vagrant images: [report](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/0a79da98-9380-11ee-8e0b-fa163e1ec1dc/report.html?sort=result)

**Comment by miskopo** [comment]
The fix look good to me, I have also reviewed the runs and it is working as expected.

**Comment by miskopo** [comment]
Just an optional nitpick, please, if possible, sign your commit (8883b45ffa91484891a40f0d26e692e4e338209b)

**Review by miskopo — APPROVED** [review]

**Comment by flo-renaud** [comment]
master:

* d61d1b059c8d760b37c7aae9ea47cb06674c76cd Make test_external_ca.py compatible with crypto 41.0.0

**Pull request closed without merging**
