### PR TITLE
[RFE] Pwdpolicy

### PR DESCRIPTION
**Pull request by simo5**
Untested but I am seeking feedback on the actual approach.

### CODE REVIEW

**Comment by martbab** [comment]
LGTM, but the PR needs some more love since it breaks CI.

**Comment by simo5** [comment]
I found two subtle bugs that cause the install failure, with the rebased patches install completes correctly for me.

**Comment by martbab** [comment]
test_kadmin and all other tests also passed. I do not see reason for not pushing. Sorry for the dealy in reviewing.

**Comment by martbab** [comment]
master:

* 9f13b330aaec468a018472dce5fc77131277de94 Add code to retrieve results from multiple bases
* 2e5cc369fd8b9d780697a9a286429cc2ca0f448a Add support for searching policies in cn=accounts

**Pull request closed without merging**
