### PR TITLE
install: replica: Show message about key synchronization

### PR DESCRIPTION
**Pull request by dkupka**
https://pagure.io/freeipa/issue/6940

### CODE REVIEW

**Comment by MartinBasti** [comment]
Py3 issue
```
************* Module ipaserver.install.custodiainstance
ipaserver/install/custodiainstance.py:133: [E1601(print-statement), CustodiaInstance.__wait_keys] print statement used)
```

**Comment by MartinBasti** [comment]
Needs rebase

**Comment by tomaskrizek** [comment]
@dkupka Please rebase so we can merge.

**Comment by pvomacka** [comment]
master:

* d6787eea4899af6bd7075a3311a45cb8eda571e5 install: replica: Show message about key synchronization

**Pull request closed without merging**
